-- TRP（FTP）写入出票航段事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第三步：写入出票航段事实表
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDERNO,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    AK_COUPON,
    AK_COUPONCODE,
    COUPON_AMOUNT,
    COUPON_COUNT,
    COUPONNO,
    COUPON_NAME,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：票号(删除横杠) + 航段三字码前三位 + 起飞日期(YYYYMMDD格式)
    CONCAT(
            REPLACE(COALESCE(t1.TICKET_NUMBER, ''), '-', ''),
            SUBSTRING(COALESCE(t1.SEGMENT_THREE_CODE, ''), 1, 3),
            REPLACE(SUBSTRING(COALESCE(t1.DEPARTURE_TIME, ''), 1, 10), '/', '')
        ) AS PK_ID,

    t1.ORDER_NUMBER AS CHANNEL_ORDERNO,

    -- 预订渠道标准化
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 是否使用优惠券
    CASE WHEN t1.VOUCHER_CODE IS NOT NULL AND t1.VOUCHER_CODE != '' THEN true ELSE false END AS AK_COUPON,

    -- 优惠券产品编码
    COALESCE(t1.COUPON_CODE, '') AS AK_COUPONCODE,

    -- 优惠券优惠金额
    CASE
        WHEN t1.COUPON_AMOUNT IS NOT NULL AND t1.COUPON_AMOUNT != ''
            THEN CAST(t1.COUPON_AMOUNT AS DECIMAL(15,2))
        ELSE NULL
        END AS COUPON_AMOUNT,

    -- 优惠券张数
    1 AS COUPON_COUNT,

    -- 优惠券券码
    COALESCE(t1.VOUCHER_CODE, '') AS COUPONNO,

    -- 优惠券名称
    COALESCE(t1.COUPON_NAME, '') AS COUPON_NAME,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.CONTACT_PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 源系统最后更新时间
    t1.PAYMENT_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_TRP_SC_SALE_DETAIL t1
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.TICKET_NUMBER IS NOT NULL
  AND t1.SEGMENT_THREE_CODE IS NOT NULL AND LENGTH(t1.SEGMENT_THREE_CODE) >= 3
  AND t1.DEPARTURE_TIME IS NOT NULL;


-- trp-数仓写入出票航段表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.ORDER_USER IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.ORDER_USER IS NOT NULL;

-- 第三步：写入出票航段事实表
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDERNO,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    AK_COUPON,
    AK_COUPONCODE,
    COUPON_AMOUNT,
    COUPON_COUNT,
    COUPONNO,
    COUPON_NAME,
    CONTACT_NAME,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：票号(删除横杠) + 航班段代码前三位 + 起飞时间(YYYYMMDD格式)
    CONCAT(
            REPLACE(COALESCE(t1.TICKET_NO, ''), '-', ''),
            SUBSTRING(COALESCE(t1.FLIGHT_SEGMENT_CODE, ''), 1, 3),
            COALESCE(DATE_FORMAT(t1.TAKEOFF_TIME, '%Y%m%d'),'')
        ) AS PK_ID,

    t1.ORDER_NO AS CHANNEL_ORDERNO,
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,
    -- 是否使用优惠券
    CASE WHEN t1.COUPON_NUM IS NOT NULL AND t1.COUPON_NUM != '' THEN true ELSE false END AS AK_COUPON,
    t1.COUPON_NO AS AK_COUPONCODE,
    -- 优惠券优惠金额
    CASE
        WHEN t1.COUPON_FARE IS NOT NULL THEN CAST(t1.COUPON_FARE AS DECIMAL(15,2))
        ELSE NULL
        END AS COUPON_AMOUNT,
    -- 优惠券张数
    1 AS COUPON_COUNT,
    t1.COUPON_NUM AS COUPONNO,
    t1.COUPON_NAME AS COUPON_NAME,
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    t1.PAY_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.TICKET_NO IS NOT NULL
  AND t1.FLIGHT_SEGMENT_CODE IS NOT NULL AND LENGTH(t1.FLIGHT_SEGMENT_CODE) >= 3
  AND t1.TAKEOFF_TIME IS NOT NULL;



-- 大客户差旅写入出票航段级事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_TEST.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER p ON o.ID = p.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT ps ON p.AIR_ORDER = ps.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_SEGMENT seg ON ps.SEGMENT = seg.ID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND rc.CERT_NO IS NOT NULL
  AND ps.TICKET_NUM IS NOT NULL AND ps.TICKET_NUM != ''
  AND seg.BOARD_POINT IS NOT NULL AND seg.BOARD_POINT != ''
  AND seg.DEPARTURE_DATE IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, rc.CERT_TYPE) AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_TEST.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER p ON o.ID = p.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT ps ON p.AIR_ORDER = ps.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_SEGMENT seg ON ps.SEGMENT = seg.ID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON rc.CERT_TYPE = sid.CFG_CODE
        AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL = 'KEY_ACCOUNT_TRAVEL'
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
  AND rc.CERT_NO IS NOT NULL
  AND ps.TICKET_NUM IS NOT NULL AND ps.TICKET_NUM != ''
  AND seg.BOARD_POINT IS NOT NULL AND seg.BOARD_POINT != ''
  AND seg.DEPARTURE_DATE IS NOT NULL;

-- 第三步：写入出票航段事实表（正常时间）
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDERNO,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：票号+起飞机场+起飞日期
    CONCAT(
            REPLACE(COALESCE(ps.TICKET_NUM, ''), '-', ''),
            COALESCE(seg.BOARD_POINT, ''),
            CASE
                WHEN seg.DEPARTURE_DATE IS NOT NULL
                    THEN DATE_FORMAT(seg.DEPARTURE_DATE, '%Y%m%d')
                ELSE ''
                END

        ) AS PK_ID,

    o.ORDER_NO AS CHANNEL_ORDERNO,

    -- 预订渠道标准化
    'SCSME' AS AK_CHANNEL,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_TEST.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER p ON o.ID = p.AIR_ORDER
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT ps ON p.AIR_ORDER = ps.AIR_ORDER
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_SEGMENT seg ON ps.SEGMENT = seg.ID
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND ps.TICKET_NUM IS NOT NULL AND ps.TICKET_NUM != ''
  AND seg.BOARD_POINT IS NOT NULL AND seg.BOARD_POINT != ''
  AND seg.DEPARTURE_DATE IS NOT NULL;

-- 第四步：23:00:00-00:00:00的订单需要T+1日期
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDERNO,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：票号+起飞机场+起飞日期
    CONCAT(
            REPLACE(COALESCE(ps.TICKET_NUM, ''), '-', ''),
            COALESCE(seg.BOARD_POINT, ''),
            CASE
                WHEN seg.DEPARTURE_DATE IS NOT NULL
                    THEN DATE_FORMAT(DATE_ADD(seg.DEPARTURE_DATE, INTERVAL 1 DAY), '%Y%m%d')
                ELSE ''
                END

        ) AS PK_ID,

    o.ORDER_NO AS CHANNEL_ORDERNO,

    'SCSME' AS AK_CHANNEL,

    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

    o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_TEST.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER p ON o.ID = p.AIR_ORDER
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT ps ON p.AIR_ORDER = ps.AIR_ORDER
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_SEGMENT seg ON ps.SEGMENT = seg.ID
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
  -- 23:00:00-00:00:00时间段
  AND HOUR(o.TICKET_OUT_DATE) = 23
  AND ps.TICKET_NUM IS NOT NULL AND ps.TICKET_NUM != ''
  AND seg.BOARD_POINT IS NOT NULL AND seg.BOARD_POINT != ''
  AND seg.DEPARTURE_DATE IS NOT NULL;

-- 呼叫白屏票务系统
-- 写入出票航段级事实表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_KFBP_BUS_FARE_TICKET TK
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_ORDER BO ON TK.ORDER_PKID = BO.PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BFT ON TK.ORDER_PKID = BFT.ORDER_PKID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE BO.IS_FICTITIOUS_ORDER = 0
  AND TK.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND BO.CUR_TEL IS NOT NULL;

INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_KFBP_BUS_FARE_TICKET TK
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_ORDER BO ON TK.ORDER_PKID = BO.PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BFT ON TK.ORDER_PKID = BFT.ORDER_PKID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE BO.IS_FICTITIOUS_ORDER = 0
  AND TK.ETL_DATE >= @ETL_DATE
  AND BO.CUR_TEL IS NOT NULL;


INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDERNO,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    CONTACT_NAME,
    CONTACT_MOBILE_NUMBER,
    CONTACT_LANDLINE_MOBILE_NUMBER,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：票号(删除横杠) + 起飞机场 + 起飞日期(YYYYMMDD格式)
    CONCAT(
            REPLACE(COALESCE(TK.TICKET_NO, ''), '-', ''),
            COALESCE(BFT.FLT_START_CITY, ''),
            DATE_FORMAT(BFT.FLT_DEPARTURE_DAY, '%Y%m%d')
        ) AS PK_ID,

    BO.ORDER_SN AS CHANNEL_ORDERNO,
    'SCWHP' AS AK_CHANNEL,  -- 写死：SCWHP

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(BO.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CONTACT_MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,
    -- 联系人固定电话
    COALESCE(BO.CONTACT_PHONE, '') AS CONTACT_LANDLINE_MOBILE_NUMBER,

    -- 源系统最后更新时间
    TK.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_KFBP_BUS_FARE_TICKET TK
         LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_ORDER BO ON TK.ORDER_PKID = BO.PKID
         LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BFT ON TK.ORDER_PKID = BFT.ORDER_PKID
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1

WHERE BO.IS_FICTITIOUS_ORDER = 0
  AND TK.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND TK.TICKET_NO IS NOT NULL
  AND BFT.FLT_START_CITY IS NOT NULL
  AND BFT.FLT_DEPARTURE_DAY IS NOT NULL ;


-- 标准数据表TB_TCN_DATA-机票-出票-航段级事实表

INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, AK_DIMARK, AK_FAREBASIS, AK_CURRENCY, AK_SALE_PRICE_CNY, AK_SALE_TAX_CNY,
 AK_SALE_FUEL_TAX_CNY, AK_SALE_TAX_ALL_CNY, AK_SALE_PRICE_ALL_CNY,
 B2B_OFFICE, B2B_IATANO, B2B_AGENCY_FEE, AK_SALE_PRICE_CURRENCY, AK_SALE_TAX_CURRENCY, AK_SALE_FUEL_TAX_CURRENCY,
 SYSTEM_CREATETIME)
SELECT
    PK_ID,
    AK_DIMARK,
    AK_FAREBASIS,
    AK_CURRENCY,
    AK_SALE_PRICE_CNY,
    AK_SALE_TAX_CNY,
    AK_SALE_FUEL_TAX_CNY,
    AK_SALE_TAX_ALL_CNY,
    AK_SALE_PRICE_ALL_CNY,
    B2B_OFFICE,
    B2B_IATANO,
    B2B_AGENCY_FEE,
    AK_SALE_PRICE_CURRENCY,
    AK_SALE_TAX_CURRENCY,
    AK_SALE_FUEL_TAX_CURRENCY,
    SYSTEM_CREATETIME
FROM (
         SELECT
             -- TK_AIR+TK_NUM+UP_LOCATION+DEP_DATE，得到主键
             CONCAT(
                     COALESCE(TK_AIR, ''),
                     COALESCE(TK_NUM, ''),
                     COALESCE(UP_LOCATION, ''),
                     COALESCE(DATE_FORMAT(DEP_DATE, '%Y%m%d'), '')
                 ) AS PK_ID,
             -- 国内国际标识
             STATID AS AK_DIMARK,
             -- 运价基础
             CP_STR AS AK_FAREBASIS,
             -- 销售币种
             FARE_TYPE AS AK_CURRENCY,
             -- 航段销售票面价格销售币种
             SEG_PRICE AS AK_SALE_PRICE_CURRENCY,
             -- 航段销售基建税销售币种
             PORT_FARE AS AK_SALE_TAX_CURRENCY,
             -- 航段销售燃油税销售币种
             ADD_FARE AS AK_SALE_FUEL_TAX_CURRENCY,
             -- 航段销售票面价格CNY(ARE_TYPE是CNY的，此处写入，其他币种，不写此字段)
             CASE
                 WHEN FARE_TYPE = 'CNY' THEN SEG_PRICE
                 ELSE NULL
                 END AS AK_SALE_PRICE_CNY,
             -- 航段销售基建税CNY
             CASE
                 WHEN FARE_TYPE = 'CNY' THEN PORT_FARE
                 ELSE NULL
                 END AS AK_SALE_TAX_CNY,
             -- 航段销售燃油税CNY
             CASE
                 WHEN FARE_TYPE = 'CNY' THEN ADD_FARE
                 ELSE NULL
                 END AS AK_SALE_FUEL_TAX_CNY,
             -- 航段销售总税费CNY(PORT_FARE+ADD_FARE)
             CASE
                 WHEN FARE_TYPE = 'CNY' THEN
                         COALESCE(PORT_FARE, 0) + COALESCE(ADD_FARE, 0)
                 ELSE NULL
                 END AS AK_SALE_TAX_ALL_CNY,
             -- 销售航段总票价CNY(SEG_PRICE+PORT_FARE+ADD_FARE)
             CASE
                 WHEN FARE_TYPE = 'CNY' THEN
                         COALESCE(SEG_PRICE, 0) + COALESCE(PORT_FARE, 0) + COALESCE(ADD_FARE, 0)
                 ELSE NULL
                 END AS AK_SALE_PRICE_ALL_CNY,
             -- B2B OFFICE(TK_AGENT=SDH888的情况，才写此字段)
             CASE
                 WHEN TK_AGENT = 'SDH888' THEN BBCODE
                 ELSE NULL
                 END AS B2B_OFFICE,
             -- B2B IATANO(TK_AGENT=SDH888的情况，才写此字段)
             CASE
                 WHEN TK_AGENT = 'SDH888' THEN VALAGT_CODE
                 ELSE NULL
                 END AS B2B_IATANO,
             -- B2B代理费(TK_AGENT=SDH888的情况，才写此字段)
             CASE
                 WHEN TK_AGENT = 'SDH888' THEN ZSAL_FARE
                 ELSE NULL
                 END AS B2B_AGENCY_FEE,
             -- 系统创建时间
             NOW() AS SYSTEM_CREATETIME,
             -- 保留原始字段用于条件判断
             TK_AGENT
         FROM ODS_TEST.T_ODS_BZSJ_TB_TCN_DATA
         WHERE ETL_DATE >= @ETL_DATE
           AND UP_LOCATION IS NOT NULL
           AND UP_LOCATION != ''
           AND TK_AIR IS NOT NULL
           AND TK_AIR != ''
           AND TK_NUM IS NOT NULL
           AND TK_NUM != ''
           AND DEP_DATE IS NOT NULL
           AND DEP_DATE != ''
     ) AS subquery_alias
WHERE PK_ID IS NOT NULL
  AND PK_ID != '';

-- 国际销售系统FTP	国际客票销售数据YXW_SALE_DATA
-- 机票-出票-航段级事实表--写DWD
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, AK_SALE_PRICE_CNY, AK_SALE_FUEL_TAX_CNY, AK_SALE_TAX_ALL_CNY, AK_SALE_PRICE_ALL_CNY, SYSTEM_CREATETIME)
SELECT *
FROM (
         SELECT CASE
                    WHEN SEGMENT_NO1 IS NOT NULL AND SEGMENT_NO1 != '' AND TICKET_TRAVEL_DATE1 != '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT1, 1, 3),
                                    TICKET_TRAVEL_DATE1)
                    WHEN SEGMENT_NO1 IS NOT NULL AND SEGMENT_NO1 != '' AND TICKET_TRAVEL_DATE1 = '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT1, 1, 3))
                    ELSE NULL
                    END                                                    AS PK_ID,
                SALE_APPORTIONMENT1                                        AS AK_SALE_PRICE_CNY,
                SALE_FUEL1                                                 AS AK_SALE_FUEL_TAX_CNY,
                TRANSPORT_APPORTIONMENT1                                   AS AK_SALE_TAX_ALL_CNY,
                COALESCE(SALE_APPORTIONMENT1, 0) + COALESCE(SALE_FUEL1, 0) AS AK_SALE_PRICE_ALL_CNY,
                NOW()                                                      AS SYSTEM_CREATETIME
         FROM ODS_TEST.T_ODS_YXW_SALE_REPORT
         WHERE TICKET_NUMBER IS NOT NULL
           AND ETL_DATE >= @ETL_DATE
     ) AS subquery_alias -- 添加别名
WHERE PK_ID IS NOT NULL;
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, AK_SALE_PRICE_CNY, AK_SALE_FUEL_TAX_CNY, AK_SALE_TAX_ALL_CNY, AK_SALE_PRICE_ALL_CNY, SYSTEM_CREATETIME)
SELECT *
FROM (
         SELECT CASE
                    WHEN SEGMENT_NO2 IS NOT NULL AND SEGMENT_NO2 != '' AND TICKET_TRAVEL_DATE2 != '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT2, 1, 3),
                                    TICKET_TRAVEL_DATE2)
                    WHEN SEGMENT_NO2 IS NOT NULL AND SEGMENT_NO2 != '' AND TICKET_TRAVEL_DATE2 = '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT2, 1, 3))
                    ELSE NULL
                    END                                                    AS PK_ID,
                SALE_APPORTIONMENT2                                        AS AK_SALE_PRICE_CNY,
                SALE_FUEL2                                                 AS AK_SALE_FUEL_TAX_CNY,
                TRANSPORT_APPORTIONMENT2                                   AS AK_SALE_TAX_ALL_CNY,
                COALESCE(SALE_APPORTIONMENT2, 0) + COALESCE(SALE_FUEL2, 0) AS AK_SALE_PRICE_ALL_CNY,
                NOW()                                                      AS SYSTEM_CREATETIME
         FROM ODS_TEST.T_ODS_YXW_SALE_REPORT
         WHERE TICKET_NUMBER IS NOT NULL
           AND ETL_DATE >= @ETL_DATE
     ) AS subquery_alias -- 添加别名
WHERE PK_ID IS NOT NULL;
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, AK_SALE_PRICE_CNY, AK_SALE_FUEL_TAX_CNY, AK_SALE_TAX_ALL_CNY, AK_SALE_PRICE_ALL_CNY, SYSTEM_CREATETIME)
SELECT *
FROM (
         SELECT CASE
                    WHEN SEGMENT_NO3 IS NOT NULL AND SEGMENT_NO3 != '' AND TICKET_TRAVEL_DATE3 != '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT_CPN3, 1, 3),
                                    TICKET_TRAVEL_DATE3)
                    WHEN SEGMENT_NO3 IS NOT NULL AND SEGMENT_NO3 != '' AND TICKET_TRAVEL_DATE3 = '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT_CPN3, 1, 3))
                    ELSE NULL
                    END                                                    AS PK_ID,
                SALE_APPORTIONMENT3                                        AS AK_SALE_PRICE_CNY,
                SALE_FUEL3                                                 AS AK_SALE_FUEL_TAX_CNY,
                TRANSPORT_APPORTIONMENT3                                   AS AK_SALE_TAX_ALL_CNY,
                COALESCE(SALE_APPORTIONMENT3, 0) + COALESCE(SALE_FUEL3, 0) AS AK_SALE_PRICE_ALL_CNY,
                NOW()                                                      AS SYSTEM_CREATETIME
         FROM ODS_TEST.T_ODS_YXW_SALE_REPORT
         WHERE TICKET_NUMBER IS NOT NULL
           AND ETL_DATE >= @ETL_DATE
     ) AS subquery_alias -- 添加别名
WHERE PK_ID IS NOT NULL;
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, AK_SALE_PRICE_CNY, AK_SALE_FUEL_TAX_CNY, AK_SALE_TAX_ALL_CNY, AK_SALE_PRICE_ALL_CNY, SYSTEM_CREATETIME)
SELECT *
FROM (
         SELECT CASE
                    WHEN SEGMENT_NO4 IS NOT NULL AND SEGMENT_NO4 != '' AND TICKET_TRAVEL_DATE4 != '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT4, 1, 3),
                                    TICKET_TRAVEL_DATE4)
                    WHEN SEGMENT_NO4 IS NOT NULL AND SEGMENT_NO4 != '' AND TICKET_TRAVEL_DATE4 = '99999999'
                        THEN CONCAT(REPLACE(TICKET_NUMBER, '-', ''), SUBSTRING(TICKET_SEGMENT4, 1, 3))
                    ELSE NULL
                    END                                                    AS PK_ID,
                SALE_APPORTIONMENT4                                        AS AK_SALE_PRICE_CNY,
                SALE_FUEL4                                                 AS AK_SALE_FUEL_TAX_CNY,
                TRANSPORT_APPORTIONMENT4                                   AS AK_SALE_TAX_ALL_CNY,
                COALESCE(SALE_APPORTIONMENT4, 0) + COALESCE(SALE_FUEL4, 0) AS AK_SALE_PRICE_ALL_CNY,
                NOW()                                                      AS SYSTEM_CREATETIME
         FROM ODS_TEST.T_ODS_YXW_SALE_REPORT
         WHERE TICKET_NUMBER IS NOT NULL
           AND ETL_DATE >= @ETL_DATE
     ) AS subquery_alias -- 添加别名
WHERE PK_ID IS NOT NULL;


-- 1、机票-出票-航段级事实表
-- 数仓-结算数据写入AK_SALE_PRICE_CNY字段
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID,
 AK_SALE_PRICE_CNY, -- 航段销售票面价格CNY
 SYSTEM_CREATETIME, -- 系统创建时间
 SYSTEM_LAST_UPDATETIME -- 系统更新时间
)
SELECT CONCAT(TICKET_AIRLINE, TICEKET_NUM, ORIG, DEP_DATE) AS PK_ID,
       -- 根据您的业务逻辑设置AK_SALE_PRICE_CNY的值
       NET_INCOME                                          AS AK_SALE_PRICE_CNY,
       CURRENT_TIMESTAMP()                                 AS SYSTEM_CREATETIME,
       CURRENT_TIMESTAMP()                                 AS SYSTEM_LAST_UPDATETIME
FROM ODS_TEST.T_ODS_SC_UPLOAD_MONTH_FIN_BALANCE
WHERE TICKET_AIRLINE != '324'
  AND CONCAT(TICKET_AIRLINE, TICEKET_NUM, ORIG, DEP_DATE) IN (
    SELECT PK_ID
    FROM DWD_TEST.T_DWD_TICKING_SEG_FACT
    WHERE AK_SALE_PRICE_CNY IS NULL)
  AND ETL_DATE >= @ETL_DATE;

-- 2、机票-出票-航段级事实表
-- 写入 Y舱标准价、折扣 、票价类型
INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID,
 AK_DISCOUNT,
 Y_CABIN_NORMAL_PRICE,
 PRICE_TYPE,
 SYSTEM_LAST_UPDATETIME)
SELECT t.PK_ID,
       CASE
           WHEN y_price.PRICE_ONEWAY > 0 THEN
               ROUND(t.AK_SALE_PRICE_CNY / y_price.PRICE_ONEWAY, 2)
           ELSE NULL
           END AS AK_DISCOUNT,
       y_price.PRICE_ONEWAY AS Y_CABIN_NORMAL_PRICE,
       CASE
           -- 公务舱全价：舱位=J
           WHEN t.AK_SEGCABIN = 'J' THEN 'JFL'
           -- 公务舱折扣：舱等=公务舱，舱位不等于J
           WHEN t.AK_CABIN = 'BC' AND t.AK_SEGCABIN != 'J' THEN 'JDS'
           -- 经济舱全价票：舱位=Y 或者 舱位=G
           WHEN t.AK_SEGCABIN IN ('Y', 'G') THEN 'YFL'
           -- 经济舱折扣：舱等=经济 或者 高经，并且折扣4折及以上（折扣>=0.40）
           WHEN (t.AK_CABIN IN ('EC', 'PE')) AND
                (t.AK_SALE_PRICE_CNY / y_price.PRICE_ONEWAY) >= 0.40 THEN 'YDS'
           -- 经济舱特价：舱等=经济 或者 高经，并且折扣4折以下（折扣<0.40）
           WHEN (t.AK_CABIN IN ('EC', 'PE')) AND
                (t.AK_SALE_PRICE_CNY / y_price.PRICE_ONEWAY) < 0.40 THEN 'YSP'
           ELSE NULL
           END AS PRICE_TYPE,
       NOW() AS SYSTEM_LAST_UPDATETIME
FROM DWD_TEST.T_DWD_TICKING_SEG_FACT t
         INNER JOIN (
    SELECT y.UP_LOCATION,
           y.DIS_LOCATION,
           y.PRICE_ONEWAY,
           y.START_DATE,
           y.END_DATE
    FROM ODS_TEST.T_ODS_SC_TB_TICKET_PRICE_ORDER y
) y_price ON y_price.UP_LOCATION = t.FK_DEPAIRPORT
    AND y_price.DIS_LOCATION = t.FK_ARRIAIRPORT
    AND t.FK_SEG_DATE BETWEEN y_price.START_DATE AND y_price.END_DATE
where t.DATA_ACTIVE = 1
  AND t.AK_DISCOUNT IS NULL
  AND t.AK_SALE_PRICE_CNY IS NOT NULL
  AND t.FK_SEG_DATE IS NOT NULL
  AND t.FK_DEPAIRPORT IS NOT NULL
  AND t.FK_ARRIAIRPORT IS NOT NULL
  AND (t.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR t.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));

-- 3、写入是否发生过换开字段
-- 鲁雁管家-高频	depart_passenger_info
-- 如果这张表里面，ORIGINALTKNE(换开前票号）字段非空，取ORIGINALTKNE(换开前票号）+ORIG+FLT_DATE（截取年月日），
-- 得到主键，把这个主键下的那一条数据“是否发生过换开”改成“是“

INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, IS_RESCHEDULED, SYSTEM_LAST_UPDATETIME)
SELECT nearest_rec.PK_ID,
       1                   AS IS_RESCHEDULED,
       CURRENT_TIMESTAMP() AS SYSTEM_LAST_UPDATETIME
FROM (
         SELECT ts.PK_ID,
                ABS(DATEDIFF(ts.FK_SEG_DATE, t.FK_DEPARTURES_DATE)) as date_diff,
                ROW_NUMBER() OVER (
                    PARTITION BY t.ORI_TIK_NUM, t.FK_DEPAIRPORT, t.FK_ARRIAIRPORT
                    ORDER BY ABS(DATEDIFF(ts.FK_SEG_DATE, t.FK_DEPARTURES_DATE)) ASC
                    )                                               as rn
         FROM DWD_TEST.T_DWD_DATECHANGE_SEG_FACT t
                  INNER JOIN DWD_TEST.T_DWD_TICKING_SEG_FACT ts ON (
                     ts.AK_TICKET_NUMBER = t.ORI_TIK_NUM
                 AND ts.FK_DEPAIRPORT = t.FK_DEPAIRPORT
                 AND ts.FK_ARRIAIRPORT = t.FK_ARRIAIRPORT
                 AND (t.SYSTEM_LAST_UPDATETIME >= @ETL_DATE
                 OR t.SYSTEM_CREATETIME >= @ETL_DATE)
             )
         WHERE t.ORI_TIK_NUM IS NOT NULL
           AND t.DATA_ACTIVE = 1
     ) nearest_rec
WHERE nearest_rec.rn = 1;


-- 4、机票-出票-航段级事实表
-- 提前出票天数（起飞日期 与 出票日期 相差天数。如果日期相同则为0。）

INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, AK_ADVBOOK_DAY)
SELECT PK_ID,
       CASE
           WHEN FK_SEG_DATE IS NULL OR FK_ISSUE_DATE IS NULL THEN NULL
           WHEN FK_SEG_DATE < FK_ISSUE_DATE THEN NULL
           WHEN FK_SEG_DATE = FK_ISSUE_DATE THEN 0
           ELSE DATEDIFF(FK_SEG_DATE, FK_ISSUE_DATE)
           END AS IS_RESCHEDULED
FROM DWD_TEST.T_DWD_TICKING_SEG_FACT t
where t.DATA_ACTIVE = 1
  and (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));




-- 5、机票-出票-航段级事实表
-- 是否为返乡段
-- "以下情况为是，否则为否
-- 1、如果乘机人证件类型为=身份证，并且 乘机人证件号码对应的省份（通过《身份证号-省份+地级市》）与到达机场对应的省份（航程维表：省）相同。
-- 2、并且起飞机场（机场维表：省）和到达机场（机场维表：省）不在一个省份。"

INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, HOMECOMING_SEG)
SELECT t.PK_ID,
       CASE
           WHEN t.CERT_TYPE = 'NI' -- 身份证类型
               AND EXISTS(
                        SELECT 1
                        FROM DIM_TEST.T_DIM_PROVINCE_CITY_DIM pc
                        WHERE pc.ID = SUBSTRING(
                                SM4_DECRYPT(FROM_BASE64(t.CERT_NUMBER), FROM_BASE64(@SM4_KEY)), 1,
                                4) -- SM4解密后取前4位
                          AND pc.PROVINCE = addr_arr.PROVINCE -- 与到达机场省份相同
                    )
               AND addr_dep.PROVINCE != addr_arr.PROVINCE -- 起飞机场与到达机场省份不同
               THEN 1
           ELSE 0
           END AS HOMECOMING_SEG
FROM DWD_TEST.T_DWD_TICKING_SEG_FACT t
         LEFT JOIN DIM_TEST.T_DIM_ADDRESS_DIM addr_dep
                   ON t.FK_DEPAIRPORT = addr_dep.ADDRESS_KEY -- 起飞机场三字码关联
         LEFT JOIN DIM_TEST.T_DIM_ADDRESS_DIM addr_arr
                   ON t.FK_ARRIAIRPORT = addr_arr.ADDRESS_KEY -- 到达机场三字码关联
WHERE t.FK_DEPAIRPORT is not null
  and t.DATA_ACTIVE = 1
  and t.FK_ARRIAIRPORT is not null
  and t.CERT_NUMBER is not null
  and t.CERT_TYPE = 'NI'
  and (t.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR t.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));





-- 6、票价类型



-- 7、机票-出票-航段级事实表
-- 是否为自己订票
-- "1、机票预订-航段级、机票出票-客票级、机票出票-航段级：判断乘机人TID是否与预订人TID一致。如果一致则为是。否则为否。
-- 2、成行-航段级，退票-航段级：通过“主键”“出票-航段级反写”"

INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT
(PK_ID, SELF_BOOKING, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT t.PK_ID,
       CASE
           WHEN t.FK_BOOKING_USER_TID = t.FK_BOOKING_USER_ORIGIN_ID
               THEN 1
           ELSE 0
           END AS SELF_BOOKING,
       NOW() AS SYSTEM_CREATETIME,
       NOW() AS SYSTEM_LAST_UPDATETIME
FROM DWD_TEST.T_DWD_TICKING_SEG_FACT t
WHERE t.FK_BOOKING_USER_TID is not null
  and t.DATA_ACTIVE = 1
  and t.FK_BOOKING_USER_ORIGIN_ID is not null
  and (t.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR t.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));

