-- 1年内购买舱位偏好
INSERT INTO DIM_PROD.T_DIM_USER_DIM (PK_ID, CABIN_CLASS_PREFERENCE_LAST_1_YEAR)
SELECT 
    COALESCE(user_cabin.FK_BOOKING_USER_TID, dim.PK_ID) as PK_ID,
    COALESCE(user_cabin.AK_SEGCABIN, dim.CABIN_CLASS_PREFERENCE_LAST_1_YEAR) as CABIN_CLASS_PREFERENCE_LAST_1_YEAR
FROM DIM_PROD.T_DIM_USER_DIM dim
LEFT JOIN (
    SELECT 
        FK_BOOKING_USER_TID,
        AK_SEGCABIN,
        COUNT(*) as cabin_count,
        ROW_NUMBER() OVER (
            PARTITION BY FK_BOOKING_USER_TID 
            ORDER BY COUNT(*) DESC
        ) as rn
    FROM DWD_PROD.T_DWD_TICKING_SEG_FACT
    WHERE FK_ISSUE_DATE >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 YEAR)
    GROUP BY FK_BOOKING_USER_TID, AK_SEGCABIN
) user_cabin ON dim.PK_ID = user_cabin.FK_BOOKING_USER_TID AND user_cabin.rn = 1
WHERE dim.CREATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999') 
OR dim.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');

--事务提交
commit;