--addExtractSql
INSERT INTO DIM_PROD.T_DIM_USER_DIM (
  PK_ID, 
  HAS_REGISTERED_FREQUENT_TRAVELER,
  LAST_REGISTRATION_TIME_FREQUENT_TRAVELER,
  MILEAGE_EXCHANGE_COUNT_12M_AIR,
  MILEAGE_EXCHANGE_AMOUNT_12M_AIR,
  MILEAGE_EXCHANGE_COUNT_12M_NON_AIR,
  MILEAGE_EXCHANGE_AMOUNT_12M_NON_AIR,
  AVERAGE_ADVANCE_CHECK_IN_TIME_LAST_12M,
  INSURANCE_PURCHASE_COUNT_LAST_12M,
  PAID_SEAT_SELECTION_PURCHASE_COUNT_LAST_12M,
  PREPAID_BAGGAGE_PURCHASE_COUNT_LAST_12M,
  TOTAL_TRAVEL_SEGMENTS_ALL_TIME,
  TOTAL_TICKET_ISSUANCE_SEGMENTS_ALL_TIME,
  TOTAL_INSURANCE_PRODUCT_PURCHASE_AMOUNT_ALL_TIME,
  TOTAL_PAID_SEAT_SELECTION_PRODUCT_PURCHASE_AMOUNT_ALL_TIME,
  TOTAL_PREPAID_BAGGAGE_PRODUCT_PURCHASE_AMOUNT_ALL_TIME,
  TICKET_PURCHASE_SEGMENTS_COUNT_LAST_1_YEAR,
  INSURANCE_PRODUCT_PURCHASE_AMOUNT_LAST_1_YEAR,
  PAID_SEAT_SELECTION_PRODUCT_PURCHASE_AMOUNT_LAST_1_YEAR,
  PREPAID_BAGGAGE_PRODUCT_PURCHASE_AMOUNT_LAST_1_YEAR,
  FLIGHT_SEGMENTS_COUNT_LAST_3_YEARS,
  HAS_MULTIPLE_FREQUENT_TRAVELER_CARD_NUMBERS,
  HAS_MULTIPLE_CUSTOMER_IDS
  ) 
  SELECT 
  tdud.pk_id,
  -- 是否报名过常客产品
  CASE 
        WHEN (
            SELECT COUNT(1) 
            FROM DWD_PROD.T_DWD_ACT_SIGNUP_FACT asu
            WHERE asu.MEMBER_TID = tdud.PK_ID
        ) >= 1
        THEN '是'
        ELSE '否' 
    END,
    -- 常客产品最近一次报名时间
    (SELECT MAX(asu.FK_ACTION_DATE) 
     FROM DWD_PROD.T_DWD_ACT_SIGNUP_FACT asu
     WHERE asu.MEMBER_TID = tdud.PK_ID),
    -- 最近12个月里程兑换次数-航空
    (SELECT SUM(mr.EXCH_COUNT) 
 from DWD_PROD.T_DWD_MILE_REDEMPTION_FACT mr
     WHERE mr.CUMULATION_TID = tdud.PK_ID
     and mr.BIZ_TYPE = 'TKT'
     AND mr.EXCH_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 最近12个月兑换里程数量-航空
     (SELECT SUM(mr.MILES_ACCUMULATED) 
 from DWD_PROD.T_DWD_MILE_REDEMPTION_FACT mr
     WHERE mr.CUMULATION_TID = tdud.PK_ID
     and mr.BIZ_TYPE = 'TKT'
     AND mr.EXCH_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 最近12个月里程兑换次数-非航
     (SELECT SUM(mr.EXCH_COUNT) 
 from DWD_PROD.T_DWD_MILE_REDEMPTION_FACT mr
     WHERE mr.CUMULATION_TID = tdud.PK_ID
     and mr.BIZ_TYPE <> 'TKT'
     AND mr.EXCH_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 最近12个月兑换里程数量-非航
     (SELECT SUM(mr.MILES_ACCUMULATED) 
 from DWD_PROD.T_DWD_MILE_REDEMPTION_FACT mr
     WHERE mr.CUMULATION_TID = tdud.PK_ID
     and mr.BIZ_TYPE <> 'TKT'
     AND mr.EXCH_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 最近12个月平均提前购票时间
     (SELECT ROUND(SUM(tt.AK_ADVBOOK_DAY)/SUM(tt.TICKET_COUNT), 1)
 from DWD_PROD.T_DWD_TICKING_TIC_FACT tt
     WHERE tt.FK_PASSENGER_USER_TID = tdud.PK_ID
     AND tt.FK_TICKETING_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)), 
     -- 最近12个月购买保险次数
     (SELECT SUM(at.INSURANCE_COUNT) 
 from DWD_PROD.T_DWD_AUIS_SEG_FACT at
     WHERE at.FK_PASSENGER_USER_TID = tdud.PK_ID
     AND at.FK_BKAUIS_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 最近12个月购买付费选座次数
     (SELECT SUM(st.SEAT_COUNT) 
 from DWD_PROD.T_DWD_SEAT_TIK_FACT st
     WHERE st.FK_PASSENGER_USER_TID = tdud.PK_ID
     AND st.FK_SEATTIK_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 最近12个月购买预付费行李次数
     (SELECT SUM(bt.BAGGAGE_COUNT) 
 from DWD_PROD.T_DWD_BAGGAGE_TIK_FACT bt
     WHERE bt.FK_PASSENGER_USER_TID = tdud.PK_ID
     AND bt.FK_BAGGAGETIK_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 全期出行航段数
     (SELECT SUM(ds.SEG_COUNT) 
 from DWD_PROD.T_DWD_DEPART_SEG_FACT ds
     WHERE ds.FK_PASSENGER_USER_TID = tdud.PK_ID),
     -- 全期出票航段次数
     (SELECT SUM(ts.TIK_SEGCOUNT) 
 from DWD_PROD.T_DWD_TICKING_SEG_FACT ts
     WHERE ts.FK_BOOKING_USER_TID = tdud.PK_ID),
     -- 全期保险产品购买金额
     (SELECT SUM(at.INSURANCE_AMT) 
 from DWD_PROD.T_DWD_AUIS_SEG_FACT at
     WHERE at.FK_BOOKING_USER_TID = tdud.PK_ID),
     -- 全期付费选座产品购买金额
     (SELECT SUM(st.SEAT_AMOUNT) 
 from DWD_PROD.T_DWD_SEAT_TIK_FACT st
     WHERE st.FK_BOOKING_USER_TID = tdud.PK_ID),
     -- 全期付费行李产品购买金额
     (SELECT SUM(bt.BAGGAGE_AMOUNT) 
 from DWD_PROD.T_DWD_BAGGAGE_TIK_FACT bt
     WHERE bt.FK_BOOKING_USER_TID = tdud.PK_ID),
     -- 过去12个月内购票航段数量
     (SELECT SUM(ts.TIK_SEGCOUNT) 
 from DWD_PROD.T_DWD_TICKING_SEG_FACT ts
     WHERE ts.FK_BOOKING_USER_TID = tdud.PK_ID
     AND ts.FK_ISSUE_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 过去12个月保险产品购买金额
     (SELECT SUM(at.INSURANCE_AMT) 
 from DWD_PROD.T_DWD_AUIS_SEG_FACT at
     WHERE at.FK_BOOKING_USER_TID = tdud.PK_ID
     AND at.FK_BKAUIS_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 过去12个月付费选座产品购买金额
     (SELECT SUM(st.SEAT_AMOUNT) 
 from DWD_PROD.T_DWD_SEAT_TIK_FACT st
     WHERE st.FK_BOOKING_USER_TID = tdud.PK_ID
     AND st.FK_SEATTIK_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 过去12个月付费行李产品购买金额
     (SELECT SUM(bt.BAGGAGE_AMOUNT) 
 from DWD_PROD.T_DWD_BAGGAGE_TIK_FACT bt
     WHERE bt.FK_BOOKING_USER_TID = tdud.PK_ID
     AND bt.FK_BAGGAGETIK_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 YEAR)),
     -- 近3年乘机航段数
     (SELECT count(1) 
 from DWD_PROD.T_DWD_DEPART_SEG_FACT ds
     WHERE ds.FK_PASSENGER_USER_TID = tdud.PK_ID
     AND ds.FK_DEPARTURES_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 3 YEAR)),
     -- 是否存在多个常客卡号
     CASE 
        WHEN (
            SELECT count(distinct(fd.FFRF)) 
 from DIM_PROD.T_DIM_FFP_DIM fd
     WHERE fd.T_ID = tdud.PK_ID
        ) > 1
        THEN '是'
        ELSE '否' 
     END,
     -- 是否存在多个customerID
     CASE 
         WHEN (
             SELECT count(distinct(cd.customer_ID)) 
  from DIM_PROD.T_DIM_CUSTOM_DIM cd
      WHERE cd.T_ID = tdud.PK_ID
         ) > 1
         THEN '是'
         ELSE '否' 
     END
  FROM DIM_PROD.T_DIM_USER_DIM tdud
  WHERE  CREATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999') 
  OR  UPDATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');

--事务提交
commit;