-- 日频
INSERT INTO DIM_PROD.T_DIM_USER_DIM (
  PK_ID,
  FLIGHT_BOOKING_COUNT_LAST_30_DAYS,
  AGE
  )
  SELECT
  tdud.pk_id,
  -- 过去30天机票预定次数
  -- FLIGHT_BOOKING_COUNT_LAST_30_DAYS
  -- 过去30天TID作为预定人预定机票次数（机票-预定：count）
  (SELECT COUNT(1)
 from DWD_PROD.T_DWD_BOOKING_SEG_FACT bs
     WHERE bs.FK_BOOKING_USER_TID = tdud.PK_ID
     AND bs.FK_BOOKING_TIME >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 1 MONTH)),
  -- 年龄
  -- AGE
  -- 当前年-出生年份的值   （如果当前月日 在  出生月日之前  ）额外再减1
  CASE
        WHEN CONCAT(MONTH(@ETL_DATE), '-', DAY(@ETL_DATE)) < CONCAT(MONTH(BIRTHDAY), '-', DAY(BIRTHDAY))
        THEN YEAR(@ETL_DATE) - YEAR(tdud.BIRTHDAY) - 1
        ELSE YEAR(@ETL_DATE) - YEAR(tdud.BIRTHDAY)
    END
  FROM DIM_PROD.T_DIM_USER_DIM tdud
  WHERE  CREATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999') 
  OR  UPDATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');

--事务提交
commit;