
-- 1、不存在的TID写入T_DIM_TID_SET表

 INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_QWSY_CUSTOMER_INFO a
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    FOLLOW_REMARK_MOBILES = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
LEFT JOIN DIM_PROD.T_DIM_TID_SET tdts ON
    FOLLOW_REMARK_MOBILES = tdts.TID
WHERE tdts.TID IS NULL
  AND a.FOLLOW_REMARK_MOBILES IS NOT NULL
  AND (a.ETL_CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.ETL_UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND TRIM(a.FOLLOW_REMARK_MOBILES) <> ''
  AND SM4_DECRYPT(FROM_BASE64(a.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)) REGEXP '^1[3-9][0-9]{9}$';



-- 2、模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    FOLLOW_REMARK_MOBILES STRONGID,
    'PHONE' AS STRONGID_TYPE,
     IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS PK_ID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_QWSY_CUSTOMER_INFO a
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    FOLLOW_REMARK_MOBILES = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
WHERE
  a.FOLLOW_REMARK_MOBILES IS NOT NULL
   AND (a.ETL_CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.ETL_UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND TRIM(a.FOLLOW_REMARK_MOBILES) <> ''
  AND SM4_DECRYPT(FROM_BASE64(a.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)) REGEXP '^1[3-9][0-9]{9}$';


-- 3、写入企微小山客户信息维表
INSERT INTO DIM_PROD.T_DIM_QWSY_DIM
(
    SYSTEM_KEY,
    T_ID,
    COMPANY_ID,
    QW_CUSTOMER_ID,
    QW_CUSTOMER_LEVEL,
    QW_CUSTOMER_TAGS,
    UPDATE_TIME,
    CREATE_TIME
)
SELECT
    -- 主键：TID + 企微客户ID
    CONCAT(
        IFNULL(tds.TID, a.FOLLOW_REMARK_MOBILES),
        IFNULL(a.EXTERNAL_USER_ID, '')
    ) AS SYSTEM_KEY,

     -- TID（基于手机号）
    IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS PK_ID,

    -- 企业ID
    a.CORP_ID AS COMPANY_ID,

    -- 企微客户ID
    a.EXTERNAL_USER_ID AS QW_CUSTOMER_ID,

    -- 企微客户等级（使用标签组名）
    c.GROUP_NAME AS QW_CUSTOMER_LEVEL,

    -- 企微客户个人标签（聚合后的标签名称）
    c.TAG_NAME AS QW_CUSTOMER_TAGS,

    -- 更新时间
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME,

    -- 创建时间
    CURRENT_TIMESTAMP(3) AS CREATE_TIME
FROM
    ODS_PROD.T_ODS_QWSY_CUSTOMER_INFO a
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    FOLLOW_REMARK_MOBILES = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
LEFT JOIN (
    -- 修复：移除 SEPARATOR ','，Doris 默认逗号分隔
    SELECT
        EXTERNAL_USER_ID,
        GROUP_NAME,
        GROUP_CONCAT(b.TAG_NAME) AS TAG_NAME  -- 核心修复点
    FROM ODS_PROD.T_ODS_QWSY_CUSTOMER_TAG_INFO b
    GROUP BY GROUP_NAME, EXTERNAL_USER_ID
) c ON a.EXTERNAL_USER_ID = c.EXTERNAL_USER_ID
WHERE
  a.FOLLOW_REMARK_MOBILES IS NOT NULL
   and (a.ETL_CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.ETL_UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND TRIM(a.FOLLOW_REMARK_MOBILES) <> ''
  AND SM4_DECRYPT(FROM_BASE64(a.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)) REGEXP '^1[3-9][0-9]{9}$';
