-- TRP（FTP）写入预订航段事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第三步：写入预订航段事实表
INSERT INTO DWD_TEST.T_DWD_BOOKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 航段三字码前三位 + 起飞日期时间 + 证件号 + 姓名
    CONCAT(
            COALESCE(t1.PNR, ''),
            SUBSTRING(COALESCE(t1.SEGMENT_THREE_CODE, ''), 1, 3),
            CASE
                WHEN t1.DEPARTURE_TIME IS NOT NULL
                    THEN DATE_FORMAT(t1.DEPARTURE_TIME, '%Y%m%d%H%i%s')
                ELSE ''
                END,
            REPLACE(COALESCE(t1.ID_NUMBER, ''), ' ', ''),
            REPLACE(COALESCE(t1.PASSENGER_NAME, ''), ' ', '')
        ) AS PK_ID,

    t1.ORDER_NUMBER AS CHANNEL_ORDER_ID,

    -- 预订渠道标准化
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.CONTACT_PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    t1.PAYMENT_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_TRP_SC_SALE_DETAIL t1
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
    -- 预订渠道标准化
         LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.PNR IS NOT NULL AND t1.PNR != ''
  AND t1.SEGMENT_THREE_CODE IS NOT NULL AND LENGTH(t1.SEGMENT_THREE_CODE) >= 3
  AND t1.DEPARTURE_TIME IS NOT NULL
  AND t1.ID_NUMBER IS NOT NULL
  AND t1.PASSENGER_NAME IS NOT NULL;



-- 呼叫白屏票务系统
-- 写入预定航段级事实表
-- 第一步：处理不存在的TID，写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS TID,
    @ETL_DATE AS ETL_DATE,
    NOW() AS CREATE_TIME,
    1 AS TID_STATUS
FROM
    ODS_TEST.T_ODS_KFBP_BUS_ORDER BO
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BFT ON BO.PKID = BFT.ORDER_PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FARE BF ON BO.PKID = BF.ORDER_PKID
        -- 关联TID集合表，找出尚未记录的TID
        LEFT JOIN DIM_TEST.T_DIM_TID_SET tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.TID
            AND tds.TID_STATUS = 1
WHERE
        BO.ORDER_TYPE = 2
  AND BO.ORDER_STATUS IS NOT NULL
  AND BO.ETL_DATE >= @ETL_DATE
  AND BO.CUR_TEL IS NOT NULL
  AND tds.TID IS NULL;


-- 第二步：模拟IDMapping，写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(
            existing_tds.TID,
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
        ) AS TID,
    1 AS STRONGID_STATUS,
    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,
    @ETL_DATE AS ETL_DATE
FROM
    ODS_TEST.T_ODS_KFBP_BUS_ORDER BO
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BFT ON BO.PKID = BFT.ORDER_PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FARE BF ON BO.PKID = BF.ORDER_PKID
        -- 关联T_DIM_STRONGID表以查找已存在的TID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID existing_tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = existing_tds.STRONGID
            AND existing_tds.STRONGID_STATUS = 1
WHERE
        BO.ORDER_TYPE = 2
  AND BO.ORDER_STATUS IS NOT NULL
  AND BO.ETL_DATE >= @ETL_DATE
  AND BO.CUR_TEL IS NOT NULL;


-- 第三步：写入预订航段事实表 T_DWD_BOOKING_SEG_FACT
INSERT INTO DWD_TEST.T_DWD_BOOKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    CONTACT_LANDLINE_MOBILE_NUMBER,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 起飞机场 + 起飞日期(去杠) + 起飞时间 + 证件号 + 旅客姓名(去斜杠)
    CONCAT(
            IFNULL(BO.PNR, ''),
            IFNULL(BFT.FLT_START_CITY, ''),
            CASE
                WHEN BFT.FLT_DEPARTURE_DAY IS NOT NULL
                    THEN DATE_FORMAT(BFT.FLT_DEPARTURE_DAY, '%Y%m%d')
                ELSE ''
                END,
            CASE
                WHEN BFT.FLT_DEPARTURE_TIME IS NOT NULL
                    THEN CONCAT(REPLACE(BFT.FLT_DEPARTURE_TIME, ':', ''), '00')
                ELSE ''
                END,
            IFNULL(BF.ID_CODE, ''),
            IFNULL(REPLACE(BF.FARE_NAME, '/', ''), '')
        ) AS PK_ID,
    BO.ORDER_SN AS CHANNEL_ORDER_ID,
    'SCWHP' AS AK_CHANNEL, -- 写死
    -- 手机号标准化：加密
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CONTACT_MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,
    -- 联系人姓名标准化：去除空白字符
    REGEXP_REPLACE(BO.CONTACT_NAME, '\\s+', '') AS CONTACT_NAME,
    -- 座机号标准化：加密
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CONTACT_PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_LANDLINE_MOBILE_NUMBER,
    -- 预订人TID：从T_DIM_STRONGID表中获取
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    -- 预订人源ID：加密后的CUR_TEL
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,
    BO.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME
FROM
    ODS_TEST.T_ODS_KFBP_BUS_ORDER BO
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BFT ON BO.PKID = BFT.ORDER_PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FARE BF ON BO.PKID = BF.ORDER_PKID
        -- 关联T_DIM_STRONGID表，获取最终的TID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
        BO.ORDER_TYPE = 2
  AND BO.ORDER_STATUS IS NOT NULL
  AND BO.ETL_DATE >= @ETL_DATE
  AND BO.PNR IS NOT NULL  AND BO.PNR != ''
  AND BFT.FLT_START_CITY IS NOT NULL
  AND BFT.FLT_DEPARTURE_DAY IS NOT NULL
  AND BFT.FLT_DEPARTURE_TIME IS NOT NULL
  AND BF.ID_CODE IS NOT NULL
  AND BF.FARE_NAME IS NOT NULL
  AND BO.CUR_TEL IS NOT NULL;



-- 大客户差旅 写入 机票-预订-航段级事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_TEST.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER p ON o.ID = p.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT ps ON p.AIR_ORDER = ps.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_SEGMENT seg ON ps.SEGMENT = seg.ID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND rc.CERT_NO IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    CASE
        WHEN tds.TID IS NOT NULL THEN tds.STRONGID_TYPE
        ELSE IFNULL(sid.CFG_VALUE, 'OT')
        END AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_TEST.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER p ON o.ID = p.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT ps ON p.AIR_ORDER = ps.AIR_ORDER
        LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_SEGMENT seg ON ps.SEGMENT = seg.ID
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON rc.CERT_TYPE = sid.CFG_CODE
        AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL = 'KEY_ACCOUNT_TRAVEL'
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.ETL_DATE >= @ETL_DATE
  AND rc.CERT_NO IS NOT NULL;

-- 第三步：写入预订航段事实表
INSERT INTO DWD_TEST.T_DWD_BOOKING_SEG_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 登机点 + 出发日期 + 出发时间 + 证件号 + 姓名
    CONCAT(
            COALESCE(o.PNR, ''),
            COALESCE(seg.BOARD_POINT, ''),
            CASE
                WHEN seg.DEPARTURE_DATE IS NOT NULL
                    THEN DATE_FORMAT(seg.DEPARTURE_DATE, '%Y%m%d%H%i%s')
                ELSE ''
                END,
            p.CERT_NO,
        -- 乘客姓名标准化（去除空白字符）
            REPLACE(COALESCE(p.NAME, ''), ' ', '')
        ) AS PK_ID,

    o.ORDER_NO AS CHANNEL_ORDER_ID,

    -- 预订渠道标准化
    'SCSME' AS AK_CHANNEL,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_TEST.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER p ON o.ID = p.AIR_ORDER
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT ps ON p.AIR_ORDER = ps.AIR_ORDER
         LEFT JOIN ODS_TEST.T_ODS_DKHCL_AIR_ORDER_SEGMENT seg ON ps.SEGMENT = seg.ID
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND seg.BOARD_POINT IS NOT NULL
  AND seg.DEPARTURE_DATE IS NOT NULL
  AND p.CERT_NO IS NOT NULL
  AND p.NAME IS NOT NULL;







-- 1、机票-预订-航段级事实表
-- 是否为返乡段
-- "以下情况为是，否则为否
-- 1、如果乘机人证件类型为=身份证，并且 乘机人证件号码对应的省份（通过《身份证号-省份+地级市》）与到达机场对应的省份（航程维表：省）相同。
-- 2、并且起飞机场（机场维表：省）和到达机场（机场维表：省）不在一个省份。"

INSERT INTO DWD_TEST.T_DWD_BOOKING_SEG_FACT
(PK_ID, HOMECOMING_SEG, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT t.PK_ID,
       CASE
           WHEN t.CERT_TYPE = 'NI' -- 身份证类型
               AND pc.PROVINCE = addr_arr.PROVINCE -- 与到达机场省份相同
               AND addr_dep.PROVINCE != addr_arr.PROVINCE -- 起飞机场与到达机场省份不同
               THEN 1
           ELSE 0
           END AS HOMECOMING_SEG,
       NOW() AS SYSTEM_CREATETIME,
       NOW() AS SYSTEM_LAST_UPDATETIME

FROM DWD_TEST.T_DWD_BOOKING_SEG_FACT t
         LEFT JOIN DIM_TEST.T_DIM_ADDRESS_DIM addr_dep
                   ON t.FK_DEPAIRPORT = addr_dep.ADDRESS_KEY -- 起飞机场三字码关联
         LEFT JOIN DIM_TEST.T_DIM_ADDRESS_DIM addr_arr
                   ON t.FK_ARRIAIRPORT = addr_arr.ADDRESS_KEY -- 到达机场三字码关联
         LEFT JOIN DIM_TEST.T_DIM_PROVINCE_CITY_DIM pc
                   ON pc.ID = SUBSTRING(SM4_DECRYPT(FROM_BASE64(t.CERT_NUMBER), FROM_BASE64(@SM4_KEY)), 1,4)
                       AND pc.PROVINCE = addr_arr.PROVINCE
WHERE t.FK_DEPAIRPORT is not null
  and t.DATA_ACTIVE = 1
  and t.FK_ARRIAIRPORT is not null
  and t.CERT_NUMBER is not null
  and t.CERT_TYPE = 'NI'
  AND addr_dep.ADDRESS_KEY is not null
  AND addr_arr.ADDRESS_KEY is not null
  AND addr_dep.PROVINCE is not null
  AND addr_arr.PROVINCE is not null
  and (t.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR t.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));


-- 2、机票-预订-航段级事实表
-- 是否为自己订票
-- "1、机票预订-航段级、机票出票-客票级、机票出票-航段级：判断乘机人TID是否与预订人TID一致。如果一致则为是。否则为否。
-- 2、成行-航段级，退票-航段级：通过“主键”“出票-航段级反写”"

INSERT INTO DWD_TEST.T_DWD_BOOKING_SEG_FACT
(PK_ID, SELF_BOOKING, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT t.PK_ID,
       CASE
           WHEN t.FK_BOOKING_USER_TID = t.FK_BOOKING_USER_ORIGIN_ID
               THEN 1
           ELSE 0
           END AS SELF_BOOKING,
       NOW() AS SYSTEM_CREATETIME,
       NOW() AS SYSTEM_LAST_UPDATETIME
FROM DWD_TEST.T_DWD_BOOKING_SEG_FACT t
WHERE t.FK_BOOKING_USER_TID is not null
  and t.DATA_ACTIVE = 1
  and t.FK_BOOKING_USER_ORIGIN_ID is not null
  and (t.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR t.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));

