INSERT INTO DIM_TEST.T_DIM_CUSTOM_DIM (SYSTEM_KEY,IS_BLACKLIST_USER,CREATE_TIME,UPDATE_TIME)
SELECT
    TO_BASE64(SM4_ENCRYPT(b.CUSTOMER_ID, FROM_BASE64(@SM4_KEY))) AS SYSTEM_KEY,
    CASE
        WHEN a.EFFECTIVE_STATUS IS NOT NULL
            AND a.ENABLE IS NOT NULL
            AND a.EFFECTIVE_STATUS = '1'
            AND a.ENABLE = '1'
            THEN TRUE
        ELSE FALSE
        END AS IS_BLACKLIST_USER,
    CURRENT_TIMESTAMP(3) AS CREATE_TIME,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_TEST.T_ODS_ZXYH_CRM_BLOCKLIST a
         INNER JOIN ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER b
                    ON a.CONTEXT = b.CUSTOMER_ID;
WHERE a.ETL_DATE = @ETL_DATE;