INSERT INTO DIM_TEST.T_DIM_CUSTOM_DIM (CUSTOMER_ID,T_ID,SYSTEM_KEY,INVOICE_TITLE,CREATE_TIME,UPDATE_TIME)
SELECT
    a.CUSTOMER_ID,
    CONCAT(TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY))), TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY)))) AS T_ID,
    TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY))) AS SYSTEM_KEY,
    a.TAXPAYER_NAME,
    CURRENT_TIMESTAMP(3) AS CREATE_TIME,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_INVOICE_TITLE a
         INNER JOIN ODS_TEST.CRM_CUSTOMER b
                    ON a.CUSTOMER_ID = b.CUSTOMER_ID;
WHERE  a.TAXPAYER_NAME is not null
AND a.ETL_DATE = @ETL_DATE;