INSERT INTO DIM_TEST.T_DIM_CUSTOM_DIM (CUSTOMER_ID,T_ID,SYSTEM_KEY,SHIP_ADDRESS,CREATE_TIME,UPDATE_TIME)
SELECT
    a.CUSTOMER_ID,
    CONCAT(TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY))), TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY)))) AS T_ID,
    TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY))) AS SYSTEM_KEY,
    a.FULL_ADDRESS,
    CURRENT_TIMESTAMP(3) AS CREATE_TIME,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_ADDRESS a
    INNER JOIN ODS_TEST.CRM_CUSTOMER b
    ON a.CUSTOMER_ID = b.CUSTOMER_ID;
WHERE  a.FULL_ADDRESS is not null;