-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    now() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_INVOICE_TITLE t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.TAXPAYER_NAME IS NOT NULL
  AND t1.CUSTOMER_ID IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    now() CREATE_TIME,
    now() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_INVOICE_TITLE t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND t1.TAXPAYER_NAME IS NOT NULL
  AND t1.CUSTOMER_ID IS NOT NULL;
