INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    now() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.CUSTOMER_ID IS NOT NULL;


-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    now() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_CONTACT_CERT_VIEW t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.CUSTOMER_ID IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    now() CREATE_TIME,
    now() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_CONTACT_CERT_VIEW t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND t1.CUSTOMER_ID IS NOT NULL;

-- 第三步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    t1.CONTACT_NUMBER STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    now() CREATE_TIME,
    now() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_CONTACT_CERT_VIEW t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.CERTIFICATION_TYPE in ('1', '2')
  AND t1.CERTIFICATION_STATUS = '1'
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.CONTACT_NUMBER IS NOT NULL and t1.CONTACT_NUMBER != '';

-- 第四步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    t1.CERT_NUMBER STRONGID,
    IFNULL(sid.CFG_VALUE, t1.CERT_TYPE) AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    now() CREATE_TIME,
    now() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_CERT t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON t1.CERT_TYPE = sid.CFG_CODE
        AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL = 'DIRECT_SALES_USER'
WHERE t1.REAL_NAME_FLAG = '1'
  AND t1.CERT_TYPE is not null and t1.CERT_TYPE != ''
  AND t1.CERT_NUMBER IS NOT NULL and t1.CERT_NUMBER != ''
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.CUSTOMER_ID IS NOT NULL;

INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    now() CREATE_TIME,
    now() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.CUSTOMER_ID is not null and t1.CUSTOMER_ID != ''
  AND t1.ETL_DATE >= @ETL_DATE;

-- 第五步：写入手机号码表
INSERT INTO DIM_TEST.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    IS_DIRECT_SALE_MOBILE,
    MOBILE_NUMBER,
    CURRENT_PHONE_HIGHEST_PRIORITY,
    IS_VIRTUAL_MOBILE,
    CREATE_TIME,
    UPDATE_TIME
)
SELECT
    -- 主键：TID + 手机号
    CONCAT(
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))),
            COALESCE(t1.CONTACT_NUMBER, '')
        ) AS SYSTEM_KEY,

    -- TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) AS T_ID,
    -- 是否直销实名认证手机号
    CASE
        WHEN t1.CERTIFICATION_TYPE IN ('1', '2')
            AND t1.CERTIFICATION_STATUS = '1'
            AND t1.CONTACT_NUMBER IS NOT NULL
            AND t1.CONTACT_NUMBER != ''
            THEN true
        ELSE false
        END AS IS_DIRECT_SALE_MOBILE,

    -- 手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.CONTACT_NUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS MOBILE_NUMBER,
    -- 当前手机号最高优先级
    CASE
        -- 实名认证标志为1
        WHEN t1.REAL_NAME_FLAG = '1' THEN
            CASE
                -- 实名认证类型为0或1
                WHEN t1.REAL_NAME_TYPE IN ('0', '1') THEN 1
                ELSE 5
                END
        ELSE 7
        END AS CURRENT_PHONE_HIGHEST_PRIORITY,

    -- 是否虚拟手机号:手机号以特定前缀开头
    CASE
        WHEN t1.CONTACT_NUMBER LIKE '170%'
            OR t1.CONTACT_NUMBER LIKE '171%'
            OR t1.CONTACT_NUMBER LIKE '162%'
            OR t1.CONTACT_NUMBER LIKE '165%'
            OR t1.CONTACT_NUMBER LIKE '167%'
            THEN true
        ELSE false
        END AS IS_VIRTUAL_MOBILE,

    now() AS CREATE_TIME,
    now() AS UPDATE_TIME

FROM ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_CONTACT_CERT_VIEW t1
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  -- 确保手机号不为空
  AND t1.CONTACT_NUMBER IS NOT NULL
  AND t1.CONTACT_NUMBER != ''
  -- 确保客户ID不为空
  AND t1.CUSTOMER_ID IS NOT NULL;


-- 第六步：写入直销注册事实表
INSERT INTO DWD_TEST.T_DWD_REGISTER_UDO_FACT
(
    PK_ID,
    FK_REGISTER_USER,
    FK_REGISTER_DATE,
    REGISTER_TIME,
    AK_REGISTER_CHANNEL,
    REGISTER_COUNT,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：加密后的CUSTOMER_ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) AS PK_ID,

    -- 注册用户TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) AS FK_REGISTER_USER,

    -- 注册日期
    CAST(t1.REGIST_DATE AS DATE)  AS FK_REGISTER_DATE,

    -- 注册时间
    DATE_FORMAT(t1.REGIST_DATE, '%H:%i:%s') AS REGISTER_TIME,

    -- 注册渠道
    t1.REGIST_CHANNEL AS AK_REGISTER_CHANNEL,

    -- 注册计数
    1 AS REGISTER_COUNT,

    -- 源系统最后更新时间
    t1.UPDATE_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_ZXYH_CRM_CUSTOMER_CONTACT_CERT_VIEW t1
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(t1.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.CUSTOMER_ID IS NOT NULL and t1.CUSTOMER_ID != '';
