-- 更新掌尚飞抖音次卡的券码字段
-- 目的:通过关联 T_ODS_ZSF_ODR_ORDER_DOUYIN 表,更新 T_DWD_MULTI_CARD_BOOK_FACT 和 T_DWD_MULTI_CARD_CANCEL_FACT 表的 COUPON_ID 字段
-- 关联条件:T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN.MAIN_ORDER_NO = T_ODS_ZSF_ODR_ORDER_DOUYIN.ORDER_NO

--SET @ETL_DATE = '2025-12-09';

-- ==================== 更新次卡预订事实表的 COUPON_ID ====================
-- 通过主订单号关联获取券码
UPDATE DWD_TEST.T_DWD_MULTI_CARD_BOOK_FACT t1
INNER JOIN (
    SELECT 
        CONCAT(COALESCE(a.ORDER_NO, ''), COALESCE(a.ID, '')) AS PK_ID,
        c.COUPON_ID
    FROM ODS_TEST.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
    LEFT JOIN ODS_TEST.T_ODS_ZSF_ODR_ORDER_DOUYIN c
        ON a.MAIN_ORDER_NO = c.ORDER_NO
    WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
        OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
      AND a.ORDER_NO IS NOT NULL
      AND a.ID IS NOT NULL
      AND c.COUPON_ID IS NOT NULL
) t2 ON t1.PK_ID = t2.PK_ID
SET t1.COUPON_ID = t2.COUPON_ID,
    t1.SYSTEM_LAST_UPDATETIME = NOW();

-- ==================== 更新次卡退订事实表的 COUPON_ID ====================
-- 通过主订单号关联获取券码
UPDATE DWD_TEST.T_DWD_MULTI_CARD_CANCEL_FACT t1
INNER JOIN (
    SELECT 
        CONCAT(COALESCE(a.ORDER_NO, ''), COALESCE(a.ID, '')) AS PK_ID,
        c.COUPON_ID
    FROM ODS_TEST.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
    LEFT JOIN ODS_TEST.T_ODS_ZSF_ODR_ORDER_DOUYIN c
        ON a.MAIN_ORDER_NO = c.ORDER_NO
    WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
        OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
      AND a.ORDER_NO IS NOT NULL
      AND a.ID IS NOT NULL
      AND c.COUPON_ID IS NOT NULL
) t2 ON t1.PK_ID = t2.PK_ID
SET t1.COUPON_ID = t2.COUPON_ID,
    t1.SYSTEM_LAST_UPDATETIME = NOW();

--事务提交
commit;
