-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))


--TID SET
INSERT INTO DIM_TEST.T_DIM_TID_SET
(TID, ETL_DATE, CREATE_TIME, TID_STATUS)
SELECT TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  as STRONGID,now() AS ETL_DATE,CURRENT_TIMESTAMP(3) AS CREATE_TIME,1
FROM ODS_TEST.T_ODS_CLK_FFP_REGISTER_INFO  a
LEFT JOIN DIM_TEST.T_DIM_TID_SET tdts ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = tdts.TID
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1' and tdts.TID IS null
and a.FCARD is not null
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
AND a.ETL_DATE = @ETL_DATE;

--事务提交
--commit;