-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--机票-预订-航段级事实表-写DWD
INSERT INTO DIM_TEST.T_DIM_CERT_DIM
(SYSTEM_KEY,T_ID,CERT_NUMBER,CERT_TYPE,IS_FREQUENT_FLYER_REGISTRATION_CARD ,CURRENT_CERT_HIGHEST_PRIORITY,UPDATE_TIME,CREATE_TIME)
SELECT
concat(TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))), COALESCE(sid.CFG_VALUE,'null'),a.FIDCARD) AS SYSTEM_KEY,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS TID ,
a.FIDCARD ,
COALESCE(sid.CFG_VALUE,'OT') AS CERT_TYPE ,
true AS IS_FREQUENT_FLYER,
1 AS CURRENT_PRIORITY,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_TEST.T_ODS_CLK_FFP_REGISTER_INFO a
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON a.FCARDTYPE =sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='FREQUENT_FLYER'
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1'
AND a.FCARD  is not null
AND a.FIDCARD is not null
AND LENGTH(SM4_DECRYPT(FROM_BASE64(a.FPHONE), FROM_BASE64(@SM4_KEY))) <15
AND a.ETL_DATE = @ETL_DATE;

--事务提交
--commit;