-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

INSERT INTO DWD_TEST.T_DWD_MEMBER_REGISTER_FACT (PK_ID,FK_TID,FREQUENT_CARD,
FK_REGISTER_DATE,FK_REGISTER_TIME,GENDER,TEST_MEMBER,FIRST_EXCH_QUALIFI,
EXPIRE_TIME,ISSUE_TIME,ISSUE_COUNTRY,CERT_TYPE,CERT_NUMBER,EN_FIRST_NAME,EN_LAST_NAME,
CN_NAME,CH_LAST_NAME,NATIONALITY,BIRTHDAY,REGIST_COUNT,FROM_INTEGRATION,DATA_ACTIVE ,DATA_ACTIVE_TIME ,
SYSTEM_LAST_UPDATETIME ,SYSTEM_CREATETIME)
SELECT
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS MEM_NUM ,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS TID ,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS FFR ,
SUBSTRING(a.FFP_CREATED,1,10) AS FFP_CREATED_DATE,
SUBSTRING(a.FFP_CREATED,12,8) AS FFP_CREATED_TIME,
a.GENDER_ID ,
 CASE
        WHEN a.TEST_MEM_FLAG = 'Y' THEN TRUE
        ELSE FALSE
END AS is_test_mem,
a.FLIGHT_FRQ_FLAG ,
a.PR_EXPIRATION_TS ,
a.PR_ISSUE_TS ,
a.PR_ISSUING_COUNTRY,
sid.CFG_VALUE AS CERT_TYPE ,
a.PR_ID ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','') ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')  ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')  ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')  ,
a.NATIONALITY,
SUBSTRING(a.BIRTH_DT,1,10) AS BIRTH_DT ,
1 as NUM_COUNT,
true AS IS_DW,
true AS DATA_ACTIVE,
now() AS DATA_ACTIVE_TIME,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_TEST.T_ODS_CLK_T_DW_D_FFP a
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON a.PR_CATEGORY_CD =sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='FREQUENT_FLYER'
WHERE a.MEM_NUM is not null
AND a.ETL_DATE = @ETL_DATE;

--事务提交
--commit;