-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--STRONG ID
INSERT INTO DIM_TEST.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME,ETL_DATE)
SELECT TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  as STRONGID,'FFP' AS STRONGID_TYPE,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS TID, 1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME, CURRENT_DATE() as ETL_DATE
FROM ODS_TEST.T_ODS_CLK_T_DW_D_FFP  a
LEFT JOIN DIM_TEST.T_DIM_STRONGID sid ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = sid.STRONGID
WHERE sid.TID IS null
AND a.ETL_DATE = @ETL_DATE;

INSERT INTO DIM_TEST.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME,ETL_DATE)
SELECT a.PR_ID  as STRONGID,COALESCE(sf.CFG_VALUE,'OT') AS STRONGID_TYPE,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS TID, 1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME, CURRENT_DATE() as ETL_DATE
FROM ODS_TEST.T_ODS_CLK_T_DW_D_FFP  a
LEFT JOIN DIM_TEST.T_DIM_STRONGID sid ON a.PR_ID  = sid.STRONGID
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))=sid.TID
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sf ON a.PR_CATEGORY_CD =sf.CFG_CODE
AND sf.CFG_TYPE = 'DOCUMENT_TYPE' AND sf.CFG_TYPE_CHANNEL ='FREQUENT_FLYER'
WHERE sid.TID  IS null
AND a.PR_ID is not null
AND a.ETL_DATE = @ETL_DATE;

--事务提交
--commit;