
package com.travelsky.trp.usercenter.data.analysis.cascrmclient.querymemberext;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "QueryMemberExtServiceImplService", targetNamespace = "http://service.QueryMemberExt.crm_interface.sda.com/", wsdlLocation = "http://10.31.0.10:58091/crm/services/queryMemberExt?wsdl")
public class QueryMemberExtServiceImplService
    extends Service
{

    private final static URL QUERYMEMBEREXTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYMEMBEREXTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName QUERYMEMBEREXTSERVICEIMPLSERVICE_QNAME = new QName("http://service.QueryMemberExt.crm_interface.sda.com/", "QueryMemberExtServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.31.0.10:58091/crm/services/queryMemberExt?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYMEMBEREXTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        QUERYMEMBEREXTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public QueryMemberExtServiceImplService() {
        super(__getWsdlLocation(), QUERYMEMBEREXTSERVICEIMPLSERVICE_QNAME);
    }

    public QueryMemberExtServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYMEMBEREXTSERVICEIMPLSERVICE_QNAME, features);
    }

    public QueryMemberExtServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, QUERYMEMBEREXTSERVICEIMPLSERVICE_QNAME);
    }

    public QueryMemberExtServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYMEMBEREXTSERVICEIMPLSERVICE_QNAME, features);
    }

    public QueryMemberExtServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryMemberExtServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns QueryMemberExtService
     */
    @WebEndpoint(name = "QueryMemberExtServicePort")
    public QueryMemberExtService getQueryMemberExtServicePort() {
        return super.getPort(new QName("http://service.QueryMemberExt.crm_interface.sda.com/", "QueryMemberExtServicePort"), QueryMemberExtService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryMemberExtService
     */
    @WebEndpoint(name = "QueryMemberExtServicePort")
    public QueryMemberExtService getQueryMemberExtServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.QueryMemberExt.crm_interface.sda.com/", "QueryMemberExtServicePort"), QueryMemberExtService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYMEMBEREXTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw QUERYMEMBEREXTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return QUERYMEMBEREXTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
