
package com.travelsky.trp.usercenter.data.analysis.cascrmclient.querymemberext;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryMemberExtService", targetNamespace = "http://service.QueryMemberExt.crm_interface.sda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryMemberExtService {


    /**
     * 
     * @param queryMemberExtInputEntity
     * @return
     *     returns com.travelsky.trp.usercenter.data.analysis.cascrmclient.querymemberext.QueryMemberExtOutputEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQueryMemberExtInfo", targetNamespace = "http://service.QueryMemberExt.crm_interface.sda.com/", className = "com.travelsky.trp.usercenter.data.analysis.cascrmclient.querymemberext.GetQueryMemberExtInfo")
    @ResponseWrapper(localName = "getQueryMemberExtInfoResponse", targetNamespace = "http://service.QueryMemberExt.crm_interface.sda.com/", className = "com.travelsky.trp.usercenter.data.analysis.cascrmclient.querymemberext.GetQueryMemberExtInfoResponse")
    public QueryMemberExtOutputEntity getQueryMemberExtInfo(
        @WebParam(name = "queryMemberExtInputEntity", targetNamespace = "")
        QueryMemberExtInputEntity queryMemberExtInputEntity);

}
