CREATE TABLE IF NOT EXISTS T_ODS_TRP_COUPON_REFUND_DETAIL (
    ID BIGINT NOT NULL COMMENT '主键ID',
    ORDER_NUMBER VARCHAR(500) REPLACE NULL COMMENT '订单号',
    BANK_ORDER_NUMBER VARCHAR(500) REPLACE NULL COMMENT '银行订单号',
    BANK_NAME VARCHAR(500) REPLACE NULL COMMENT '银行名称',
    CHANNEL VARCHAR(500) REPLACE NULL COMMENT '渠道',
    CONTACT_NAME VARCHAR(500) REPLACE NULL COMMENT '联系人姓名',
    CONTACT_PHONE_NUMBER VARCHAR(500) REPLACE NULL COMMENT '联系人手机号码',
    ORDER_DATE VARCHAR(500) REPLACE NULL COMMENT '订单日期',
    ORDER_STATUS VARCHAR(500) REPLACE NULL COMMENT '订单状态',
    VOUCHER_CODE VARCHAR(500) REPLACE NULL COMMENT '券码',
    VOUCHER_NAME VARCHAR(500) REPLACE NULL COMMENT '券名称',
    VOUCHER_AMOUNT DECIMAL(20,2) REPLACE NULL COMMENT '券面额',
    PAYMENT_AMOUNT DECIMAL(20,2) REPLACE NULL COMMENT '支付金额',
    REFUND_AMOUNT DECIMAL(20,2) REPLACE NULL COMMENT '退款金额',
    REFUND_DATE VARCHAR(500) REPLACE NULL COMMENT '退款日期',
    REFUND_STATUS VARCHAR(500) REPLACE NULL COMMENT '退款状态',
    USERNAME VARCHAR(500) REPLACE NULL COMMENT '用户名',
    ETL_CREATE_TIME DATETIME(3) REPLACE NULL COMMENT '数据入仓时间',
    ETL_UPDATE_TIME DATETIME(3) REPLACE NULL COMMENT '数据在数仓更新时间',
    ETL_DATE DATE REPLACE NULL COMMENT '数据ETL日期'
)
ENGINE=OLAP
AGGREGATE KEY(`ID`)
COMMENT 'SC_优惠券退款报表明细表'
DISTRIBUTED BY HASH(`ID`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V1",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);