CREATE TABLE IF NOT EXISTS T_ODS_TRP_INSURANCE_SALE_DETAIL (
    ID BIGINT NOT NULL COMMENT '主键ID',
    ORDER_NUMBER VARCHAR(500) REPLACE NULL COMMENT '订单号',
    PASSENGER_NAME VARCHAR(500) REPLACE NULL COMMENT '旅客姓名',
    BOOKING_TIME VARCHAR(500) REPLACE NULL COMMENT '订票时间',
    BANK_ORDER_NUMBER VARCHAR(500) REPLACE NULL COMMENT '银行订单号',
    BANK_NAME VARCHAR(500) REPLACE NULL COMMENT '银行名称',
    PNR VARCHAR(500) REPLACE NULL COMMENT 'PNR',
    TICKET_NUMBER VARCHAR(500) REPLACE NULL COMMENT '票号',
    TICKET_NATURE VARCHAR(500) REPLACE NULL COMMENT '客票性质',
    ACCOUNT_USERNAME VARCHAR(500) REPLACE NULL COMMENT '账号用户名',
    DEPARTURE_DATE VARCHAR(500) REPLACE NULL COMMENT '起飞日期',
    DEPARTURE_CITY VARCHAR(500) REPLACE NULL COMMENT '出发地',
    ARRIVAL_CITY VARCHAR(500) REPLACE NULL COMMENT '到达地',
    ID_TYPE VARCHAR(500) REPLACE NULL COMMENT '证件类型',
    ID_NUMBER VARCHAR(500) REPLACE NULL COMMENT '证件号码',
    INSURANCE_POLICY_NUMBER VARCHAR(500) REPLACE NULL COMMENT '保险单号',
    INSURANCE_FEE DECIMAL(20,2) REPLACE NULL COMMENT '保险费用',
    PAYMENT_TIME VARCHAR(500) REPLACE NULL COMMENT '支付时间',
    INSURANCE_PURCHASE_SUCCESS_TIME VARCHAR(500) REPLACE NULL COMMENT '购保成功时间',
    INSURANCE_PURCHASE_TYPE VARCHAR(500) REPLACE NULL COMMENT '购保类型',
    INSURANCE_STATUS VARCHAR(500) REPLACE NULL COMMENT '保险状态',
    REMARKS VARCHAR(500) REPLACE NULL COMMENT '备注',
    INSURANCE_TYPE VARCHAR(500) REPLACE NULL COMMENT '保险类型',
    CHANNEL_SOURCE VARCHAR(500) REPLACE NULL COMMENT '渠道来源',
    INSURANCE_PURCHASE_STATUS VARCHAR(500) REPLACE NULL COMMENT '购保状态',
    INSURANCE_PURCHASE_INITIATION_TIME VARCHAR(500) REPLACE NULL COMMENT '购保发起时间',
    INSURANCE_PURCHASE_FAILURE_TIME VARCHAR(500) REPLACE NULL COMMENT '购保失败时间',
    SITE VARCHAR(500) REPLACE NULL COMMENT '站点',
    CURRENCY VARCHAR(500) REPLACE NULL COMMENT '币种',
    AIRLINE_ORDER_NUMBER VARCHAR(500) REPLACE NULL COMMENT '航联订单号',
    ETL_CREATE_TIME DATETIME(3) REPLACE NULL COMMENT '数据入仓时间',
    ETL_UPDATE_TIME DATETIME(3) REPLACE NULL COMMENT '数据在数仓更新时间',
    ETL_DATE DATE REPLACE NULL COMMENT '数据ETL日期'
)
ENGINE=OLAP
AGGREGATE KEY(`ID`)
COMMENT 'SC 保险销售报表明细表'
DISTRIBUTED BY HASH(`ID`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V1",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);