-- 掌尚飞抖音次卡 T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN 写入
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
-- 1.1 证件号TID写入
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND tds.TID IS NULL
  AND a.CERT_NO IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
-- 2.1 证件号STRONGID写入
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, 'OT') AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON a.CERT_TYPE = sid.CFG_CODE
            AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
            AND sid.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 3.3 写入证件信息维表 (T_DIM_CERT_DIM)
INSERT INTO DIM_PROD.T_DIM_CERT_DIM
(
    SYSTEM_KEY,
    T_ID,
    CERT_TYPE,
    CERT_NUMBER,
    CERT_EXPIRE_DATE,
    CURRENT_CERT_HIGHEST_PRIORITY,
    UPDATE_TIME,
    CREATE_TIME
)
SELECT
    -- 主键：TID + 证件类型 + 证件号
    CONCAT(
            COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
            COALESCE(IFNULL(sid1.CFG_VALUE, a.CERT_TYPE), ''),
            COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))), '')
        ) AS SYSTEM_KEY,

    -- TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS T_ID,
    -- 证件类型标准化
    IFNULL(sid1.CFG_VALUE, a.CERT_TYPE) AS CERT_TYPE,
    -- 证件号码（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CERT_NUMBER,
    -- 证件过期日期
    CASE WHEN a.EXPIRATION_DATE IS NOT NULL THEN STR_TO_DATE(a.EXPIRATION_DATE, '%Y-%m-%d') ELSE NULL END AS CERT_EXPIRE_DATE,
    -- 当前证件最高优先级
    1 AS CURRENT_CERT_HIGHEST_PRIORITY,
    NOW() AS UPDATE_TIME,
    NOW() AS CREATE_TIME
FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.CERT_TYPE = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'DOCUMENT_TYPE' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL;





-- =====================================================================
-- 大客户差旅系统 DKHCL T_ODS_DKHCL_CRM_EMPLOYEE_CERT 写入
-- =====================================================================
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
-- 1.1 证件号TID写入
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_DKHCL_CRM_COMPANY comp
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE emp ON comp.ID = emp.COMPANY_ID
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT cert ON emp.ID = cert.EMPLOYEE_ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE comp.CUS_BIG_CODE = '99998181'
  AND cert.ETL_DATE = @ETL_DATE
  AND tds.TID IS NULL
  AND cert.CERT_NO IS NOT NULL
  AND TRIM(cert.CERT_NO) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
-- 2.1 证件号STRONGID写入
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, 'OT') AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_DKHCL_CRM_COMPANY comp
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE emp ON comp.ID = emp.COMPANY_ID
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT cert ON emp.ID = cert.EMPLOYEE_ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON cert.CERT_TYPE = sid.CFG_CODE
            AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
            AND sid.CFG_TYPE_CHANNEL = 'KEY_ACCOUNT_TRAVEL'
WHERE comp.CUS_BIG_CODE = '99998181'
  AND cert.ETL_DATE = @ETL_DATE
  AND cert.CERT_NO IS NOT NULL
  AND TRIM(cert.CERT_NO) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入证件信息维表 (T_DIM_CERT_DIM) ====================
INSERT INTO DIM_PROD.T_DIM_CERT_DIM
(
    SYSTEM_KEY,
    T_ID,
    CERT_TYPE,
    CERT_NUMBER,
    CERT_EXPIRE_DATE,
    CURRENT_CERT_HIGHEST_PRIORITY,
    UPDATE_TIME,
    CREATE_TIME,
    IS_CORP_TRAVEL_MILITARY_CARD
)
SELECT
    -- 主键：TID + 证件类型 + 证件号
    CONCAT(
            COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
            COALESCE(IFNULL(sid1.CFG_VALUE, cert.CERT_TYPE), ''),
            COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))), '')
        ) AS SYSTEM_KEY,

    -- TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS T_ID,
    -- 证件类型标准化
    IFNULL(sid1.CFG_VALUE, cert.CERT_TYPE) AS CERT_TYPE,
    -- 证件号码（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CERT_NUMBER,
    -- 证件过期日期
    CASE WHEN cert.EFFECTIVE_DATE IS NOT NULL THEN CAST(cert.EFFECTIVE_DATE AS DATE) ELSE NULL END AS CERT_EXPIRE_DATE,
    -- 当前证件最高优先级
    1 AS CURRENT_CERT_HIGHEST_PRIORITY,
    NOW() AS UPDATE_TIME,
    NOW() AS CREATE_TIME,
    -- 是否为大客户差旅军人证件：该员工拥有身份证外的其他证件时，标记为军人
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT cert_other 
            WHERE cert_other.EMPLOYEE_ID = cert.EMPLOYEE_ID 
              AND cert_other.CERT_TYPE <> '身份证'
              AND cert_other.CERT_NO IS NOT NULL 
              AND TRIM(cert_other.CERT_NO) <> ''
         )
        THEN 1 
        ELSE 0 
    END AS IS_CORP_TRAVEL_MILITARY_CARD
FROM ODS_PROD.T_ODS_DKHCL_CRM_COMPANY comp
         INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE emp ON comp.ID = emp.COMPANY_ID
         INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT cert ON emp.ID = cert.EMPLOYEE_ID
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON cert.CERT_TYPE = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'DOCUMENT_TYPE' AND sid1.CFG_TYPE_CHANNEL = 'KEY_ACCOUNT_TRAVEL'
WHERE comp.CUS_BIG_CODE = '99998181'
  AND cert.ETL_DATE = @ETL_DATE
  AND cert.CERT_NO IS NOT NULL
  AND TRIM(cert.CERT_NO) <> '';






-- 掌尚飞次卡受益人----------
-- 1.1 受益人证件号TID写入（源数据未加密，需先加密）
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARYCARD a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND tds.TID IS NULL
  AND a.CERT_NO IS NOT NULL
  AND TRIM(a.CERT_NO) != ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
-- 2.1 受益人证件号STRONGID写入（源数据未加密）
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, 'OT') AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARYCARD a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON a.CERT_TYPE = sid.CFG_CODE
            AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
            AND sid.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL
  AND TRIM(a.CERT_NO) != ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 3.3 写入证件信息维表 (T_DIM_CERT_DIM)
INSERT INTO DIM_PROD.T_DIM_CERT_DIM
(
    SYSTEM_KEY,
    T_ID,
    CERT_TYPE,
    CERT_NUMBER,
    CERT_EXPIRE_DATE,
    CURRENT_CERT_HIGHEST_PRIORITY,
    UPDATE_TIME,
    CREATE_TIME
)
SELECT
    -- 主键：TID + 证件类型 + 证件号
    CONCAT(
            COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))), ''),
            COALESCE(IFNULL(sid1.CFG_VALUE, a.CERT_TYPE), ''),
            COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))), '')
        ) AS SYSTEM_KEY,
    -- TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))) AS T_ID,
    -- 证件类型标准化
    IFNULL(sid1.CFG_VALUE, a.CERT_TYPE) AS CERT_TYPE,
    -- 证件号码（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) AS CERT_NUMBER,
    -- 证件签发国
    a.PASSPORT_ISSUE_NATION AS CERT_ISSUING_COUNTRY,
    -- 当前证件最高等级
    1 AS CURRENT_CERT_HIGHEST_PRIORITY,
    NOW() AS UPDATE_TIME,
    NOW() AS CREATE_TIME
FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARYCARD a
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.CERT_TYPE = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'DOCUMENT_TYPE' AND sid1.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL;

