SET @ETL_DATE = '2025-12-23';
SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
-- =====================================================================
-- 大客户差旅系统 DKHCL T_ODS_DKHCL_CRM_EMPLOYEE 写入手机号维表
-- =====================================================================
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
-- 1.1 证件号TID写入（基于员工证件）
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE emp
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_COMPANY comp ON comp.ID = emp.COMPANY_ID
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT cert ON emp.ID = cert.EMPLOYEE_ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE comp.CUS_BIG_CODE = '99998181'
--   AND emp.ETL_DATE = @ETL_DATE
  AND tds.TID IS NULL
  AND cert.CERT_NO IS NOT NULL
  AND TRIM(cert.CERT_NO) <> ''
  AND emp.MOBILE IS NOT NULL
  AND TRIM(emp.MOBILE) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
-- 2.1 证件号STRONGID写入
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, 'OT') AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
     ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE emp
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_COMPANY comp ON comp.ID = emp.COMPANY_ID
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT cert ON emp.ID = cert.EMPLOYEE_ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON cert.CERT_TYPE = sid.CFG_CODE
            AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
            AND sid.CFG_TYPE_CHANNEL = 'KEY_ACCOUNT_TRAVEL'
WHERE comp.CUS_BIG_CODE = '99998181'
--   AND emp.ETL_DATE = @ETL_DATE
  AND cert.CERT_NO IS NOT NULL
  AND TRIM(cert.CERT_NO) <> ''
  AND emp.MOBILE IS NOT NULL
  AND TRIM(emp.MOBILE) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入手机号维表 (T_DIM_MOBILE_DIM) ====================
INSERT INTO DIM_PROD.T_DIM_USER_DIM
(
    PK_ID,
    CN_NAME,
    NATIONALITY,
    CREATE_TIME,
    UPDATE_TIME
)
SELECT
    -- TID（基于证件号）
    IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS PK_ID,
    emp.NAME AS CN_NAME,
    cert.NATIONALITY AS NATIONALITY,
    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,

     FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE emp
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_COMPANY comp ON comp.ID = emp.COMPANY_ID
        INNER JOIN ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT cert ON emp.ID = cert.EMPLOYEE_ID
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE comp.CUS_BIG_CODE = '99998181'
  AND TRIM(emp.MOBILE) <> ''
  AND cert.CERT_NO IS NOT NULL
  AND TRIM(cert.CERT_NO) <> '';
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(cert.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;



-- =====================================================================
-- 鲁雁管家 LYGJ T_ODS_LYGJ_COMPLAINT_INFO_ACTIVITI 写入手机号维表
-- TID来源：证件号 CARD_NUM
-- 手机号：PHONENUM
-- =====================================================================
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
-- 1.1 证件号TID写入（基于CARD_NUM）
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_LYGJ_COMPLAINT_INFO_ACTIVITI lygj
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   lygj.ETL_DATE = @ETL_DATE
  tds.TID IS NULL
  AND lygj.CARD_NUM IS NOT NULL
  AND TRIM(lygj.CARD_NUM) <> ''
  AND lygj.PHONENUM IS NOT NULL
  AND TRIM(lygj.PHONENUM) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
-- 2.1 证件号STRONGID写入
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, 'OT') AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_LYGJ_COMPLAINT_INFO_ACTIVITI lygj
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON lygj.CARD_TYPE = sid.CFG_CODE
            AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
            AND sid.CFG_TYPE_CHANNEL = 'LUYAN_STEWARD'
WHERE
--   lygj.ETL_DATE = @ETL_DATE
  lygj.CARD_NUM IS NOT NULL
  AND TRIM(lygj.CARD_NUM) <> ''
  AND lygj.PHONENUM IS NOT NULL
  AND TRIM(lygj.PHONENUM) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入手机号维表 (T_DIM_MOBILE_DIM) ====================
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    MOBILE_NUMBER,
    CREATE_TIME,
    UPDATE_TIME,
    CURRENT_PHONE_HIGHEST_PRIORITY
)
SELECT
    -- 主键：TID + 手机号
    CONCAT(
        COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
        COALESCE(TO_BASE64(SM4_ENCRYPT(SM4_DECRYPT(FROM_BASE64(lygj.PHONENUM), FROM_BASE64(@SM4_KEY)), FROM_BASE64(@SM4_KEY))), '')
    ) AS SYSTEM_KEY,
    -- TID（基于证件号）
    IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS T_ID,
    -- 手机号（加密）
    TO_BASE64(SM4_ENCRYPT(SM4_DECRYPT(FROM_BASE64(lygj.PHONENUM), FROM_BASE64(@SM4_KEY)), FROM_BASE64(@SM4_KEY))) AS MOBILE_NUMBER,

    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,
    4 AS CURRENT_PHONE_HIGHEST_PRIORITY

FROM ODS_PROD.T_ODS_LYGJ_COMPLAINT_INFO_ACTIVITI lygj
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(lygj.CARD_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE
--   lygj.ETL_DATE = @ETL_DATE
  lygj.PHONENUM IS NOT NULL
  AND TRIM(lygj.PHONENUM) <> ''
  AND lygj.CARD_NUM IS NOT NULL
  AND TRIM(lygj.CARD_NUM) <> '';




-- =====================================================================
-- 白屏票务 KFBP T_ODS_KFBP_BUS_ORDER 写入手机号维表
-- TID来源：手机号 CUR_TEL
-- 手机号：CUR_TEL
-- =====================================================================
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   BO.ETL_DATE = @ETL_DATE
  tds.TID IS NULL
  AND BO.CUR_TEL IS NOT NULL
  AND TRIM(BO.CUR_TEL) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   BO.ETL_DATE = @ETL_DATE
  BO.CUR_TEL IS NOT NULL
  AND TRIM(BO.CUR_TEL) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入手机号维表 (T_DIM_MOBILE_DIM) ====================
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    MOBILE_NUMBER,
    CREATE_TIME,
    UPDATE_TIME,
    CURRENT_PHONE_HIGHEST_PRIORITY
)
SELECT
    -- 主键：TID + 手机号
    CONCAT(
        COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
        COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))), '')
    ) AS SYSTEM_KEY,
    -- TID（基于手机号）
    IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS T_ID,
    -- 手机号（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS MOBILE_NUMBER,
    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,
    5 AS CURRENT_PHONE_HIGHEST_PRIORITY
FROM ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE
--   BO.ETL_DATE = @ETL_DATE
  BO.CUR_TEL IS NOT NULL
  AND TRIM(BO.CUR_TEL) <> '';




-- =====================================================================
-- 升舱整合 JSSC 写入手机号维表
-- TID来源：预订人手机号 EMAILPHONENUMBER 和 MOBILE
-- 手机号：EMAILPHONENUMBER 和 MOBILE
-- =====================================================================
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
-- 1.1 基于TB_CUSTOMER.EMAILPHONENUMBER
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_JSSC_TB_ORDER t2
        LEFT JOIN ODS_PROD.T_ODS_JSSC_TB_CUSTOMER t3 ON t2.CUSTOMER_ID = t3.ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   t2.ETL_DATE = @ETL_DATE
  tds.TID IS NULL
  AND t3.EMAILPHONENUMBER IS NOT NULL
  AND TRIM(t3.EMAILPHONENUMBER) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 1.2 基于TB_OTA_ORDER.MOBILE
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_JSSC_TB_OTA_ORDER ota
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   ota.ETL_DATE = @ETL_DATE
  tds.TID IS NULL
  AND ota.MOBILE IS NOT NULL
  AND TRIM(ota.MOBILE) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
-- 2.1 基于TB_CUSTOMER.EMAILPHONENUMBER
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_JSSC_TB_ORDER t2
        LEFT JOIN ODS_PROD.T_ODS_JSSC_TB_CUSTOMER t3 ON t2.CUSTOMER_ID = t3.ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   t2.ETL_DATE = @ETL_DATE
   t3.EMAILPHONENUMBER IS NOT NULL
  AND TRIM(t3.EMAILPHONENUMBER) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 2.2 基于TB_OTA_ORDER.MOBILE
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_JSSC_TB_OTA_ORDER ota
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   ota.ETL_DATE = @ETL_DATE
  ota.MOBILE IS NOT NULL
  AND TRIM(ota.MOBILE) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入手机号维表 (T_DIM_MOBILE_DIM) ====================
-- 3.1 基于TB_CUSTOMER.EMAILPHONENUMBER
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    MOBILE_NUMBER,
    CREATE_TIME,
    UPDATE_TIME,
    CURRENT_PHONE_HIGHEST_PRIORITY
)
SELECT
    -- 主键：TID + 手机号
    CONCAT(
        COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
        COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))), '')
    ) AS SYSTEM_KEY,
    -- TID（基于手机号）
    IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS T_ID,
    -- 手机号（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS MOBILE_NUMBER,

    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,
    5 AS CURRENT_PHONE_HIGHEST_PRIORITY
FROM ODS_PROD.T_ODS_JSSC_TB_ORDER t2
         LEFT JOIN ODS_PROD.T_ODS_JSSC_TB_CUSTOMER t3 ON t2.CUSTOMER_ID = t3.ID
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t3.EMAILPHONENUMBER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE
--   t2.ETL_DATE = @ETL_DATE
  t3.EMAILPHONENUMBER IS NOT NULL
  AND TRIM(t3.EMAILPHONENUMBER) <> '';

-- 3.2 基于TB_OTA_ORDER.MOBILE
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    MOBILE_NUMBER,
    CREATE_TIME,
    UPDATE_TIME,
    CURRENT_PHONE_HIGHEST_PRIORITY
)
SELECT
    -- 主键：TID + 手机号
    CONCAT(
        COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
        COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))), '')
    ) AS SYSTEM_KEY,
    -- TID（基于手机号）
    IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS T_ID,
    -- 手机号（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS MOBILE_NUMBER,

    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,
    5 AS CURRENT_PHONE_HIGHEST_PRIORITY
FROM ODS_PROD.T_ODS_JSSC_TB_OTA_ORDER ota
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ota.MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE
--   ota.ETL_DATE = @ETL_DATE
  ota.MOBILE IS NOT NULL
  AND TRIM(ota.MOBILE) <> '';


-- ====================================================================
-- 企微小山 QWSY T_ODS_QWSY_CUSTOMER_INFO 写入手机号维表
-- TID来源：手机号 FOLLOW_REMARK_MOBILES
-- 手机号：FOLLOW_REMARK_MOBILES
-- =====================================================================
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_QWSY_CUSTOMER_INFO qwsy
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   qwsy.ETL_DATE = @ETL_DATE
  tds.TID IS NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL
  AND TRIM(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) <> '';

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_QWSY_CUSTOMER_INFO qwsy
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   qwsy.ETL_DATE = @ETL_DATE
  TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL
  AND TRIM(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) <> '';

-- ==================== 第三步：写入手机号维表 (T_DIM_MOBILE_DIM) ====================
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    MOBILE_NUMBER,
    CREATE_TIME,
    UPDATE_TIME,
    CURRENT_PHONE_HIGHEST_PRIORITY,
    IS_WECOM_XIAOSHAN_CUSTOMER_MOBILE
)
SELECT
    -- 主键：TID + 手机号
    CONCAT(
        COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
        COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))), '')
    ) AS SYSTEM_KEY,
    -- TID（基于手机号）
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS T_ID,
    -- 手机号（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(qwsy.FOLLOW_REMARK_MOBILES), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS MOBILE_NUMBER,

    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,
    5 AS CURRENT_PHONE_HIGHEST_PRIORITY,
    1 AS IS_WECOM_XIAOSHAN_CUSTOMER_MOBILE
FROM ODS_PROD.T_ODS_QWSY_CUSTOMER_INFO qwsy
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            qwsy.FOLLOW_REMARK_MOBILES = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE
--   qwsy.ETL_DATE = @ETL_DATE
  qwsy.FOLLOW_REMARK_MOBILES IS NOT NULL
  AND TRIM(qwsy.FOLLOW_REMARK_MOBILES) <> '';


-- =====================================================================
-- 升舱整合平台 JSSC_EXTERNAL T_ODS_JSSC_TB_EXTERNAL_ORDERS 写入手机号维表
-- TID来源：证件号 PSG_CARDID (用户说使用证件号，虽然字段名为MOBILE)
-- 手机号：MOBILE
-- =====================================================================
-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_JSSC_TB_EXTERNAL_ORDERS ext
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   ext.ETL_DATE = @ETL_DATE
  tds.TID IS NULL
  AND ext.PSG_CARDID IS NOT NULL
  AND TRIM(ext.PSG_CARDID) <> ''
  AND ext.MOBILE IS NOT NULL
  AND TRIM(ext.MOBILE) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, 'OT') AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_JSSC_TB_EXTERNAL_ORDERS ext
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE
--   ext.ETL_DATE = @ETL_DATE
  ext.PSG_CARDID IS NOT NULL
  AND TRIM(ext.PSG_CARDID) <> ''
  AND ext.MOBILE IS NOT NULL
  AND TRIM(ext.MOBILE) <> ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入手机号维表 (T_DIM_MOBILE_DIM) ====================
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    MOBILE_NUMBER,
    CREATE_TIME,
    UPDATE_TIME,
    CURRENT_PHONE_HIGHEST_PRIORITY
)
SELECT
    -- 主键：TID + 手机号
    CONCAT(
        COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
        COALESCE(TO_BASE64(SM4_ENCRYPT(SM4_DECRYPT(FROM_BASE64(ext.MOBILE), FROM_BASE64(@SM4_KEY)), FROM_BASE64(@SM4_KEY))), '')
    ) AS SYSTEM_KEY,
    -- TID（基于证件号）
    IFNULL(
        tds.TID,
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
    ) AS T_ID,
    -- 手机号（加密）
    TO_BASE64(SM4_ENCRYPT(SM4_DECRYPT(FROM_BASE64(ext.MOBILE), FROM_BASE64(@SM4_KEY)), FROM_BASE64(@SM4_KEY))) AS MOBILE_NUMBER,

    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME,
    3 AS CURRENT_PHONE_HIGHEST_PRIORITY

FROM ODS_PROD.T_ODS_JSSC_TB_EXTERNAL_ORDERS ext
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(ext.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE
--   ext.ETL_DATE = @ETL_DATE
  ext.MOBILE IS NOT NULL
  AND TRIM(ext.MOBILE) <> ''
  AND ext.PSG_CARDID IS NOT NULL
  AND TRIM(ext.PSG_CARDID) <> '';

