-- 掌上飞抖音次卡受益人数据写入DWD层和DIM层
-- 数据来源：T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN (抖音次卡受益人表) + T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION_DOUYIN (客户关系表)
-- 目标表：
-- 1. T_DWD_MULTI_CARD_BOOK_FACT (次卡预订事实表)
-- 2. T_DWD_MULTI_CARD_CANCEL_FACT (次卡退订事实表)
-- 3. T_DIM_CERT_DIM (证件信息维表)
-- 4. T_DIM_USER_DIM (用户维表)
-- 5. T_DIM_MOBILE_DIM (手机号维表)

--SET @ETL_DATE = '2025-12-09';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';

-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
-- 1.1 受益人证件号TID写入
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND tds.TID IS NULL
  AND a.CERT_NO IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;


-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================

-- 2.1 受益人证件号STRONGID写入
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, 'OT') AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON a.CERT_TYPE = sid.CFG_CODE
            AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
            AND sid.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;



-- ==================== 第三步：写入业务事实表和维表 ====================

-- 3.1 写入次卡预订事实表 (T_DWD_MULTI_CARD_BOOK_FACT)
INSERT INTO DWD_PROD.T_DWD_MULTI_CARD_BOOK_FACT
(
    PK_ID,
    AK_ORDERNUM,
    ARK_MAINORDERNUM ,
    PROD_NO,
    SALE_PRICE,
    PROD_STATE,
    BENEFI_CERT_NO,
    BENEFI_CERT_TYPE,
    BENEFI_TID,
    CN_LAST_NAME,
    CN_FIRST_NAME,
    EN_FIRST_NAME,
    EN_LAST_NAME,
    BENEFI_EXPIRATION_DATE,
    BENEFI_SEX,
    BENEFI_BIRTHDAY,
    BENEFI_PASSPORT_ISSUE_NATION,
    BENEFI_PASSPORT_NATION,
    BENEFI_MOBILE_NUMBER,
    ACT_TIME,
    EXPIR_DATE,
    DEP_DATE,
    ARR_DATE,
    INTER_FLAG,
    EXCH_COUNT,
    BOOKING_CHANNEL,
    FK_BOOKING_TIME,
    FK_BOOKING_DATE,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键：订单号 + ID
    CONCAT(
            COALESCE(a.ORDER_NO, ''),
            COALESCE(a.ID, '')
        ) AS PK_ID,
    -- 订单号
    a.ORDER_NO AS AK_ORDERNUM,
    -- 关联主订单号
    a.MAIN_ORDER_NO AS AK_MAIN_ORDERNUM,
    -- 产品编号
    a.PRODUCT_NO AS PROD_NO,
    -- 销售价格
    a.SALE_PRICE AS SALE_PRICE,
    -- 产品状态
    a.STATE AS PROD_STATE,
    -- 受益人证件号（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS BENEFI_CERT_NO,
    -- 受益人证件类型标准化
    IFNULL(sid1.CFG_VALUE, a.CERT_TYPE) AS BENEFI_CERT_TYPE,
    -- 受益人TID
    IFNULL(tds1.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS BENEFI_TID,
    -- 姓名信息
    a.CN_LAST_NAME AS CN_LAST_NAME,
    a.CN_FIRST_NAME AS CN_FIRST_NAME,
    a.EN_FIRST_NAME AS EN_FIRST_NAME,
    a.EN_LAST_NAME AS EN_LAST_NAME,
    -- 证件过期日期
    CASE
        WHEN a.EXPIRATION_DATE IS NOT NULL
        THEN STR_TO_DATE(a.EXPIRATION_DATE, '%Y-%m-%d')
        ELSE NULL
    END AS BENEFI_EXPIRATION_DATE,
    -- 性别标准化
    IFNULL(sid2.CFG_VALUE, a.SEX) AS BENEFI_SEX,
    -- 生日
    CASE
        WHEN a.BIRTHDAY IS NOT NULL
        THEN STR_TO_DATE(a.BIRTHDAY, '%Y-%m-%d')
        ELSE NULL
    END AS BENEFI_BIRTHDAY,
    -- 护照签发国
    a.PASSPORT_ISSUE_NATION AS BENEFI_PASSPORT_ISSUE_NATION,
    -- 护照国籍标准化
    IFNULL(sid3.CFG_VALUE, a.PASSPORT_NATION) AS BENEFI_PASSPORT_NATION,
    -- 手机号（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS BENEFI_MOBILE_NUMBER,
    -- 激活时间
    a.ACTIVE_TIME AS ACT_TIME,
    -- 失效日期（优先使用EXPIRY_DATE）
    COALESCE(DATE(a.EXPIRY_DATE), DATE(a.ACTIVE_TIME)) AS EXPIR_DATE,
    -- 出行开始日期
    DATE(a.TRAVEL_START_DATE) AS DEP_DATE,
    -- 出行结束日期
    DATE(a.TRAVEL_END_DATE) AS ARR_DATE,
    -- 国际国内标识标准化
    IFNULL(sid4.CFG_VALUE, a.INTERNATIONAL_FLAG) AS INTER_FLAG,
    -- 兑换次数
--     CONVERT(a.EXCHANGE_NUM AS SIGNED) AS EXCH_COUNT,
    a.EXCHANGE_NUM AS EXCH_COUNT,
    -- 预订渠道标准化
    'SCDYN' AS BOOKING_CHANNEL,
    -- 预订时间
    DATE_FORMAT(a.CREATE_TIME, '%H:%i:%s') AS FK_BOOKING_TIME,

    -- 预订日期
    DATE(a.CREATE_TIME) AS FK_BOOKING_DATE,

    -- 预订人TID
    IFNULL(tds2.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    a.UPDATE_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
         LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION_DOUYIN b
                   ON a.MAIN_ORDER_NO = b.MAIN_ORDER_NO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds1 ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds1.STRONGID
        AND tds1.STRONGID_STATUS = 1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds2 ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds2.STRONGID
        AND tds2.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.CERT_TYPE = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'DOCUMENT_TYPE' AND sid1.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid2 ON a.SEX = sid2.CFG_CODE
            AND sid2.CFG_TYPE = 'GENDER' AND sid2.CFG_TYPE_CHANNEL = 'ALL'
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid3 ON a.PASSPORT_NATION = sid3.CFG_CODE
            AND sid3.CFG_TYPE = 'NATIONALITY' AND sid3.CFG_TYPE_CHANNEL = 'ALL'
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid4 ON a.INTERNATIONAL_FLAG = sid4.CFG_CODE
            AND sid4.CFG_TYPE = 'INTERNATIONAL_DOMESTIC_FLAG' AND sid4.CFG_TYPE_CHANNEL = 'ALL'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.ORDER_NO IS NOT NULL
  AND a.ID IS NOT NULL;

-- 3.2 写入次卡退订事实表 (T_DWD_MULTI_CARD_CANCEL_FACT)
INSERT INTO DWD_PROD.T_DWD_MULTI_CARD_CANCEL_FACT
(
    PK_ID,
    AK_ORDERNUM,
    ARK_MAINORDERNUM,
    PROD_NO,
    SALE_PRICE,
    PROD_STATE,
    BENEFI_CERT_NO,
    BENEFI_CERT_TYPE,
    BENEFI_TID,
    CN_LAST_NAME,
    CN_FIRST_NAME,
    EN_FIRST_NAME,
    EN_LAST_NAME,
    BENEFI_EXPIRATION_DATE,
    BENEFI_SEX,
    BENEFI_BIRTHDAY,
    BENEFI_PASSPORT_ISSUE_NATION,
    BENEFI_PASSPORT_NATION,
    BENEFI_MOBILE_NUMBER,
    ACT_TIME,
    EXPIR_DATE,
    DEP_DATE,
    ARR_DATE,
    INTER_FLAG,
    EXCH_COUNT,
    BOOKING_CHANNEL,
    FK_BOOKING_TIME,
    FK_BOOKING_DATE,
    FK_BOOKING_USER_TID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键：订单号 + ID
    CONCAT(
            COALESCE(a.ORDER_NO, ''),
            COALESCE(a.ID, '')
        ) AS PK_ID,

    a.ORDER_NO AS AK_ORDERNUM,
    a.MAIN_ORDER_NO AS AK_MAIN_ORDERNUM,
    a.PRODUCT_NO AS PROD_NO,
    a.SALE_PRICE AS SALE_PRICE,
    a.STATE AS PROD_STATE,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS BENEFI_CERT_NO,
    IFNULL(sid1.CFG_VALUE, a.CERT_TYPE) AS BENEFI_CERT_TYPE,
    IFNULL(tds1.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS BENEFI_TID,
    a.CN_LAST_NAME AS CN_LAST_NAME,
    a.CN_FIRST_NAME AS CN_FIRST_NAME,
    a.EN_FIRST_NAME AS EN_FIRST_NAME,
    a.EN_LAST_NAME AS EN_LAST_NAME,
    CASE WHEN a.EXPIRATION_DATE IS NOT NULL THEN STR_TO_DATE(a.EXPIRATION_DATE, '%Y-%m-%d') ELSE NULL END AS BENEFI_EXPIRATION_DATE,
    IFNULL(sid2.CFG_VALUE, a.SEX) AS BENEFI_SEX,
    CASE WHEN a.BIRTHDAY IS NOT NULL THEN STR_TO_DATE(a.BIRTHDAY, '%Y-%m-%d') ELSE NULL END AS BENEFI_BIRTHDAY,
    a.PASSPORT_ISSUE_NATION AS BENEFI_PASSPORT_ISSUE_NATION,
    IFNULL(sid3.CFG_VALUE, a.PASSPORT_NATION) AS BENEFI_PASSPORT_NATION,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS BENEFI_MOBILE_NUMBER,
    a.ACTIVE_TIME AS ACT_TIME,
    COALESCE(DATE(a.EXPIRY_DATE), DATE(a.ACTIVE_TIME)) AS EXPIR_DATE,
    DATE(a.TRAVEL_START_DATE) AS DEP_DATE,
    DATE(a.TRAVEL_END_DATE) AS ARR_DATE,
    IFNULL(sid4.CFG_VALUE, a.INTERNATIONAL_FLAG) AS INTER_FLAG,
--     CAST(a.EXCHANGE_NUM AS SIGNED) AS EXCH_COUNT,
    a.EXCHANGE_NUM  AS EXCH_COUNT,
    'SCDYN' AS BOOKING_CHANNEL,
    DATE_FORMAT(a.CREATE_TIME, '%H:%i:%s') AS FK_BOOKING_TIME,
    DATE(a.CREATE_TIME) AS FK_BOOKING_DATE,
    IFNULL(tds2.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    a.UPDATE_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
         LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION_DOUYIN b
                   ON a.MAIN_ORDER_NO = b.MAIN_ORDER_NO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds1 ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds1.STRONGID
        AND tds1.STRONGID_STATUS = 1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds2 ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds2.STRONGID
        AND tds2.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.CERT_TYPE = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'DOCUMENT_TYPE' AND sid1.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid2 ON a.SEX = sid2.CFG_CODE
            AND sid2.CFG_TYPE = 'GENDER' AND sid2.CFG_TYPE_CHANNEL = 'ALL'
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid3 ON a.PASSPORT_NATION = sid3.CFG_CODE
            AND sid3.CFG_TYPE = 'NATIONALITY' AND sid3.CFG_TYPE_CHANNEL = 'ALL'
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid4 ON a.INTERNATIONAL_FLAG = sid4.CFG_CODE
            AND sid4.CFG_TYPE = 'INTERNATIONAL_DOMESTIC_FLAG' AND sid4.CFG_TYPE_CHANNEL = 'ALL'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.ORDER_NO IS NOT NULL
  AND a.ID IS NOT NULL;

-- 3.3 写入证件信息维表 (T_DIM_CERT_DIM)
INSERT INTO DIM_PROD.T_DIM_CERT_DIM
(
    SYSTEM_KEY,
    T_ID,
    CERT_TYPE,
    CERT_NUMBER,
    IS_DIRECT_SALES_REAL_NAME_VERIFIED_CARD,
    IS_LY_REGIST_CARD,
    IS_FREQUENT_FLYER_REGISTRATION_CARD,
    IS_PURCHASERS_BENEFICIARY_CARD,
    IS_DOUYIN_PURCHASERS_BENEFICIARY_CARD ,
    IS_CODE_RULE_COMPLIANT,
    CERT_EXPIRE_DATE,
    CERT_ISSUING_COUNTRY,
    CURRENT_CERT_HIGHEST_PRIORITY,
    UPDATE_TIME,
    CREATE_TIME
)
SELECT
    -- 主键：TID + 证件类型 + 证件号
    CONCAT(
            COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),
            COALESCE(IFNULL(sid1.CFG_VALUE, a.CERT_TYPE), ''),
            COALESCE(TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))), '')
        ) AS SYSTEM_KEY,

    -- TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS T_ID,

    -- 证件类型标准化
    IFNULL(sid1.CFG_VALUE, a.CERT_TYPE) AS CERT_TYPE,

    -- 证件号码（加密）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CERT_NUMBER,

    -- 是否直销实名认证证件
    FALSE AS IS_DIRECT_SALES_REAL_NAME_VERIFIED_CARD,

    -- 是否鲁雁行实名认证证件
    FALSE AS IS_LY_REGIST_CARD,

    -- 是否常客注册证件
    FALSE AS IS_FREQUENT_FLYER_REGISTRATION_CARD,

    -- 是否次卡受益人证件
    FALSE AS IS_PURCHASERS_BENEFICIARY_CARD,

    -- 是否抖音次卡受益人证件
    TRUE AS IS_DOUYIN_PURCHASERS_BENEFICIARY_CARD,

    -- 是否符合编码规则（简单校验：身份证18位）
    CASE
        WHEN a.CERT_TYPE = 'NI' AND LENGTH(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY))) = 18
        THEN TRUE
        ELSE FALSE
    END AS IS_CODE_RULE_COMPLIANT,

    -- 证件过期日期
    CASE WHEN a.EXPIRATION_DATE IS NOT NULL THEN STR_TO_DATE(a.EXPIRATION_DATE, '%Y-%m-%d') ELSE NULL END AS CERT_EXPIRE_DATE,

    -- 证件签发国
    a.PASSPORT_ISSUE_NATION AS CERT_ISSUING_COUNTRY,

    -- 当前最可信来源
    1 AS CURRENT_CERT_HIGHEST_PRIORITY,

    NOW() AS UPDATE_TIME,
    NOW() AS CREATE_TIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.CERT_TYPE = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'DOCUMENT_TYPE' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL;

-- 3.4 写入用户维表 (T_DIM_USER_DIM)
INSERT INTO DIM_PROD.T_DIM_USER_DIM
(
    PK_ID,
    CN_NAME,
    EN_NAME,
    SEX,
    BIRTHDAY,
    IS_DOUYIN_CARD_PURCHASER,
    CREATE_TIME,
    UPDATE_TIME
)
SELECT
    -- 主键：TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS PK_ID,

    -- 中文姓名（去除空格并转大写）
    UPPER(REPLACE(CONCAT(COALESCE(a.CN_LAST_NAME, ''), COALESCE(a.CN_FIRST_NAME, '')), ' ', '')) AS CN_NAME,

    -- 英文姓名（去除INF/CHD等后缀）
    UPPER(TRIM(CONCAT(COALESCE(a.EN_LAST_NAME, ''), ' ', COALESCE(a.EN_FIRST_NAME, '')))) AS EN_NAME,

    -- 性别标准化
    IFNULL(sid1.CFG_VALUE, a.SEX) AS SEX,

    -- 生日
    CASE WHEN a.BIRTHDAY IS NOT NULL THEN DATE(STR_TO_DATE(a.BIRTHDAY, '%Y-%m-%d')) ELSE NULL END AS BIRTHDAY,

     -- 是否抖音次卡购买人：手机号非空（非NULL/非空字符串）则为TRUE，否则为NULL
    CASE
        WHEN a.MOBILE IS NOT NULL AND TRIM(a.MOBILE) <> '' THEN TRUE
        ELSE NULL
    END AS DOUYIN_CARD_PURCHASER,

    NOW() AS CREATE_TIME,
    NOW() AS UPDATE_TIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.SEX = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'GENDER' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL LIMIT 10;

-- 3.5 写入手机号维表 (T_DIM_MOBILE_DIM)
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(
    SYSTEM_KEY,
    T_ID,
    MOBILE_NUMBER,
    CREATE_TIME,
    UPDATE_TIME
)
SELECT

	-- 主键：TID + 手机号
	CONCAT(
	    COALESCE(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))), ''),  -- 修正括号闭合+移除内部AS
	    COALESCE(TO_BASE64(SM4_ENCRYPT(PHONE_NUM, FROM_BASE64(@SM4_KEY))), '')
	) AS SYSTEM_KEY,

	-- TID
	IFNULL(
	    tds.TID,
	    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))
	) AS T_ID,

	-- 手机号（加密）
	TO_BASE64(SM4_ENCRYPT(PHONE_NUM, FROM_BASE64(@SM4_KEY)))  AS MOBILE_NUMBER,

	NOW() AS CREATE_TIME,
	NOW() AS UPDATE_TIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE_NUM), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.PHONE_NUM IS NOT NULL;

-- ==================== 更新次卡退订预定表的 COUPON_ID ====================
-- 通过主订单号关联获取券码
INSERT INTO DWD_PROD.T_DWD_MULTI_CARD_BOOK_FACT(PK_ID, COUPON_ID)
SELECT
        CONCAT(COALESCE(a.ORDER_NO, ''), COALESCE(a.ID, '')) AS PK_ID,
        c.COUPON_ID
FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_DOUYIN c
     ON a.MAIN_ORDER_NO = c.ORDER_NO
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
         OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
AND a.ORDER_NO IS NOT NULL
AND a.ID IS NOT NULL
AND c.COUPON_ID IS NOT NULL
-- 核心条件：仅筛选目标表中已存在的PK_ID
    AND EXISTS (
        SELECT 1
        FROM DWD_TEST.T_DWD_MULTI_CARD_BOOK_FACT t
        WHERE t.PK_ID = CONCAT(COALESCE(a.ORDER_NO, ''), COALESCE(a.ID, ''))
    );

-- ==================== 更新次卡退订事实表的 COUPON_ID ====================
-- 通过主订单号关联获取券码
INSERT INTO DWD_PROD.T_DWD_MULTI_CARD_CANCEL_FACT(PK_ID,COUPON_ID)
SELECT
        CONCAT(COALESCE(a.ORDER_NO, ''), COALESCE(a.ID, '')) AS PK_ID,
        c.COUPON_ID
    FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN a
    LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_DOUYIN c
        ON a.MAIN_ORDER_NO = c.ORDER_NO
     WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
         OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
      AND a.ORDER_NO IS NOT NULL
      AND a.ID IS NOT NULL
      AND c.COUPON_ID IS NOT NULL
-- 核心条件：仅筛选目标表中已存在的PK_ID
AND EXISTS (
        SELECT 1
        FROM DWD_PROD.T_DWD_MULTI_CARD_BOOK_FACT t
        WHERE t.PK_ID = CONCAT(COALESCE(a.ORDER_NO, ''), COALESCE(a.ID, ''))
);



