-- 掌尚飞次卡支付数据写入次卡兑换事实表
-- 数据来源：T_ODS_ZSF_ODR_ORDER_PAY_SECONDARYCARD (次卡支付表)
-- 目标表：T_DWD_MULTI_CARD_REDEEM_FACT (次卡兑换事实表)
-- 业务逻辑：记录次卡抵用机票的兑换信息
-- 
-- 注意：源数据库CERT_NO字段为未加密状态，需要先加密再标准化处理

-- --SET @ETL_DATE = '2025-12-10';
-- --SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';

-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================

-- 1.1 乘客证件号TID写入（源数据未加密，需先加密）
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY_SECONDARYCARD a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND tds.TID IS NULL
  AND a.CERT_NO IS NOT NULL
  AND TRIM(a.CERT_NO) != '' AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================

-- 2.1 乘客证件号STRONGID写入（源数据未加密）
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) STRONGID,
    'OT' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY_SECONDARYCARD a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.CERT_NO IS NOT NULL
  AND TRIM(a.CERT_NO) != ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入次卡兑换事实表 ====================

-- 3.1 写入次卡兑换事实表 (T_DWD_MULTI_CARD_REDEEM_FACT)
INSERT INTO DWD_PROD.T_DWD_MULTI_CARD_REDEEM_FACT
(
    PK_ID,
    AK_ORDERNUM,
    PROD_NO,
    DEPCITY,
    ARRCITY,
    CABIN,
    CN_NAME,
    CERT_NO,
    PASSENGER_USER,
    PSGR_NAME,
    DEP_DATE,
    DEP_TIME,
    CARD_NO,
    CARD_AMOUNT,
    CARD_PAYSTATUS,
    FK_BOOKING_DATE,
    FK_BOOKING_TIME,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME
)
SELECT
    -- 主键：ID
    a.ID AS PK_ID,

    -- 订单号
    a.SALE_ORDER_NO AS AK_ORDERNUM,

    -- 产品编号
    a.PRODUCT_NO AS PROD_NO,

    -- 出发城市（标准化）
    IFNULL(sid1.CFG_VALUE, a.ORG_CITY) AS DEPCITY,

    -- 到达城市（标准化）
    IFNULL(sid2.CFG_VALUE, a.DST_CITY) AS ARRCITY,

    -- 舱位
    a.CABIN AS CABIN,

    -- 乘客姓名（标准化）
    IFNULL(sid3.CFG_VALUE, a.PSGR_NAME) AS CN_NAME,

    -- 证件号码（源数据未加密，直接使用原始值）
    a.CERT_NO AS CERT_NO,

    -- 乘客TID（先加密再查询映射，如果没有映射则回退到加密后的证件号）
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))) AS PASSENGER_USER,

    -- 乘客姓名
    a.PSGR_NAME AS PSGR_NAME,

    -- 出发日期
    a.DEP_DATE AS DEP_DATE,

    -- 出发时间
    a.DEP_TIME AS DEP_TIME,

    -- 次卡卡号（标准化）
    IFNULL(sid4.CFG_VALUE, a.CARD_NO) AS CARD_NO,

    -- 次卡抵用金额
    a.CARD_VALUE AS CARD_AMOUNT,

    -- 次卡使用状态
    a.CARD_PAY_STATUS AS CARD_PAYSTATUS,

    -- 预订日期（取CREATE_TIME的日期部分）
    DATE(a.CREATE_TIME) AS FK_BOOKING_DATE,

    -- 预订时间（取CREATE_TIME的时间部分）
    DATE_FORMAT(a.CREATE_TIME, '%H:%i:%s') AS FK_BOOKING_TIME,

    -- 源系统最后更新时间（格式化）
    CASE
        WHEN a.UPDATE_TIME IS NOT NULL
        THEN REPLACE(REPLACE(a.UPDATE_TIME, 'T', ' '), 'Z', '')
        ELSE NULL
    END AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY_SECONDARYCARD a
         -- 乘客TID映射
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         -- 出发城市标准化（假设使用TICKET_NO类型，实际应使用CITY_CODE）
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.ORG_CITY = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'CITY_CODE' AND sid1.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 到达城市标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid2 ON a.DST_CITY = sid2.CFG_CODE
            AND sid2.CFG_TYPE = 'CITY_CODE' AND sid2.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 姓名标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid3 ON a.PSGR_NAME = sid3.CFG_CODE
            AND sid3.CFG_TYPE = 'CN_NAME' AND sid3.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 次卡卡号标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid4 ON a.CARD_NO = sid4.CFG_CODE
            AND sid4.CFG_TYPE = 'DOCUMENT_NUM' AND sid4.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'));

