-- 任务名 ZSF_PRD_PRODUCT_COUPON_DOUYIN2DWD
-- 掌尚飞-抖音券码购买 T_ODS_ZSF_PRD_PRODUCT_COUPON_DOUYIN 写入事实表 T_DWD_TIKTOK_VCHR_PUR_FACT
-- 主键：数据源代号+ID 数据源代号：SCZSF

-- 1、不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_PRD_PRODUCT_COUPON_DOUYIN a
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND tds.TID IS NULL
  AND a.PHONE IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 2、模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_PRD_PRODUCT_COUPON_DOUYIN a
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.PHONE IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

COMMIT;

-- 3、写入抖音券码购买事实表
INSERT INTO DWD_PROD.T_DWD_TIKTOK_VCHR_PUR_FACT
(
    PK_ID,
    AK_ORDER_ID,
    ISSUED_COUNT,
    START_TIME,
    EXPIRE_TIME,
    DOUYIN_GOODS_NAME,
    DOUYIN_GOODS_ID,
    CARD_CODE,
    COUPON_CODE,
    PURCHASER_MOBILE_NUMBER,
    COUPON_STATUS,
    VERIFICATION_TIME,
    REFUND_TYPE,
    REFUND_ID,
    COUPON_ID,
    REFUND_APPLY_TIME,
    REFUND_AUDIT_TIME,
    REFUND_AUDIT_RESULT,
    FK_PURCHASE_DATE,
    FK_PURCHASE_TIME,
    UPDATE_TIME,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    PURCHASE_COUNT,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    a.ID AS PK_ID,
    a.ORDER_ID AS AK_ORDER_ID,
    a.COUNT AS ISSUED_COUNT,
    -- START_TIME 和 EXPIRE_TIME 是 INT 时间戳，需要转换为 DATETIME 格式
    CASE
        WHEN a.START_TIME IS NOT NULL THEN FROM_UNIXTIME(a.START_TIME)
        ELSE NULL
    END AS START_TIME,
    CASE
        WHEN a.EXPIRE_TIME IS NOT NULL THEN FROM_UNIXTIME(a.EXPIRE_TIME)
        ELSE NULL
    END AS EXPIRE_TIME,
    a.SKU_NAME AS DOUYIN_GOODS_NAME,
    a.SKU_ID AS DOUYIN_GOODS_ID,
    a.CARD_CODE,
    a.COUPON_CODE,
    -- 手机号标准化处理
    CASE
        WHEN a.PHONE IS NOT NULL THEN
            CASE
                WHEN LENGTH(TRIM(a.PHONE)) = 11 AND LEFT(TRIM(a.PHONE), 1) = '1' THEN TRIM(a.PHONE)
                ELSE NULL
            END
        ELSE NULL
    END AS PURCHASER_MOBILE_NUMBER,
    a.STATUS AS COUPON_STATUS,
    -- TIMESTAMP(6) --> DATETIME
    a.VERIFICATION_TIME,
    a.REFUND_TYPE,
    a.AFTER_SALE_ID AS REFUND_ID,
    a.CERTIFICATE_ID AS COUPON_ID,
    -- REFUND_APPLY_TIME 和 REFUND_AUDIT_TIME 是 INT 时间戳
    CASE
        WHEN a.REFUND_APPLY_TIME IS NOT NULL THEN FROM_UNIXTIME(a.REFUND_APPLY_TIME)
        ELSE NULL
    END AS REFUND_APPLY_TIME,
    CASE
        WHEN a.REFUND_AUDIT_TIME IS NOT NULL THEN FROM_UNIXTIME(a.REFUND_AUDIT_TIME)
        ELSE NULL
    END AS REFUND_AUDIT_TIME,
    a.REFUND_AUDIT_RESULT,
    -- 预订日期和时间
    DATE(a.CREATE_TIME) AS FK_PURCHASE_DATE,
    DATE_FORMAT(a.CREATE_TIME, '%H:%i:%s') AS FK_PURCHASE_TIME,
    a.UPDATE_TIME,
    -- TID处理
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,
    1 AS PURCHASE_COUNT,
    a.UPDATE_TIME AS SOURCE_LAST_UPDATETIME,
    CURRENT_TIMESTAMP(3) AS SYSTEM_CREATETIME,
    CURRENT_TIMESTAMP(3) AS SYSTEM_LAST_UPDATETIME
FROM ODS_PROD.T_ODS_ZSF_PRD_PRODUCT_COUPON_DOUYIN a
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'));

INSERT INTO DIM_PROD.T_DIM_USER_DIM
(
    PK_ID,
    IS_DOUYIN_CARD_PURCHASER,
    UPDATE_TIME
)
SELECT
    a.ID AS PK_ID,
    TRUE AS IS_DOUYIN_CARD_PURCHASER,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_PROD.T_ODS_ZSF_PRD_PRODUCT_COUPON_DOUYIN a
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'));
