-- 任务名 ZSF_ODR_ORDER_PAY_ONLINE2DWD
-- 掌尚飞-在线支付信息表 T_ODS_ZSF_ODR_ORDER_PAY_ONLINE 写入事实表 T_DWD_PAYDETAILS_ORD_FACT
-- 主键：数据源代号+业务大订单编号+支付流水号 数据源代号：SCAPP
-- 说明：掌尚飞在线支付数据T+1入库后，PAY_STATUS='3'（支付成功）的数据进入本表
-- 连表：ODR_ORDER_PAY_ONLINE支付表的ORDER_PAY_ID=ODR_ORDER_PAY支付记录表的ID，获取ORDER_NO订单号

-- 1、不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY_ONLINE a
INNER JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY b
    ON a.ORDER_PAY_ID = b.ID
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.PAY_STATUS = '3'
  AND tds.TID IS NULL
  AND a.CUSTOMER_ID IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 2、模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY_ONLINE a
INNER JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY b
    ON a.ORDER_PAY_ID = b.ID
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.PAY_STATUS = '3'
  AND a.CUSTOMER_ID IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

COMMIT;

-- 3、写入支付流水号事实表
INSERT INTO DWD_PROD.T_DWD_PAYDETAILS_ORD_FACT
(
    PK_ID,
    BUSINESS_ORDER_ID,
    PAY_NO,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    FK_BOOKING_DATE,
    FK_BOOKING_TIME,
    FK_PAY_DATE,
    FK_PAY_TIME,
    AK_PAY_CHANNEL,
    AK_PAY_METHOD,
    AK_CASH_PAY_PLATFORM,
    AK_PAY_STATUS,
    AK_CASH_TYPE,
    CASH_AMOUNT,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME,
    ORD_COUNT
)
SELECT
    -- 主键：数据源代号 + 订单号 + 支付流水号
    CONCAT('SCAPP', IFNULL(b.ORDER_NO, ''), IFNULL(a.PAY_NO, '')) AS PK_ID,

    -- 业务大订单编号
    b.ORDER_NO AS BUSINESS_ORDER_ID,

    -- 支付流水号
    a.PAY_NO,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    a.CUSTOMER_ID AS FK_BOOKING_USER_ORIGIN_ID,

    -- 预订日期
    DATE(a.CREATE_TIME) AS FK_BOOKING_DATE,

    -- 预订时间
    DATE(a.CREATE_TIME) AS FK_BOOKING_TIME,

    -- 支付日期
    DATE(a.CREATE_TIME) AS FK_PAY_DATE,

    -- 支付时间
    DATE_FORMAT(a.CREATE_TIME, '%H:%i:%s') AS FK_PAY_TIME,

    -- 支付渠道（标准化后）
    'SCZSF' AS AK_PAY_CHANNEL,

    -- 支付方式（固定值：现金）
    'CSH' AS AK_PAY_METHOD,

    -- 现金支付平台（标准化后）
    IFNULL(sid2.CFG_VALUE, a.PAY_BANK_CODE) AS AK_CASH_PAY_PLATFORM,

    -- 支付状态
    a.PAY_STATUS AS AK_PAY_STATUS,

    -- 现金支付币种（固定值：CNY）
    'CNY' AS AK_CASH_TYPE,

    -- 现金支付金额
    a.PAY_AMOUNT AS CASH_AMOUNT,

    -- 源系统最后更新时间
    a.UPDATE_TIME AS SOURCE_LAST_UPDATETIME,

    -- 本系统创建日期时间
    CURRENT_TIMESTAMP(3) AS SYSTEM_CREATETIME,

    -- 本系统最后更新日期时间
    CURRENT_TIMESTAMP(3) AS SYSTEM_LAST_UPDATETIME,

    -- 支付单计数
    1 AS ORD_COUNT

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY_ONLINE a
INNER JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_PAY b
    ON a.ORDER_PAY_ID = b.ID
LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(a.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
    AND tds.STRONGID_STATUS = 1
LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid2 ON
    a.PAY_BANK_CODE = sid2.CFG_CODE
    AND sid2.CFG_TYPE = 'CASH_PAYMENT_PLATFORM'
    AND sid2.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.PAY_STATUS = '3';

