-- 掌上飞选座订单附加信息写入DWD层
-- 数据来源：T_ODS_ZSF_ODR_ORDER_DETAIL_SEAT (选座订单详情表) + T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION (客户关系表)
-- 目标表：
-- 1. T_DWD_TICKING_SEG_FACT (机票出票-航段级事实表)
-- 2. T_DWD_SEAT_TIK_FACT (附加服务_选座出票_航段事实表)
-- 3. T_DWD_SEAT_REFUND_FACT (附加服务_选座退票_航段事实表)

-- SET @ETL_DATE = '2025-01-01';

-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SEAT a
        LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION b
            ON a.ORDER_NO = b.MAIN_ORDER_NO
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND tds.TID IS NULL
  AND b.CUSTOMER_ID IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SEAT a
        LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION b
            ON a.ORDER_NO = b.MAIN_ORDER_NO
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND b.CUSTOMER_ID IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入业务事实表 ====================

-- 3.1 写入机票出票-航段级事实表 (T_DWD_TICKING_SEG_FACT)
-- 条件：SEAT_TYPE = 'SEAT' 或 'SEAT_CHECKIN'
INSERT INTO DWD_PROD.T_DWD_TICKING_SEG_FACT
(
    PK_ID,
    SEAT_CHANNEL,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键：票号 + 起飞机场 + 起飞日期(YYYYMMDD格式)
    CONCAT(
            REPLACE(COALESCE(a.TICKET_NO, ''), '-', ''),
            COALESCE(a.ORG_CITY, ''),
            REPLACE(COALESCE(a.DEP_DATE, ''), '-', '')
        ) AS PK_ID,

    -- 选座渠道标准化
    IFNULL(sid1.CFG_VALUE, 'SCZSF') AS SEAT_CHANNEL,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SEAT a
    LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON a.SEAT_TYPE = sid1.CFG_CODE
        AND sid1.CFG_TYPE = 'SEAT_CHANNEL' 
        AND sid1.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.SEAT_TYPE IN ('SEAT', 'SEAT_CHECKIN')
  AND a.TICKET_NO IS NOT NULL
  AND a.ORG_CITY IS NOT NULL
  AND a.DEP_DATE IS NOT NULL;

-- 3.2 写入附加服务_选座出票_航段事实表 (T_DWD_SEAT_TIK_FACT)
-- 条件：IS_PRICE_SEAT = 1
INSERT INTO DWD_PROD.T_DWD_SEAT_TIK_FACT
(
    PK_ID,
    AK_ORDERNUM,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    AK_CHANNEL,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键：EMD票号 + 起飞机场 + 到达机场
    CONCAT(
            REPLACE(COALESCE(a.EMD_TICKET_NO, ''), '-', ''),
            COALESCE(a.ORG_CITY, ''),
            COALESCE(a.DST_CITY, '')
        ) AS PK_ID,

    -- 订单号
    a.ORDER_NO AS AK_ORDERNUM,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 渠道标准化
    IFNULL(sid2.CFG_VALUE, 'SCZSF') AS AK_CHANNEL,

    -- 源系统最后更新时间
    a.UPDATE_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SEAT a
         LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION b
                   ON a.ORDER_NO = b.MAIN_ORDER_NO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid2 ON a.SEAT_SOURCE = sid2.CFG_CODE
        AND sid2.CFG_TYPE = 'ORDER_CHANNEL_SEAT' 
        AND sid2.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.IS_PRICE_SEAT = 1
  -- 确保关键字段不为空
  AND a.EMD_TICKET_NO IS NOT NULL
  AND a.ORG_CITY IS NOT NULL
  AND a.DST_CITY IS NOT NULL;

-- 3.3 写入附加服务_选座退票_航段事实表 (T_DWD_SEAT_REFUND_FACT)
-- 条件：SEAT_STATUS = '6' (退票状态)
INSERT INTO DWD_PROD.T_DWD_SEAT_REFUND_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_REFUND_CHANNEL,
    FK_REFUND_USER_TID,
    FK_REFUND_USER_ORIGIN_ID,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键：EMD票号 + 起飞机场 + 到达机场
    CONCAT(
            REPLACE(COALESCE(a.EMD_TICKET_NO, ''), '-', ''),
            COALESCE(a.ORG_CITY, ''),
            COALESCE(a.DST_CITY, '')
        ) AS PK_ID,

    -- 订单号
    a.ORDER_NO AS AK_ORDERNUM,

    -- 退票渠道标准化
    IFNULL(sid3.CFG_VALUE, 'SCZSF') AS AK_REFUND_CHANNEL,

    -- 退票用户TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_REFUND_USER_TID,

    -- 退票用户源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_REFUND_USER_ORIGIN_ID,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SEAT a
         LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION b
                   ON a.ORDER_NO = b.MAIN_ORDER_NO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid3 ON a.SEAT_STATUS = sid3.CFG_CODE
        AND sid3.CFG_TYPE = 'REFUND_CHANNEL_SEAT' 
        AND sid3.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
    OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.SEAT_STATUS = '6'
  -- 确保关键字段不为空
  AND a.EMD_TICKET_NO IS NOT NULL
  AND a.ORG_CITY IS NOT NULL
  AND a.DST_CITY IS NOT NULL;
