-- 掌尚飞保险订单数据写入保险事实表
-- 数据来源：T_ODS_ZSF_ODR_ORDER_DETAIL_INSURANCE (保险订单表) + T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION (客户关系表)
-- 目标表：T_DWD_AUIS_SEG_FACT (保险事实表-航段级)
-- 业务逻辑：保险状态为3（已出单）、6（退保成功）、7（退保失败）的数据进入事实表
-- 
-- 注意：源数据库CERT_NO字段为未加密状态，需要先加密再标准化处理

-- --SET @ETL_DATE = '2025-12-10';
-- --SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';

-- ==================== 第一步：不存在的TID写入T_DIM_TID_SET表 ====================

-- 1.1 乘机人证件号TID写入（源数据未加密，需先加密）
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_INSURANCE a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.INS_STATUS IN ('3', '6', '7')
  AND tds.TID IS NULL
  AND a.CERT_NO IS NOT NULL
  AND TRIM(a.CERT_NO) != ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 1.2 预订人TID写入（CUSTOMER_ID已加密，需解密后重新加密标准化）
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_INSURANCE a
        LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION b
                  ON a.MAIN_ORDER_ID = b.MAIN_ORDER_ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.INS_STATUS IN ('3', '6', '7')
  AND tds.TID IS NULL
  AND b.CUSTOMER_ID IS NOT NULL
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第二步：模拟IDMapping写入T_DIM_STRONGID表 ====================

-- 2.1 乘机人证件号STRONGID写入（源数据未加密）
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, a.CERT_TYPE) AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_INSURANCE a
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON a.CERT_TYPE = sid.CFG_CODE
            AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
            AND sid.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.INS_STATUS IN ('3', '6', '7')
  AND a.CERT_NO IS NOT NULL
  AND TRIM(a.CERT_NO) != ''
  AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- 2.2 预订人CUSTOMER_ID STRONGID写入（已加密，需解密后重新加密标准化）
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_INSURANCE a
        LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION b
                  ON a.MAIN_ORDER_ID = b.MAIN_ORDER_ID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.INS_STATUS IN ('3', '6', '7')
  AND b.CUSTOMER_ID IS NOT NULL AND TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) IS NOT NULL;

-- ==================== 第三步：写入保险事实表 ====================

-- 3.1 写入保险事实表-航段级 (T_DWD_AUIS_SEG_FACT)
INSERT INTO DWD_PROD.T_DWD_AUIS_SEG_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_TIKNUM,
    FK_BKAUIS_DATE,
    FK_BKAUIS_TIME,
    CN_NAME,
    AK_CERT_TYPE,
    CERT_NUMBER,
    FK_PASSENGER_USER_TID,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    FK_SEG_DATE,
    FK_SEG_TIME,
    FK_DEPAIRPORT,
    FK_ARRIAIRPORT,
    AK_INSURANCE_TYPE,
    INSURANCE_COMPANY,
    INSURANCE_POLICY_NO,
    AK_CHANNEL,
    AK_INSURSTATUS,
    INSURANCE_AMT,
    UPDATE_TIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键：票号 + 保单号（如果保单号为空则用ID）
    CONCAT(
            COALESCE(IFNULL(sid1.CFG_VALUE, REPLACE(a.TICKET_NO, '-', '')), ''),
            COALESCE(IFNULL(a.INS_TRADE_NO, a.ID), '')
        ) AS PK_ID,

    -- 订单号
    a.ORDER_NO AS AK_ORDERNUM,

    -- 票号（标准化：先去除横杠XXX-0123456789->XXX0123456789，再查询标准化配置）
    IFNULL(sid1.CFG_VALUE, REPLACE(a.TICKET_NO, '-', '')) AS AK_TIKNUM,

    -- 预订日期（取CREATE_TIME的日期部分）
    DATE(a.CREATE_TIME) AS FK_BKAUIS_DATE,

    -- 预订时间（取CREATE_TIME的时间部分）
    DATE(a.CREATE_TIME) AS FK_BKAUIS_TIME,

    -- 乘客姓名（标准化）
    IFNULL(sid2.CFG_VALUE, a.PSGR_NAME) AS CN_NAME,

    -- 证件类型（标准化）
    IFNULL(sid3.CFG_VALUE, a.CERT_TYPE) AS AK_CERT_TYPE,

    -- 证件号码（加密并标准化）
    IFNULL(sid4.CFG_VALUE, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))) AS CERT_NUMBER,

    -- 乘机人TID（先加密再查询映射，如果没有映射则回退到加密后的证件号）
    IFNULL(tds1.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY)))) AS FK_PASSENGER_USER_TID,

    -- 预订人TID（解密后重新加密标准化，再查询映射）
    IFNULL(tds2.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    b.CUSTOMER_ID AS FK_BOOKING_USER_ORIGIN_ID,

    -- 航班日期（处理非标准格式）
    CASE
        WHEN a.FLIGHT_DATE IS NOT NULL AND LENGTH(a.FLIGHT_DATE) = 8 AND a.FLIGHT_DATE REGEXP '^[0-9]+$'
        THEN STR_TO_DATE(a.FLIGHT_DATE, '%Y%m%d')
        WHEN a.FLIGHT_DATE IS NOT NULL
        THEN STR_TO_DATE(a.FLIGHT_DATE, '%Y-%m-%d')
        ELSE NULL
    END AS FK_SEG_DATE,

    -- 航班时间
    a.FLIGHT_TIME AS FK_SEG_TIME,

    -- 出发机场
    a.ORG_CITY AS FK_DEPAIRPORT,

    -- 到达机场
    a.DST_CITY AS FK_ARRIAIRPORT,

    -- 保险类型（标准化）
    IFNULL(sid5.CFG_VALUE, a.INS_TYPE) AS AK_INSURANCE_TYPE,

    -- 保险公司
    a.INS_COMPANY AS INSURANCE_COMPANY,

    -- 保单号（如果为空则使用ID）
    IFNULL(a.INS_TRADE_NO, a.ID) AS INSURANCE_POLICY_NO,

    -- 订单渠道
    'SCZSF' AS AK_CHANNEL,

    -- 保险状态（标准化：1/2/8->unconfirmed, 3/5/7/10->booked, 4/9->failedbooking, 6->cancelled）
    CASE
        WHEN a.INS_STATUS IN ('1', '2', '8') THEN 'unconfirmed'
        WHEN a.INS_STATUS IN ('3', '5', '7', '10') THEN 'booked'
        WHEN a.INS_STATUS IN ('4', '9') THEN 'failedbooking'
        WHEN a.INS_STATUS = '6' THEN 'cancelled'
        ELSE a.INS_STATUS
    END AS AK_INSURSTATUS,

--     IFNULL(sid5.CFG_VALUE, a.INS_STATUS) AS AK_INSURSTATUS,

    -- 保险金额
    a.INS_PRICE AS INSURANCE_AMT,

    -- 更新时间（格式化：去掉分隔符）
    CASE
        WHEN a.UPDATE_TIME IS NOT NULL
        THEN REPLACE(REPLACE(REPLACE(a.UPDATE_TIME, '-', ''), ':', ''), ' ', '')
        ELSE NULL
    END AS UPDATE_TIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_INSURANCE a
         LEFT JOIN ODS_PROD.T_ODS_ZSF_ODR_ORDER_CUSTOMER_RELATION b
                   ON a.MAIN_ORDER_ID = b.MAIN_ORDER_ID
         -- 乘机人TID映射
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds1 ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = tds1.STRONGID
        AND tds1.STRONGID_STATUS = 1
         -- 预订人TID映射
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds2 ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(b.CUSTOMER_ID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds2.STRONGID
        AND tds2.STRONGID_STATUS = 1
         -- 票号标准化（先去除横杠后再匹配）
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON REPLACE(a.TICKET_NO, '-', '') = sid1.CFG_CODE
            AND sid1.CFG_TYPE = 'TICKET_NO' AND sid1.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 姓名标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid2 ON a.PSGR_NAME = sid2.CFG_CODE
            AND sid2.CFG_TYPE = 'CN_NAME' AND sid2.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 证件类型标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid3 ON a.CERT_TYPE = sid3.CFG_CODE
            AND sid3.CFG_TYPE = 'DOCUMENT_TYPE' AND sid3.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 证件号标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid4 ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CERT_NO)), FROM_BASE64(@SM4_KEY))) = sid4.CFG_CODE
            AND sid4.CFG_TYPE = 'DOCUMENT_NUM' AND sid4.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 保险类型标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid5 ON a.INS_TYPE = sid5.CFG_CODE
            AND sid5.CFG_TYPE = 'INSURANCE_TYPE' AND sid5.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
         -- 保险状态标准化（已在SELECT中使用CASE进行映射，无需关联配置表）
--          LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid6 ON a.INS_STATUS = sid6.CFG_CODE
--             AND sid6.CFG_TYPE = 'INSURANCE_STATUS' AND sid6.CFG_TYPE_CHANNEL = 'ZHANGSHANGFEI'
 WHERE (a.CREATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999')
     OR a.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE, ' 00:00:00') AND CONCAT(@ETL_DATE, ' 23:59:59.999'))
  AND a.INS_STATUS IN ('3', '6', '7');

COMMIT;
