# local or nacos
config.route=local
config.infoenckey=1fd3593d5d1a1951a1dc36
config.filename=application-config.properties
#sc-cloud
nacos.server-addr=10.31.0.21:38848
nacos.username=ucvtest
nacos.password=82197c986462eec7b0e247f9f3ba9145
nacos.namespace=8d8db293-300a-45d7-b3cf-85d770f5ea03
nacos.group=DATA_ANALYSIS
nacos.timeout-ms=10000
nacos.connect-timeout=3000
nacos.read-timeout=5000