# local or nacos
config.route=local
config.infoenckey=1fd3593d5d1a1951a1dc36
config.filename=application-config.properties
#sc-cloud
nacos.server-addr=10.31.0.22:38848
nacos.username=ucvdev
nacos.password=82197c986462eec7b0e247f9f3ba9145
nacos.namespace=16b351a7-34d7-45cc-a5c8-78ab09890061
nacos.group=DATA_ANALYSIS
nacos.timeout-ms=10000
nacos.connect-timeout=3000
nacos.read-timeout=5000

#ts-east
#nacos.server-addr=172.24.126.172:18848
#nacos.username=nacos
#nacos.password=e4c2d8500af05fd8b577c4aa371a5aa7
#nacos.namespace=4031c53e-2160-4cf3-962a-5d49e2e1a130
#nacos.group=DATA_ANALYSIS
#nacos.timeout-ms=10000
#nacos.connect-timeout=3000
#nacos.read-timeout=5000