# Constants Configuration
CHECKPOINTING=180000
MIN_PAUSE_BETWEEN_CHECKPOINTS=500
CHECKPOINT_TIMEOUT=600000
SM4_KEY=3cbd24a0bd9820a3da238186af5244422326cddf1345415896d85b735a9a8a09

CA_CRM_INTERFACE=ca_crm_interface
CA_CRM_KEY=ea0335620563e0edf98f235b7e9381be
CA_CRM_CHANNEL=SC
CA_CRM_SUBCHANNEL=SCTS
CA_CRM_SC_SUB_CHANNEL=SCTS_TYKHST
CA_CRM_SC_CHANNEL=SC

ODS_USER=ods_prod
DWD_USER=dwd_prod
DIM_USER=dim_prod
ODS_PWD=2F0E506D9EB9C07BCE6C954714DC9CBD
DWD_PWD=07105E59AAF2D3D0F08A1C22C33281C4
DIM_PWD=EF9974381251A93982F2D855B71B54B7
ODS_DB=ODS_PROD
DWD_DB=DWD_PROD
DIM_DB=DIM_PROD
DWQ_DB=DWQ_PROD
DORIS_IP=10.14.34.58
DORIS_PORT=31878
DORIS_FE_IP=10.14.34.58
DORIS_FE_PORT=31334
DORIS_BE_IP=10.14.34.58
DORIS_BE_PORT=32605
DORIS_FLIGHT_PORT=32546
DORIS_BATCH_SIZE=8192
DORIS_READ_TIMEOUT=300

#DMconfig
DM_DRIVER=dm.jdbc.driver.DmDriver
DM_IP=10.31.3.10
DM_PORT=50080
DM_SCHEMA=UCVPROD
DM_USER=ucvprod
DM_PWD=34E4A1B75D5DAB76D347596AF96481DA


WXAP_AES_KEY=53444179796B6677787E303730392121
WXAP_USER=scwxh5_etl
WXAP_PWD=cf5e877fb26bdfe71d5c8f125b9310e0
WXAP_DB=webora
WXAP_IP=weborabak.sda.cn
WXAP_PORT=1521
WXAP_SCHEMA=scwxh5

ALP_AES_KEY=534441797873797A66627E3037323721
ALP_USER=zfbxcx_uo_etl
ALP_PWD=c8d06eaf8e34640ad753740fc65f44f7
ALP_DB=zfbxcxuoa
ALP_IP=msgbak.sda.cn
ALP_PORT=1521
ALP_SCHEMA=zfbxcx_uo

HYTD_AES_KEY=2I3zHkJ9OrCGpd7K
HYTD_USER=scphoenix_etl
HYTD_PWD=29e6bb06a5de04f8610e15462be0f8a7
HYTD_DB=SCPHOENIX
HYTD_IP=scphonenixbak.sda.cn
HYTD_PORT=5237
HYTD_SCHEMA=scphoenix


ORACLE_DRIVER=oracle.jdbc.driver.OracleDriver

ZXYH_AES_KEY=5344415A585948787477687E73646121
ZXYH_USER=zxyh_etl
ZXYH_PWD=4a93d55e1a4a3f5c31e58a7f6c2bdd61
ZXYH_DB=ZXYH
ZXYH_IP=zxyhbak.sda.cn
ZXYH_PORT=1521
ZXYH_SCHEMA=zxyh

CLK_AES_KEY=
CLK_USER=scffp_etl
CLK_PWD=c167278ecb69624a7adac39619b7baef
CLK_DB=clk
CLK_IP=c-clk.sda.cn
CLK_PORT=1521
CLK_SCHEMA=scffp
CLK_FILE_PATH=hdfs://cmss/data/test/encrypt/clk_xml_upload
CLK_FILE_FTP_PATH=hdfs://cmss/data/test/encrypt/clk_ftp_upload
GROUPING_FILE_PATH=hdfs://cmss/data/test/encrypt/user_grouping
GROUPING_CSV_SIZE=100000

CLK_DW_USER=ods_wshh_etl
CLK_DW_PWD=3052e1d37f1cbcfbe50b3d4e5ea71e7f
CLK_DW_DB=clk
CLK_DW_IP=c-clk.sda.cn
CLK_DW_PORT=1521
CLK_DW_SCHEMA=dw_wshh
CLK_ODS_SCHEMA=ods_wshh


CLK_MILE_FTP_HOST=10.66.90.4
CLK_MILE_FTP_USERNAME=cacrm
CLK_MILE_FTP_PWD=633d93a6807ae93930f2065d51d851cc
CLK_MILE_FTP_PORT=21

CLK_BUSINESS_FTP_HOST=10.66.90.4
CLK_BUSINESS_FTP_USERNAME=cacrm
CLK_BUSINESS_FTP_PWD=633d93a6807ae93930f2065d51d851cc
CLK_BUSINESS_FTP_PORT=21

# TRP-FTP
TRP_FTP_HOST=10.31.0.20
TRP_FTP_USERNAME=TFTP_C_FTI_715_5764_SCB2C_SCB2C_REPORT_SAL
TRP_FTP_PWD=a9cefd297da57d06db0d7e9effe18450
TRP_FTP_PORT=5001
TRP_FTP_DOWNLOAD_PATH=/5764_SCB2C/SCB2C_REPORT_SAL
TRP_AES_KEY=1a36216a67836f9eec43517ddf4baa377e29be11e8c1f38828fb3e499c6aaeab


INTL_SALES_FTP_HOST=10.31.0.10
INTL_SALES_FTP_USERNAME=bidt_data_dw
INTL_SALES_FTP_PWD=a1963d1d8e31fc7acedae9fda9bd0302
INTL_SALES_FTP_PORT=52222
INTL_SALES_FTP_PATH=/financial_sales

TRP_FTP_HDFS=/data/trp/sftp_transfer
YXW_FTP_HDFS=/data/yxw/sftp_transfer
CLK_FTP_HDFS=/data/clk/sftp_transfer

HSD_KAFKA_SERVICES=10.26.92.2:9093,10.26.92.3:9093,10.26.92.4:9093
HSD_KAFKA_USERNAME=admin
HSD_KAFKA_PASSWORD=bc9efc5b16eb982dc82643a7fdb43c76
HSD_KAFKA_TOPIC=AIC_HSD_SC_A
HSD_KAFKA_GROUPID=high_frequency_data_ucv
HSD_KAFKA_JAAS_CLAZZ=org.apache.kafka.common.security.scram.ScramLoginModule
HSD_KAFKA_SECURITY_PROTOCOL=SASL_PLAINTEXT
HSD_KAFKA_SASLME_CHANISM=PLAIN
HSD_KAFKA_PARALLELISM=3

LYX_AES_KEY=
LYX_USER=lyxsc_etl
LYX_PWD=9a393ffe01c041ef0e6d9d2183407559
LYX_DB=lyx
LYX_IP=crmdbbak.sda.cn
LYX_PORT=1521
LYX_SCHEMA=lyxsc

ZSF_AES_KEY=53444178747768313233347E73646121
ZSF_USER=sdair_yunwei
ZSF_PWD=5b9a18d21e65dfd16c85f1c161c7982d
ZSF_DB=sdair_app
ZSF_IP=172.31.105.201
ZSF_PORT=3681
ZSF_SCHEMA=sdair_yunwei

MYSQL_DRIVER=com.mysql.cj.jdbc.Driver

LYGJ_AES_KEY=51333547686231616D76392A66596E6E
LYGJ_IP=crmdbbak.sda.cn
LYGJ_SCHEMA=sis_user_v3
LYGJ_USER=sis_user_v3_etl
LYGJ_PWD=cea325e173ca451eb50df9692fb88a5775bff870393c05d0849ee876f5f12508
LYGJ_PORT=1521
LYGJ_DB=CRMDB

JSSC_AES_KEY=
JSSC_IP=upgradebak.sda.cn
JSSC_SCHEMA=upgrade
JSSC_USER=upgrade_etl
JSSC_PWD=8dd787edc4f34d6caae0a0c082ceb1d0
JSSC_PORT=1521
JSSC_DB=upgrade

LYGJ_ZB_AES_KEY=5343534953403230
LYGJ_ZB_IP=lybak.sda.cn
LYGJ_ZB_SCHEMA=sis_user_v3
LYGJ_ZB_USER=SIS_BAK_ETL
LYGJ_ZB_PWD=d982e000d4189d87a2a7006f0949f97f75bff870393c05d0849ee876f5f12508
LYGJ_ZB_PORT=1521
LYGJ_ZB_DB=lybak_etl

DKHXT_AES_KEY=
DKHXT_IP=crmdbbak.sda.cn
DKHXT_SCHEMA=sddb
DKHXT_USER=sddb_etl
DKHXT_PWD=ddc2e61fbf10f2ca268cea0c75743a15
DKHXT_PORT=1521
DKHXT_DB=CRMDB

KHBP_AES_KEY=
KHBP_IP=crmdbbak.sda.cn
KHBP_SCHEMA=TICKET_SERVICE
KHBP_USER=TICKET_SERVICE_ETL
KHBP_PWD=bcc9882553ace6058ab958e0a2d98d37
KHBP_PORT=1521
KHBP_DB=CRMDB

DKHCL_AES_KEY_AIR_ORDER_PASSENGER=4149525F4F524445525F50415353454E474552
DKHCL_AES_KEY_CRM_EMPLOYEE=43524D5F454D504C4F594545
DKHCL_AES_KEY_CRM_EMPLOYEE_CERT=43524D5F454D504C4F5945455F43455254
DKHCL_IP=msgbak.sda.cn
DKHCL_SCHEMA=smedba
DKHCL_USER=smedba_etl
DKHCL_PWD=7f52e09a3a489e1dfb1f2397f922605b
DKHCL_PORT=1521
DKHCL_DB=smedba

QWSY_AES_KEY=53444178747768313233347E73646121
QWSY_IP=b-sjcjsj.sda.cn
QWSY_SCHEMA=privatetraffic
QWSY_USER=privatetraffic_etl
QWSY_PWD=11f4a288b2e1fc00f1827da701fdc8bf
QWSY_PORT=1521
QWSY_DB=privatetraffic

TRP_KAFKA_SERVICES=10.193.151.250:32697
TRP_KAFKA_USERNAME=TongyikehuProd
TRP_KAFKA_PASSWORD=88e99a9aa0eedd432a0e38fea630c4b5
TRP_KAFKA_TOPIC=AIC_TRP_SC_A
TRP_KAFKA_GROUPID=trp_sysuency_data_ucv

DJKSC_AES_KEY=534441646A6B73633132337E73646121
DJKSC_USER=djksc_etl
DJKSC_PWD=3ca83027e7bf03c4d1a68e35cfa1b690
DJKSC_DB=djksc
DJKSC_IP=crmdbbak.sda.cn
DJKSC_PORT=1521
DJKSC_SCHEMA=djksc

BZSJ_USER=sdsky_etl
BZSJ_PWD=c344c069c7e495340313e22062824ebf
BZSJ_DB=sjcjsj
BZSJ_IP=bjsjbak.sda.cn
BZSJ_PORT=1521
BZSJ_SCHEMA=SDSKY

SDEXT_USER=sdext
SDEXT_PWD=9db63d3c1d6f8ad01282bf34aeab74d3
SDEXT_DB=sdext
SDEXT_IP=172.16.33.1
SDEXT_PORT=1521
SDEXT_SCHEMA=SDEXT

EXCHANGE_RATE_FTP_HOST=10.31.0.20
EXCHANGE_RATE_FTP_PORT=22
EXCHANGE_RATE_FTP_USERNAME=sftp_downloader
EXCHANGE_RATE_FTP_PWD=988bb851a12440f3561eff70b3ff7641
EXCHANGE_RATE_FTP_DOWNLOAD_PATH=/International_Currency

PRIMARY_KAFKA_BOOTSTRAP_SERVERS=172.16.9.74:9093,172.16.9.75:9093,10.216.129.7:9093
PRIMARY_KAFKA_GROUPID=high_frequency_data_ucv
PRIMARY_KAFKA_TOPICS=AIC_HSD_SC_A
PRIMARY_KAFKA_USERNAME=admin
PRIMARY_KAFKA_PASSWORD=bc9efc5b16eb982dc82643a7fdb43c76
PRIMARY_KAFKA_JAAS_CLAZZ=org.apache.kafka.common.security.scram.ScramLoginModule
PRIMARY_KAFKA_SECURITY_PROTOCOL=SASL_PLAINTEXT
PRIMARY_KAFKA_SASLME_CHANISM=PLAIN

KAFKA_BOOTSTRAP_SERVERS=10.193.151.250:32697
KAFKA_SPNR_PARQUET_GROUP=test1
KAFKA_CONSUME_TOPIC=test2
KAFKA_USERNAME=TongyikehuProd
KAFKA_PASSWORD=88e99a9aa0eedd432a0e38fea630c4b5
KAFKA_JAAS_CLAZZ=org.apache.kafka.common.security.scram.ScramLoginModule
KAFKA_SECURITY_PROTOCOL=SASL_PLAINTEXT
KAFKA_SASLME_CHANISM=SCRAM-SHA-256

KRB5_CONF_PATH=src/main/resources/krb5.conf

SYS_UCV_TEST_FOR_MAPREDUCE_KEYTAB_PATH=src/main/resources/sys_ucv_test_for_mapreduce.keytab
SYS_UCV_TEST_FOR_MAPREDUCE_PRINCIPAL=sys_ucv_test_for_mapreduce@BCHKDC

CHECKPOINT_STORAGE=hdfs://cmss/data/prod/checkpoint/

USERGROUP_KAFKA_GROUPID=user_grouping_groupId_csv
USERGROUP_KAFKA_TOPICS=grouping_topic_prod


# Variflight API Configuration
VARIFLIGHT_APPSECURITY=017bae99468d65
VARIFLIGHT_BASE_URL=https://fapis.variflight.com/data/flight/ask
VARIFLIGHT_APP_ID=11635