#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05BE\uFFFD\u013C\uFFFD\uFFFD\uD84E\uDF36\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05BE\uFFFD\uFFFD\u03E2\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013F\uFFFD\uFFFD
log4j.rootLogger=INFO, CA ,RFA, console
log4j.logger.org.apache.flink=INFO, console
#\uFFFD\uFFFD\uFFFD\uFFFDCA\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013F\uFFFD\u0135\uFFFD\u03AA\uFFFD\uFFFD\uFFFD\uFFFD\u0328
log4j.appender.CA=org.apache.log4j.ConsoleAppender
#\uFFFD\uFFFD\uFFFD\uFFFD\u03AA PatternLayout \uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05B8\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0123\u02BD\uFFFD\uFFFD
log4j.appender.CA.layout=org.apache.log4j.PatternLayout
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02BD
log4j.appender.CA.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss.SSS} %p %t %c - %m%n
#\uFFFD\uFFFD\uFFFD\uFFFDR\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013F\uFFFD\u0135\uFFFD\u03AA\uFFFD\u013C\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013C\uFFFD\uFFFD\uFFFD\u0421\uFFFD\uFFFD\uFFFD\uFFFD\u05B8\uFFFD\uFFFD\uFFFD\u07F4\uFFFD\uFFFD\u02B1\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04BB\uFFFD\uFFFD\uFFFD\u00B5\uFFFD\uFFFD\u013C\uFFFD
log4j.appender.RFA=org.apache.log4j.RollingFileAppender
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013C\uFFFD\uFFFD\uFFFD\u05B7
#log4j.appender.RFA.File=Log4j.log
log4j.appender.RFA.File=/mnt/test/log/datatrans.log
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013C\uFFFD\uFFFD\uFFFD\u0421\u03B0100 kb \uFFFD\u013C\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD100\u02B1\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04BB\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013C\uFFFD\uFFFD\uFFFD
#MaxBackupIndex \uFFFD\uFFFD\uFFFD\uFFFD\u00BC\uFFFD\uFFFD\uFFFD\u013C\uFFFD\uFFFD\uFFFD\u03AA1 \uFFFD\uFFFD\uFFFD\u04BB\uFFFD\uFFFD\uFFFD\u013C\uFFFD\u027E\uFFFD\uFFFD\uFFFD\u013C\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0121\uFFFD
log4j.appender.RFA.MaxFileSize=100MB log4j.appender.RFA.MaxBackupIndex=50
#\uFFFD\uFFFD\uFFFD\u00BA\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04BB\uFFFD\uFFFD
log4j.appender.RFA.layout=org.apache.log4j.PatternLayout
log4j.appender.RFA.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss.SSS} %p %t %c - %m%n
# Console appender configuration
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n