#航空公司
air.company=SC
air.line.lower=sc
#Oracle相关(后台)
!Oracle地址及端口
oracle.url=jdbc:oracle:thin:@10.220.105.34:1523/SC_P_XREZ
oracle.driver=oracle.jdbc.driver.OracleDriver
!Oracle用户名及密码
oracle.username=
oracle.password=
#Hbase相关
!zookeeper
zk.server=s240k1-nn-zk.travelsky.bdp.com,s240k3-nn-zk.travelsky.bdp.com,s240k5-nn-zk.travelsky.bdp.com
zk.port=2181
!HBase刷写数据量阈值
hbase.flush.num=2000
!Hbase连接超时时间
hbase.rpc.timeout=30000
hbase.client.operation.timeout=30000
hbase.client.scanner.timeout.period=30000
hbase.namespace=JXHDA_NHPBD_PRD
!列簇
hbase.index.table.family=order
hbase.table.order.search=order_search
hbase.table.order.spnr=order_spnr
hbase.table.order.fetch.log=order_fetch_log
hbase.table.order.run.log=run_log
hbase.table.order.data.log=data_log
#程序运行相关
!hadoop用户
hadoop.user.name=BDATA_NHPBD_ADM
!低并行度
parallelism=1
!高并行度
highparallelism=3
!数据处理的测试目录(/TEMP/DATA)false和真实存储目录(/DATA)true切换
finish.mode=true
temp.mode=false
!log打印数据量阈值
show.count=1000
!盐，用于混交md5
slat=
!主机.z文件使用的编码
charset=GBK
#HDFS相关
!HDFS地址
hdfs.server=hdfs://nameservice1
#数据在HDFS的地址拼接参数
!事件中心告警上传接口url
ark.monitor.event.service.url=http://10.224.23.91:1080/trp/api/ark/v0/ark-monitor-event-service/events
!keytab文件名
keytab=BDATA_NHPBD_ADM.keytab
！krb5配置文件名
krb5=krb5-pro.conf
!登录用户
login.user=BDATA_NHPBD_ADM@TRAVELSKY.BDP.COM
!获取summary报文请求开头
get.summary.message.head=<?xml version="1.0" encoding="utf-8"?><OJ_SuperPNRReadRQ AgentID="admin" CorrelationID="f79f7382-8b8d-4776-a94b-305ca89166d6" DeviceID="b29e119a-15b2-407e-816c-1de76a06f30e" EchoToken="CreateSession" ReturnHistory="false" RowLimit="100" SessionID="6DBE632F0265A397216354D512A2686F.lzy-HP-EliteBook-840-G3.1" TimeZone="UTC" xmlns="http://www.opentravel.org/OTA/2003/05"><POS><Source Channel="CC" ISOCurrency="CNY" PseudoCityCode="CLCNTR" TerminalID="0:0:0:0:0:0:0:1"><RequestorID ID="CC" Type="18"/></Source><Agent Agent="admin" SourceAddress="0:0:0:0:0:0:0:1" Timestamp="2021-04-28 09:00:18.991"/></POS><Verification><UniqueIDs>
!获取summary报文请求结尾
get.summary.message.end=</UniqueIDs><ArchivalStatus State="Archived"/></Verification></OJ_SuperPNRReadRQ>
!获取报文接口
get.spnr.message.url=http://10.224.29.31:80/scb2c/services/spm/spm
get.spnr.message.url.big=http://10.224.27.72:8080/search/api/hisordersearch/v1/historyOrderQueryList
get.spnr.message.url.big.tk=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE5NDQ2MjYzOTgsImlzcyI6Ik1JTkciLCJzaWQiOiJTQ19QUk9EVUNUSU9OXzIwMjUwODEzMTM1NzUzX1NDIiwiYXBwSWQiOiJTQyIsIm5hbWUiOiJTQyJ9.b1TlrexsMMfDAz2hTJV3gmTt604xp1bu_YM_l6X7Dsc
!获取spnr报文请求开头
get.spnr.message.head=<?xml version="1.0" encoding="utf-8"?><OJ_SuperPNRReadRQ AgentID="admin" DeviceID="f5ca0a31-8f80-4643-9424-73c65bd45756" EchoToken="CreateSession" ReturnHistory="false" RowLimit="100" SessionID="DE7BFF5FA50586F82113B88C670E7DC3.155_32HNAEditorServer20191112.1" TimeZone="GMT+08:00" xmlns="http://www.opentravel.org/OTA/2003/05"><POS><Source Channel="CC" ISOCurrency="CNY" PseudoCityCode="CLCNTR" TerminalID="172.26.3.106"><RequestorID ID="CC" Type="18"/></Source><Agent Agent="admin" SourceAddress="172.26.3.106" Timestamp="2021-05-07T02:11:30" URL="172.26.3.106"/></POS>
!获取spnr报文请求结尾
get.spnr.message.end=<Verification><ArchivalStatus State="Archived"/></Verification></OJ_SuperPNRReadRQ>
order.history.path=/user/BDATA_NHPBD_ADM/data/file
!单个spnrID获取报文重试次数阀值
number.of.retries=2
get.summary.message.number.of.retries=10
get.spnr.message.number.of.retries=10
！单节点连续获取报文重试次数阀值
continuous.failure.threshold=200
！单节点总获取报文重试次数
total.failure.threshold=10000
service.ip=10.224.25.238
character=utf-8
get.spnr.timeout=6000
!httpex配置
http.client.conf=PRODUCTION
