-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';

--常客客舱奖励积分表-写DWD
INSERT INTO DWD_PROD.T_DWD_CLK_FFP_FZ_USER_SCORE_FACT
(ID, USERCODE, INTEGRAL, ADD_DATE, DEPT, FFP_SDMEMBER_ATTRS_ID, FLAG, REST_INTEGRAL, REMARKS, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, DEL_FLAG, EXP_DATE, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT ID, USERCODE, INTEGRAL, ADD_DATE, DEPT, FFP_SDMEMBER_ATTRS_ID, FLAG, REST_INTEGRAL, REMARKS, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, DEL_FLAG, EXP_DATE, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM ODS_PROD.T_ODS_CLK_FFP_FZ_USER_SCORE ffus
WHERE ffus.ETL_DATE = @ETL_DATE;








