-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--TID SET
INSERT INTO DIM_PROD.T_DIM_TID_SET
(TID, ETL_DATE, CREATE_TIME, TID_STATUS)
SELECT
IFNULL(sid.TID, TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))))  as STRONGID,
now() AS ETL_DATE,CURRENT_TIMESTAMP(3) AS CREATE_TIME,1
FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO  a
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = sid.STRONGID
and sid.STRONGID_STATUS =1
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1'
and a.FCARD is not null
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
AND a.ETL_DATE = @ETL_DATE;



--STRONG ID
INSERT INTO DIM_PROD.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME,ETL_DATE)
SELECT TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  as STRONGID,'FFP' AS STRONGID_TYPE,
 IFNULL(sid.TID, TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))))  AS TID,
1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME, CURRENT_DATE() as ETL_DATE
FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO  a
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = sid.STRONGID
and sid.STRONGID_STATUS =1
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1' and sid.TID IS null
and a.FCARD is not null
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
and LENGTH(SM4_DECRYPT(FROM_BASE64(a.FPHONE), FROM_BASE64(@SM4_KEY))) <15
AND a.ETL_DATE = @ETL_DATE;



INSERT INTO DIM_PROD.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME,ETL_DATE)
SELECT a.FIDCARD  as STRONGID,COALESCE(sf.CFG_VALUE,'OT') AS STRONGID_TYPE,
 IFNULL(sid.TID, TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))))  AS TID,
1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME, CURRENT_DATE() as ETL_DATE
FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO  a
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = sid.STRONGID
and sid.STRONGID_STATUS =1
LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sf ON a.FCARDTYPE  =sf.CFG_CODE
AND sf.CFG_TYPE = 'DOCUMENT_TYPE' AND sf.CFG_TYPE_CHANNEL ='FREQUENT_FLYER'
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1' and sid.TID  IS null
AND a.FIDCARD is not null
and a.FCARD is not null
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
and LENGTH(SM4_DECRYPT(FROM_BASE64(a.FPHONE), FROM_BASE64(@SM4_KEY))) <15
AND a.ETL_DATE = @ETL_DATE;

--事务提交
--commit;