-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

INSERT INTO DIM_PROD.T_DIM_FFP_DIM (SYSTEM_KEY ,T_ID ,FFRF ,FT_REGISTER_TIME,PARENT_CARD_NUMBER ,MOST_TRUSTED_SOURCE,UPDATE_TIME,CREATE_TIME)
SELECT
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS MEM_NUM ,
IFNULL(sid.TID, TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))))  AS TID,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS FFR ,
a.CREATE_DATE ,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.PARENT_FFP_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS PARENT_FFR,
'1' as SOURCE,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO a
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = sid.STRONGID
and sid.STRONGID_STATUS =1
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1'
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
and (LENGTH(SM4_DECRYPT(FROM_BASE64(a.FPHONE), FROM_BASE64(@SM4_KEY))) >=15 OR a.FPHONE is null)
AND a.ETL_DATE = @ETL_DATE;

--事务提交
--commit;