-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--用户维表
INSERT INTO DIM_PROD.T_DIM_USER_DIM (PK_ID,FFP_REGISTER_ID ,SEX,EN_NAME,CN_NAME,BIRTHDAY,PROVINCE ,CITY ,EMAIL ,UPDATE_TIME,CREATE_TIME)
SELECT
IFNULL(sid.TID, TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))))  AS TID,
a.ID ,
a.FSEX  ,
concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_FIRST_NAME_EN  , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_SECOND_NAME_EN , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')) EN_NAME,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.FNAMECN , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')  CN_NAME,
a.FBIRTHDAY,
a.PROVINCE,
a.CITY ,
a.EMAIL ,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO a
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = sid.STRONGID
and sid.STRONGID_STATUS =1
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1'
and a.FCARD  is not null
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
and (LENGTH(SM4_DECRYPT(FROM_BASE64(a.FPHONE), FROM_BASE64(@SM4_KEY))) >=15 OR a.FPHONE is null)
AND a.ETL_DATE = @ETL_DATE;



--用户维表记录表 summary
INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY (PK_ID,FFP_REGISTER_ID_SOURCE,FFP_REGISTER_ID_UPDATETIME ,
SEX_SOURCE ,SEX_UPDATETIME ,EN_NAME_SOURCE,EN_NAME_UPDATETIME,CN_NAME_SOURCE,CN_NAME_UPDATETIME,
BIRTHDAY_SOURCE,BIRTHDAY_UPDATETIME,PROVINCE_SOURCE ,PROVINCE_UPDATETIME  ,
CITY_SOURCE ,CITY_UPDATETIME  ,EMAIL_SOURCE,EMAIL_UPDATETIME)
SELECT
IFNULL(sid.TID, TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))))  AS TID,
CASE
        WHEN a.ID IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS FFP_REGISTER_ID_SOURCE,
CASE
        WHEN a.ID IS NOT NULL THEN now()
        ELSE NULL
    END AS FFP_REGISTER_ID_DATE,
CASE
        WHEN a.FSEX IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS SEX_SOURCE,
CASE
        WHEN a.FSEX IS NOT NULL THEN now()
        ELSE NULL
    END AS SEX_DATE,
CASE
        WHEN concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_FIRST_NAME_EN  , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_SECOND_NAME_EN , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')) IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS EN_NAME_SOURCE,
CASE
        WHEN concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_FIRST_NAME_EN  , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_SECOND_NAME_EN , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')) IS NOT NULL THEN now()
        ELSE NULL
    END AS EN_NAME_DATE,
CASE
        WHEN REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.FNAMECN , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')
 IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS CN_NAME_SOURCE,
CASE
        WHEN REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.FNAMECN , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')
 IS NOT NULL THEN now()
        ELSE NULL
    END AS CN_NAME_DATE,
CASE
        WHEN a.FBIRTHDAY IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS FBIRTHDAY_SOURCE,
CASE
        WHEN a.FBIRTHDAY IS NOT NULL THEN now()
        ELSE NULL
    END AS FBIRTHDAY_DATE,
CASE
        WHEN a.PROVINCE IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS PROVINCE_SOURCE,
CASE
        WHEN a.PROVINCE IS NOT NULL THEN now()
        ELSE NULL
    END AS PROVINCE_DATE,
CASE
        WHEN a.CITY IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS CITY_SOURCE,
CASE
        WHEN a.CITY IS NOT NULL THEN now()
        ELSE NULL
    END AS CITY_DATE,
CASE
        WHEN a.EMAIL IS NOT NULL THEN 'CLK'
        ELSE NULL
    END AS EMAIL_SOURCE,
CASE
        WHEN a.EMAIL IS NOT NULL THEN now()
        ELSE NULL
    END AS EMAIL_DATE
FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO a
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = sid.STRONGID
and sid.STRONGID_STATUS =1
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1'
and a.FCARD  is not null
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
and (LENGTH(SM4_DECRYPT(FROM_BASE64(a.FPHONE), FROM_BASE64(@SM4_KEY))) >=15 OR a.FPHONE is null)
AND a.ETL_DATE = @ETL_DATE;
--commit;