-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';

--常客客舱奖励积分表-写DWD
INSERT INTO DIM_PROD.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME,ETL_DATE)
SELECT a.MEMBERNO  as STRONGID,'FFP' AS STRONGID_TYPE,a.MEMBERNO AS TID, 1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME, CURRENT_DATE() as ETL_DATE
FROM ODS_PROD.T_ODS_CLK_ACCUINT  a
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON a.MEMBERNO  = sid.STRONGID
WHERE sid.TID IS null
AND a.ETL_DATE = @ETL_DATE;

INSERT INTO DIM_PROD.T_DIM_TID_SET
(TID, ETL_DATE, CREATE_TIME, TID_STATUS)
SELECT MEMBERNO as STRONGID,now() AS ETL_DATE,CURRENT_TIMESTAMP(3) AS CREATE_TIME,1
FROM ODS_PROD.T_ODS_CLK_ACCUINT  a
LEFT JOIN DIM_PROD.T_DIM_TID_SET tdts ON a.MEMBERNO  = tdts.TID
WHERE tdts.TID IS null
AND a.ETL_DATE = @ETL_DATE;

INSERT INTO DWD_PROD.T_DWD_MILE_ACCRUAL_FACT
SELECT
CONCAT(COALESCE(DOCNAME, ''),COALESCE(EVENTNO, ''),
COALESCE(ACTIVITYID, ''),'ACCUINT')  AS PK_ID,
'ACCUINT' AS MILEAGE_TYPE,
DOCNAME,
TOTALRECORD,
TOTALAMOUNT,
TOTALVALUE,
BILLINGMONTH,
CAST(BILLINGSTARTDT AS DATE) BILLINGSTARTDT,
CAST(BILLINGENDDT AS DATE) BILLINGENDDT,
MEMBERNO,
MEMBERTIERCODE,
MEMBERBRAND,
BIZTYPECODE,
BIZSUBTYPECODE,
CHANNELCODE,
PARTNERCODE,
EVENTNO,
ACTIVITYID,
TRANID,
ORDERNO,
TKTNO,
COUPONNO,
BILLCOMPANY,
BILLEDCOMPANY,
MILES,
CURRENCY,
SALESPRICE,
COSTSPRICE,
`VALUE` ,
EXCHPOINT,
CAST(IFNULL(ACTIVITYDATE,FLIGHTDATE) AS DATE) ACTIVITYDATE,
OC,
OCFLIGHTNO,
OCCABIN,
OCSUBCLASS,
UPLSTN,
DESSTN,
ASS,
 IRN,
 OAN,
 MEMBERNO TID,
 1,
 1,
 CURRENT_TIMESTAMP(3),
 '1',
  CURRENT_TIMESTAMP(3),
   CURRENT_TIMESTAMP(3)
  FROM ODS_PROD.T_ODS_CLK_ACCUINT 
  WHERE ETL_DATE = @ETL_DATE








