-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--机票-预订-航段级事实表-写DWD
INSERT INTO DIM_PROD.T_DIM_MOBILE_DIM
(T_ID,SYSTEM_KEY,MOBILE_NUMBER,IS_FREQUENT_FLYER_MOBILE,CURRENT_PHONE_HIGHEST_PRIORITY,IS_VIRTUAL_MOBILE,UPDATE_TIME,CREATE_TIME)
SELECT
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS TID ,
concat(TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))),a.PR_MOBILE) AS SYSTEM_KEY,
a.PR_MOBILE ,
TRUE AS IS_FREQUENT_FLYER_MOBILE,
7 AS CURRENT_PHONE_HIGHEST_PRIORITY,
SM4_DECRYPT(FROM_BASE64(a.PR_MOBILE), FROM_BASE64(@SM4_KEY)) REGEXP '^(170|171|162|165|167)[0-9]+' AS IS_VIRTUAL_MOBILE,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_PROD.T_ODS_CLK_T_DW_D_FFP a
WHERE concat(TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))),a.PR_MOBILE)
IS NOT NULL
and a.FFP_LAST_UPD <'2026-01-01'

--事务提交
--commit;