-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--用户维表
INSERT INTO T_DIM_USER_DIM (PK_ID,HISTORICAL_FFP_ID,SEX,EN_NAME,CN_NAME,BIRTHDAY,UPDATE_TIME,CREATE_TIME)
SELECT
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS TID ,
a.FFP_ID,
a.GENDER_ID ,
concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')) EN_NAME,
concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''))  CN_NAME,
a.BIRTH_DT,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_PROD.T_ODS_CLK_T_DW_D_FFP a
WHERE a.MEM_NUM is not null
and a.FFP_LAST_UPD <'2026-01-01'



--用户维表记录表 summary
INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY (PK_ID,HISTORICAL_FFP_ID_SOURCE,HISTORICAL_FFP_ID_UPDATETIME,
SEX_SOURCE,SEX_UPDATETIME,EN_NAME_SOURCE,EN_NAME_UPDATETIME,CN_NAME_SOURCE,CN_NAME_UPDATETIME,BIRTHDAY_SOURCE,BIRTHDAY_UPDATETIME)
SELECT
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.MEM_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS TID ,
CASE
        WHEN FFP_ID IS NOT NULL THEN 'LSCK'
        ELSE NULL
    END AS FFP_ID_SOURCE,
CASE
        WHEN FFP_ID IS NOT NULL THEN now()
        ELSE NULL
    END AS FFP_ID_DATE,
CASE
        WHEN GENDER_ID IS NOT NULL THEN 'LSCK'
        ELSE NULL
    END AS GENDER_ID_SOURCE,
CASE
        WHEN GENDER_ID IS NOT NULL THEN now()
        ELSE NULL
    END AS GENDER_ID_DATE,
CASE
        WHEN concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''))
 IS NOT NULL THEN 'LSCK'
        ELSE NULL
    END AS EN_NAME_SOURCE,
CASE
        WHEN concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.EN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''))
	IS NOT NULL THEN now()
        ELSE NULL
    END AS EN_NAME_DATE,
CASE
        WHEN concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')) IS NOT NULL THEN 'LSCK'
        ELSE NULL
    END AS CN_NAME_SOURCE,
CASE
        WHEN concat(REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_LAST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''),
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.CN_FST_NAME, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')) IS NOT NULL THEN now()
        ELSE NULL
    END AS CN_NAME_DATE,
CASE
        WHEN BIRTH_DT IS NOT NULL THEN 'LSCK'
        ELSE NULL
    END AS BIRTH_DT_SOURCE,
CASE
        WHEN BIRTH_DT IS NOT NULL THEN now()
        ELSE NULL
    END AS BIRTH_DT_DATE
FROM ODS_PROD.T_ODS_CLK_T_DW_D_FFP a
WHERE a.MEM_NUM is not null
and a.FFP_LAST_UPD <'2026-01-01'
--commit;