-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

INSERT INTO DWD_PROD.T_DWD_MEMBER_REGISTER_FACT (PK_ID,FK_TID,FREQUENT_CARD,PARENT_CARD_NUMBER ,
FK_REGISTER_DATE,FK_REGISTER_TIME,GENDER,
EN_FIRST_NAME,EN_LAST_NAME,CH_LAST_NAME ,
CN_NAME ,BIRTHDAY,MEMBER_REGIST_FLT_DATE ,DEV_STAFF_ID ,DEV_NAME ,DEV_DEPARTMENT ,
REGIST_COUNT,FROM_MILE_REGISTER ,DATA_ACTIVE ,DATA_ACTIVE_TIME ,
SYSTEM_LAST_UPDATETIME ,SYSTEM_CREATETIME)
SELECT
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS MEM_NUM ,
IFNULL(scd.TID, TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))))  AS TID,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS FFR ,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.PARENT_FFP_NUM), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS PARENT_FFR ,
SUBSTRING(a.CREATE_DATE,1,10) AS FFP_CREATED_DATE,
SUBSTRING(a.CREATE_DATE,12,8) AS FFP_CREATED_TIME,
a.FSEX ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_FIRST_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','') ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_SECOND_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')  ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.F_FIRTST_NAME_CN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')  ,
REPLACE(UPPER(TRIM(REGEXP_REPLACE(a.FNAMECN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/','')  ,
SUBSTRING(a.FBIRTHDAY,1,10) AS BIRTH_DT ,
a.FFLTDATE ,
COALESCE(a.OP_ACCOUNT,a.FUSER) AS STAFF_ID,
a.OP_NAME ,
a.OPERATE_DEPT ,
1 as NUM_COUNT,
true AS IS_MILE_REGISTER,
true AS DATA_ACTIVE,
now() AS DATA_ACTIVE_TIME,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO a
LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON a.FCARDTYPE  =sid.CFG_CODE
LEFT JOIN DIM_PROD.T_DIM_STRONGID scd ON TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY)))  = scd.STRONGID
and scd.STRONGID_STATUS =1
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='FREQUENT_FLYER'
WHERE a.SEND_FLAG = 'Y'
AND a.SEND_STATUS = '1'
and a.FCARD  is not null
and TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(a.FCARD), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) is not null
and (LENGTH(SM4_DECRYPT(FROM_BASE64(a.FPHONE), FROM_BASE64(@SM4_KEY))) >=15 OR a.FPHONE is null)
AND a.ETL_DATE = @ETL_DATE;

--事务提交
--commit;