-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';

--附加服务_逾重行李出EMD票_航段事实表-升舱金额CNY
INSERT INTO DWD_PROD.T_DWD_EXCESS_BAGGAGE_TIK_FACT
(PK_ID, AK_EXCESSBAGGAGE_OLDAMOUNT_CNY)
SELECT
	PK_ID,
    CASE
        WHEN rt.FIVE_DAY_RATE IS NULL THEN 0 -- 如果找不到汇率，则返回 NULL
        ELSE ROUND(tdutf.AK_EXCESSBAGGAGE_OLDAMOUNT_CNY / rt.FIVE_DAY_RATE, 2)
    END AS AK_EXCESSBAGGAGE_OLDAMOUNT_CNY
FROM DWD_PROD.T_DWD_EXCESS_BAGGAGE_TIK_FACT AS tdutf
LEFT JOIN
(
SELECT
	ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
FROM
	(
	SELECT
		CURRENCY_CODE,
		MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
	FROM
		ODS_PROD.T_ODS_SCCRM_EXCHANGE_RATE er
	GROUP BY
		CURRENCY_CODE
	) rate
LEFT JOIN ODS_PROD.T_ODS_SCCRM_EXCHANGE_RATE ee
ON
	rate.CURRENCY_CODE = ee.CURRENCY_CODE
	AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
) rt
ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
commit;