-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';

-- 附加服务_预付费行李出票_航段事实表-写DWD（呼叫白屏票务系统）
INSERT INTO DWD_PROD.T_DWD_BAGGAGE_TIK_FACT
(PK_ID, FK_BAGGAGETIK_DATE, DEPAIRPORT, ARRIAIRPORT, FK_BAGGAGESTART_DATE, AK_DIMARK,
AK_TIKNUM, AK_EMDNUM, AK_EMD_STATUS, AK_SEGCABIN, AK_CURRENCY, BAGGAGE_AMOUNT,
BAGGAGE_DETAIL, AK_BAGGAGE_ATT, BAGGAGE_BAGS, BAGGAGE_QUANTITY,
AK_EMDTIKCHANNEL, AK_EMDIATACODE, AK_EMDTYPE, PURCHASED_WITH_TICKET,
DATA_ACTIVE, DATA_ACTIVE_TIME, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME,
FK_BOOKING_USER_TID, FK_BOOKING_USER_ORIGIN_ID, AK_CHANNEL, AK_ORDERNUM)
SELECT CONCAT(bo.EMD_NO, flt.FLT_START_CITY, flt.FLT_ARRIVE_CITY) PK_ID,
date_format(bo.CREATE_DATE ,'%Y-%m-%d') AS FK_BAGGAGETIK_DATE, 
flt.FLT_START_CITY AS DEPAIRPORT,flt.FLT_ARRIVE_CITY AS ARRIAIRPORT,
flt.FLT_DEPARTURE_DAY AS FK_BAGGAGESTART_DATE,
CASE WHEN bo.TK_ORDER_TYPE = 1 THEN 'D' ELSE 'I' END AS AK_DIMARK,
NULL AS AK_TIKNUM,bo.EMD_NO AS AK_EMDNUM,
CASE WHEN bo.LUAAGE_ORDER_STATUS = 1 THEN 'I' ELSE 'O' END AS AK_EMD_STATUS,
flt.FLT_CABIN AS AK_SEGCABIN,
CASE WHEN bo.CASH_CURRENCY_CODE IS NOT NULL THEN bo.CASH_CURRENCY_CODE ELSE 'CNY' END AS AK_CURRENCY,
bo.CASH_TOTAL_PRODUCT_PRICE_CUR AS BAGGAGE_AMOUNT,
NULL AS BAGGAGE_DETAIL,
NULL AS AK_BAGGAGE_ATT,
NULL AS BAGGAGE_BAGS,
NULL AS BAGGAGE_QUANTITY,
NULL AS AK_EMDTIKCHANNEL, NULL AS AK_EMDIATACODE,
CASE WHEN bo.EMD_TYPE = 2 THEN 'Y' ELSE NULL END AS AK_EMDTYPE,
CASE WHEN EXISTS (
    SELECT 1 FROM ODS_PROD.T_ODS_KFBP_BUS_ORDER bo2
    WHERE bo2.UNION_ORDER_PKID = bo.UNION_ORDER_PKID 
    AND bo2.ORDER_TYPE = 2
) THEN 1 ELSE 0 END AS PURCHASED_WITH_TICKET,
1 AS DATA_ACTIVE,now() AS DATA_ACTIVE_TIME,now() AS SYSTEM_CREATETIME,now() AS SYSTEM_LAST_UPDATETIME,
NULL AS FK_BOOKING_USER_TID,bo.CUR_TEL AS FK_BOOKING_USER_ORIGIN_ID,
'SCWHP' AS AK_CHANNEL,bo.ORDER_SN AS AK_ORDERNUM
FROM ODS_PROD.T_ODS_KFBP_BUS_ORDER bo
INNER JOIN ODS_PROD.T_ODS_KFBP_BUS_FARE_TICKET_FLT flt
ON bo.FLIGHT_PKID = flt.FLIGHT_PKID
WHERE bo.ORDER_TYPE = 4 
AND bo.EMD_NO IS NOT NULL 
AND bo.EMD_NO != ''
AND date_format(bo.CREATE_DATE ,'%Y-%m-%d') = @ETL_DATE
AND bo.ETL_DATE >= @ETL_DATE;

-- 附加服务_预付费行李出票_航段事实表-预付费行李金额CNY
INSERT INTO DWD_PROD.T_DWD_BAGGAGE_TIK_FACT
(PK_ID, BAGGAGE_AMOUNT_CNY)
SELECT
	PK_ID,
	ROUND(
        CASE
            WHEN rt.FIVE_DAY_RATE IS NULL THEN 
                CASE WHEN tdutf.AK_CURRENCY = 'CNY' THEN tdutf.BAGGAGE_AMOUNT ELSE 0 END
            ELSE tdutf.BAGGAGE_AMOUNT / rt.FIVE_DAY_RATE
        END,
        2
    ) AS BAGGAGE_AMOUNT_CNY
FROM DWD_PROD.T_DWD_BAGGAGE_TIK_FACT AS tdutf
LEFT JOIN
(
SELECT
	ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
FROM
	(
	SELECT
		CURRENCY_CODE,
		MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
	FROM
		ODS_PROD.T_ODS_SCCRM_EXCHANGE_RATE er
	GROUP BY
		CURRENCY_CODE
	) rate
LEFT JOIN ODS_PROD.T_ODS_SCCRM_EXCHANGE_RATE ee
ON
	rate.CURRENCY_CODE = ee.CURRENCY_CODE
	AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
) rt
ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'))
AND tdutf.AK_CHANNEL = 'SCWHP';

-- 事务提交
commit;

