-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';

-- 附加服务_预付费行李退票_航段事实表-写DWD（鲁雁管家-EMD高频）
-- 数据来源：TRACE_EMDINFO表，取ISSUANCE_CODE=C并且ISSUANCE_SUBCODE=0AA的数据，以及EMD_COUPONSTATUS=R的进入本表
-- 主键：EMD票号（不带横杠，纯数字13位）+起飞机场+到达机场
INSERT INTO DWD_PROD.T_DWD_BAGGAGE_REFUND_FACT
(PK_ID, FK_REFUND_DATE, FK_REFUND_TIME, DEPAIRPORT, ARRIAIRPORT, FK_BAGGAGESTART_DATE, AK_DIMARK,
AK_TIKNUM, AK_EMDNUM, AK_EMD_STATUS, AK_SEGCABIN, AK_CURRENCY, BAGGAGE_AMOUNT,
BAGGAGE_DETAIL, AK_BAGGAGE_ATT, BAGGAGE_BAGS, BAGGAGE_QUANTITY, BAGGAGE_COUNT,
DATA_ACTIVE, DATA_ACTIVE_TIME, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME,
EN_FIRST_NAME,EN_LAST_NAME,CN_NAME,PASSENGER_TYPE,CERT__TYPE,
CERT_NUMBER,PASSENGER_AGE,FK_PASSENGER_USER_TID,FK_BAGGAGE_SEG,AK_CABIN)
SELECT CONCAT(REPLACE(temd.EMDTICKETNUMBER, '-', ''), temd.ORIG, temd.DEST) PK_ID,
date_format(temd.UPDATE_TIME ,'%Y-%m-%d') AS FK_REFUND_DATE, 
date_format(temd.UPDATE_TIME ,'%H:%i:%s') AS FK_REFUND_TIME,
temd.ORIG AS DEPAIRPORT,temd.DEST AS ARRIAIRPORT,
temd.FLT_DATE AS FK_BAGGAGESTART_DATE,
temd.EMDTICKETTYPE AS AK_DIMARK,
REPLACE(temd.ET_NUM, '-', '') AS AK_TIKNUM,
REPLACE(temd.EMDTICKETNUMBER, '-', '') AS AK_EMDNUM,
temd.EMD_COUPONSTATUS AS AK_EMD_STATUS,
seg.AK_SEGCABIN AS AK_SEGCABIN,
temd.PAYCURRENCYCODE AS AK_CURRENCY,
CAST(temd.PAYAMOUNT AS DOUBLE) AS BAGGAGE_AMOUNT,
temd.ISSUANCE_DESCRIPTION AS BAGGAGE_DETAIL,
CASE WHEN INSTR(temd.ISSUANCE_DESCRIPTION, 'PC') > 0 THEN 'PC' 
     WHEN INSTR(temd.ISSUANCE_DESCRIPTION, 'KG') > 0 THEN 'KG' 
     ELSE NULL END AS AK_BAGGAGE_ATT,
CASE WHEN INSTR(temd.ISSUANCE_DESCRIPTION, 'PC') > 0 THEN 
     CAST(REPLACE(REPLACE(split_part(temd.ISSUANCE_DESCRIPTION, ' ', 1), 'PC', ''), 'KG', '') AS INT) 
     ELSE NULL END AS BAGGAGE_BAGS,
CASE WHEN INSTR(temd.ISSUANCE_DESCRIPTION, 'KG') > 0 AND INSTR(temd.ISSUANCE_DESCRIPTION, 'PC') = 0 THEN 
     CAST(REPLACE(split_part(temd.ISSUANCE_DESCRIPTION, ' ', 1), 'KG', '') AS INT) 
     ELSE NULL END AS BAGGAGE_QUANTITY,
1 AS BAGGAGE_COUNT,
1 AS DATA_ACTIVE,
now() AS DATA_ACTIVE_TIME,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME,
-- 直接获取航班事实表数据，无需再次标准化
seg.EN_FIRST_NAME,seg.EN_LAST_NAME,seg.CN_NAME,seg.PASSENGER_TYPE,seg.CERT_TYPE,
seg.CERT_NUMBER,seg.PASSENGER_AGE,seg.FK_PASSENGER_USER_TID,seg.FK_SEG_SEGMENT AS FK_BAGGAGE_SEG,seg.AK_CABIN AS AK_CABIN
FROM ODS_PROD.T_ODS_LYGJ_TRACE_EMDINFO temd
LEFT JOIN DWD_PROD.T_DWD_TICKING_SEG_FACT seg
ON CONCAT(REPLACE(temd.ET_NUM, '-', ''), temd.ORIG, REPLACE(temd.FLT_DATE,'-',''))=seg.PK_ID
WHERE temd.ISSUANCE_CODE='C' AND temd.ISSUANCE_SUBCODE='0AA' AND temd.EMD_COUPONSTATUS='R'
AND temd.ETL_DATE >= @ETL_DATE;

-- 附加服务_预付费行李退票_航段事实表-写DWD（呼叫白屏票务系统）
-- 数据来源：BUS_ORDER表，白屏的数据T+1入库后，找BUS_ORDER的update_date是T时间的，同时order_type=4（行李）的，emd_no非空，emd_luaage_order_refund_pkid非空
-- 连表：BUS_ORDER和BUS_FLIGHT连表，BUS_ORDER.flight_pkid=BUS_FLIGHT.pkid
-- 主键：BUS_ORDER.emd_no+BUS_FLIGHT.FLT_START_CITY+FLT_ARRIVE_CITY
INSERT INTO DWD_PROD.T_DWD_BAGGAGE_REFUND_FACT
(PK_ID, FK_REFUND_DATE, FK_REFUND_TIME, DEPAIRPORT, ARRIAIRPORT, FK_BAGGAGESTART_DATE, FK_BAGGAGESTART_TIME, AK_DIMARK,
AK_TIKNUM, AK_EMDNUM, AK_EMD_STATUS, AK_SEGCABIN, AK_CURRENCY, BAGGAGE_AMOUNT,
BAGGAGE_DETAIL, AK_BAGGAGE_ATT, BAGGAGE_BAGS, BAGGAGE_QUANTITY, BAGGAGE_COUNT,
DATA_ACTIVE, DATA_ACTIVE_TIME, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME,
AK_ORDERNUM, REFUND_CHANNEL, FK_REFUND_USER_TID, FK_REFUND_USER_ORIGIN_ID)
SELECT CONCAT(bo.EMD_NO, flt.FLT_START_CITY, flt.FLT_ARRIVE_CITY) PK_ID,
date_format(bo.UPDATE_DATE ,'%Y-%m-%d') AS FK_REFUND_DATE,
date_format(bo.UPDATE_DATE ,'%H:%i:%s') AS FK_REFUND_TIME,
flt.FLT_START_CITY AS DEPAIRPORT,
flt.FLT_ARRIVE_CITY AS ARRIAIRPORT,
flt.FLT_DEPARTURE_DAY AS FK_BAGGAGESTART_DATE,
flt.FLT_DEPARTURE_TIME AS FK_BAGGAGESTART_TIME,
CASE WHEN bo.TK_ORDER_TYPE = 1 THEN 'D' ELSE 'I' END AS AK_DIMARK,
NULL AS AK_TIKNUM,
bo.EMD_NO AS AK_EMDNUM,
'R' AS AK_EMD_STATUS,
flt.FLT_CABIN AS AK_SEGCABIN,
CASE WHEN bo.CASH_CURRENCY_CODE IS NOT NULL THEN bo.CASH_CURRENCY_CODE ELSE 'CNY' END AS AK_CURRENCY,
bo.CASH_TOTAL_PRODUCT_PRICE_CUR AS BAGGAGE_AMOUNT,
NULL AS BAGGAGE_DETAIL,
NULL AS AK_BAGGAGE_ATT,
NULL AS BAGGAGE_BAGS,
NULL AS BAGGAGE_QUANTITY,
1 AS BAGGAGE_COUNT,
1 AS DATA_ACTIVE,
now() AS DATA_ACTIVE_TIME,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME,
bo.ORDER_SN AS AK_ORDERNUM,
'SCWHP' AS REFUND_CHANNEL,
NULL AS FK_REFUND_USER_TID,
br.CUR_TEL AS FK_REFUND_USER_ORIGIN_ID
FROM ODS_PROD.T_ODS_KFBP_BUS_ORDER bo
INNER JOIN ODS_PROD.T_ODS_KFBP_BUS_FLIGHT flt
ON bo.FLIGHT_PKID = flt.PKID
LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_REFUND br
ON bo.ORDER_PKID = br.ORDER_PKID
WHERE bo.ORDER_TYPE = 4
AND bo.EMD_NO IS NOT NULL
AND bo.EMD_NO != ''
AND bo.EMD_LUAAGE_ORDER_REFUND_PKID IS NOT NULL
AND bo.EMD_LUAAGE_ORDER_REFUND_PKID != ''
AND date_format(bo.UPDATE_DATE ,'%Y-%m-%d') = @ETL_DATE
AND bo.ETL_DATE >= @ETL_DATE;

-- 附加服务_预付费行李退票_航段事实表-预付费行李金额CNY
-- 汇率转换：如果原币种=CNY，直接将原币种预付费行李金额写入；如果不是CNY，根据汇率表转化
-- 按照EMD的退票月份，取比价月是上个月的数据，如果没有上月数据，取上上个月的，以此类推
INSERT INTO DWD_PROD.T_DWD_BAGGAGE_REFUND_FACT
(PK_ID, BAGGAGE_AMOUNT_CNY)
SELECT
	tdutf.PK_ID,
	ROUND(
        CASE
            WHEN rt.FIVE_DAY_RATE IS NULL THEN 
                CASE WHEN tdutf.AK_CURRENCY = 'CNY' THEN tdutf.BAGGAGE_AMOUNT ELSE 0 END
            ELSE tdutf.BAGGAGE_AMOUNT / rt.FIVE_DAY_RATE
        END,
        2
    ) AS BAGGAGE_AMOUNT_CNY
FROM DWD_PROD.T_DWD_BAGGAGE_REFUND_FACT AS tdutf
LEFT JOIN
(
SELECT
	ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
FROM
	(
	SELECT
		CURRENCY_CODE,
		MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
	FROM
		ODS_PROD.T_ODS_SCCRM_EXCHANGE_RATE er
	GROUP BY
		CURRENCY_CODE
	) rate
LEFT JOIN ODS_PROD.T_ODS_SCCRM_EXCHANGE_RATE ee
ON
	rate.CURRENCY_CODE = ee.CURRENCY_CODE
	AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
) rt
ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
AND (tdutf.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR tdutf.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'))
AND tdutf.BAGGAGE_AMOUNT_CNY IS NULL;

-- 事务提交
commit;

