INSERT INTO DWD_PROD.T_DWD_MULTI_CARD_REDEEM_FACT
(PK_ID, FK_TKTPRICE)
SELECT
    t1.PK_ID,
    t2.SALE_PRICE / NULLIF(t2.EXCHANGE_NUM, 0) AS FK_TKTPRICE
FROM
    (SELECT PK_ID ,AK_ORDERNUM
     FROM DWD_PROD.T_DWD_MULTI_CARD_REDEEM_FACT a
      WHERE (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000') AND SYSTEM_CREATETIME < CONCAT(@ETL_DATE, ' 23:59:59.999'))
         OR (SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000') AND SYSTEM_LAST_UPDATETIME < CONCAT(@ETL_DATE, ' 23:59:59.999'))
    ) t1
JOIN (
    SELECT
        MAIN_ORDER_NO,
       SALE_PRICE,
       EXCHANGE_NUM
    FROM ODS_PROD.T_ODS_ZSF_ODR_ORDER_DETAIL_SECONDARY_DOUYIN b
) t2 ON t1.AK_ORDERNUM = t2.MAIN_ORDER_NO ;

--事务提交
commit;