--微信小程序写入出票航段级事实表
--SET @ETL_DATE='2025-05-23';

INSERT INTO DWD_PROD.T_DWD_TICKING_SEG_FACT
(
    PK_ID
    ,SEAT_CHANNEL
)
SELECT replace(CONCAT(TICKET_NO,DEP,FLIGHT_DATE,IFNULL(SHARE_FLIGHT_NO,'')),'-','') PK_ID,"SCXCX" AS SEAT_CHANNEL FROM ODS_PROD.T_ODS_WXAP_CHECKIN_TRP_ORDER_PASSENGER WHERE SEAT_TYPE=0 AND ETL_DATE=@ETL_DATE;