-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';

--写入用户维表-常客卡号证件信息校验表
INSERT INTO DIM_TEST.T_DIM_FFP_CERT_CHECK_DIM
(SYSTEM_KEY, MEMBERNUMBER, MEMBERNUMBER_TYPE, NAME_CN, NAME_EN,CREDENTIALTYPE,CREDENTIALNUM, MOBILE, EMAIL, UPDATE_TIME, CREATE_TIME)
SELECT concat(acc.MEMBERNO, toldpi.CERT_NO) AS SYSTEM_KEY,acc.MEMBERNO AS MEMBERNUMBER,
toldpi.IS_FFP_JK AS MEMBERNUMBER_TYPE,toldpi.PSG_NAME_CN AS NAME_CN,
UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))) AS NAME_EN,
sid.CFG_VALUE AS CREDENTIALTYPE,toldpi.CERT_NO AS CREDENTIALNUM,
toldpi.MOBILE_PHONE AS MOBILE,toldpi.EMAIL ,now() UPDATE_TIME,now() CREATE_TIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO AS toldpi
LEFT JOIN ODS_TEST.T_ODS_CLK_ACCU acc ON
toldpi.ET_NUM=acc.TKTNO AND toldpi.ORIG = acc.UPLSTN AND toldpi.FLT_DATE = acc.FLIGHTDATE
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE acc.id IS not NULL
AND instr(SM4_DECRYPT(FROM_BASE64(acc.MEMBERNO), FROM_BASE64(@SM4_KEY)),REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(toldpi.FFP), FROM_BASE64(@SM4_KEY)),'\\D',''))>0
AND toldpi.CERT_NO IS NOT NULL;

--写入强ID
INSERT INTO DIM_TEST.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME)
SELECT CREDENTIALNUM as STRONGID,ffc.CREDENTIALTYPE AS STRONGID_TYPE,CREDENTIALNUM AS TID, 1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM DIM_TEST.T_DIM_FFP_CERT_CHECK_DIM ffc
LEFT JOIN DIM_TEST.T_DIM_STRONGID sid ON ffc.CREDENTIALNUM = sid.STRONGID
WHERE sid.TID IS null;--只插入没有的，存在的不用插入，所以CREDENTIALNUM直接作为TID

--写入强ID（常客卡号）
INSERT INTO DIM_TEST.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME)
SELECT MEMBERNUMBER as STRONGID,'FFP' AS STRONGID_TYPE,sid.TID, 1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM DIM_TEST.T_DIM_FFP_CERT_CHECK_DIM ffc
LEFT JOIN DIM_TEST.T_DIM_STRONGID sid ON ffc.CREDENTIALNUM = sid.STRONGID
WHERE sid.TID IS null;--只插入没有的，存在的不用插入

INSERT INTO DIM_TEST.T_DIM_STRONGID
(STRONGID, STRONGID_TYPE, TID, STRONGID_STATUS, CREATE_TIME, UPDATE_TIME)
SELECT MEMBERNUMBER as STRONGID,'FFP' AS STRONGID_TYPE,sid.TID, 1, CURRENT_TIMESTAMP(3) AS CREATE_TIME,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM DIM_TEST.T_DIM_FFP_CERT_CHECK_DIM ffc
LEFT JOIN DIM_TEST.T_DIM_STRONGID sid ON ffc.MEMBERNUMBER = sid.STRONGID
WHERE sid.TID IS null;--只插入没有的，存在的不用插入

--写入TID集合
INSERT INTO DIM_TEST.T_DIM_TID_SET
(TID, ETL_DATE, CREATE_TIME, TID_STATUS)
SELECT CREDENTIALNUM as STRONGID,now() AS ETL_DATE,CURRENT_TIMESTAMP(3) AS CREATE_TIME,1
FROM DIM_TEST.T_DIM_FFP_CERT_CHECK_DIM ffc
LEFT JOIN DIM_TEST.T_DIM_TID_SET tdts ON ffc.CREDENTIALNUM = tdts.TID
WHERE tdts.TID IS null;

--写入用户维表-常客信息维表
INSERT INTO DIM_TEST.T_DIM_FFP_DIM
(SYSTEM_KEY, T_ID, FFRF, FF_LEVEL, MOST_TRUSTED_SOURCE, UPDATE_TIME, CREATE_TIME)
SELECT MEMBERNUMBER AS SYSTEM_KEY,sid.TID AS T_ID, MEMBERNUMBER, MEMBERNUMBER_TYPE, 0 AS MOST_TRUSTED_SOURCE,
CURRENT_TIMESTAMP(3) AS UPDATE_TIME, CURRENT_TIMESTAMP(3) AS CREATE_TIME
FROM DIM_TEST.T_DIM_FFP_CERT_CHECK_DIM ffc
LEFT JOIN DIM_TEST.T_DIM_STRONGID sid ON ffc.CREDENTIALNUM = sid.STRONGID;










