-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-11-11';

-- 附加服务_预付费行李出票_航段事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_BAGGAGE_TIK_FACT
(PK_ID, FK_BAGGAGETIK_DATE, DEPAIRPORT, ARRIAIRPORT, FK_BAGGAGESTART_DATE, AK_DIMARK,
AK_TIKNUM, AK_EMDNUM, AK_EMD_STATUS, AK_SEGCABIN, AK_CURRENCY, BAGGAGE_AMOUNT,
BAGGAGE_DETAIL, AK_BAGGAGE_ATT, BAGGAGE_BAGS, BAGGAGE_QUANTITY,
AK_EMDTIKCHANNEL, AK_EMDIATACODE, AK_EMDTYPE, PURCHASED_WITH_TICKET,
DATA_ACTIVE, DATA_ACTIVE_TIME, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME,
EN_FIRST_NAME,EN_LAST_NAME,CN_NAME,PASSENGER_TYPE,CERT_TYPE,
CERT_NUMBER,PASSENGER_AGE,FK_PASSENGER_USER_TID,FK_BAGGAGE_SEG,AK_CABIN)
SELECT CONCAT(REPLACE(temd.EMDTICKETNUMBER, '-', ''), temd.ORIG, temd.DEST) PK_ID,
EMDISSUEDATE AS FK_BAGGAGETIK_DATE, ORIG AS DEPAIRPORT,DEST AS ARRIAIRPORT,
FLT_DATE AS FK_BAGGAGESTART_DATE,EMDTICKETTYPE AS AK_DIMARK,
REPLACE(temd.ET_NUM, '-', '') AS AK_TIKNUM,
REPLACE(temd.EMDTICKETNUMBER, '-', '') AS AK_EMDNUM,EMD_COUPONSTATUS AS AK_EMD_STATUS,
seg.AK_SEGCABIN AS AK_SEGCABIN,PAYCURRENCYCODE AS AK_CURRENCY,CAST(PAYAMOUNT AS DOUBLE) AS BAGGAGE_AMOUNT,
ISSUANCE_DESCRIPTION AS BAGGAGE_DETAIL,
CASE WHEN INSTR(ISSUANCE_DESCRIPTION, 'PC') > 0 THEN 'PC' 
     WHEN INSTR(ISSUANCE_DESCRIPTION, 'KG') > 0 THEN 'KG' 
     ELSE NULL END AS AK_BAGGAGE_ATT,
CASE WHEN INSTR(ISSUANCE_DESCRIPTION, 'PC') > 0 THEN 
     CAST(REPLACE(REPLACE(split_part(ISSUANCE_DESCRIPTION, ' ', 1), 'PC', ''), 'KG', '') AS INT) 
     ELSE NULL END AS BAGGAGE_BAGS,
CASE WHEN INSTR(ISSUANCE_DESCRIPTION, 'KG') > 0 AND INSTR(ISSUANCE_DESCRIPTION, 'PC') = 0 THEN 
     CAST(REPLACE(split_part(ISSUANCE_DESCRIPTION, ' ', 1), 'KG', '') AS INT) 
     ELSE NULL END AS BAGGAGE_QUANTITY,
EMDISSUEOFFICE AS AK_EMDTIKCHANNEL, EMDIATACODE AS AK_EMDIATACODE,EMD_TYPE AS AK_EMDTYPE,
1 AS PURCHASED_WITH_TICKET,1 AS DATA_ACTIVE,
now() AS DATA_ACTIVE_TIME,now() AS SYSTEM_CREATETIME,now() AS SYSTEM_LAST_UPDATETIME,
-- 直接获取航班事实表数据，无需再次标准化
seg.EN_FIRST_NAME,seg.EN_LAST_NAME,seg.CN_NAME,seg.PASSENGER_TYPE,seg.CERT_TYPE,
seg.CERT_NUMBER,seg.PASSENGER_AGE,seg.FK_PASSENGER_USER_TID,seg.FK_SEG_SEGMENT AS FK_BAGGAGE_SEG,seg.AK_CABIN AS AK_CABIN
FROM ODS_TEST.T_ODS_LYGJ_TRACE_EMDINFO temd
LEFT JOIN DWD_TEST.T_DWD_TICKING_SEG_FACT seg
ON CONCAT(REPLACE(temd.ET_NUM, '-', ''), temd.ORIG, REPLACE(temd.FLT_DATE,'-',''))=seg.PK_ID
WHERE temd.ISSUANCE_CODE='C' AND temd.ISSUANCE_SUBCODE='0AA'
AND temd.ETL_DATE >= @ETL_DATE;

-- 附加服务_预付费行李出票_航段事实表-预付费行李金额CNY
INSERT INTO DWD_TEST.T_DWD_BAGGAGE_TIK_FACT
(PK_ID, BAGGAGE_AMOUNT_CNY)
SELECT
	PK_ID,
	ROUND(
        CASE
            WHEN rt.FIVE_DAY_RATE IS NULL THEN 
                CASE WHEN tdutf.AK_CURRENCY = 'CNY' THEN tdutf.BAGGAGE_AMOUNT ELSE 0 END
            ELSE tdutf.BAGGAGE_AMOUNT / rt.FIVE_DAY_RATE
        END,
        2
    ) AS BAGGAGE_AMOUNT_CNY
FROM DWD_TEST.T_DWD_BAGGAGE_TIK_FACT AS tdutf
LEFT JOIN
(
SELECT
	ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
FROM
	(
	SELECT
		CURRENCY_CODE,
		MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
	FROM
		ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE er
	GROUP BY
		CURRENCY_CODE
	) rate
LEFT JOIN ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE ee
ON
	rate.CURRENCY_CODE = ee.CURRENCY_CODE
	AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
) rt
ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

-- 事务提交
commit;

