-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';

--附加服务_升舱出EMD票_航段事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_UPGR_TIK_FACT
(PK_ID, FK_UPGRTIK_DATE, DEPAIRPORT, ARRIAIRPORT, FK_SEG_DATE, AK_DIMARK,
AK_TIKNUM, AK_EMDNUM, AK_EMD_STATUS, AK_UPGRDOLD_CABIN, AK_UPGRDNEW_CABIN,UPGRDOLD_CLASS,UPGRDNEW_CLASS,
AK_CURRENCY, UPGRDOLD_AMOUNT, UPGRDOLD_DETTAIL, AK_EMDTIKCHANNEL, AK_EMDIATACODE,
AK_EMDTYPE, DATA_ACTIVE, DATA_ACTIVE_TIME, SYSTEM_LAST_UPDATETIME,
EN_FIRST_NAME,EN_LAST_NAME,CN_NAME,PASSENGER_TYPE,CERT_TYPE,
CERT_NUMBER,PASSENGER_AGE,FK_PASSENGER_USER_TID,FK_CABINUPGRINV_SEG)
SELECT CONCAT(temd.EMDTICKETNUMBER, temd.ORIG, temd.DEST) PK_ID,
EMDISSUEDATE AS FK_UPGRTIK_DATE, ORIG AS DEPAIRPORT,DEST AS ARRIAIRPORT,
FLT_DATE AS FK_SEG_DATE,EMDTICKETTYPE AS AK_DIMARK,ET_NUM AS AK_TIKNUM,
EMDTICKETNUMBER AS AK_EMDNUM,EMD_COUPONSTATUS AS AK_EMD_STATUS,
split_part(ISSUANCE_DESCRIPTION, ' ', 2) AS AK_UPGRDOLD_CABIN, split_part(ISSUANCE_DESCRIPTION, ' ', 3) AS AK_UPGRDNEW_CABIN,
CASE
  WHEN to_date(FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
    CASE
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 2)), 'CDPI') > 0 THEN 'BC'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 2)), 'WR') > 0 THEN 'PE'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 2)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
  ELSE  -- 2023.10.29及以后
    CASE
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 2)), 'JCDRZI') > 0 THEN 'BC'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 2)), 'GE') > 0 THEN 'PE'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 2)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
END AS UPGRDOLD_CLASS,
CASE
  WHEN to_date(FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
    CASE
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 3)), 'CDPI') > 0 THEN 'BC'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 3)), 'WR') > 0 THEN 'PE'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 3)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
  ELSE  -- 2023.10.29及以后
    CASE
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 3)), 'JCDRZI') > 0 THEN 'BC'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 3)), 'GE') > 0 THEN 'PE'
      WHEN locate(upper(split_part(ISSUANCE_DESCRIPTION, ' ', 3)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
END AS UPGRDNEW_ClASS,
PAYCURRENCYCODE AS AK_CURRENCY,PAYAMOUNT AS UPGRDOLD_AMOUNT,
ISSUANCE_DESCRIPTION AS UPGRDOLD_DETTAIL,EMDISSUEOFFICE AS AK_EMDTIKCHANNEL,
EMDIATACODE AS AK_EMDIATACODE,EMD_TYPE AS AK_EMDTYPE,1 AS DATA_ACTIVE,
now() AS DATA_ACTIVE_TIME,now() AS SYSTEM_LAST_UPDATETIME,
--直接获取航班事实表数据，无需再次标准化
seg.EN_FIRST_NAME,seg.EN_LAST_NAME,seg.CN_NAME,seg.PASSENGER_TYPE,seg.CERT_TYPE,
seg.CERT_NUMBER,seg.PASSENGER_AGE,seg.FK_PASSENGER_USER_TID,seg.FK_SEG_SEGMENT AS FK_CABINUPGRINV_SEG
FROM ODS_TEST.T_ODS_LYGJ_TRACE_EMDINFO temd
LEFT JOIN DWD_TEST.T_DWD_TICKING_SEG_FACT seg
ON CONCAT(temd.ET_NUM, temd.ORIG, REPLACE(temd.FLT_DATE,'-',''))=seg.PK_ID
WHERE temd.ISSUANCE_CODE='A' AND temd.ISSUANCE_SUBCODE='04E'
AND temd.ETL_DATE >= @ETL_DATE;

--附加服务_升舱出EMD票_航段事实表-升舱金额CNY
INSERT INTO DWD_TEST.T_DWD_UPGR_TIK_FACT
(PK_ID, UPGRDOLD_AMOUNT_CNY)
SELECT
	PK_ID,
	ROUND(
        CASE
            WHEN rt.FIVE_DAY_RATE IS NULL THEN 1 -- 如果找不到汇率，则返回 NULL
            ELSE tdutf.UPGRDOLD_AMOUNT / rt.FIVE_DAY_RATE
        END,
        2
    ) AS UPGRDOLD_AMOUNT_CNY
FROM DWD_TEST.T_DWD_UPGR_TIK_FACT AS tdutf
LEFT JOIN
(
SELECT
	ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
FROM
	(
	SELECT
		CURRENCY_CODE,
		MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
	FROM
		ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE er
	GROUP BY
		CURRENCY_CODE
	) rate
LEFT JOIN ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE ee
ON
	rate.CURRENCY_CODE = ee.CURRENCY_CODE
	AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
) rt
ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));








