-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';

--附加服务_升舱出EMD票_航段事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_UPGR_TIK_FACT
(PK_ID, AK_ORDERNUM, AK_BOOK_CHANNEL , IS_USE_UPGR_CUPON , PAY_TYPE, UPGRDOLD_AMOUNT, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT
    CONCAT(COALESCE(oi.EMD_NO,''), COALESCE(uoi.ORGCITY_CODE,''), COALESCE(uoi.DSTCITY_CODE,'')) PK_ID,
    oi.ORDER_NO AS AK_ORDERNUM,
    COALESCE(fc_channel.CFG_VALUE, oi.CHANNEL_CODE) AS AK_BOOK_CHANNEL,
    CASE
        WHEN COALESCE(fc_paytype.CFG_VALUE, 'CSH') = 'VCH' THEN 'true'
        ELSE 'false'  -- 如果不是 'VCH'，总是设置为 false
    END AS IS_USE_UPGR_CUPON,
    COALESCE(fc_paytype.CFG_VALUE, 'CSH') AS PAY_TYPE,
    pi.PAY_AMOUNT AS UPGRDOLD_AMOUNT,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME
FROM
    ODS_TEST.T_ODS_DJKSC_ORDER_INFO oi
LEFT JOIN ODS_TEST.T_ODS_DJKSC_PAYMENT_INFO pi ON oi.ORDER_NO = pi.ORDER_NO
LEFT JOIN ODS_TEST.T_ODS_DJKSC_UPGFLT_ORDER_INFO uoi ON oi.USER_ID = uoi.USER_ID
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD fc_channel
    ON oi.CHANNEL_CODE = fc_channel.CFG_CODE
    AND fc_channel.CFG_TYPE = 'UPGRADE_ORDER_CHANNEL'
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD fc_paytype
    ON pi.PAY_TYPE = fc_paytype.CFG_CODE
    AND fc_paytype.CFG_TYPE = 'ORDER_PAYMENT_METHOD'
    AND fc_paytype.CFG_TYPE_CHANNEL = 'GATE_UPGRADE'
WHERE
    oi.EMD_NO IS NOT NULL
AND CONCAT(COALESCE(oi.EMD_NO,''), COALESCE(uoi.ORGCITY_CODE,''), COALESCE(uoi.DSTCITY_CODE,'')) IS NOT NULL
AND oi.ETL_DATE BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');

--附加服务_升舱出EMD票_航段事实表-原币种升舱金额
INSERT INTO DWD_TEST.T_DWD_UPGR_TIK_FACT (PK_ID, UPGRDOLD_AMOUNT)
SELECT PK_ID,0 FROM DWD_TEST.T_DWD_UPGR_TIK_FACT
WHERE PAY_TYPE='VCH' AND UPGRDOLD_AMOUNT>0 AND DATA_ACTIVE = 1
AND DATA_ACTIVE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000');

--附加服务_升舱出EMD票_航段事实表-预订人TID
INSERT INTO DWD_TEST.T_DWD_UPGR_TIK_FACT (PK_ID, FK_BOOKING_USER_TID)
SELECT PK_ID,FK_PASSENGER_USER_TID FROM DWD_TEST.T_DWD_UPGR_TIK_FACT
WHERE AK_EMDNUM IS NOT NULL
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--附加服务_升舱出EMD票_航段事实表-升舱金额CNY
INSERT INTO DWD_TEST.T_DWD_UPGR_TIK_FACT
(PK_ID, UPGRDOLD_AMOUNT_CNY)
SELECT
	PK_ID,
	ROUND(
        CASE
            WHEN rt.FIVE_DAY_RATE IS NULL THEN 1 -- 如果找不到汇率，则返回 NULL
            ELSE tdutf.UPGRDOLD_AMOUNT / rt.FIVE_DAY_RATE
        END,
        2
    ) AS UPGRDOLD_AMOUNT_CNY
FROM DWD_TEST.T_DWD_UPGR_TIK_FACT AS tdutf
LEFT JOIN
(
SELECT
	ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
FROM
	(
	SELECT
		CURRENCY_CODE,
		MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
	FROM
		ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE er
	GROUP BY
		CURRENCY_CODE
	) rate
LEFT JOIN ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE ee
ON
	rate.CURRENCY_CODE = ee.CURRENCY_CODE
	AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
) rt
ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));




--附加服务_升舱退EMD票_航段事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_UPGR_REFUND_FACT
(PK_ID, AK_ORDERNUM, AK_REFUND_CHANNEL , IS_USE_UPGR_CUPON , PAY_TYPE, UPGRDOLD_AMOUNT, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT
    CONCAT(COALESCE(oi.EMD_NO,''), COALESCE(uoi.ORGCITY_CODE,''), COALESCE(uoi.DSTCITY_CODE,'')) PK_ID,
    oi.ORDER_NO AS AK_ORDERNUM,
    COALESCE(fc_channel.CFG_VALUE, oi.CHANNEL_CODE) AS AK_BOOK_CHANNEL,
    CASE
        WHEN COALESCE(fc_paytype.CFG_VALUE, 'CSH') = 'VCH' THEN 'true'
        ELSE 'false'  -- 如果不是 'VCH'，总是设置为 false
    END AS IS_USE_UPGR_CUPON,
    COALESCE(fc_paytype.CFG_VALUE, 'CSH') AS PAY_TYPE,
    pi.PAY_AMOUNT AS UPGRDOLD_AMOUNT,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME
FROM
    ODS_TEST.T_ODS_DJKSC_ORDER_INFO oi
LEFT JOIN ODS_TEST.T_ODS_DJKSC_PAYMENT_INFO pi ON oi.ORDER_NO = pi.ORDER_NO
LEFT JOIN ODS_TEST.T_ODS_DJKSC_UPGFLT_ORDER_INFO uoi ON oi.USER_ID = uoi.USER_ID
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD fc_channel
    ON oi.CHANNEL_CODE = fc_channel.CFG_CODE
    AND fc_channel.CFG_TYPE = 'UPGRADE_ORDER_CHANNEL'
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD fc_paytype
    ON pi.PAY_TYPE = fc_paytype.CFG_CODE
    AND fc_paytype.CFG_TYPE = 'ORDER_PAYMENT_METHOD'
    AND fc_paytype.CFG_TYPE_CHANNEL = 'GATE_UPGRADE'
WHERE
    oi.EMD_NO IS NOT NULL
AND oi.ORDER_STATE = '6'
AND CONCAT(COALESCE(oi.EMD_NO,''), COALESCE(uoi.ORGCITY_CODE,''), COALESCE(uoi.DSTCITY_CODE,'')) IS NOT NULL
AND oi.ETL_DATE BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');

--附加服务_升舱退EMD票_航段事实表-原币种升舱金额
INSERT INTO DWD_TEST.T_DWD_UPGR_REFUND_FACT (PK_ID, UPGRDOLD_AMOUNT)
SELECT PK_ID,0 FROM DWD_TEST.T_DWD_UPGR_REFUND_FACT
WHERE PAY_TYPE='VCH' AND UPGRDOLD_AMOUNT>0 AND DATA_ACTIVE = 1
AND DATA_ACTIVE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');

--附加服务_升舱退EMD票_航段事实表-预订人TID
INSERT INTO DWD_TEST.T_DWD_UPGR_REFUND_FACT (PK_ID, FK_BOOKING_USER_TID)
SELECT PK_ID,FK_PASSENGER_USER_TID FROM DWD_TEST.T_DWD_UPGR_REFUND_FACT
WHERE AK_EMDNUM IS NOT NULL
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--附加服务_升舱退EMD票_航段事实表-升舱金额CNY
INSERT INTO DWD_TEST.T_DWD_UPGR_REFUND_FACT
(PK_ID, UPGRDOLD_AMOUNT_CNY)
SELECT
	PK_ID,
	ROUND(
        CASE
            WHEN rt.FIVE_DAY_RATE IS NULL THEN 1 -- 如果找不到汇率，则返回 NULL
            ELSE tdutf.UPGRDOLD_AMOUNT / rt.FIVE_DAY_RATE
        END,
        2
    ) AS UPGRDOLD_AMOUNT_CNY
FROM DWD_TEST.T_DWD_UPGR_REFUND_FACT AS tdutf
LEFT JOIN
(
SELECT
	ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
FROM
	(
	SELECT
		CURRENCY_CODE,
		MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
	FROM
		ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE er
	GROUP BY
		CURRENCY_CODE
	) rate
LEFT JOIN ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE ee
ON
	rate.CURRENCY_CODE = ee.CURRENCY_CODE
	AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
) rt
ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
AND (SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
OR SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;