
package com.travelsky.trp.usercenter.data.analysis.cascrmclient.memberinfoquerynew;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MemberInfoQueryNewService", targetNamespace = "http://service.memberInfoQueryNew.crm_interface.sda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MemberInfoQueryNewService {


    /**
     * 
     * @param memberInfoQueryNewInputEntity
     * @return
     *     returns com.travelsky.trp.usercenter.data.analysis.cascrmclient.memberinfoquerynew.MemberInfoQueryNewOutputEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMemberInfoNew", targetNamespace = "http://service.memberInfoQueryNew.crm_interface.sda.com/", className = "com.travelsky.trp.usercenter.data.analysis.cascrmclient.memberinfoquerynew.GetMemberInfoNew")
    @ResponseWrapper(localName = "getMemberInfoNewResponse", targetNamespace = "http://service.memberInfoQueryNew.crm_interface.sda.com/", className = "com.travelsky.trp.usercenter.data.analysis.cascrmclient.memberinfoquerynew.GetMemberInfoNewResponse")
    public MemberInfoQueryNewOutputEntity getMemberInfoNew(
        @WebParam(name = "memberInfoQueryNewInputEntity", targetNamespace = "")
        MemberInfoQueryNewInputEntity memberInfoQueryNewInputEntity);

}
