
package com.travelsky.trp.usercenter.data.analysis.cascrmclient.memberinfoquerynew;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "MemberInfoQueryNewServiceImplService", targetNamespace = "http://service.memberInfoQueryNew.crm_interface.sda.com/", wsdlLocation = "http://10.31.0.10:58091/crm/services/memberInfoQueryNew?wsdl")
public class MemberInfoQueryNewServiceImplService
    extends Service
{

    private final static URL MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_QNAME = new QName("http://service.memberInfoQueryNew.crm_interface.sda.com/", "MemberInfoQueryNewServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.31.0.10:58091/crm/services/memberInfoQueryNew?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MemberInfoQueryNewServiceImplService() {
        super(__getWsdlLocation(), MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_QNAME);
    }

    public MemberInfoQueryNewServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_QNAME, features);
    }

    public MemberInfoQueryNewServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_QNAME);
    }

    public MemberInfoQueryNewServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_QNAME, features);
    }

    public MemberInfoQueryNewServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberInfoQueryNewServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MemberInfoQueryNewService
     */
    @WebEndpoint(name = "MemberInfoQueryNewServicePort")
    public MemberInfoQueryNewService getMemberInfoQueryNewServicePort() {
        return super.getPort(new QName("http://service.memberInfoQueryNew.crm_interface.sda.com/", "MemberInfoQueryNewServicePort"), MemberInfoQueryNewService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberInfoQueryNewService
     */
    @WebEndpoint(name = "MemberInfoQueryNewServicePort")
    public MemberInfoQueryNewService getMemberInfoQueryNewServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.memberInfoQueryNew.crm_interface.sda.com/", "MemberInfoQueryNewServicePort"), MemberInfoQueryNewService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MEMBERINFOQUERYNEWSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
