-- DWD层 TRP-休息室券销售-业务事实表
-- T_DWD_TRP_COUPON_SALE_FACT
CREATE TABLE IF NOT EXISTS T_DWD_TRP_COUPON_SALE_FACT (
    PK_ID VARCHAR(600) NOT NULL COMMENT '主键ID (订单号+券码)',
    ORDER_NUMBER VARCHAR(500) REPLACE NULL COMMENT '订单号',
    PURCHASE_CHANNEL VARCHAR(500) REPLACE NULL COMMENT '购买渠道',
    PURCHASE_DATE VARCHAR(50) REPLACE NULL COMMENT '购买日期',
    PURCHASE_TIME VARCHAR(50) REPLACE NULL COMMENT '购买时间',
    VOUCHER_NAME VARCHAR(500) REPLACE NULL COMMENT '券名称',
    VOUCHER_AMOUNT DECIMAL(20,2) REPLACE NULL COMMENT '券面额',
    VOUCHER_PAYMENT_AMOUNT DECIMAL(20,2) REPLACE NULL COMMENT '券支付金额',
    VOUCHER_CODE VARCHAR(500) REPLACE NULL COMMENT '券码',
    FK_BUYER_ORIGIN_ID VARCHAR(500) REPLACE NULL COMMENT '购买人源ID',
    FK_BUYER_TID VARCHAR(256) REPLACE NULL COMMENT '购买人TID',
    SOURCE_LAST_UPDATETIME VARCHAR(50) REPLACE NULL COMMENT '源系统最后更新时间',
    SYSTEM_CREATETIME DATETIME(3) REPLACE NULL COMMENT '本系统创建日期时间',
    SYSTEM_LAST_UPDATETIME DATETIME(3) REPLACE NULL COMMENT '本系统最后更新日期时间'
)
ENGINE=OLAP
AGGREGATE KEY(`PK_ID`)
COMMENT 'DWD_TRP-休息室券销售-业务事实表'
DISTRIBUTED BY HASH(`PK_ID`) BUCKETS 10
PROPERTIES (
    "replication_allocation" = "tag.location.default: 1",
    "storage_medium" = "hdd",
    "storage_format" = "V2",
    "light_schema_change" = "true",
    "disable_auto_compaction" = "false",
    "enable_single_replica_compaction" = "false"
);
