-- DWD层：国航系会员发展量事实表
-- 数据来源：T_ODS_CLK_MEMBER_DEVELOPMENT
-- 对应ETL脚本：MEMBER_DEVELOPMENT_FACT.sql

DROP TABLE IF EXISTS T_DWD_CLK_MEMBER_DEVELOPMENT_FACT;

CREATE TABLE IF NOT EXISTS T_DWD_CLK_MEMBER_DEVELOPMENT_FACT (
    PK_ID VARCHAR(50) NOT NULL COMMENT '主键：日期',
    `DATE` DATE REPLACE NULL COMMENT '日期',
    AIR_CHINA DECIMAL(20,2) REPLACE NULL COMMENT '国航',
    SHENZHEN_AIRLINES DECIMAL(20,2) REPLACE NULL COMMENT '深航',
    SHANDONG_AIRLINES DECIMAL(20,2) REPLACE NULL COMMENT '山航',
    AIR_MACAU DECIMAL(20,2) REPLACE NULL COMMENT '澳航',
    TOTAL_DEVELOPMENT DECIMAL(20,2) REPLACE NULL COMMENT '总发展量',
    DAILY_MEMBER_TOTAL DECIMAL(20,2) REPLACE NULL COMMENT '当日会员总量',
    SYSTEM_CREATETIME DATETIME REPLACE NULL COMMENT '本系统创建日期时间',
    SYSTEM_LAST_UPDATETIME DATETIME REPLACE NULL COMMENT '本系统最后更新日期时间'
)
ENGINE=OLAP
AGGREGATE KEY(PK_ID)
COMMENT '国航系会员发展量事实表'
DISTRIBUTED BY HASH(PK_ID) BUCKETS 10
PROPERTIES (
    "replication_allocation" = "tag.location.default: 1",
    "storage_medium" = "hdd",
    "storage_format" = "V2",
    "light_schema_change" = "true",
    "disable_auto_compaction" = "false",
    "enable_single_replica_compaction" = "false"
);
