--最近12个月平均提前值机小时
INSERT INTO DIM_TEST.T_DIM_USER_DIM (PK_ID, AVERAGE_ADVANCE_CHECK_IN_TIME_LAST_12M)
SELECT 
    COALESCE(checkin_stats.FK_PASSENGER_USER_TID, dim.PK_ID) as PK_ID,
    COALESCE(
        CASE 
            WHEN checkin_stats.TOTAL_CHECKIN_COUNT > 0 
            THEN checkin_stats.TOTAL_EARLY_CHECKINTIME / checkin_stats.TOTAL_CHECKIN_COUNT
            ELSE dim.AVERAGE_ADVANCE_CHECK_IN_TIME_LAST_12M  -- 保持原值如果没有值机记录
        END, 
        dim.AVERAGE_ADVANCE_CHECK_IN_TIME_LAST_12M  -- 保持原值如果计算结果为NULL
    ) as AVERAGE_ADVANCE_CHECK_IN_TIME_LAST_12M
FROM DIM_TEST.T_DIM_USER_DIM dim
LEFT JOIN (
    SELECT 
        FK_PASSENGER_USER_TID,
        SUM(EARLY_CHECKINTIME) as TOTAL_EARLY_CHECKINTIME,
        SUM(CHECKIN_COUNT) as TOTAL_CHECKIN_COUNT
    FROM DWD_TEST.T_DWD_CHECKIN_SEG_FACT
    WHERE FK_CHECKIN_DATE >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 YEAR)
    GROUP BY FK_PASSENGER_USER_TID
) checkin_stats ON dim.PK_ID = checkin_stats.FK_PASSENGER_USER_TID 
 WHERE dim.CREATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999')
 OR dim.UPDATE_TIME BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');

--事务提交
commit;