-- 支付方式偏好
INSERT INTO DIM_TEST.T_DIM_USER_DIM (PK_ID, PAYMENT_METHOD_PREFERENCE)
SELECT 
    user_pay.FK_BOOKING_USER_TID as PK_ID,
    user_pay.AK_PAY_METHOD as PAYMENT_METHOD_PREFERENCE
FROM (
    SELECT 
        pay.FK_BOOKING_USER_TID,
        pay.AK_PAY_METHOD,
        pay.pay_count,
        pay.rn
    FROM (
        SELECT 
            FK_BOOKING_USER_TID,
            AK_PAY_METHOD,
            COUNT(*) as pay_count,
            ROW_NUMBER() OVER (PARTITION BY FK_BOOKING_USER_TID ORDER BY COUNT(*) DESC) as rn
        FROM DWD_TEST.T_DWD_PAYDETAILS_ORD_FACT
        GROUP BY FK_BOOKING_USER_TID, AK_PAY_METHOD
    ) pay
    INNER JOIN DIM_TEST.T_DIM_USER_DIM dim ON pay.FK_BOOKING_USER_TID = dim.PK_ID
    WHERE dim.CREATE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999') 
	OR dim.UPDATE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999')
) user_pay
WHERE user_pay.rn = 1;

--事务提交
commit;