-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
-- SET batch_size = 4096;
-- SET @ETL_DATE = '2025-01-01';

-- TRP（FTP）
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_TRP_AIR_REFUND_DETAIL t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND t1.CHANNEL NOT IN ('TSDF', 'TSIF', 'SD', '全渠道')
  AND tds.TID IS NULL
  AND t1.ACCOUNT_USERNAME IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_TRP_AIR_REFUND_DETAIL t1
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND t1.CHANNEL NOT IN ('TSDF', 'TSIF', 'SD', '全渠道')
  AND t1.ACCOUNT_USERNAME is not null ;

-- 第三步：写入退票航段事实表
INSERT INTO DWD_TEST.T_DWD_REFUND_SEG_FACT
(
    PK_ID,
    AK_REFUND_CHANNEL,
    AK_REFUND_TYPE,
    REFUND_REASON,
    FK_REFUND_USER_TID,
    FK_REFUND_USER_ORIGIN_ID,
    FK_COMPLETE_DATE,
    FK_COMPLETE_TIME,
    AK_CURRENCY,
    SEG_CURREFUNDAMOUNT,
    SEG_CURREFUNDCHARGES,
    SEG_REFUNDAMOUNT,
    SEG_REFUNDCHARGES,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：票号+起飞机场+起飞日期
    CONCAT(
            REPLACE(COALESCE(t1.TICKET_NUMBER, ''), '-', ''),
            COALESCE(t1.DEPARTURE_CITY_CODE, ''),
            REPLACE(SUBSTRING(COALESCE(t1.DEPARTURE_DATE, ''), 1, 10), '-', '')
        ) AS PK_ID,

    -- 退票渠道标准化
    IFNULL(sid.CFG_VALUE, t1.TICKET_REFUND_APPLICATION_CHANNEL) AS AK_REFUND_CHANNEL,
    -- 退票类型标准化
    IFNULL(sid1.CFG_VALUE, t1.TICKET_REFUND_NATURE) AS AK_REFUND_TYPE,
    -- 非自愿退票原因（当退票类型为NOV时）
    CASE
        WHEN IFNULL(sid1.CFG_VALUE, t1.TICKET_REFUND_NATURE) = 'NOV'
            THEN  IFNULL(sid2.CFG_VALUE, '')
        ELSE NULL
        END AS REFUND_REASON,

    -- 退订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_REFUND_USER_TID,

    -- 退订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_REFUND_USER_ORIGIN_ID,

    -- 退票审核完成日期
    CASE
        WHEN t1.SECOND_REVIEW_TIME IS NOT NULL
            THEN DATE_FORMAT(t1.SECOND_REVIEW_TIME, '%Y-%m-%d')
        ELSE NULL
        END AS FK_COMPLETE_DATE,

    -- 退票审核完成时间
    CASE
        WHEN t1.SECOND_REVIEW_TIME IS NOT NULL AND LENGTH(t1.SECOND_REVIEW_TIME) >= 16
            THEN DATE_FORMAT(t1.SECOND_REVIEW_TIME, '%H:%i:%s')
        ELSE NULL
        END AS FK_COMPLETE_TIME,

    -- 原币种
    COALESCE(t1.CURRENCY, '') AS AK_CURRENCY,

    -- 原币种应退金额
    CASE
        WHEN t1.REFUND_AMOUNT IS NOT NULL AND t1.REFUND_AMOUNT != ''
            THEN CAST(t1.REFUND_AMOUNT AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_CURREFUNDAMOUNT,

    -- 原币种退票手续费
    CASE
        WHEN t1.TICKET_REFUND_FEE IS NOT NULL AND t1.TICKET_REFUND_FEE != ''
            THEN CAST(t1.TICKET_REFUND_FEE AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_CURREFUNDCHARGES,

    -- 应退金额CNY（当币种为CNY时）
    CASE
        WHEN UPPER(t1.CURRENCY) = 'CNY' AND t1.REFUND_AMOUNT IS NOT NULL AND t1.REFUND_AMOUNT != ''
            THEN CAST(t1.REFUND_AMOUNT AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_REFUNDAMOUNT,

    -- 退票手续费CNY（当币种为CNY时）
    CASE
        WHEN UPPER(t1.CURRENCY) = 'CNY' AND t1.TICKET_REFUND_FEE IS NOT NULL AND t1.TICKET_REFUND_FEE != ''
            THEN CAST(t1.TICKET_REFUND_FEE AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_REFUNDCHARGES,

    -- 源系统最后更新时间
    t1.SECOND_REVIEW_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_TRP_AIR_REFUND_DETAIL t1
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ACCOUNT_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON t1.TICKET_REFUND_APPLICATION_CHANNEL=sid.CFG_CODE
    AND sid.CFG_TYPE = 'REFUND_CHANNEL_AIRTICKET' AND sid.CFG_TYPE_CHANNEL ='ALL'
          LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid1 ON t1.TICKET_REFUND_NATURE=sid1.CFG_CODE
      AND sid1.CFG_TYPE = 'REFUND_TYPE' AND sid1.CFG_TYPE_CHANNEL ='TRP_FTP'
          LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid2 ON t1.TICKET_REFUND_NATURE=sid2.CFG_CODE
      AND sid2.CFG_TYPE = 'NON_VOLUNTARY_REFUND_REASON' AND sid2.CFG_TYPE_CHANNEL ='TRP_FTP'
WHERE t1.ETL_DATE >= @ETL_DATE
  AND t1.CHANNEL NOT IN ('TSDF', 'TSIF', 'SD', '全渠道')
  -- 确保关键字段不为空
  AND t1.TICKET_NUMBER IS NOT NULL AND t1.TICKET_NUMBER != ''
  AND t1.DEPARTURE_CITY_CODE IS NOT NULL AND t1.DEPARTURE_CITY_CODE != ''
  AND t1.DEPARTURE_DATE IS NOT NULL;

-- 呼叫白屏票务系统 写入退票表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_TEST.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_TEST.T_ODS_KFBP_BUS_REFUND RF
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_TK_REFUND_FARE_TICKET_FLT RFTF ON RF.PKID = RFTF.TK_REFUND_PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_ORDER BO ON RF.ORDER_PKID = BO.PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BF ON BO.PKID = BF.ORDER_PKID
WHERE RF.ETL_DATE >= @ETL_DATE
  AND RF.REFUNDTYPE = 'TkRefund'
  AND RF.REFUND_MARK_STATUS = 1
  AND BF.FLT_START_CITY = RFTF.START_CITY
  AND tds.TID IS NULL
  AND RF.CUR_TEL IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_TEST.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_TEST.T_ODS_KFBP_BUS_REFUND RF
        LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_TK_REFUND_FARE_TICKET_FLT RFTF ON RF.PKID = RFTF.TK_REFUND_PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_ORDER BO ON RF.ORDER_PKID = BO.PKID
        LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BF ON BO.PKID = BF.ORDER_PKID
WHERE RF.ETL_DATE >= @ETL_DATE
  AND RF.REFUNDTYPE = 'TkRefund'
  AND RF.REFUND_MARK_STATUS = 1
  AND BF.FLT_START_CITY = RFTF.START_CITY
  AND RF.CUR_TEL IS NOT NULL;

-- 第三步：写入退票航段事实表
INSERT INTO DWD_TEST.T_DWD_REFUND_SEG_FACT
(
    PK_ID,
    AK_REFUND_CHANNEL,
    AK_REFUND_TYPE,
    REFUND_REASON,
    FK_REFUND_USER_TID,
    FK_REFUND_USER_ORIGIN_ID,
    FK_COMPLETE_DATE,
    FK_COMPLETE_TIME,
    AK_CURRENCY,
    SEG_CURREFUNDAMOUNT,
    SEG_CURREFUNDCHARGES,
    SEG_REFUNDAMOUNT,
    SEG_REFUNDCHARGES,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：票号(删除横杠) + 起飞机场 + 起飞日期(YYYYMMDD格式)
    CONCAT(
            REPLACE(COALESCE(RFTF.TICKET_NO, ''), '-', ''),
            COALESCE(RFTF.START_CITY, ''),
            CASE
                WHEN BF.FLT_DEPARTURE_DAY IS NOT NULL
                    THEN REPLACE(SUBSTRING(BF.FLT_DEPARTURE_DAY, 1, 10), '-', '')
                ELSE ''
                END
        ) AS PK_ID,

    -- 退票渠道标准化
    IFNULL(sid1.CFG_VALUE, RF.OFFLINE_TICKET_REFUND) AS AK_REFUND_CHANNEL,

    -- 退票类型标准化
    IFNULL(sid2.CFG_VALUE, 'NOV') AS AK_REFUND_TYPE,

    -- 非自愿退票原因
    IFNULL(sid3.CFG_VALUE, RF.BUSINESS_TYPE) AS REFUND_REASON,

    -- 退订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_REFUND_USER_TID,

    -- 退订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_REFUND_USER_ORIGIN_ID,

    -- 退票审核完成日期
    CASE
        WHEN RF.AUDITING_THROUGH_DATE IS NOT NULL
            THEN DATE_FORMAT(RF.AUDITING_THROUGH_DATE, '%Y-%m-%d')
        ELSE NULL
        END AS FK_COMPLETE_DATE,

    -- 退票审核完成时间
    CASE
        WHEN RF.AUDITING_THROUGH_DATE IS NOT NULL AND LENGTH(RF.AUDITING_THROUGH_DATE) >= 16
            THEN DATE_FORMAT(RF.AUDITING_THROUGH_DATE, '%H:%i:%s')
        ELSE NULL
        END AS FK_COMPLETE_TIME,
    -- 原币种
    COALESCE(BO.CASH_CURRENCY_CODE, '') AS AK_CURRENCY,

    -- 原币种应退金额
    CASE
        WHEN RFTF.REFUND_TOTAL_FEE IS NOT NULL
            THEN CAST(RFTF.REFUND_TOTAL_FEE AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_CURREFUNDAMOUNT,

    -- 原币种退票手续费
    CASE
        WHEN RFTF.REC_TOTAL_FEE IS NOT NULL
            THEN CAST(RFTF.REC_TOTAL_FEE AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_CURREFUNDCHARGES,

    -- 应退金额CNY（当币种为CNY时）
    CASE
        WHEN UPPER(BO.CASH_CURRENCY_CODE) = 'CNY' AND RFTF.REFUND_TOTAL_FEE IS NOT NULL
            THEN CAST(RFTF.REFUND_TOTAL_FEE AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_REFUNDAMOUNT,

    -- 退票手续费CNY（当币种为CNY时）
    CASE
        WHEN UPPER(BO.CASH_CURRENCY_CODE) = 'CNY' AND RFTF.REC_TOTAL_FEE IS NOT NULL
            THEN CAST(RFTF.REC_TOTAL_FEE AS DECIMAL(15,2))
        ELSE NULL
        END AS SEG_REFUNDCHARGES,

    -- 源系统最后更新时间
    RF.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_TEST.T_ODS_KFBP_BUS_REFUND RF
         LEFT JOIN DIM_TEST.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(RF.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_TK_REFUND_FARE_TICKET_FLT RFTF ON RF.PKID = RFTF.TK_REFUND_PKID
         LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_ORDER BO ON RF.ORDER_PKID = BO.PKID
         LEFT JOIN ODS_TEST.T_ODS_KFBP_BUS_FLIGHT BF ON BO.PKID = BF.ORDER_PKID
    -- 退票渠道标准化
         LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid1 ON RF.OFFLINE_TICKET_REFUND = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'REFUND_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
    -- 退票类型标准化
         LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid2 ON RF.REASON = sid2.CFG_CODE
    AND sid2.CFG_TYPE = 'REFUND_TYPE' AND sid2.CFG_TYPE_CHANNEL = 'CALL_CENTER_TICKETING_SYSTEM'
    -- 非自愿退票原因标准化
         LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid3 ON RF.BUSINESS_TYPE = sid3.CFG_CODE
    AND sid3.CFG_TYPE = 'NON_VOLUNTARY_REFUND_REASON' AND sid3.CFG_TYPE_CHANNEL = 'CALL_CENTER_TICKETING_SYSTEM'
WHERE RF.ETL_DATE >= @ETL_DATE
  AND RF.REFUNDTYPE = 'TkRefund'
  AND RF.REFUND_MARK_STATUS = 1
  AND BF.FLT_START_CITY = RFTF.START_CITY
  -- 确保关键字段不为空
  AND RFTF.TICKET_NO IS NOT NULL AND RFTF.TICKET_NO != ''
  AND BF.FLT_START_CITY IS NOT NULL AND BF.FLT_START_CITY != '';



-- 机票-退票-航段级事实表-
-- 应退金额CNY
INSERT INTO DWD_TEST.T_DWD_REFUND_SEG_FACT
(PK_ID, SEG_REFUNDAMOUNT)
SELECT
    PK_ID,
    CASE
        WHEN rt.FIVE_DAY_RATE IS NULL THEN 0 -- 如果找不到汇率，则返回 NULL
        ELSE ROUND(tdutf.SEG_REFUNDAMOUNT / rt.FIVE_DAY_RATE, 2)
        END AS SEG_REFUNDAMOUNT
FROM DWD_TEST.T_DWD_REFUND_SEG_FACT AS tdutf
         LEFT JOIN
     (
         SELECT
             ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
         FROM
             (
                 SELECT
                     CURRENCY_CODE,
                     MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
                 FROM
                     ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE er
                 GROUP BY
                     CURRENCY_CODE
             ) rate
                 LEFT JOIN ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE ee
                           ON
                                       rate.CURRENCY_CODE = ee.CURRENCY_CODE
                                   AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
     ) rt
     ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
  and tdutf.DATA_ACTIVE = 1
  AND tdutf.AK_CURRENCY != 'CNY'
  AND tdutf.SEG_REFUNDAMOUNT is not null
  AND (tdutf.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
    OR tdutf.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));


-- 机票-退票-航段级事实表
-- 退票手续费CNY

INSERT INTO DWD_TEST.T_DWD_REFUND_SEG_FACT
(PK_ID, SEG_REFUNDCHARGES)
SELECT
    PK_ID,
    CASE
        WHEN rt.FIVE_DAY_RATE IS NULL THEN 0 -- 如果找不到汇率，则返回 NULL
        ELSE ROUND(tdutf.SEG_REFUNDCHARGES / rt.FIVE_DAY_RATE, 2)
        END AS SEG_REFUNDCHARGES
FROM DWD_TEST.T_DWD_REFUND_SEG_FACT AS tdutf
         LEFT JOIN
     (
         SELECT
             ee.CURRENCY_CODE,ee.FIVE_DAY_RATE
         FROM
             (
                 SELECT
                     CURRENCY_CODE,
                     MAX(EXCHANGE_MONTH) AS EXCHANGE_MONTH
                 FROM
                     ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE er
                 GROUP BY
                     CURRENCY_CODE
             ) rate
                 LEFT JOIN ODS_TEST.T_ODS_SCCRM_EXCHANGE_RATE ee
                           ON
                                       rate.CURRENCY_CODE = ee.CURRENCY_CODE
                                   AND rate.EXCHANGE_MONTH = ee.EXCHANGE_MONTH
     ) rt
     ON tdutf.AK_CURRENCY = rt.CURRENCY_CODE
WHERE tdutf.AK_CURRENCY IS NOT null
  and tdutf.DATA_ACTIVE = 1
  AND tdutf.AK_CURRENCY != 'CNY'
  AND tdutf.SEG_REFUNDCHARGES is not null
  AND (tdutf.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
    OR tdutf.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));


-- 机票-退票-航段级事实表
-- 是否为大客户订单

INSERT INTO DWD_TEST.T_DWD_REFUND_SEG_FACT
(PK_ID, IS_KEY_ACCOUNT)
SELECT
    T2.PK_ID,
    T1.IS_KEY_ACCOUNT
FROM DWD_TEST.T_DWD_REFUND_SEG_FACT T2
         LEFT JOIN DWD_TEST.T_DWD_TICKING_SEG_FACT T1
                   ON T1.PK_ID = T2.PK_ID
WHERE T1.IS_KEY_ACCOUNT IS NOT NULL
  AND T1.DATA_ACTIVE = 1
  AND T2.DATA_ACTIVE = 1
  AND (T2.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
    OR T2.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));



-- 机票-退票-航段级事实表
-- 是否为自己订票
-- "1、机票预订-航段级、机票出票-客票级、机票出票-航段级：判断乘机人TID是否与预订人TID一致。如果一致则为是。否则为否。
-- 2、成行-航段级，退票-航段级：通过“主键”“出票-航段级反写”"

INSERT INTO DWD_TEST.T_DWD_REFUND_SEG_FACT
(PK_ID, SELF_BOOKING)
SELECT
    T2.PK_ID,
    T1.SELF_BOOKING
FROM DWD_TEST.T_DWD_REFUND_SEG_FACT T2
         LEFT JOIN DWD_TEST.T_DWD_TICKING_SEG_FACT T1
                   ON T1.PK_ID = T2.PK_ID
WHERE T1.SELF_BOOKING IS NOT NULL
  AND T1.DATA_ACTIVE = 1
  AND T2.DATA_ACTIVE = 1
  AND (T2.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000')
    OR T2.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

