-- 密钥 (Base64格式)
-- SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
-- 写入主表 (T_DIM_USER_DIM)

INSERT
	INTO
	DIM_PROD.T_DIM_USER_DIM (
    PK_ID,
	-- 主键
	CRM_CUSTOMER_ID,
	-- CRM原系统ID
	CN_NAME,
	-- 中文名
	EN_NAME,
	-- 英文名
	BIRTHDAY,
	-- 生日
	SEX,
	-- 性别
	NATIONALITY,
	-- 国籍
	ETHNICITY,
	-- 民族
	IS_DIRECT_USER,
	-- 是否直销用户
	CREATE_TIME,
	-- 创建时间
	UPDATE_TIME
	-- 更新时间
)
SELECT
	-- 【主键】直接加密 CUSTOMER_ID (对应 Java 的 TID)
	IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) AS PK_ID,
	-- 【CRM ID】
	CUSTOMER_ID AS CRM_CUSTOMER_ID,
	-- 【中文名】逻辑：优先取 CN_NAME，没有则拼接 LAST+FIRST
    CASE
		WHEN CN_NAME IS NOT NULL THEN REPLACE(UPPER(TRIM(REGEXP_REPLACE(CN_NAME , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))), '/', '')
		WHEN LAST_CN_NAME IS NOT NULL
		AND FIRST_CN_NAME IS NOT NULL THEN CONCAT(REPLACE(UPPER(TRIM(REGEXP_REPLACE(LAST_CN_NAME , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))), '/', ''), REPLACE(UPPER(TRIM(REGEXP_REPLACE(FIRST_CN_NAME , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))), '/', ''))
		ELSE NULL
	END AS CN_NAME,
	-- 【英文名】逻辑：优先取 ENG_NAME，没有则拼接 LAST+FIRST
    CASE
		WHEN ENG_NAME IS NOT NULL THEN REPLACE(UPPER(TRIM(REGEXP_REPLACE(ENG_NAME , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))), '/', '')
		WHEN LAST_ENG_NAME IS NOT NULL
		AND FIRST_ENG_NAME IS NOT NULL THEN CONCAT(REPLACE(UPPER(TRIM(REGEXP_REPLACE(LAST_ENG_NAME , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))), '/', ''), REPLACE(UPPER(TRIM(REGEXP_REPLACE(FIRST_ENG_NAME , '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))), '/', ''))
		ELSE NULL
	END AS EN_NAME,
	-- 【基础属性】
	BIRTHDAY,
	COALESCE(sid.CFG_VALUE,'U'),
	NATIONAL AS NATIONALITY,
	-- Java映射: NATIONAL -> Nationality
	ETHNIC_GROUP AS ETHNICITY,
	-- Java映射: ETHNIC_GROUP -> Ethnicity
	-- 【直销用户标识】Java逻辑: CUSTOMER_STATUS == '1'
    CASE
		WHEN CUSTOMER_STATUS = '1' THEN 1
		ELSE 0
	END AS IS_DIRECT_USER,
	NOW() AS CREATE_TIME,
	NOW() AS UPDATE_TIME
FROM
	ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER a
	LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON a.sex =sid.CFG_CODE
AND sid.CFG_TYPE = 'GENDER' AND sid.CFG_TYPE_CHANNEL ='ALL'
left join DIM_PROD.T_DIM_STRONGID tds
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
AND tds.STRONGID_STATUS = 1
WHERE a.ETL_DATE >= @ETL_DATE;



-- =========================================================
-- 2. 写入 SUMMARY 概要表 (T_DIM_USER_DIM_SUMMARY)
-- =========================================================
-- 业务逻辑：凡是上面写入了非空值的字段，都要在这里记录来源为 'ZXYH'
INSERT
	INTO
	DIM_PROD.T_DIM_USER_DIM_SUMMARY (
    PK_ID,
	CRM_CUSTOMER_ID_SOURCE,
	-- CRM ID 来源
	CRM_CUSTOMER_ID_UPDATETIME,
	CN_NAME_SOURCE,
	-- 中文名来源
	CN_NAME_UPDATETIME,
	EN_NAME_SOURCE,
	-- 英文名来源
	EN_NAME_UPDATETIME,
	BIRTHDAY_SOURCE,
	-- 生日来源
	BIRTHDAY_UPDATETIME,
	SEX_SOURCE,
	-- 性别来源
	SEX_UPDATETIME,
	NATIONALITY_SOURCE,
	-- 国籍来源
	NATIONALITY_UPDATETIME,
	ETHNICITY_SOURCE,
	-- 民族来源
	ETHNICITY_UPDATETIME,
	IS_DIRECT_USER_SOURCE,
	-- 直销用户标识来源
	IS_DIRECT_USER_UPDATETIME
)
SELECT
	-- 【主键】
	IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) AS PK_ID,
	-- 【CRM ID 来源】(只要有 ID 就算 ZXYH)
    'ZXYH',
	NOW(),
	-- 【中文名来源】(有中文名 或 有拼接名)
    CASE
		WHEN CN_NAME IS NOT NULL
		OR (LAST_CN_NAME IS NOT NULL
			AND FIRST_CN_NAME IS NOT NULL) THEN 'ZXYH'
		ELSE NULL
	END,
	CASE
		WHEN CN_NAME IS NOT NULL
		OR (LAST_CN_NAME IS NOT NULL
			AND FIRST_CN_NAME IS NOT NULL) THEN NOW()
		ELSE NULL
	END,
	-- 【英文名来源】
    CASE
		WHEN ENG_NAME IS NOT NULL
		OR (LAST_ENG_NAME IS NOT NULL
			AND FIRST_ENG_NAME IS NOT NULL) THEN 'ZXYH'
		ELSE NULL
	END,
	CASE
		WHEN ENG_NAME IS NOT NULL
		OR (LAST_ENG_NAME IS NOT NULL
			AND FIRST_ENG_NAME IS NOT NULL) THEN NOW()
		ELSE NULL
	END,
	-- 【生日来源】
    CASE
		WHEN BIRTHDAY IS NOT NULL THEN 'ZXYH'
		ELSE NULL
	END,
	CASE
		WHEN BIRTHDAY IS NOT NULL THEN NOW()
		ELSE NULL
	END,
	-- 【性别来源】
    CASE
		WHEN SEX IS NOT NULL THEN 'ZXYH'
		ELSE NULL
	END,
	CASE
		WHEN SEX IS NOT NULL THEN NOW()
		ELSE NULL
	END,
	-- 【国籍来源】
    CASE
		WHEN NATIONAL IS NOT NULL THEN 'ZXYH'
		ELSE NULL
	END,
	CASE
		WHEN NATIONAL IS NOT NULL THEN NOW()
		ELSE NULL
	END,
	-- 【民族来源】
    CASE
		WHEN ETHNIC_GROUP IS NOT NULL THEN 'ZXYH'
		ELSE NULL
	END,
	CASE
		WHEN ETHNIC_GROUP IS NOT NULL THEN NOW()
		ELSE NULL
	END,
	-- 【直销用户标识来源】
    CASE
		WHEN CUSTOMER_STATUS = '1' THEN 'ZXYH'
		ELSE NULL
	END,
	CASE
		WHEN CUSTOMER_STATUS = '1' THEN NOW()
		ELSE NULL
	END
FROM
	ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER a
left join DIM_PROD.T_DIM_STRONGID tds
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
AND tds.STRONGID_STATUS = 1
WHERE
	 a.ETL_DATE >= @ETL_DATE;