INSERT INTO DIM_PROD.T_DIM_CERT_DIM
(SYSTEM_KEY,T_ID,CERT_TYPE,CERT_NUMBER,IS_FREQUENT_FLYER_REGISTRATION_CARD ,CERT_ISSUE_DATE,CERT_EXPIRE_DATE,CERT_ISSUING_COUNTRY,CERT_ISSUING_AUTHORITY,CREATE_TIME,UPDATE_TIME)
SELECT
    CONCAT(
            IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))),
            COALESCE(sid.CFG_VALUE, 'OT'),
            a.CERT_NUMBER
    ) AS SYSTEM_KEY,
    TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY))) AS ENCRYPTED_CUSTOMER_ID,
    COALESCE(sid.CFG_VALUE, 'OT') AS CERT_TYPE,
    a.CERT_NUMBER,
    CASE
        WHEN a.REAL_NAME_FLAG IS NOT NULL AND a.REAL_NAME_FLAG = '1' THEN TRUE
        ELSE FALSE
        END AS DIRECT_SALES_REAL_NAME_VERIFIED_CARD,
    DATE(a.ISSUE_DATE) AS CERT_ISSUE_DATE,
    DATE(a.EXPIRATION_DATE) AS CERT_EXPIRE_DATE,
    a.SIGNING_AUTHORITY,
    a.SIGNING_AUTHORITY AS CERT_ISSUING_COUNTRY,
    CURRENT_TIMESTAMP(3) AS CREATE_TIME,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER_CERT a
    LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid
ON a.CERT_TYPE = sid.CFG_CODE
    AND sid.CFG_TYPE = 'DOCUMENT_TYPE'
    AND sid.CFG_TYPE_CHANNEL = 'DIRECT_SALES_USER'
left join DIM_PROD.T_DIM_STRONGID tds
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
AND tds.STRONGID_STATUS = 1
WHERE a.CERT_NUMBER is not null
AND a.ETL_DATE >= @ETL_DATE ;