INSERT INTO DIM_PROD.T_DIM_CUSTOM_DIM (CUSTOMER_ID,SYSTEM_KEY,T_ID,SHIP_ADDRESS,CREATE_TIME,UPDATE_TIME)
SELECT
    a.CUSTOMER_ID,
    CONCAT(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))), TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY)))) AS SYSTEM_KEY,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    a.FULL_ADDRESS,
    CURRENT_TIMESTAMP(3) AS CREATE_TIME,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER_ADDRESS a
    INNER JOIN ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER b
    ON a.CUSTOMER_ID = b.CUSTOMER_ID
left join DIM_PROD.T_DIM_STRONGID tds
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
AND tds.STRONGID_STATUS = 1
WHERE  a.FULL_ADDRESS is not null
AND a.ETL_DATE >= @ETL_DATE ;