INSERT INTO DIM_PROD.T_DIM_CUSTOM_DIM (CUSTOMER_ID,T_ID,SYSTEM_KEY,INVOICE_TITLE,CREATE_TIME,UPDATE_TIME)
SELECT
    a.CUSTOMER_ID,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    CONCAT(TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY))), TO_BASE64(SM4_ENCRYPT(a.CUSTOMER_ID, FROM_BASE64(@SM4_KEY)))) AS SYSTEM_KEY,
    a.TAXPAYER_NAME,
    CURRENT_TIMESTAMP(3) AS CREATE_TIME,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER_INVOICE_TITLE a
         INNER JOIN ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER b
                    ON a.CUSTOMER_ID = b.CUSTOMER_ID
left join DIM_PROD.T_DIM_STRONGID tds
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
AND tds.STRONGID_STATUS = 1
WHERE  a.TAXPAYER_NAME is not null
AND a.ETL_DATE >= @ETL_DATE;



INSERT INTO DIM_PROD.T_DIM_CUSTOM_DIM (SYSTEM_KEY,T_ID,CUSTOMER_ID,LAST_LOGIN_TIME,DIRECT_REGISTER_CHANNEL,
DIRECT_USER_STATUS,DIRECT_REGISTER_DATE,WEB_VIRTUAL_STATUS,WEB_ACCOUNT_STATUS,DIRECT_VERIFY_DATE,DIRECT_VERIFIED_METHOD ,
DIRECT_VERIFIED_FLAG ,UPDATE_TIME,CREATE_TIME)
SELECT
CONCAT(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))),
TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) SYSTEM_KEY,
IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
a.CUSTOMER_ID ,a.LAST_LOGIN_TIME,a.REGIST_CHANNEL,a.CUSTOMER_STATUS,a.REGIST_DATE,
a.WEB_IS_LIMITED,a.WEB_AUTHORIZE,CAST(a.REAL_NAME_TIME as DATETIME) REAL_NAME_TIME,a.CERTIFICATION_TYPE ,
CASE WHEN REAL_NAME_FLAG  = '1' THEN true  END AS REAL_NAME_FLAG,NOW(),NOW()
from ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER_CONTACT_CERT_VIEW a
left join DIM_PROD.T_DIM_STRONGID tds
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(a.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
AND tds.STRONGID_STATUS = 1
where a.ETL_DATE >= @ETL_DATE;