INSERT INTO DIM_PROD.T_DIM_CUSTOM_DIM (SYSTEM_KEY,CUSTOMER_ID ,T_ID ,IS_BLACKLIST_USER,CREATE_TIME,UPDATE_TIME)
SELECT
    CONCAT(IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(b.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))), TO_BASE64(SM4_ENCRYPT(b.CUSTOMER_ID, FROM_BASE64(@SM4_KEY)))) AS SYSTEM_KEY,
    b.CUSTOMER_ID,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(b.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY)))) TID,
    CASE
        WHEN a.EFFECTIVE_STATUS IS NOT NULL
            AND a.ENABLE IS NOT NULL
            AND a.EFFECTIVE_STATUS = '1'
            AND a.ENABLE = '1'
            THEN TRUE
        ELSE FALSE
        END AS IS_BLACKLIST_USER,
    CURRENT_TIMESTAMP(3) AS CREATE_TIME,
    CURRENT_TIMESTAMP(3) AS UPDATE_TIME
FROM ODS_PROD.T_ODS_ZXYH_CRM_BLOCKLIST a
         INNER JOIN ODS_PROD.T_ODS_ZXYH_CRM_CUSTOMER b
                    ON a.CONTEXT = b.CUSTOMER_ID
left join DIM_PROD.T_DIM_STRONGID tds
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(b.CUSTOMER_ID)), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
AND tds.STRONGID_STATUS = 1
    WHERE a.ETL_DATE >= @ETL_DATE ;