-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

BEGIN;
--用户维表-中文名字-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, CN_NAME, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.CN_NAME_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.CN_NAME_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN PSG_NAME_CN
	  	ELSE NULL
	  END
	ELSE PSG_NAME_CN
END AS CN_NAME,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.CN_NAME_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'CN_NAME' AND pc1.DATA_SOURCE = ds.CN_NAME_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'CN_NAME' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND PSG_NAME_CN IS NOT NULL AND LENGTH(TRIM(PSG_NAME_CN)) > 0;
--用户维表-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, CN_NAME_SOURCE, CN_NAME_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.CN_NAME_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.CN_NAME_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS CN_NAME_SOURCE,
CASE
	WHEN ds.CN_NAME_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.CN_NAME_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS CN_NAME_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.CN_NAME_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'CN_NAME' AND pc1.DATA_SOURCE = ds.CN_NAME_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'CN_NAME' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND PSG_NAME_CN IS NOT NULL AND LENGTH(TRIM(PSG_NAME_CN)) > 0;
--事务提交
COMMIT;


BEGIN;
--用户维表-英文名字-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, EN_NAME, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.EN_NAME_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.EN_NAME_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN REGEXP_REPLACE(PSG_NAME_EN,'(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')
	  	ELSE NULL
	  END
	ELSE REGEXP_REPLACE(PSG_NAME_EN,'(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')
END AS EN_NAME,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.EN_NAME_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'EN_NAME' AND pc1.DATA_SOURCE = ds.EN_NAME_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'EN_NAME' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND PSG_NAME_EN IS NOT NULL AND LENGTH(TRIM(PSG_NAME_EN)) > 0;

INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, EN_NAME_SOURCE, EN_NAME_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.EN_NAME_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.EN_NAME_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS EN_NAME_SOURCE,
CASE
	WHEN ds.EN_NAME_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.EN_NAME_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS EN_NAME_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.EN_NAME_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'EN_NAME' AND pc1.DATA_SOURCE = ds.EN_NAME_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'EN_NAME' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND PSG_NAME_EN IS NOT NULL AND LENGTH(TRIM(PSG_NAME_EN)) > 0;
COMMIT;


BEGIN;
--用户维表-性别-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, SEX, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.SEX_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.SEX_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN IFNULL(sid.CFG_VALUE, 'U')
	  	ELSE NULL
	  END
	ELSE IFNULL(sid.CFG_VALUE, 'U')
END AS SEX,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON GENDER=sid.CFG_CODE
AND sid.CFG_TYPE = 'GENDER' AND sid.CFG_TYPE_CHANNEL ='ALL'
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.SEX_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'SEX' AND pc1.DATA_SOURCE = ds.SEX_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'SEX' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL;

INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, SEX_SOURCE, SEX_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.SEX_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.SEX_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS SEX_SOURCE,
CASE
	WHEN ds.SEX_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.SEX_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS SEX_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.SEX_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'SEX' AND pc1.DATA_SOURCE = ds.SEX_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'SEX' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL;
COMMIT;

--BEGIN;
--用户维表-用户类型-写DWD
--INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, USER_TYPE, CREATE_TIME, UPDATE_TIME)
--SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
--CASE
--  	WHEN ds.USER_TYPE_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.USER_TYPE_SOURCE)) > 0
--  	THEN
--  	  CASE
--  	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
--  	  	THEN CASE WHEN IS_CHILD = 'Y' THEN 'CHD' WHEN IS_INFANT = '1' THEN 'INF' ELSE NULL END
--  	  	ELSE NULL
--  	  END
--  	ELSE CASE WHEN IS_CHILD = 'Y' THEN 'CHD' WHEN IS_INFANT = '1' THEN 'INF' ELSE NULL END
--END AS USER_TYPE,now() AS CREATE_TIME,now() AS UPDATE_TIME
--FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
--LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
--ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
--LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
--ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
--AND ds.USER_TYPE_SOURCE <> 'LYGJ'
--LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
--ON pc1.FIELD_NAME = 'USER_TYPE' AND pc1.DATA_SOURCE = ds.USER_TYPE_SOURCE
--LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
--ON pc11.FIELD_NAME = 'USER_TYPE' AND pc11.DATA_SOURCE = 'LYGJ'
--WHERE CERT_NO IS NOT NULL AND (IS_CHILD = 'Y' OR (IS_CHILD <> 'Y' AND IS_INFANT = '1'));
--
--INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, USER_TYPE_SOURCE, USER_TYPE_UPDATETIME)
--SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
--CASE
--	WHEN ds.USER_TYPE_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.USER_TYPE_SOURCE)) > 0
--	THEN
--	  CASE
--	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
--	  	THEN 'LYGJ'
--	  	ELSE NULL
--	  END
--	ELSE 'LYGJ'
--END AS USER_TYPE_SOURCE,
--CASE
--	WHEN ds.USER_TYPE_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.USER_TYPE_SOURCE)) > 0
--	THEN
--	  CASE
--	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
--	  	THEN now()
--	  	ELSE NULL
--	  END
--	ELSE now()
--END AS USER_TYPE_UPDATETIME
--FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
--LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
--ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
--LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
--ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
--AND ds.USER_TYPE_SOURCE <> 'LYGJ'
--LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
--ON pc1.FIELD_NAME = 'USER_TYPE' AND pc1.DATA_SOURCE = ds.USER_TYPE_SOURCE
--LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
--ON pc11.FIELD_NAME = 'USER_TYPE' AND pc11.DATA_SOURCE = 'LYGJ'
--WHERE CERT_NO IS NOT NULL AND (IS_CHILD = 'Y' OR (IS_CHILD <> 'Y' AND IS_INFANT = '1'));
--COMMIT;

BEGIN;
--用户维表-生日-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, BIRTHDAY, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
  	WHEN ds.BIRTHDAY_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.BIRTHDAY_SOURCE)) > 0
  	THEN
  	  CASE
  	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
  	  	THEN BIRTHDAY
  	  	ELSE NULL
  	  END
  	ELSE BIRTHDAY
END AS BIRTHDAY,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.BIRTHDAY_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'BIRTHDAY' AND pc1.DATA_SOURCE = ds.BIRTHDAY_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'BIRTHDAY' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND BIRTHDAY IS NOT NULL AND LENGTH(TRIM(BIRTHDAY)) > 0;

INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, BIRTHDAY_SOURCE, BIRTHDAY_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.BIRTHDAY_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.BIRTHDAY_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS BIRTHDAY_SOURCE,
CASE
	WHEN ds.BIRTHDAY_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.BIRTHDAY_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS BIRTHDAY_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.BIRTHDAY_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'BIRTHDAY' AND pc1.DATA_SOURCE = ds.BIRTHDAY_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'BIRTHDAY' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND BIRTHDAY IS NOT NULL AND LENGTH(TRIM(BIRTHDAY)) > 0;
COMMIT;

BEGIN;
--用户维表-盲人-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, BLIND_PASSENGER, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.BLIND_PASSENGER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.BLIND_PASSENGER_SOURCE)) > 0
  	THEN
  	  CASE
  	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
  	  	THEN IS_BLND = '1' OR SPECIAL_TYPE = '4'
  	  	ELSE NULL
  	  END
  	ELSE IS_BLND = '1' OR SPECIAL_TYPE = '4'
END AS BLIND_PASSENGER,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.BLIND_PASSENGER_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'BLIND_PASSENGER' AND pc1.DATA_SOURCE = ds.BLIND_PASSENGER_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'BLIND_PASSENGER' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (IS_BLND = '1' OR SPECIAL_TYPE = '4');

INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, BLIND_PASSENGER_SOURCE, BLIND_PASSENGER_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.BLIND_PASSENGER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.BLIND_PASSENGER_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS BLIND_PASSENGER_SOURCE,
CASE
	WHEN ds.BLIND_PASSENGER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.BLIND_PASSENGER_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS BLIND_PASSENGER_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.BLIND_PASSENGER_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'BLIND_PASSENGER' AND pc1.DATA_SOURCE = ds.BLIND_PASSENGER_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'BLIND_PASSENGER' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (IS_BLND = '1' OR SPECIAL_TYPE = '4');
COMMIT;

BEGIN;
--用户维表-聋哑人-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, DEAF_PASSENGER, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.DEAF_PASSENGER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.DEAF_PASSENGER_SOURCE)) > 0
  	THEN
  	  CASE
  	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
  	  	THEN IS_DEAF = '1' OR SPECIAL_TYPE = '5'
  	  	ELSE NULL
  	  END
  	ELSE IS_DEAF = '1' OR SPECIAL_TYPE = '5'
END AS DEAF_PASSENGER,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.DEAF_PASSENGER_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'DEAF_PASSENGER' AND pc1.DATA_SOURCE = ds.DEAF_PASSENGER_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'DEAF_PASSENGER' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (IS_DEAF = '1' OR SPECIAL_TYPE = '5');

INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, DEAF_PASSENGER_SOURCE, DEAF_PASSENGER_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.DEAF_PASSENGER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.DEAF_PASSENGER_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS DEAF_PASSENGER_SOURCE,
CASE
	WHEN ds.DEAF_PASSENGER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.DEAF_PASSENGER_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS DEAF_PASSENGER_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.DEAF_PASSENGER_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'DEAF_PASSENGER' AND pc1.DATA_SOURCE = ds.DEAF_PASSENGER_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'DEAF_PASSENGER' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (IS_DEAF = '1' OR SPECIAL_TYPE = '5');
COMMIT;

BEGIN;
--用户维表-大客户-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, KEY_ACCOUNT_NUMBER, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
    WHEN ds.KEY_ACCOUNT_NUMBER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.KEY_ACCOUNT_NUMBER_SOURCE)) > 0
    THEN
      CASE
        WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
        THEN BIG_CUTNUM
        ELSE NULL
      END
    ELSE BIG_CUTNUM
END AS KEY_ACCOUNT_NUMBER,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.KEY_ACCOUNT_NUMBER_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'KEY_ACCOUNT_NUMBER' AND pc1.DATA_SOURCE = ds.KEY_ACCOUNT_NUMBER_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'KEY_ACCOUNT_NUMBER' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (BIG_CUTNUM REGEXP '^[0-9][A-Za-z0-9]{7}$' or  BIG_CUTNUM REGEXP '^[A-Za-z0-9]{5}$' or BIG_CUTNUM REGEXP '^[0-9]{8}$');


INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, KEY_ACCOUNT_NUMBER_SOURCE, KEY_ACCOUNT_NUMBER_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.KEY_ACCOUNT_NUMBER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.KEY_ACCOUNT_NUMBER_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS KEY_ACCOUNT_NUMBER_SOURCE,
CASE
	WHEN ds.KEY_ACCOUNT_NUMBER_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.KEY_ACCOUNT_NUMBER_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS KEY_ACCOUNT_NUMBER_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.KEY_ACCOUNT_NUMBER_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'KEY_ACCOUNT_NUMBER' AND pc1.DATA_SOURCE = ds.KEY_ACCOUNT_NUMBER_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'KEY_ACCOUNT_NUMBER' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (BIG_CUTNUM REGEXP '^[0-9][A-Za-z0-9]{7}$' or  BIG_CUTNUM REGEXP '^[A-Za-z0-9]{5}$' or BIG_CUTNUM REGEXP '^[0-9]{8}$');
COMMIT;

BEGIN;
--用户维表-大客户-写DWD
INSERT INTO DIM_PROD.T_DIM_USER_DIM(PK_ID, IS_KEY_ACCOUNT, CREATE_TIME, UPDATE_TIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.IS_KEY_ACCOUNT_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.IS_KEY_ACCOUNT_SOURCE)) > 0
  	THEN
  	  CASE
  	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
  	  	THEN TRUE
  	  	ELSE NULL
  	  END
  	ELSE TRUE
END AS IS_KEY_ACCOUNT,now() AS CREATE_TIME,now() AS UPDATE_TIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.IS_KEY_ACCOUNT_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'IS_KEY_ACCOUNT' AND pc1.DATA_SOURCE = ds.IS_KEY_ACCOUNT_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'IS_KEY_ACCOUNT' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (BIG_CUTNUM REGEXP '^[0-9][A-Za-z0-9]{7}$' or  BIG_CUTNUM REGEXP '^[A-Za-z0-9]{5}$' or BIG_CUTNUM REGEXP '^[0-9]{8}$');

INSERT INTO DIM_PROD.T_DIM_USER_DIM_SUMMARY(PK_ID, IS_KEY_ACCOUNT_SOURCE, IS_KEY_ACCOUNT_UPDATETIME)
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS PK_ID,
CASE
	WHEN ds.IS_KEY_ACCOUNT_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.IS_KEY_ACCOUNT_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN 'LYGJ'
	  	ELSE NULL
	  END
	ELSE 'LYGJ'
END AS IS_KEY_ACCOUNT_SOURCE,
CASE
	WHEN ds.IS_KEY_ACCOUNT_SOURCE IS NOT NULL AND LENGTH(TRIM(ds.IS_KEY_ACCOUNT_SOURCE)) > 0
	THEN
	  CASE
	  	WHEN IFNULL(pc11.PRIORITY, 100) <= IFNULL(pc1.PRIORITY, 100)
	  	THEN now()
	  	ELSE NULL
	  END
	ELSE now()
END AS IS_KEY_ACCOUNT_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DIM_PROD.T_DIM_STRONGID strid
ON TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = strid.STRONGID AND strid.STRONGID_STATUS=1
LEFT JOIN DIM_PROD.T_DIM_USER_DIM_SUMMARY ds
ON IFNULL(strid.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))))=ds.PK_ID
AND ds.IS_KEY_ACCOUNT_SOURCE <> 'LYGJ'
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc1
ON pc1.FIELD_NAME = 'IS_KEY_ACCOUNT' AND pc1.DATA_SOURCE = ds.IS_KEY_ACCOUNT_SOURCE
LEFT JOIN DIM_PROD.T_DIM_PRIORITY_CONFIG pc11
ON pc11.FIELD_NAME = 'IS_KEY_ACCOUNT' AND pc11.DATA_SOURCE = 'LYGJ'
WHERE CERT_NO IS NOT NULL AND (BIG_CUTNUM REGEXP '^[0-9][A-Za-z0-9]{7}$' or  BIG_CUTNUM REGEXP '^[A-Za-z0-9]{5}$' or BIG_CUTNUM REGEXP '^[0-9]{8}$');
COMMIT;