-- 高端旅客维表
-- 更新VIP_FLAG、CIP_FLAG、VVIP_FLAG字段
INSERT INTO DIM_PROD.T_DIM_GDLK_DIM
(SYSTEM_KEY, FK_USER_TID,HIGH_TRAVELER_TYPE, HIGH_TRAVELER_TIER, TIER_PRESTIGE_EXPIREDATE,
 TIER_HONOR_EXPIREDATE,HIGH_TRAVELER_DS,VIP_FLAG,CIP_FLAG,VVIP_FLAG,FOOD_PREFERENCE,
 SEAT_PREFERENCE,TEMP_FOOD_PREFERENCE,TEMP_SEAT_PREFERENCE,BEVERAGE_PREFERENCE,LONG_TERM_SEAT_PREFERENCE,
     FIRST_CLASS_LOUNGE_PREFERENCE,UPDATE_TIME,CREATE_TIME
)
SELECT
    gdlk.SYSTEM_KEY as SYSTEM_KEY,
    gdlk.FK_USER_TID as FK_USER_TID,
    gdlk.HIGH_TRAVELER_TYPE as HIGH_TRAVELER_TYPE,
    gdlk.HIGH_TRAVELER_TIER as HIGH_TRAVELER_TIER,
    gdlk.TIER_PRESTIGE_EXPIREDATE as TIER_PRESTIGE_EXPIREDATE,
    gdlk.TIER_HONOR_EXPIREDATE,
    gdlk.HIGH_TRAVELER_DS,
    dpi.IS_VIP as VIP_FLAG,
    dpi.IS_CIP as CIP_FLAG,
    dpi.IS_VVIP as VVIP_FLAG,
    gdlk.FOOD_PREFERENCE,
    gdlk.SEAT_PREFERENCE,
    gdlk.TEMP_FOOD_PREFERENCE,
    gdlk.TEMP_SEAT_PREFERENCE,
    gdlk.BEVERAGE_PREFERENCE,
    gdlk.LONG_TERM_SEAT_PREFERENCE,
    gdlk.FIRST_CLASS_LOUNGE_PREFERENCE,
    now() as UPDATE_TIME,
    gdlk.CREATE_TIME
FROM DIM_PROD.T_DIM_GDLK_DIM gdlk
         INNER JOIN DIM_PROD.T_DIM_STRONGID strong ON gdlk.FK_USER_TID = strong.TID
         INNER JOIN ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO dpi ON strong.STRONGID = dpi.CERT_NO
where (dpi.IS_VIP is not null or dpi.IS_CIP is not null or dpi.IS_VVIP is not null)
  and gdlk.SYSTEM_KEY is not null;
