-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--机票-出票-客票级事实表-写DWD
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(PK_ID,PNR_NUMBER,AK_TICKET_TYPE,TICKET_NUMBER,AK_BOOKING_OFFICE_NUMBER,FK_TICKETING_DATE,FK_TICKETING_TIME,EN_LAST_NAME,EN_FIRST_NAME,CN_NAME,CERT_TYPE,CERT_NUMBER,FK_PASSENGER_USER_TID,PASSENGER_AGE,FF_AIRLINE,FFRF,FF_LEVEL,AK_DIMARK,AK_CONJUCTION,AK_FAREBASIS,UNACCOMPANIED_MINOR,IS_GOVERNMENT_PURCHASE,AK_TEAMMARK,AK_KEY_ACCOUNT_CODE,IS_KEY_ACCOUNT,AK_PEER_NUMBER,SINGLE_TRAVELER,PASSENGER_TYPE,AK_PEER_CHD,PEER_SENIOR,DATA_ACTIVE,DATA_ACTIVE_TIME,SYSTEM_CREATETIME,SYSTEM_LAST_UPDATETIME)
SELECT concat(date_format(PRINT_TICKET_TIME,'%Y%m%d'),ET_NUM) AS PK_ID,
PNR_ICS AS PNR_NUMBER,CASE WHEN ORIGINALTKNE IS NOT NULL THEN 'ReIssue' ELSE 'Issue' END AS AK_TICKET_TYPE,
ET_NUM AS TICKET_NUMBER,ISSUE_OFFI AS AK_BOOKING_OFFICE_NUMBER,
date_format(PRINT_TICKET_TIME,'%Y-%m-%d') AS FK_TICKETING_DATE, date_format(PRINT_TICKET_TIME,'%T') AS FK_TICKETING_TIME,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[1] AS EN_LAST_NAME,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[2] AS EN_FIRST_NAME,
PSG_NAME_CN AS CN_NAME,sid.CFG_VALUE AS CERT_TYPE,CERT_NO AS CERT_NUMBER,CERT_NO AS FK_PASSENGER_USER_TID,
(YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END
AS PASSENGER_AGE,
SUBSTRING(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),1, 2) AS FF_AIRLINE,
TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),'\\D',''),FROM_BASE64(@SM4_KEY))) AS FFRF,
IS_FFP_JK AS FF_LEVEL,TICKET_TYPE AS AK_DIMARK,
CASE WHEN IO_FLAG = '1' THEN true ELSE false END AS AK_CONJUCTION,FARE_BASIS_CODE AS AK_FAREBASIS,CASE WHEN IS_UM = '1' THEN true ELSE false END AS UNACCOMPANIED_MINOR,
CASE WHEN TKNEGP = '1' THEN true ELSE false END AS IS_GOVERNMENT_PURCHASE,
CASE WHEN IS_GROUP = 'Y' THEN true ELSE FALSE END AS AK_TEAMMARK,BIG_CUTNUM AS AK_KEY_ACCOUNT_CODE,
CASE
    WHEN BIG_CUTNUM REGEXP '^[0-9][A-Za-z0-9]{7}$' THEN true  -- 匹配 CA_PATTERN
    WHEN BIG_CUTNUM REGEXP '^[A-Za-z0-9]{5}$' THEN true  -- 匹配 CA_GLOBAL_PATTERN
    WHEN BIG_CUTNUM REGEXP '^[0-9]{8}$' THEN true  -- 匹配 DIGITAL_PATTERN
    ELSE false
END AS IS_KEY_ACCOUNT, CASE WHEN PASSENGER_NUMBER IS NULL THEN 1 ELSE PASSENGER_NUMBER END AS AK_PEER_NUMBER,
CASE
    WHEN PASSENGER_NUMBER IS NULL THEN TRUE
    WHEN PASSENGER_NUMBER = 1 THEN TRUE
    ELSE false
END AS SINGLE_TRAVELER,
CASE WHEN IS_CHILD = 'Y' THEN 'CHD' WHEN IS_INFANT = '1' THEN 'INF' ELSE 'ADT' END AS PASSENGER_TYPE,
CASE WHEN IS_CHILD = 'Y' THEN true ELSE false END AS AK_PEER_CHD,
CASE WHEN (YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END > 65
    THEN TRUE
    ELSE FALSE
END AS PEER_SENIOR,
true AS DATA_ACTIVE, now() AS DATA_ACTIVE_TIME,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE concat(date_format(PRINT_TICKET_TIME,'%Y%m%d'),ET_NUM) IS not NULL
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;