-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--BEGIN;
--写入强ID表，证件,只写入没有的强ID
INSERT INTO DIM_PROD.T_DIM_STRONGID (STRONGID, STRONGID_TYPE, TID, CREATE_TIME, UPDATE_TIME, ETL_DATE)
SELECT CERT_NO AS STRONGID, STRONGID_TYPE, TID, now() AS CREATE_TIME,now() AS UPDATE_TIME, now() AS ETL_DATE FROM (
SELECT dpic.CERT_NO, dpic.STRONGID_TYPE, CASE WHEN sid.TID IS NULL THEN dpic.CERT_NO ELSE NULL END AS TID
FROM (
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CERT_NO,
     IFNULL(sid.CFG_VALUE, ID_TYPE) AS STRONGID_TYPE
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE CERT_NO IS NOT NULL
AND ETL_DATE >= @ETL_DATE -- 取数时间
) dpic
LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON dpic.CERT_NO = sid.STRONGID AND sid.STRONGID_STATUS=1
) finaldpi WHERE finaldpi.TID IS NOT NULL;

--写入强ID表，会员号关联证件
--INSERT INTO DIM_PROD.T_DIM_STRONGID (STRONGID, STRONGID_TYPE, TID, CREATE_TIME, UPDATE_TIME, ETL_DATE)
--SELECT MEMBER_NUMBER AS STRONGID, STRONGID_TYPE, TID, now() AS CREATE_TIME,now() AS UPDATE_TIME, now() AS ETL_DATE
--FROM (SELECT dpic.CERT_NO, dpic.STRONGID_TYPE,dpic.MEMBER_NUMBER,
--    CASE
--        WHEN sid.TID IS NULL THEN dpic.CERT_NO
--        ELSE NULL
--    END AS TID
--FROM (
--SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(
--    SM4_DECRYPT(FROM_BASE64(CREDENTIAL_NUM), FROM_BASE64('VFlLSFNUc200MjAyNX5+fg=='))
--    )), FROM_BASE64('VFlLSFNUc200MjAyNX5+fg=='))) AS CERT_NO,
--    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(
--    SM4_DECRYPT(FROM_BASE64(MEMBER_NUMBER), FROM_BASE64('VFlLSFNUc200MjAyNX5+fg=='))
--    )), FROM_BASE64('VFlLSFNUc200MjAyNX5+fg=='))) AS MEMBER_NUMBER,
--    CASE
--        WHEN sid.CFG_VALUE IS NOT NULL THEN sid.CFG_VALUE
--        ELSE CREDENTIAL_TYPE
--    END AS STRONGID_TYPE
--FROM ODS_PROD.T_ODS_HYTD_SYS_REGISTER toldpi
--LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON CREDENTIAL_TYPE=sid.CFG_CODE
--AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='MEMBER_WORLD'
--WHERE CREDENTIAL_NUM IS NOT NULL
--AND ETL_DATE >= @ETL_DATE
--) dpic
--LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON dpic.MEMBER_NUMBER = sid.STRONGID AND sid.STRONGID_STATUS=1
--) finaldpi WHERE finaldpi.TID IS NOT NULL;--只写入没有的强ID

--写入idmapping TID集合表
INSERT INTO DIM_PROD.T_DIM_TID_SET (TID, ETL_DATE, CREATE_TIME, TID_STATUS)
SELECT IFNULL(sid.TID, dpic.CERT_NO) AS TID,now() AS ETL_DATE, now() AS CREATE_TIME, 1
FROM (
SELECT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CERT_NO
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE CERT_NO IS NOT NULL
AND ETL_DATE >= @ETL_DATE -- 取数时间
) dpic LEFT JOIN DIM_PROD.T_DIM_STRONGID sid ON dpic.CERT_NO = sid.STRONGID AND sid.STRONGID_STATUS=1

--机票预订-PNR级-写DWD
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(PK_ID, PNR_NUMBER, FK_PNRCREATE_DATE, FK_PNRCREATE_TIME, GDS_CODE, AK_BOOKING_OFFICE, AK_TEAMMARK, AK_KEY_ACCOUNT_CODE, IS_KEY_ACCOUNT, AK_PEER_NUMBER, SINGLE_TRAVEL, FK_BOOKING_USER_TID, PEER_SENIOR, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT concat(PNR_ICS,REPLACE(SUBSTRING(RECORD_CREATE_TIME,1,10),'-','')) AS PK_ID,
PNR_ICS AS PNR_NUMBER,
SUBSTRING(RECORD_CREATE_TIME,1,10) AS FK_PNRCREATE_DATE,
SUBSTRING(RECORD_CREATE_TIME,12,8) AS FK_PNRCREATE_TIME,
GDS_CODE,BOOK_OFFI AS AK_BOOKING_OFFICE,
CASE
    WHEN IS_GROUP = 'Y' THEN true
    ELSE false
END AS AK_TEAMMARK,
BIG_CUTNUM AS AK_KEY_ACCOUNT_CODE,
CASE
    WHEN BIG_CUTNUM IS NOT NULL THEN true
    ELSE false
END AS IS_KEY_ACCOUNT,
PASSENGER_NUMBER AS AK_PEER_NUMBER,
CASE
    WHEN PASSENGER_NUMBER IS NULL THEN TRUE
    WHEN PASSENGER_NUMBER = 1 THEN true
    ELSE false
END AS SINGLE_TRAVEL,
CERT_NO AS FK_BOOKING_USER_TID,
CASE
    WHEN (YEAR(CURDATE()) - YEAR(
        CASE
            WHEN LENGTH(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY))) = 18 THEN
                STR_TO_DATE(SUBSTRING(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY))), 7, 8), '%Y%m%d')
            ELSE
                BIRTHDAY
        END
    )) -
      CASE
      WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) <   MONTH(CASE  WHEN LENGTH(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY))) = 18 THEN  STR_TO_DATE(SUBSTRING(TRIM(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY))), 7, 8), '%Y%m%d') ELSE BIRTHDAY END) * 100 + DAY(CASE  WHEN LENGTH(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY))) = 18 THEN  STR_TO_DATE(SUBSTRING(SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)), 7, 8), '%Y%m%d') ELSE BIRTHDAY END)
      THEN 1 ELSE 0 END > 65 THEN TRUE
        ELSE FALSE
END AS PEER_SENIOR,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME
FROM ODS_PROD.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
WHERE concat(PNR_ICS,REPLACE(SUBSTRING(RECORD_CREATE_TIME,1,10),'-','')) is not null
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;