-- 高端旅客类型 写入
INSERT INTO DIM_PROD.T_DIM_USER_DIM (PK_ID,HIGH_TRAVELER_TYPE)
SELECT PK_ID, ARRAY_JOIN(ARRAY_DISTINCT(SPLIT_BY_STRING(T2.HIGH_TRAVELER_TYPE, '/')), '/') AS HIGH_TRAVELER_TYPE
FROM
    (
    SELECT PK_ID
    FROM DWQ_PROD.T_DIM_USER_DIM_VIEW WHERE
         PK_ID IN ( SELECT T_ID
         FROM DWQ_PROD.T_DIM_GDLK_TYPE_DIM
         WHERE (CREATE_TIME >= CONCAT(@ETL_DATE, ' 00:00:00.000') AND CREATE_TIME < CONCAT(@ETL_DATE, ' 23:59:59.999'))
            OR (UPDATE_TIME >= CONCAT(@ETL_DATE, ' 00:00:00.000') AND UPDATE_TIME < CONCAT(@ETL_DATE, ' 23:59:59.999')))
    ) T1
    JOIN (
        SELECT T_ID, GROUP_CONCAT(HIGH_TRAVELER_TYPE, '/') AS HIGH_TRAVELER_TYPE
        FROM DWQ_PROD.T_DIM_GDLK_TYPE_DIM
        WHERE HIGH_TRAVELER_TYPE IS NOT NULL
        GROUP BY T_ID
    ) T2 ON T1.PK_ID = T2.T_ID;