-- 预订人是否在乘机人列表
-- 机票预订航段级事实表
INSERT INTO DWD_TEST.T_DWD_BOOKING_SEG_FACT (PK_ID,AK_BOOKER_IS_PASSENGER)
SELECT
    PK_ID,
    CASE
        WHEN MAX(CASE
                     WHEN FK_BOOKING_USER_TID IS NOT NULL
                         AND FK_PASSENGER_USER_TID IS NOT NULL
                         AND FK_BOOKING_USER_TID = FK_PASSENGER_USER_TID
                         THEN 1 ELSE 0
            END) OVER (
            PARTITION BY PNR_NUMBER
        ) = 1 THEN 1
        ELSE 0
        END AS AK_BOOKER_IS_PASSENGER
FROM
    DWD_TEST.T_DWD_BOOKING_SEG_FACT
WHERE DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
--机票出票航段级事实表
    INSERT INTO DWD_TEST.T_DWD_TICKING_SEG_FACT (PK_ID,AK_BOOKING_PASSENGER)
SELECT
    t.PK_ID,b.AK_BOOKER_IS_PASSENGER AS AK_BOOKING_PASSENGER
FROM DWD_TEST.T_DWD_TICKING_SEG_FACT AS t INNER JOIN DWD_TEST.T_DWD_BOOKING_SEG_FACT AS b
  ON t.AK_PNR_NUMBER = b.PNR_NUMBER AND t.FK_DEPAIRPORT = b.FK_DEPAIRPORT
  AND t.FK_SEG_DATE = b.FK_SEG_DATE AND t.FK_SEG_TIME = b.FK_SEG_TIME
  AND t.CERT_NUMBER = b.CERT_NUMBER AND t.CN_NAME = b.CN_NAME AND t.CERT_NUMBER = b.CERT_NUMBER
AND t.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
---- 机票预订PNR级事实表
INSERT INTO DWD_TEST.T_DWD_BOOKING_PNR_FACT (PK_ID,AK_BOOKER_IS_PASSENGER)
SELECT
    bpf.PK_ID,
    CASE
        WHEN MAX(CASE WHEN bsf.AK_BOOKER_IS_PASSENGER = 1 THEN 1 ELSE 0 END) = 1 THEN 1
        ELSE 0
        END AS AK_BOOKER_IS_PASSENGER
FROM
    DWD_TEST.T_DWD_BOOKING_PNR_FACT bpf
        LEFT JOIN
    DWD_TEST.T_DWD_BOOKING_SEG_FACT bsf
    ON
        bpf.PNR_NUMBER = bsf.PNR_NUMBER
            AND bpf.FK_PNRCREATE_DATE = bsf.FK_BOOKING_DATE
WHERE bpf.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999')
GROUP BY
    bpf.PK_ID,
    bpf.PNR_NUMBER,
    bpf.FK_PNRCREATE_DATE;
--机票出票客票级事实表
INSERT INTO DWD_TEST.T_DWD_TICKING_TIC_FACT (PK_ID,AK_BOOKING_PASSENGER)
SELECT
    tic.PK_ID,
    CASE
        WHEN MAX(CASE WHEN seg.AK_BOOKING_PASSENGER = 1 THEN 1 ELSE 0 END) = 1 THEN 1
        ELSE 0
        END AS AK_BOOKING_PASSENGER
FROM
    DWD_TEST.T_DWD_TICKING_TIC_FACT tic
        LEFT JOIN
    DWD_TEST.T_DWD_TICKING_SEG_FACT seg
    ON
        tic.TICKET_NUMBER = seg.AK_TICKET_NUMBER
            AND tic.FK_TICKETING_DATE = seg.FK_ISSUE_DATE
WHERE tic.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999')
GROUP BY
    tic.PK_ID,
    tic.TICKET_NUMBER,
    tic.FK_TICKETING_DATE;;
--事务提交
commit;