-- 是否首次乘机
INSERT INTO  DWD_TEST.T_DWD_DEPART_SEG_FACT (FK_PASSENGER_USER_TID,FIRST_TRAVELER)
SELECT
    FK_PASSENGER_USER_TID,
    CASE
        WHEN COUNT(*) OVER (PARTITION BY FK_PASSENGER_USER_TID) = 1 THEN 1
        ELSE 0
        END AS FIRST_TRAVELER
FROM
    DWD_TEST.T_DWD_DEPART_SEG_FACT
WHERE DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
--事务提交
commit;