-- 每天T+1数据入库后，取TB_EXTERNAL_ORDERS升舱使用订单，
-- UPGRADE_TIME是T到T-30天的数据，只取CHANNEL_TYPE=2，UPGRADE_STATUS=1（成功）,
-- PAY_STATUS等于2或7的，的数据进入本表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_JSSC_TB_EXTERNAL_ORDERS t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE BETWEEN DATE_SUB(@ETL_DATE, INTERVAL 30 DAY) AND @ETL_DATE
  AND t1.CHANNEL_TYPE = 2
  AND t1.UPGRADE_STATUS = 1
  AND t1.PAY_STATUS IN (2, 7)
  AND tds.TID IS NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'OT' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_JSSC_TB_EXTERNAL_ORDERS t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE BETWEEN DATE_SUB(@ETL_DATE, INTERVAL 30 DAY) AND @ETL_DATE
  AND t1.CHANNEL_TYPE = 2
  AND t1.UPGRADE_STATUS = 1
  AND t1.PAY_STATUS IN (2, 7);


-- 第三步：写入升舱业务事实表
INSERT INTO DWD_PROD.T_DWD_UPGRADE_INFLIGHT_BUSINESS_FACT
(
    PK_ID,
    ORDER_NO,
    UPGRADE_DATE,
    UPGRADE_TIME,
    ORIG,
    DEST,
    FLT_DATE,
    TAKE_OFF,
    PSGNAME,
    PSG_CARDID,
    FLY_TYPE,
    TICKET_NUM,
    BEFORE_CABIN,
    BEFORE_FARE,
    AFTER_CABIN,
    AFTER_FARE,
    PAY_TYPE,
    PAY_STATUS,
    UPGRADE_PRICE,
    MAKEUPFLAG,
    IS_UPGRADE_COUPON_USED,
    FK_PASSENGER_USER_TID,
    FK_BOOKING_USER_TID,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    t1.ORDER_NO AS PK_ID,
    t1.ORDER_NO,
    DATE(t1.UPGRADE_TIME) AS UPGRADE_DATE,
    DATE_FORMAT(t1.UPGRADE_TIME, '%H:%i:%S') AS UPGRADE_TIME,
    t1.ORIG,
    t1.DEST,
    t1.FLT_DATE,
    t1.TAKE_OFF,
    t1.PSGNAME,
    t1.PSG_CARDID,
    CASE
        WHEN t1.FLY_TYPE = 'W' THEN 'I'
        WHEN t1.FLY_TYPE = 'Z' THEN 'D'
        ELSE t1.FLY_TYPE
        END AS FLY_TYPE,
    t1.TICKET_NUM,
    t1.BEFORE_CABIN,
    CASE
        WHEN to_date(t1.FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
            CASE
                WHEN locate(upper(substring(t1.BEFORE_CABIN, 1, 1)), 'CDPI') > 0 THEN 'BC'
                WHEN locate(upper(substring(t1.BEFORE_CABIN, 1, 1)), 'WR') > 0 THEN 'PE'
                WHEN locate(upper(substring(t1.BEFORE_CABIN, 1, 1)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
                ELSE NULL  -- 可选：处理未匹配的舱位代码
                END
        ELSE  -- 2023.10.29及以后
            CASE
                WHEN locate(upper(substring(t1.BEFORE_CABIN, 1, 1)), 'JCDRZI') > 0 THEN 'BC'
                WHEN locate(upper(substring(t1.BEFORE_CABIN, 1, 1)), 'GE') > 0 THEN 'PE'
                WHEN locate(upper(substring(t1.BEFORE_CABIN, 1, 1)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
                ELSE NULL  -- 可选：处理未匹配的舱位代码
                END
        END AS BEFORE_FARE,
    t1.AFTER_CABIN,
    CASE
        WHEN to_date(t1.FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
            CASE
                WHEN locate(upper(substring(t1.AFTER_CABIN, 1, 1)), 'CDPI') > 0 THEN 'BC'
                WHEN locate(upper(substring(t1.AFTER_CABIN, 1, 1)), 'WR') > 0 THEN 'PE'
                WHEN locate(upper(substring(t1.AFTER_CABIN, 1, 1)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
                ELSE NULL  -- 可选：处理未匹配的舱位代码
                END
        ELSE  -- 2023.10.29及以后
            CASE
                WHEN locate(upper(substring(t1.AFTER_CABIN, 1, 1)), 'JCDRZI') > 0 THEN 'BC'
                WHEN locate(upper(substring(t1.AFTER_CABIN, 1, 1)), 'GE') > 0 THEN 'PE'
                WHEN locate(upper(substring(t1.AFTER_CABIN, 1, 1)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
                ELSE NULL  -- 可选：处理未匹配的舱位代码
                END
        END AS AFTER_FARE,
    CASE
        WHEN t1.PAY_TYPE IN ('1', '2') THEN 'CSH'
        WHEN t1.PAY_TYPE IN ('3', '4', '5') THEN 'VCH'
        ELSE NULL
        END AS PAY_TYPE,
    -- 支付状态
    IFNULL(sid2.CFG_VALUE, t1.PAY_STATUS) PAY_STATUS,
    t1.UPGRADE_PRICE,
    CASE
        WHEN t1.MAKEUPFLAG IS NULL OR t1.MAKEUPFLAG = '' THEN '1'
        WHEN t1.MAKEUPFLAG = '1' THEN '0'
        ELSE '1'
        END AS MAKEUPFLAG,
    CASE
        WHEN t1.PAY_TYPE IN ('3', '4', '5') THEN 1
        ELSE 0
        END AS IS_UPGRADE_COUPON_USED,
    -- 使用T_DIM_STRONGID表中的TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_PASSENGER_USER_TID,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME
FROM
    ODS_PROD.T_ODS_JSSC_TB_EXTERNAL_ORDERS t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.PSG_CARDID), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid2
                  ON t1.PAY_STATUS = sid2.CFG_CODE
                      AND sid2.CFG_TYPE = 'PAYMENT_STATUS'
                      AND sid2.CFG_TYPE_CHANNEL = 'PRE_PURCHASED_UPGRADE'
WHERE t1.ETL_DATE BETWEEN DATE_SUB(@ETL_DATE, INTERVAL 30 DAY) AND @ETL_DATE
  AND t1.CHANNEL_TYPE = 2
  AND t1.UPGRADE_STATUS = 1
  AND t1.PAY_STATUS IN (2, 7)
  AND t1.ORDER_NO IS NOT NULL;
