SET enable_unique_key_partial_update = true;

-- v2 - 04 消费额及排名
-- 目标表：DWQ_TEST.T_DIM_USER_DIM

INSERT INTO DWQ_TEST.T_DIM_USER_DIM (
    PK_ID,                                              -- 用户T_ID
	TOTAL_CONSUMPTION_AMOUNT_ALL_TIME,                  -- 全期总消费额（乘机人）
	TOTAL_CONSUMPTION_RANK_ALL_TIME,                    -- 全期总消费额排名（乘机人）
	PASSENGER_TOTAL_CONSUME_PERCENTILE_ALL_TIME,        -- 全期总消费额所在百分位（乘机人）
	TOTAL_TICKET_ISSUANCE_AMOUNT_INTERNATIONAL_ALL_TIME, -- 全期出票金额（国际）
	TOTAL_TICKET_ISSUANCE_AMOUNT_DOMESTIC_ALL_TIME,     -- 全期出票金额（国内）
	TICKET_PURCHASE_AMOUNT_INTERNATIONAL_LAST_1_YEAR,   -- 过去12个月内出票金额（国际）
	TICKET_PURCHASE_AMOUNT_DOMESTIC_LAST_1_YEAR,        -- 过去12个月出票金额（国内）
	GROUP_TICKET_PURCHASE_ISSUANCE_COUNT_LAST_1_YEAR,   -- 过去12个月团队票出票航段数
	GROUP_TICKET_PURCHASE_ISSUANCE_COUNT_ALL_TIME,      -- 全期团队票出票次数
    UPDATE_TIME                                         -- 更新时间
)
WITH
	-- CTE 1: 纵向合并所有消费明细
	cte_flat_consumption AS (
	SELECT
		FK_PASSENGER_USER_TID AS uid,
		SEG_TRANSPORT_TIK_PRICE AS amt
	FROM
		DWQ_PROD.T_DWD_DEPART_SEG_FACT
UNION ALL
	SELECT
		FK_PASSENGER_USER_TID,
		SEAT_AMOUNT_CNY
	FROM
		DWQ_PROD.T_DWD_SEAT_TIK_FACT
	WHERE
		AK_EMD_STATUS = 'F'
UNION ALL
	SELECT
		FK_PASSENGER_USER_TID,
		BAGGAGE_AMOUNT_CNY
	FROM
		DWQ_PROD.T_DWD_BAGGAGE_TIK_FACT
	WHERE
		AK_EMD_STATUS = 'F'
UNION ALL
	SELECT
		FK_PASSENGER_USER_TID,
		AK_EXCESSBAGGAGE_OLDAMOUNT_CNY
	FROM
		DWQ_PROD.T_DWD_EXCESS_BAGGAGE_TIK_FACT
	WHERE
		AK_EMD_STATUS = 'F'
UNION ALL
	SELECT
		FK_PASSENGER_USER_TID,
		UPGRDOLD_AMOUNT_CNY
	FROM
		DWQ_PROD.T_DWD_UPGR_TIK_FACT
	WHERE
		AK_EMD_STATUS = 'F'
UNION ALL
	SELECT
		FK_PASSENGER_USER_TID,
		INSURANCE_AMT
	FROM
		DWQ_PROD.T_DWD_AUIS_SEG_FACT
UNION ALL
	SELECT
		FK_PASSENGER_USER_TID,
		CAST(UPGRADE_PRICE AS DECIMAL(15, 2))
	FROM
		DWQ_PROD.T_DWD_UPGRADE_INFLIGHT_BUSINESS_FACT
	WHERE
		UPGRADE_PRICE IS NOT NULL
		AND UPGRADE_PRICE != ''
UNION ALL
	SELECT
		BUYER_TID,
		COUPON_VALUE
	FROM
		DWQ_PROD.T_DWD_UPGRADE_COUPON_SALES_FACT
	WHERE
		COUPON_USE_DATE IS NOT NULL
UNION ALL
	SELECT
		FK_BUYER_TID,
		VOUCHER_PAYMENT_AMOUNT
	FROM
		DWQ_PROD.T_DWD_TRP_COUPON_SALE_FACT
),


	-- CTE 2: 全局聚合 & 全局排名计算
	-- 计算排名，基于“全量历史数据”的真实排名
	cte_user_global_metrics AS (
	SELECT
		uid,
		SUM(amt) AS total_amt,
		-- 在聚合的同时直接计算排名
        RANK() OVER (ORDER BY SUM(amt) DESC) AS rank_val,
		PERCENT_RANK() OVER (ORDER BY SUM(amt) DESC) * 100 AS percentile_val
	FROM
		cte_flat_consumption
	WHERE
		uid IS NOT NULL
	GROUP BY
		uid
),
	-- CTE 3: 机票相关指标
	cte_ticket_metrics AS (
	SELECT
		ts.FK_BOOKING_USER_TID,
		SUM(CASE WHEN ts.AK_DIMARK = 'I' AND ts.IS_RESCHEDULED = 0 THEN ts.AK_SALE_PRICE_ALL_CNY ELSE 0 END) AS total_intl,
		SUM(CASE WHEN ts.AK_DIMARK = 'D' AND ts.IS_RESCHEDULED = 0 THEN ts.AK_SALE_PRICE_ALL_CNY ELSE 0 END) AS total_dom,
		SUM(CASE WHEN ts.AK_DIMARK = 'I' AND ts.IS_RESCHEDULED = 0 AND ts.FK_ISSUE_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 12 MONTH) THEN ts.AK_SALE_PRICE_ALL_CNY ELSE 0 END) AS last1y_intl,
		SUM(CASE WHEN ts.AK_DIMARK = 'D' AND ts.IS_RESCHEDULED = 0 AND ts.FK_ISSUE_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 12 MONTH) THEN ts.AK_SALE_PRICE_ALL_CNY ELSE 0 END) AS last1y_dom,
		SUM(CASE WHEN ts.IS_TEAM_TICKET = 1 AND ts.FK_ISSUE_DATE >= DATE_SUB(DATE(@ETL_DATE), INTERVAL 12 MONTH) THEN ts.TIK_SEGCOUNT ELSE 0 END) AS group_cnt_1y,
		SUM(CASE WHEN ts.IS_TEAM_TICKET = 1 THEN ts.TIK_SEGCOUNT ELSE 0 END) AS group_cnt_all
	FROM
		DWQ_PROD.T_DWD_TICKING_SEG_FACT ts
	GROUP BY
		ts.FK_BOOKING_USER_TID
)



SELECT
	target.PK_ID,
	-- 消费金额与排名 (来自 CTE 2)
	ROUND(metrics.total_amt, 2),
	metrics.rank_val,
	metrics.percentile_val,
	-- 机票指标 (来自 CTE 3)
    COALESCE(tm.total_intl, 0),
	COALESCE(tm.total_dom, 0),
	COALESCE(tm.last1y_intl, 0),
	COALESCE(tm.last1y_dom, 0),
	COALESCE(tm.group_cnt_1y, 0),
	COALESCE(tm.group_cnt_all, 0),
    UPDATE_TIME = now()
FROM
	DWQ_TEST.T_DIM_USER_DIM target
LEFT JOIN cte_user_global_metrics metrics ON
	target.PK_ID = metrics.uid
LEFT JOIN cte_ticket_metrics tm ON
	target.PK_ID = tm.FK_BOOKING_USER_TID

where target.IS_VALID_USER = 1;
