package com.travelsky.dataplatform.main.ods;

import com.travelsky.dataplatform.constans.Constants;
import com.travelsky.dataplatform.udf.SM4EncryptUDF;
import com.travelsky.dataplatform.utils.CheckpointUtils;
import org.apache.flink.streaming.api.CheckpointingMode;
import org.apache.flink.streaming.api.environment.CheckpointConfig;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.table.api.TableResult;
import org.apache.flink.table.api.bridge.java.StreamTableEnvironment;

import java.io.IOException;
import java.util.UUID;

/**
 * @author
 * @date 2025/7/2 9:31
 */
public class ExtractTOdsClkTDwDFfp {
    public static void main(String[] args) throws IOException {
        if (args.length < 1) {
            /*加日志：etl_date参数为空*/
            System.exit(0);
        }
        String etlDate = args[0];
//        String etlDate = "2021-05-07";
        String sm4key =  Constants.SM4_KEY;
        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        //checkpoint设置
        CheckpointUtils.setCheckpoint(env, "ExtractTOdsClkTDwDFfp");
        env.setParallelism(1);
        final StreamTableEnvironment tEnv = StreamTableEnvironment.create(env);
// 注册SM4加密UDF
        tEnv.createTemporarySystemFunction("sm4_encrypt", SM4EncryptUDF.class);
        long timestamp = System.currentTimeMillis();
        UUID uuid = UUID.randomUUID();

//创建上游数据源表
        StringBuffer sourceTableSql = new StringBuffer();
        sourceTableSql.append("CREATE TABLE T_DW_D_FFP (\n");
        sourceTableSql.append("FFP_ID VARCHAR(45) ,\n");
        sourceTableSql.append("AGE_ID DECIMAL ,\n");
        sourceTableSql.append("GUEST_ID DECIMAL ,\n");
        sourceTableSql.append("B2C_MEM_ID VARCHAR(60) ,\n");
        sourceTableSql.append("BRAND_ID VARCHAR(60) ,\n");
        sourceTableSql.append("PR_MOBILE_ID DECIMAL ,\n");
        sourceTableSql.append("LST_MOBILE_ID DECIMAL ,\n");
        sourceTableSql.append("HIGH_MOBILE_ID DECIMAL ,\n");
        sourceTableSql.append("REGION_ID VARCHAR(60) ,\n");
        sourceTableSql.append("SC_TIER_ID VARCHAR(90) ,\n");
        sourceTableSql.append("FFP_TIER_ID VARCHAR(90) ,\n");
        sourceTableSql.append("CHANNEL_DEV_ID DECIMAL ,\n");
        sourceTableSql.append("GENDER_ID VARCHAR(30) ,\n");
        sourceTableSql.append("FFP_CREATED TIMESTAMP(6),\n");
        sourceTableSql.append("FFP_LAST_UPD TIMESTAMP(6),\n");
        sourceTableSql.append("MEM_NUM VARCHAR(90),\n");
        sourceTableSql.append("MEM_TYPE_CD VARCHAR(90),\n");
        sourceTableSql.append("CONTACT_ID VARCHAR(45),\n");
        sourceTableSql.append("EXPIRY_DT TIMESTAMP(6),\n");
        sourceTableSql.append("LAST_ACCR_TXN_DT TIMESTAMP(6),\n");
        sourceTableSql.append("LAST_RDM_TXN_DT TIMESTAMP(6),\n");
        sourceTableSql.append("LAST_TXN_PROCED_DT TIMESTAMP(6),\n");
        sourceTableSql.append("LFTM_PT_TYPE_A_VAL DECIMAL(22,7),\n");
        sourceTableSql.append("LFTM_PT_TYPE_B_VAL DECIMAL(22,7),\n");
        sourceTableSql.append("LFTM_PT_TYPE_D_VAL DECIMAL(22,7),\n");
        sourceTableSql.append("MAX_POINT_LOAN DECIMAL(22,7),\n");
        sourceTableSql.append("POINT_TYPE_A_VAL DECIMAL(22,7),\n");
        sourceTableSql.append("POINT_TYPE_B_VAL DECIMAL(22,7),\n");
        sourceTableSql.append("POINT_TYPE_C_VAL DECIMAL(22,7),\n");
        sourceTableSql.append("START_DT TIMESTAMP(6),\n");
        sourceTableSql.append("SUBMIT_DT TIMESTAMP(6),\n");
        sourceTableSql.append("NAME VARCHAR(300),\n");
        sourceTableSql.append("ORG_GROUP_ID VARCHAR(45),\n");
        sourceTableSql.append("PAR_MEM_ID VARCHAR(45),\n");
        sourceTableSql.append("STATUS_CD VARCHAR(90),\n");
        sourceTableSql.append("VAL_SCORE VARCHAR(90),\n");
        sourceTableSql.append("MEM_VAL VARCHAR(90),\n");
        sourceTableSql.append("SUBMIT_PERSON VARCHAR(90),\n");
        sourceTableSql.append("TEST_MEM_FLAG VARCHAR(3),\n");
        sourceTableSql.append("PR_MEM_CARD_ID VARCHAR(45),\n");
        sourceTableSql.append("ABBRE_NAME VARCHAR(90),\n");
        sourceTableSql.append("BLOCK_LIST VARCHAR(60),\n");
        sourceTableSql.append("CARD_NAME VARCHAR(150),\n");
        sourceTableSql.append("FLIGHT_FRQ_FLAG VARCHAR(3),\n");
        sourceTableSql.append("FLIGHT_TIMES DECIMAL(10,0),\n");
        sourceTableSql.append("FORCE_CREATE_FLG VARCHAR(3),\n");
        sourceTableSql.append("FROZ_POINT DECIMAL(10,0),\n");
        sourceTableSql.append("NONAIR_FRQ_FLAG VARCHAR(3),\n");
        sourceTableSql.append("TRANSFER VARCHAR(90),\n");
        sourceTableSql.append("TRANSFER_END_DT TIMESTAMP(6),\n");
        sourceTableSql.append("TRANSFER_START_DT TIMESTAMP(6),\n");
        sourceTableSql.append("CARD_FLG VARCHAR(15),\n");
        sourceTableSql.append("QF_POINT DECIMAL(22,0),\n");
        sourceTableSql.append("QF_SEGMENT DECIMAL(22,2),\n");
        sourceTableSql.append("QF_UPDATE_DT TIMESTAMP(6),\n");
        sourceTableSql.append("LAST_AIR_TXN_DT TIMESTAMP(6),\n");
        sourceTableSql.append("SLEEP_AIR_TXN_DT DECIMAL,\n");
        sourceTableSql.append("LAST_ALL_TXN_DT TIMESTAMP(6),\n");
        sourceTableSql.append("SLEEP_ALL_TXN_DT DECIMAL,\n");
        sourceTableSql.append("LAST_SCAIR_TXN_DT TIMESTAMP(6),\n");
        sourceTableSql.append("SLEEP_SCAIR_TXN_DT DECIMAL,\n");
        sourceTableSql.append("POINT_A DECIMAL(22,7),\n");
        sourceTableSql.append("TXN_CREATED TIMESTAMP(6),\n");
        sourceTableSql.append("TXN_LAST_UPD TIMESTAMP(6),\n");
        sourceTableSql.append("SC_VALUE DECIMAL(22,7),\n");
        sourceTableSql.append("IS_BIG_GUEST VARCHAR(3),\n");
        sourceTableSql.append("IS_BUS_MEM VARCHAR(3),\n");
        sourceTableSql.append("PIN_STATUS VARCHAR(150),\n");
        sourceTableSql.append("PR_ADDR VARCHAR(1500),\n");
        sourceTableSql.append("PR_COMPANY VARCHAR(300),\n");
        sourceTableSql.append("PR_DEPART VARCHAR(300),\n");
        sourceTableSql.append("PR_ADDR_TYPE VARCHAR(150),\n");
        sourceTableSql.append("PR_ADDR_CITY VARCHAR(150),\n");
        sourceTableSql.append("PR_ADDR_STATE VARCHAR(150),\n");
        sourceTableSql.append("PR_ADDR_ZIPCODE VARCHAR(150),\n");
        sourceTableSql.append("PR_EMAIL VARCHAR(300),\n");
        sourceTableSql.append("PR_EMAIL_TYPE VARCHAR(90),\n");
        sourceTableSql.append("PR_MOBILE VARCHAR(150),\n");
        sourceTableSql.append("LST_MOBILE VARCHAR(150),\n");
        sourceTableSql.append("PR_ID VARCHAR(90),\n");
        sourceTableSql.append("PR_CATEGORY_CD VARCHAR(90),\n");
        sourceTableSql.append("PR_EXPIRATION_TS TIMESTAMP(6),\n");
        sourceTableSql.append("PR_ISSUE_TS TIMESTAMP(6),\n");
        sourceTableSql.append("PR_ISSUING_COUNTRY VARCHAR(90),\n");
        sourceTableSql.append("HIGH_SCORE_MOBILE VARCHAR(150),\n");
        sourceTableSql.append("PR_CHECKIN VARCHAR(300),\n");
        sourceTableSql.append("PR_PORT_CITY VARCHAR(600),\n");
        sourceTableSql.append("PR_BUY_CHANNEL VARCHAR(300),\n");
        sourceTableSql.append("PR_EX_AIRLINE VARCHAR(300),\n");
        sourceTableSql.append("PR_EX_SC_SEGMENT VARCHAR(300),\n");
        sourceTableSql.append("PR_EX_SC_CABIN VARCHAR(300),\n");
        sourceTableSql.append("PR_EX_SC_SEAT VARCHAR(300),\n");
        sourceTableSql.append("P_MOBILE VARCHAR(300),\n");
        sourceTableSql.append("P_PRODUCT VARCHAR(600),\n");
        sourceTableSql.append("P_ACTIVITY VARCHAR(600),\n");
        sourceTableSql.append("P_BUY_TICKETS VARCHAR(300),\n");
        sourceTableSql.append("P_SEAT VARCHAR(300),\n");
        sourceTableSql.append("P_CABIN VARCHAR(300),\n");
        sourceTableSql.append("P_MEALS VARCHAR(300),\n");
        sourceTableSql.append("FFP_TIER_START_DT TIMESTAMP(6),\n");
        sourceTableSql.append("FFP_TIER_END_DT TIMESTAMP(6),\n");
        sourceTableSql.append("FFP_PTIER VARCHAR(150),\n");
        sourceTableSql.append("CON_LAST_UPD TIMESTAMP(6),\n");
        sourceTableSql.append("EN_FST_NAME VARCHAR(150),\n");
        sourceTableSql.append("EN_LAST_NAME VARCHAR(150),\n");
        sourceTableSql.append("CN_FST_NAME VARCHAR(150),\n");
        sourceTableSql.append("CN_LAST_NAME VARCHAR(150),\n");
        sourceTableSql.append("SP_FST_NAME VARCHAR(150),\n");
        sourceTableSql.append("SP_LST_NAME VARCHAR(150),\n");
        sourceTableSql.append("TS_FST_NAME VARCHAR(150),\n");
        sourceTableSql.append("TS_LST_NAME VARCHAR(150),\n");
        sourceTableSql.append("BIRTH_DT TIMESTAMP(6),\n");
        sourceTableSql.append("JOB_TITLE VARCHAR(225),\n");
        sourceTableSql.append("NATIONALITY VARCHAR(90),\n");
        sourceTableSql.append("PER_TITLE VARCHAR(45),\n");
        sourceTableSql.append("MARRIAGE_STATUS VARCHAR(60),\n");
        sourceTableSql.append("DATA_ACTIVE_FLG VARCHAR(3),\n");
        sourceTableSql.append("SOURCE_ID DECIMAL,\t\n");
        sourceTableSql.append("ETL_INSERT_TIME TIMESTAMP(6) ,\n");
        sourceTableSql.append("ETL_UPDATE_TIME TIMESTAMP(6) ,\n");
        sourceTableSql.append("SC_TYPE_RFM VARCHAR(600)\n");
        sourceTableSql.append(") WITH (\n");
        sourceTableSql.append("    'connector' = 'jdbc',\n");
        sourceTableSql.append("    'url' = 'jdbc:oracle:thin:@//").append(Constants.CLK_DW_IP).append(":").append(Constants.CLK_DW_PORT).append("/").append(Constants.CLK_DW_DB).append("',\n");
        sourceTableSql.append("    'table-name' = '").append(Constants.CLK_DW_SCHEMA).append(".T_DW_D_FFP', \n");
        sourceTableSql.append("    'username' = '").append(Constants.CLK_DW_USER).append("',\n");
        sourceTableSql.append("    'password' = '").append(Constants.CLK_DW_PWD).append("'\n");
        sourceTableSql.append(",\n");
        sourceTableSql.append("  'driver' = '").append(Constants.ORACLE_DRIVER).append("'");
        sourceTableSql.append(")");
        tEnv.executeSql(sourceTableSql.toString());
        
        //创建Doris目标表
        StringBuffer targetTableSql = new StringBuffer();
        targetTableSql.append("CREATE TABLE T_ODS_CLK_T_DW_D_FFP (\n");
        targetTableSql.append("    ETL_DATE DATE,\n");
        targetTableSql.append("FFP_ID VARCHAR(45) ,\n");
        targetTableSql.append("AGE_ID DECIMAL ,\n");
        targetTableSql.append("GUEST_ID DECIMAL ,\n");
        targetTableSql.append("B2C_MEM_ID VARCHAR(60) ,\n");
        targetTableSql.append("BRAND_ID VARCHAR(60) ,\n");
        targetTableSql.append("PR_MOBILE_ID DECIMAL ,\n");
        targetTableSql.append("LST_MOBILE_ID DECIMAL ,\n");
        targetTableSql.append("HIGH_MOBILE_ID DECIMAL ,\n");
        targetTableSql.append("REGION_ID VARCHAR(60) ,\n");
        targetTableSql.append("SC_TIER_ID VARCHAR(90) ,\n");
        targetTableSql.append("FFP_TIER_ID VARCHAR(90) ,\n");
        targetTableSql.append("CHANNEL_DEV_ID DECIMAL ,\n");
        targetTableSql.append("GENDER_ID VARCHAR(30) ,\n");
        targetTableSql.append("FFP_CREATED TIMESTAMP(6),\n");
        targetTableSql.append("FFP_LAST_UPD TIMESTAMP(6),\n");
        targetTableSql.append("MEM_NUM VARCHAR(90),\n");
        targetTableSql.append("MEM_TYPE_CD VARCHAR(90),\n");
        targetTableSql.append("CONTACT_ID VARCHAR(45),\n");
        targetTableSql.append("EXPIRY_DT TIMESTAMP(6),\n");
        targetTableSql.append("LAST_ACCR_TXN_DT TIMESTAMP(6),\n");
        targetTableSql.append("LAST_RDM_TXN_DT TIMESTAMP(6),\n");
        targetTableSql.append("LAST_TXN_PROCED_DT TIMESTAMP(6),\n");
        targetTableSql.append("LFTM_PT_TYPE_A_VAL DECIMAL(22,7),\n");
        targetTableSql.append("LFTM_PT_TYPE_B_VAL DECIMAL(22,7),\n");
        targetTableSql.append("LFTM_PT_TYPE_D_VAL DECIMAL(22,7),\n");
        targetTableSql.append("MAX_POINT_LOAN DECIMAL(22,7),\n");
        targetTableSql.append("POINT_TYPE_A_VAL DECIMAL(22,7),\n");
        targetTableSql.append("POINT_TYPE_B_VAL DECIMAL(22,7),\n");
        targetTableSql.append("POINT_TYPE_C_VAL DECIMAL(22,7),\n");
        targetTableSql.append("START_DT TIMESTAMP(6),\n");
        targetTableSql.append("SUBMIT_DT TIMESTAMP(6),\n");
        targetTableSql.append("NAME VARCHAR(300),\n");
        targetTableSql.append("ORG_GROUP_ID VARCHAR(45),\n");
        targetTableSql.append("PAR_MEM_ID VARCHAR(45),\n");
        targetTableSql.append("STATUS_CD VARCHAR(90),\n");
        targetTableSql.append("VAL_SCORE VARCHAR(90),\n");
        targetTableSql.append("MEM_VAL VARCHAR(90),\n");
        targetTableSql.append("SUBMIT_PERSON VARCHAR(90),\n");
        targetTableSql.append("TEST_MEM_FLAG VARCHAR(3),\n");
        targetTableSql.append("PR_MEM_CARD_ID VARCHAR(45),\n");
        targetTableSql.append("ABBRE_NAME VARCHAR(90),\n");
        targetTableSql.append("BLOCK_LIST VARCHAR(60),\n");
        targetTableSql.append("CARD_NAME VARCHAR(150),\n");
        targetTableSql.append("FLIGHT_FRQ_FLAG VARCHAR(3),\n");
        targetTableSql.append("FLIGHT_TIMES DECIMAL(10,0),\n");
        targetTableSql.append("FORCE_CREATE_FLG VARCHAR(3),\n");
        targetTableSql.append("FROZ_POINT DECIMAL(10,0),\n");
        targetTableSql.append("NONAIR_FRQ_FLAG VARCHAR(3),\n");
        targetTableSql.append("TRANSFER VARCHAR(90),\n");
        targetTableSql.append("TRANSFER_END_DT TIMESTAMP(6),\n");
        targetTableSql.append("TRANSFER_START_DT TIMESTAMP(6),\n");
        targetTableSql.append("CARD_FLG VARCHAR(15),\n");
        targetTableSql.append("QF_POINT DECIMAL(22,0),\n");
        targetTableSql.append("QF_SEGMENT DECIMAL(22,2),\n");
        targetTableSql.append("QF_UPDATE_DT TIMESTAMP(6),\n");
        targetTableSql.append("LAST_AIR_TXN_DT TIMESTAMP(6),\n");
        targetTableSql.append("SLEEP_AIR_TXN_DT DECIMAL,\n");
        targetTableSql.append("LAST_ALL_TXN_DT TIMESTAMP(6),\n");
        targetTableSql.append("SLEEP_ALL_TXN_DT DECIMAL,\n");
        targetTableSql.append("LAST_SCAIR_TXN_DT TIMESTAMP(6),\n");
        targetTableSql.append("SLEEP_SCAIR_TXN_DT DECIMAL,\n");
        targetTableSql.append("POINT_A DECIMAL(22,7),\n");
        targetTableSql.append("TXN_CREATED TIMESTAMP(6),\n");
        targetTableSql.append("TXN_LAST_UPD TIMESTAMP(6),\n");
        targetTableSql.append("SC_VALUE DECIMAL(22,7),\n");
        targetTableSql.append("IS_BIG_GUEST VARCHAR(3),\n");
        targetTableSql.append("IS_BUS_MEM VARCHAR(3),\n");
        targetTableSql.append("PIN_STATUS VARCHAR(150),\n");
        targetTableSql.append("PR_ADDR VARCHAR(1500),\n");
        targetTableSql.append("PR_COMPANY VARCHAR(300),\n");
        targetTableSql.append("PR_DEPART VARCHAR(300),\n");
        targetTableSql.append("PR_ADDR_TYPE VARCHAR(150),\n");
        targetTableSql.append("PR_ADDR_CITY VARCHAR(150),\n");
        targetTableSql.append("PR_ADDR_STATE VARCHAR(150),\n");
        targetTableSql.append("PR_ADDR_ZIPCODE VARCHAR(150),\n");
        targetTableSql.append("PR_EMAIL VARCHAR(300),\n");
        targetTableSql.append("PR_EMAIL_TYPE VARCHAR(90),\n");
        targetTableSql.append("PR_MOBILE VARCHAR(150),\n");
        targetTableSql.append("LST_MOBILE VARCHAR(150),\n");
        targetTableSql.append("PR_ID VARCHAR(300),\n");
        targetTableSql.append("PR_CATEGORY_CD VARCHAR(90),\n");
        targetTableSql.append("PR_EXPIRATION_TS TIMESTAMP(6),\n");
        targetTableSql.append("PR_ISSUE_TS TIMESTAMP(6),\n");
        targetTableSql.append("PR_ISSUING_COUNTRY VARCHAR(90),\n");
        targetTableSql.append("HIGH_SCORE_MOBILE VARCHAR(150),\n");
        targetTableSql.append("PR_CHECKIN VARCHAR(300),\n");
        targetTableSql.append("PR_PORT_CITY VARCHAR(600),\n");
        targetTableSql.append("PR_BUY_CHANNEL VARCHAR(300),\n");
        targetTableSql.append("PR_EX_AIRLINE VARCHAR(300),\n");
        targetTableSql.append("PR_EX_SC_SEGMENT VARCHAR(300),\n");
        targetTableSql.append("PR_EX_SC_CABIN VARCHAR(300),\n");
        targetTableSql.append("PR_EX_SC_SEAT VARCHAR(300),\n");
        targetTableSql.append("P_MOBILE VARCHAR(300),\n");
        targetTableSql.append("P_PRODUCT VARCHAR(600),\n");
        targetTableSql.append("P_ACTIVITY VARCHAR(600),\n");
        targetTableSql.append("P_BUY_TICKETS VARCHAR(300),\n");
        targetTableSql.append("P_SEAT VARCHAR(300),\n");
        targetTableSql.append("P_CABIN VARCHAR(300),\n");
        targetTableSql.append("P_MEALS VARCHAR(300),\n");
        targetTableSql.append("FFP_TIER_START_DT TIMESTAMP(6),\n");
        targetTableSql.append("FFP_TIER_END_DT TIMESTAMP(6),\n");
        targetTableSql.append("FFP_PTIER VARCHAR(150),\n");
        targetTableSql.append("CON_LAST_UPD TIMESTAMP(6),\n");
        targetTableSql.append("EN_FST_NAME VARCHAR(150),\n");
        targetTableSql.append("EN_LAST_NAME VARCHAR(150),\n");
        targetTableSql.append("CN_FST_NAME VARCHAR(150),\n");
        targetTableSql.append("CN_LAST_NAME VARCHAR(150),\n");
        targetTableSql.append("SP_FST_NAME VARCHAR(150),\n");
        targetTableSql.append("SP_LST_NAME VARCHAR(150),\n");
        targetTableSql.append("TS_FST_NAME VARCHAR(150),\n");
        targetTableSql.append("TS_LST_NAME VARCHAR(150),\n");
        targetTableSql.append("BIRTH_DT TIMESTAMP(6),\n");
        targetTableSql.append("JOB_TITLE VARCHAR(225),\n");
        targetTableSql.append("NATIONALITY VARCHAR(90),\n");
        targetTableSql.append("PER_TITLE VARCHAR(45),\n");
        targetTableSql.append("MARRIAGE_STATUS VARCHAR(60),\n");
        targetTableSql.append("DATA_ACTIVE_FLG VARCHAR(3),\n");
        targetTableSql.append("SOURCE_ID DECIMAL,\t\n");
        targetTableSql.append("ETL_INSERT_TIME TIMESTAMP(6) ,\n");
        targetTableSql.append("ETL_UPDATE_TIME TIMESTAMP(6) ,\n");
        targetTableSql.append("SC_TYPE_RFM VARCHAR(600)\n");
        targetTableSql.append(") WITH (\n");
        targetTableSql.append(" 'connector' = 'doris',\n");
        targetTableSql.append("'fenodes' = '").append(Constants.DORIS_FE_IP).append(":").append(Constants.DORIS_FE_PORT).append("', -- 替换为 Doris FE 的地址和端口\n");
        targetTableSql.append("'benodes' = '").append(Constants.DORIS_BE_IP).append(":").append(Constants.DORIS_BE_PORT).append("', -- 替换为 Doris FE 的地址和端口\n");
        targetTableSql.append(" 'table.identifier' = '").append(Constants.ODS_DB).append(".T_ODS_CLK_T_DW_D_FFP',\n");
        targetTableSql.append("'sink.label-prefix' = '").append(timestamp).append(uuid).append("',");
        targetTableSql.append(" 'sink.properties.read_json_by_line' = 'true',");
        targetTableSql.append(" 'sink.properties.format' = 'json',");
        targetTableSql.append("    'username' = '").append(Constants.ODS_USER).append("',\n");
        targetTableSql.append("    'password' = '").append(Constants.ODS_PWD).append("'\n");
        targetTableSql.append(")");
        tEnv.executeSql(targetTableSql.toString());
        
        //数据抽取sql，配置增量字段、数据加密等
        StringBuffer extractSqlBuffer = new StringBuffer();
        extractSqlBuffer.append("INSERT INTO T_ODS_CLK_T_DW_D_FFP(");
        extractSqlBuffer.append("ETL_DATE,\n");
        extractSqlBuffer.append("FFP_ID,\n");
        extractSqlBuffer.append("AGE_ID,\n");
        extractSqlBuffer.append("GUEST_ID,\n");
        extractSqlBuffer.append("B2C_MEM_ID,\n");
        extractSqlBuffer.append("BRAND_ID,\n");
        extractSqlBuffer.append("PR_MOBILE_ID,\n");
        extractSqlBuffer.append("LST_MOBILE_ID,\n");
        extractSqlBuffer.append("HIGH_MOBILE_ID,\n");
        extractSqlBuffer.append("REGION_ID,\n");
        extractSqlBuffer.append("SC_TIER_ID,\n");
        extractSqlBuffer.append("FFP_TIER_ID,\n");
        extractSqlBuffer.append("CHANNEL_DEV_ID,\n");
        extractSqlBuffer.append("GENDER_ID,\n");
        extractSqlBuffer.append("FFP_CREATED,\n");
        extractSqlBuffer.append("FFP_LAST_UPD,\n");
        extractSqlBuffer.append("MEM_NUM,\n");
        extractSqlBuffer.append("MEM_TYPE_CD,\n");
        extractSqlBuffer.append("CONTACT_ID,\n");
        extractSqlBuffer.append("EXPIRY_DT,\n");
        extractSqlBuffer.append("LAST_ACCR_TXN_DT,\n");
        extractSqlBuffer.append("LAST_RDM_TXN_DT,\n");
        extractSqlBuffer.append("LAST_TXN_PROCED_DT,\n");
        extractSqlBuffer.append("LFTM_PT_TYPE_A_VAL,\n");
        extractSqlBuffer.append("LFTM_PT_TYPE_B_VAL,\n");
        extractSqlBuffer.append("LFTM_PT_TYPE_D_VAL,\n");
        extractSqlBuffer.append("MAX_POINT_LOAN,\n");
        extractSqlBuffer.append("POINT_TYPE_A_VAL,\n");
        extractSqlBuffer.append("POINT_TYPE_B_VAL,\n");
        extractSqlBuffer.append("POINT_TYPE_C_VAL,\n");
        extractSqlBuffer.append("START_DT,\n");
        extractSqlBuffer.append("SUBMIT_DT,\n");
        extractSqlBuffer.append("NAME,\n");
        extractSqlBuffer.append("ORG_GROUP_ID,\n");
        extractSqlBuffer.append("PAR_MEM_ID,\n");
        extractSqlBuffer.append("STATUS_CD,\n");
        extractSqlBuffer.append("VAL_SCORE,\n");
        extractSqlBuffer.append("MEM_VAL,\n");
        extractSqlBuffer.append("SUBMIT_PERSON,\n");
        extractSqlBuffer.append("TEST_MEM_FLAG,\n");
        extractSqlBuffer.append("PR_MEM_CARD_ID,\n");
        extractSqlBuffer.append("ABBRE_NAME,\n");
        extractSqlBuffer.append("BLOCK_LIST,\n");
        extractSqlBuffer.append("CARD_NAME,\n");
        extractSqlBuffer.append("FLIGHT_FRQ_FLAG,\n");
        extractSqlBuffer.append("FLIGHT_TIMES,\n");
        extractSqlBuffer.append("FORCE_CREATE_FLG,\n");
        extractSqlBuffer.append("FROZ_POINT,\n");
        extractSqlBuffer.append("NONAIR_FRQ_FLAG,\n");
        extractSqlBuffer.append("TRANSFER,\n");
        extractSqlBuffer.append("TRANSFER_END_DT,\n");
        extractSqlBuffer.append("TRANSFER_START_DT,\n");
        extractSqlBuffer.append("CARD_FLG,\n");
        extractSqlBuffer.append("QF_POINT,\n");
        extractSqlBuffer.append("QF_SEGMENT,\n");
        extractSqlBuffer.append("QF_UPDATE_DT,\n");
        extractSqlBuffer.append("LAST_AIR_TXN_DT,\n");
        extractSqlBuffer.append("SLEEP_AIR_TXN_DT,\n");
        extractSqlBuffer.append("LAST_ALL_TXN_DT,\n");
        extractSqlBuffer.append("SLEEP_ALL_TXN_DT,\n");
        extractSqlBuffer.append("LAST_SCAIR_TXN_DT,\n");
        extractSqlBuffer.append("SLEEP_SCAIR_TXN_DT,\n");
        extractSqlBuffer.append("POINT_A,\n");
        extractSqlBuffer.append("TXN_CREATED,\n");
        extractSqlBuffer.append("TXN_LAST_UPD,\n");
        extractSqlBuffer.append("SC_VALUE,\n");
        extractSqlBuffer.append("IS_BIG_GUEST,\n");
        extractSqlBuffer.append("IS_BUS_MEM,\n");
        extractSqlBuffer.append("PIN_STATUS,\n");
        extractSqlBuffer.append("PR_ADDR,\n");
        extractSqlBuffer.append("PR_COMPANY,\n");
        extractSqlBuffer.append("PR_DEPART,\n");
        extractSqlBuffer.append("PR_ADDR_TYPE,\n");
        extractSqlBuffer.append("PR_ADDR_CITY,\n");
        extractSqlBuffer.append("PR_ADDR_STATE,\n");
        extractSqlBuffer.append("PR_ADDR_ZIPCODE,\n");
        extractSqlBuffer.append("PR_EMAIL,\n");
        extractSqlBuffer.append("PR_EMAIL_TYPE,\n");
        extractSqlBuffer.append("PR_MOBILE,\n");
        extractSqlBuffer.append("LST_MOBILE,\n");
        extractSqlBuffer.append("PR_ID,\n");
        extractSqlBuffer.append("PR_CATEGORY_CD,\n");
        extractSqlBuffer.append("PR_EXPIRATION_TS,\n");
        extractSqlBuffer.append("PR_ISSUE_TS,\n");
        extractSqlBuffer.append("PR_ISSUING_COUNTRY,\n");
        extractSqlBuffer.append("HIGH_SCORE_MOBILE,\n");
        extractSqlBuffer.append("PR_CHECKIN,\n");
        extractSqlBuffer.append("PR_PORT_CITY,\n");
        extractSqlBuffer.append("PR_BUY_CHANNEL,\n");
        extractSqlBuffer.append("PR_EX_AIRLINE,\n");
        extractSqlBuffer.append("PR_EX_SC_SEGMENT,\n");
        extractSqlBuffer.append("PR_EX_SC_CABIN,\n");
        extractSqlBuffer.append("PR_EX_SC_SEAT,\n");
        extractSqlBuffer.append("P_MOBILE,\n");
        extractSqlBuffer.append("P_PRODUCT,\n");
        extractSqlBuffer.append("P_ACTIVITY,\n");
        extractSqlBuffer.append("P_BUY_TICKETS,\n");
        extractSqlBuffer.append("P_SEAT,\n");
        extractSqlBuffer.append("P_CABIN,\n");
        extractSqlBuffer.append("P_MEALS,\n");
        extractSqlBuffer.append("FFP_TIER_START_DT,\n");
        extractSqlBuffer.append("FFP_TIER_END_DT,\n");
        extractSqlBuffer.append("FFP_PTIER,\n");
        extractSqlBuffer.append("CON_LAST_UPD,\n");
        extractSqlBuffer.append("EN_FST_NAME,\n");
        extractSqlBuffer.append("EN_LAST_NAME,\n");
        extractSqlBuffer.append("CN_FST_NAME,\n");
        extractSqlBuffer.append("CN_LAST_NAME,\n");
        extractSqlBuffer.append("SP_FST_NAME,\n");
        extractSqlBuffer.append("SP_LST_NAME,\n");
        extractSqlBuffer.append("TS_FST_NAME,\n");
        extractSqlBuffer.append("TS_LST_NAME,\n");
        extractSqlBuffer.append("BIRTH_DT,\n");
        extractSqlBuffer.append("JOB_TITLE,\n");
        extractSqlBuffer.append("NATIONALITY,\n");
        extractSqlBuffer.append("PER_TITLE,\n");
        extractSqlBuffer.append("MARRIAGE_STATUS,\n");
        extractSqlBuffer.append("DATA_ACTIVE_FLG,\n");
        extractSqlBuffer.append("SOURCE_ID,\n");
        extractSqlBuffer.append("ETL_INSERT_TIME,\n");
        extractSqlBuffer.append("ETL_UPDATE_TIME,\n");
        extractSqlBuffer.append("SC_TYPE_RFM)\n");
        extractSqlBuffer.append("SELECT ");
        extractSqlBuffer.append("CAST('").append(etlDate).append("' AS DATE) ETL_DATE,");
        extractSqlBuffer.append("FFP_ID,\n");
        extractSqlBuffer.append("AGE_ID,\n");
        extractSqlBuffer.append("GUEST_ID,\n");
        extractSqlBuffer.append("B2C_MEM_ID,\n");
        extractSqlBuffer.append("BRAND_ID,\n");
        extractSqlBuffer.append("PR_MOBILE_ID,\n");
        extractSqlBuffer.append("LST_MOBILE_ID,\n");
        extractSqlBuffer.append("HIGH_MOBILE_ID,\n");
        extractSqlBuffer.append("REGION_ID,\n");
        extractSqlBuffer.append("SC_TIER_ID,\n");
        extractSqlBuffer.append("FFP_TIER_ID,\n");
        extractSqlBuffer.append("CHANNEL_DEV_ID,\n");
        extractSqlBuffer.append("GENDER_ID,\n");
        extractSqlBuffer.append("FFP_CREATED,\n");
        extractSqlBuffer.append("FFP_LAST_UPD,\n");
        extractSqlBuffer.append(" sm4_encrypt (MEM_NUM,'").append(sm4key).append("') MEM_NUM, \n");
        extractSqlBuffer.append("MEM_TYPE_CD,\n");
        extractSqlBuffer.append("CONTACT_ID,\n");
        extractSqlBuffer.append("EXPIRY_DT,\n");
        extractSqlBuffer.append("LAST_ACCR_TXN_DT,\n");
        extractSqlBuffer.append("LAST_RDM_TXN_DT,\n");
        extractSqlBuffer.append("LAST_TXN_PROCED_DT,\n");
        extractSqlBuffer.append("LFTM_PT_TYPE_A_VAL,\n");
        extractSqlBuffer.append("LFTM_PT_TYPE_B_VAL,\n");
        extractSqlBuffer.append("LFTM_PT_TYPE_D_VAL,\n");
        extractSqlBuffer.append("MAX_POINT_LOAN,\n");
        extractSqlBuffer.append("POINT_TYPE_A_VAL,\n");
        extractSqlBuffer.append("POINT_TYPE_B_VAL,\n");
        extractSqlBuffer.append("POINT_TYPE_C_VAL,\n");
        extractSqlBuffer.append("START_DT,\n");
        extractSqlBuffer.append("SUBMIT_DT,\n");
        extractSqlBuffer.append("NAME,\n");
        extractSqlBuffer.append("ORG_GROUP_ID,\n");
        extractSqlBuffer.append("PAR_MEM_ID,\n");
        extractSqlBuffer.append("STATUS_CD,\n");
        extractSqlBuffer.append("VAL_SCORE,\n");
        extractSqlBuffer.append("MEM_VAL,\n");
        extractSqlBuffer.append("SUBMIT_PERSON,\n");
        extractSqlBuffer.append("TEST_MEM_FLAG,\n");
        extractSqlBuffer.append("PR_MEM_CARD_ID,\n");
        extractSqlBuffer.append("ABBRE_NAME,\n");
        extractSqlBuffer.append("BLOCK_LIST,\n");
        extractSqlBuffer.append("CARD_NAME,\n");
        extractSqlBuffer.append("FLIGHT_FRQ_FLAG,\n");
        extractSqlBuffer.append("FLIGHT_TIMES,\n");
        extractSqlBuffer.append("FORCE_CREATE_FLG,\n");
        extractSqlBuffer.append("FROZ_POINT,\n");
        extractSqlBuffer.append("NONAIR_FRQ_FLAG,\n");
        extractSqlBuffer.append("TRANSFER,\n");
        extractSqlBuffer.append("TRANSFER_END_DT,\n");
        extractSqlBuffer.append("TRANSFER_START_DT,\n");
        extractSqlBuffer.append("CARD_FLG,\n");
        extractSqlBuffer.append("QF_POINT,\n");
        extractSqlBuffer.append("QF_SEGMENT,\n");
        extractSqlBuffer.append("QF_UPDATE_DT,\n");
        extractSqlBuffer.append("LAST_AIR_TXN_DT,\n");
        extractSqlBuffer.append("SLEEP_AIR_TXN_DT,\n");
        extractSqlBuffer.append("LAST_ALL_TXN_DT,\n");
        extractSqlBuffer.append("SLEEP_ALL_TXN_DT,\n");
        extractSqlBuffer.append("LAST_SCAIR_TXN_DT,\n");
        extractSqlBuffer.append("SLEEP_SCAIR_TXN_DT,\n");
        extractSqlBuffer.append("POINT_A,\n");
        extractSqlBuffer.append("TXN_CREATED,\n");
        extractSqlBuffer.append("TXN_LAST_UPD,\n");
        extractSqlBuffer.append("SC_VALUE,\n");
        extractSqlBuffer.append("IS_BIG_GUEST,\n");
        extractSqlBuffer.append("IS_BUS_MEM,\n");
        extractSqlBuffer.append("PIN_STATUS,\n");
        extractSqlBuffer.append("PR_ADDR,\n");
        extractSqlBuffer.append("PR_COMPANY,\n");
        extractSqlBuffer.append("PR_DEPART,\n");
        extractSqlBuffer.append("PR_ADDR_TYPE,\n");
        extractSqlBuffer.append("PR_ADDR_CITY,\n");
        extractSqlBuffer.append("PR_ADDR_STATE,\n");
        extractSqlBuffer.append("PR_ADDR_ZIPCODE,\n");
        extractSqlBuffer.append(" sm4_encrypt (PR_EMAIL,'").append(sm4key).append("') PR_EMAIL, \n");
        extractSqlBuffer.append("PR_EMAIL_TYPE,\n");
        extractSqlBuffer.append(" sm4_encrypt (PR_MOBILE,'").append(sm4key).append("') PR_MOBILE, \n");
        extractSqlBuffer.append(" sm4_encrypt (LST_MOBILE,'").append(sm4key).append("') LST_MOBILE, \n");
        extractSqlBuffer.append(" sm4_encrypt (PR_ID,'").append(sm4key).append("') PR_ID, \n");
        extractSqlBuffer.append("PR_CATEGORY_CD,\n");
        extractSqlBuffer.append("PR_EXPIRATION_TS,\n");
        extractSqlBuffer.append("PR_ISSUE_TS,\n");
        extractSqlBuffer.append("PR_ISSUING_COUNTRY,\n");
        extractSqlBuffer.append(" sm4_encrypt (HIGH_SCORE_MOBILE,'").append(sm4key).append("') HIGH_SCORE_MOBILE, \n");
        extractSqlBuffer.append("PR_CHECKIN,\n");
        extractSqlBuffer.append("PR_PORT_CITY,\n");
        extractSqlBuffer.append("PR_BUY_CHANNEL,\n");
        extractSqlBuffer.append("PR_EX_AIRLINE,\n");
        extractSqlBuffer.append("PR_EX_SC_SEGMENT,\n");
        extractSqlBuffer.append("PR_EX_SC_CABIN,\n");
        extractSqlBuffer.append("PR_EX_SC_SEAT,\n");
        extractSqlBuffer.append(" sm4_encrypt (P_MOBILE,'").append(sm4key).append("') P_MOBILE, \n");
        extractSqlBuffer.append("P_PRODUCT,\n");
        extractSqlBuffer.append("P_ACTIVITY,\n");
        extractSqlBuffer.append("P_BUY_TICKETS,\n");
        extractSqlBuffer.append("P_SEAT,\n");
        extractSqlBuffer.append("P_CABIN,\n");
        extractSqlBuffer.append("P_MEALS,\n");
        extractSqlBuffer.append("FFP_TIER_START_DT,\n");
        extractSqlBuffer.append("FFP_TIER_END_DT,\n");
        extractSqlBuffer.append("FFP_PTIER,\n");
        extractSqlBuffer.append("CON_LAST_UPD,\n");
        extractSqlBuffer.append("EN_FST_NAME,\n");
        extractSqlBuffer.append("EN_LAST_NAME,\n");
        extractSqlBuffer.append("CN_FST_NAME,\n");
        extractSqlBuffer.append("CN_LAST_NAME,\n");
        extractSqlBuffer.append("SP_FST_NAME,\n");
        extractSqlBuffer.append("SP_LST_NAME,\n");
        extractSqlBuffer.append("TS_FST_NAME,\n");
        extractSqlBuffer.append("TS_LST_NAME,\n");
        extractSqlBuffer.append("BIRTH_DT,\n");
        extractSqlBuffer.append("JOB_TITLE,\n");
        extractSqlBuffer.append("NATIONALITY,\n");
        extractSqlBuffer.append("PER_TITLE,\n");
        extractSqlBuffer.append("MARRIAGE_STATUS,\n");
        extractSqlBuffer.append("DATA_ACTIVE_FLG,\n");
        extractSqlBuffer.append("SOURCE_ID,\n");
        extractSqlBuffer.append("ETL_INSERT_TIME,\n");
        extractSqlBuffer.append("ETL_UPDATE_TIME,\n");
        extractSqlBuffer.append("SC_TYPE_RFM\n");
        extractSqlBuffer.append(" FROM T_DW_D_FFP ");
        String extractSql = extractSqlBuffer.toString();

        TableResult result = tEnv.executeSql(extractSql
        );

        result.print();


    }
}
