-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    t1.MTM_CARD_NUM  AS TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_LYX_LY_MTMEMBER t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                t1.MTM_CARD_NUM = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.MTM_CARD_NUM IS NOT NULL AND t1.MTM_CARD_NUM != '';

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表-MTM_CARD_NUM
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    t1.MTM_CARD_NUM AS STRONGID,
    'LYC' AS STRONGID_TYPE,

    IFNULL(tds.TID, t1.MTM_CARD_NUM) TID,

    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_LYX_LY_MTMEMBER t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                t1.MTM_CARD_NUM= tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND t1.MTM_CARD_NUM IS NOT NULL AND t1.MTM_CARD_NUM != '';

-- 第三步：模拟IDMapping写入T_DIM_STRONGID表-MAIN_ID_NUM
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    t1.MAIN_ID_NUM AS STRONGID,
    IFNULL(sid_type.CFG_VALUE, t1.MAIN_ID_TYPE) AS STRONGID_TYPE,

    -- TID：使用会员卡号加密
    IFNULL(tds.TID, t1.MTM_CARD_NUM) TID,

    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_LYX_LY_MTMEMBER t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                t1.MTM_CARD_NUM = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        -- 证件类型标准化
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid_type ON t1.MAIN_ID_TYPE = sid_type.CFG_CODE
        AND sid_type.CFG_TYPE = 'DOCUMENT_TYPE' AND sid_type.CFG_TYPE_CHANNEL = 'LUYAN_TRIP'
WHERE t1.ETL_DATE >= @ETL_DATE
  AND t1.MAIN_ID_NUM IS NOT NULL AND t1.MAIN_ID_NUM != '';

-- 第四步：处理手机号强ID映射（符合条件的手机号）
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    -- 手机号作为STRONGID
    t1.MTM_MOBILE  AS STRONGID,

    -- STRONGID_TYPE为'PHONE'
    'PHONE' AS STRONGID_TYPE,

    -- 对应的TID
    IFNULL(tds.TID, t1.MTM_CARD_NUM) as TID,

    1 as STRONGID_STATUS,
    now() AS CREATE_TIME,
    now() AS  UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_LYX_LY_MTMEMBER t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                t1.MTM_CARD_NUM = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  -- 条件1：实名认证标识是已认证(0)且认证方式不为LIP认证(5)的手机号
  AND (
        (t1.REALNAME_ATTESTATION = '0' AND t1.ATTESTATION_MODE != '5')
        OR
        -- 条件2：认证方式为LIP认证(5)同时三要素认证结果是匹配(0)的手机号
        (t1.REALNAME_ATTESTATION = '0' AND t1.ATTESTATION_MODE = '5' AND t1.LIP_ATTESTATION = '0')
    )
  -- 确保手机号不为空
  AND t1.MTM_MOBILE IS NOT NULL AND t1.MTM_MOBILE != '';

