-- TRP（FTP）写入出票客票事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第三步：写入出票客票事实表
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：出票日期(YYYYMMDD格式) + 票号(删除横杠)
    CONCAT(
            COALESCE(DATE_FORMAT(t1.TICKETING_DATE, '%Y%m%d'), ''),
            REPLACE(COALESCE(t1.TICKET_NUMBER, ''), '-', '')
        ) AS PK_ID,

    t1.ORDER_NUMBER AS AK_ORDERNUM,
    -- 预订渠道标准化
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.CONTACT_PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 源系统最后更新时间
    t1.PAYMENT_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
    -- 预订渠道标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.TICKET_NUMBER IS NOT NULL
  AND t1.TICKETING_DATE IS NOT NULL;



-- trp-数仓写入出票客票表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.ORDER_USER IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.ORDER_USER IS NOT NULL;

-- 第三步：写入出票客票事实表
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    CONTACT_NAME,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：出票日期(YYYYMMDD格式) + 票号(删除横杠)
    CONCAT(
            DATE_FORMAT(t1.TK_TIME, '%Y%m%d'),
            REPLACE(COALESCE(t1.TICKET_NO, ''), '-', '')
        ) AS PK_ID,

    t1.ORDER_NO AS AK_ORDERNUM,
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    t1.PAY_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.TICKET_NO IS NOT NULL
  AND t1.TK_TIME IS NOT NULL;

-- 大客户差旅写入出票客票事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        INNER JOIN ODS_PROD.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT s ON o.ID = s.AIR_ORDER
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL
  AND s.TICKET_NUM IS NOT NULL
  AND TRIM(s.TICKET_NUM) <> ''
  AND o.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND rc.CERT_NO IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, rc.CERT_TYPE) AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        INNER JOIN ODS_PROD.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT s ON o.ID = s.AIR_ORDER
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON rc.CERT_TYPE = sid.CFG_CODE
        AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL = 'KEY_ACCOUNT_TRAVEL'
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL
  AND s.TICKET_NUM IS NOT NULL
  AND TRIM(s.TICKET_NUM) <> ''
  AND o.ETL_DATE >= @ETL_DATE
  AND rc.CERT_NO IS NOT NULL;

-- 第三步：写入出票客票事实表（正常时间）
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：出票日期+票号
    CONCAT(
            COALESCE(DATE_FORMAT(o.TICKET_OUT_DATE, '%Y%m%d'), ''),
            REPLACE(COALESCE(s.TICKET_NUM, ''), '-', '')
        ) AS PK_ID,

    o.ORDER_NO AS AK_ORDERNUM,

    -- 预订渠道标准化
    'SCSME' AS AK_CHANNEL,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         INNER JOIN ODS_PROD.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT s ON o.ID = s.AIR_ORDER
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL
  AND s.TICKET_NUM IS NOT NULL
  AND TRIM(s.TICKET_NUM) <> ''
  AND o.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.CREATE_TIME IS NOT NULL;

-- 第四步：23:00:00-00:00:00的订单需要T+1日期
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：出票日期+票号
    CONCAT(
            DATE_FORMAT(DATE_ADD(o.TICKET_OUT_DATE, INTERVAL 1 DAY), '%Y%m%d'),
            REPLACE(COALESCE(s.TICKET_NUM, ''), '-', '')
        ) AS PK_ID,

    o.ORDER_NO AS AK_ORDERNUM,

    'SCSME' AS AK_CHANNEL,

    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

    o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         INNER JOIN ODS_PROD.T_ODS_DKHCL_AIR_ORDER_PASSENGER_SEGMENT s ON o.ID = s.AIR_ORDER
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL
  AND s.TICKET_NUM IS NOT NULL
  AND TRIM(s.TICKET_NUM) <> ''
  AND o.ETL_DATE >= @ETL_DATE
  -- 23:00:00-00:00:00时间段
  AND HOUR(o.CREATE_TIME) = 23
  AND o.PNR IS NOT NULL
  AND o.CREATE_TIME IS NOT NULL;

-- 客服白屏-写入机票-出票-客票级事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_KFBP_BUS_FARE_TICKET TK
        LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_ORDER BO ON TK.ORDER_PKID = BO.PKID
        LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_FLIGHT BFT ON TK.ORDER_PKID = BFT.ORDER_PKID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE BO.IS_FICTITIOUS_ORDER = 0
  AND TK.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND BO.CUR_TEL IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_KFBP_BUS_FARE_TICKET TK
        LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_ORDER BO ON TK.ORDER_PKID = BO.PKID
        LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_FLIGHT BFT ON TK.ORDER_PKID = BFT.ORDER_PKID
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE BO.IS_FICTITIOUS_ORDER = 0
  AND TK.ETL_DATE >= @ETL_DATE
  AND BO.CUR_TEL IS NOT NULL;

-- 第三步：写入出票客票事实表
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    CONTACT_LANDLINE_MOBILE_NUMBER,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：创建日期(YYYYMMDD格式) + 票号(删除横杠)
    CONCAT(
            DATE_FORMAT(TK.CREATE_DATE, '%Y%m%d'),
            REPLACE(COALESCE(TK.TICKET_NO, ''), '-', '')
        ) AS PK_ID,

    BO.ORDER_SN AS AK_ORDERNUM,
    'SCWHP' AS AK_CHANNEL,  -- 写死：SCWHP

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CONTACT_MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,
    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(BO.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 联系人固定电话
    COALESCE(BO.CONTACT_PHONE, '') AS CONTACT_LANDLINE_MOBILE_NUMBER,

    -- 源系统最后更新时间
    TK.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_KFBP_BUS_FARE_TICKET TK
         LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_ORDER BO ON TK.ORDER_PKID = BO.PKID
         LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_FLIGHT BFT ON TK.ORDER_PKID = BFT.ORDER_PKID
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE BO.IS_FICTITIOUS_ORDER = 0
  AND TK.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND TK.TICKET_NO IS NOT NULL
  AND TK.CREATE_DATE IS NOT NULL;


-- 第四步：特殊时间段每天23点这一个小时的订单需要T，T+1
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(
    PK_ID,
    AK_ORDERNUM,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    CONTACT_LANDLINE_MOBILE_NUMBER,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：创建日期(YYYYMMDD格式) + 票号(删除横杠)
    CONCAT(
            DATE_FORMAT(DATE_ADD(TK.CREATE_DATE, INTERVAL 1 DAY), '%Y%m%d'),
            REPLACE(COALESCE(TK.TICKET_NO, ''), '-', '')
        ) AS PK_ID,

    BO.ORDER_SN AS AK_ORDERNUM,
    'SCWHP' AS AK_CHANNEL,  -- 写死：SCWHP

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CONTACT_MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(BO.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 联系人固定电话
    COALESCE(BO.CONTACT_PHONE, '') AS CONTACT_LANDLINE_MOBILE_NUMBER,

    -- 源系统最后更新时间
    TK.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_KFBP_BUS_FARE_TICKET TK
         LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_ORDER BO ON TK.ORDER_PKID = BO.PKID
         LEFT JOIN ODS_PROD.T_ODS_KFBP_BUS_FLIGHT BFT ON TK.ORDER_PKID = BFT.ORDER_PKID
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE BO.IS_FICTITIOUS_ORDER = 0
  AND HOUR(TK.CREATE_DATE) = 23
  AND TK.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND TK.TICKET_NO IS NOT NULL
  AND TK.CREATE_DATE IS NOT NULL;


-- 标准数据表TB_TCN_DATA-机票-出票-客票级事实表
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(PK_ID, AK_DIMARK, AK_FAREBASIS, AK_CURRENCY, FARE_CURAMOUNT, FARE_AMOUNT, SYSTEM_CREATETIME)
SELECT PK_ID,
       AK_DIMARK,
       AK_FAREBASIS,
       AK_CURRENCY,
       FARE_CURAMOUNT,
       FARE_AMOUNT,
       SYSTEM_CREATETIME
FROM (
         SELECT
             -- 主键：TK_DATE + TK_AIR + TK_NUM
             CONCAT(

                     COALESCE(DATE_FORMAT(TK_DATE, '%Y%m%d'), ''),
                     COALESCE(TK_AIR, ''),
                     COALESCE(TK_NUM, '')
                 )     AS PK_ID,
             -- 国内国际标识
             STATID    AS AK_DIMARK,
             -- 运价基础
             CP_STR    AS AK_FAREBASIS,
             -- 销售币种
             FARE_TYPE AS AK_CURRENCY,
             -- 票面价格
             FARE_TOL  AS FARE_CURAMOUNT,
             -- EQFPN字段
             EQFPN     AS FARE_AMOUNT,
             -- 系统创建时间
             NOW()     AS SYSTEM_CREATETIME
         FROM ODS_PROD.T_ODS_BZSJ_TB_TCN_DATA
         WHERE ETL_DATE >= @ETL_DATE
           AND TK_DATE IS NOT NULL
           AND TK_AIR IS NOT NULL
           AND TK_NUM IS NOT NULL
     ) AS subquery_alias
WHERE PK_ID IS NOT NULL
  AND PK_ID != '';

-- 1、机票-出票-客票级事实表
-- 是否为自己订票
-- "1、机票预订-航段级、机票出票-客票级、机票出票-航段级：判断乘机人TID是否与预订人TID一致。如果一致则为是。否则为否。
-- 2、成行-航段级，退票-航段级：通过“主键”“出票-航段级反写”"
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(PK_ID, SELF_BOOKING, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT t.PK_ID,
       CASE
           WHEN t.FK_BOOKING_USER_TID = t.FK_BOOKING_USER_ORIGIN_ID
               THEN 1
           ELSE 0
           END AS SELF_BOOKING,
       NOW()   AS SYSTEM_CREATETIME,
       NOW()   AS SYSTEM_LAST_UPDATETIME
FROM DWD_PROD.T_DWD_TICKING_TIC_FACT t
WHERE t.FK_BOOKING_USER_TID is not null
  and t.DATA_ACTIVE = 1
  and t.FK_BOOKING_USER_ORIGIN_ID is not null
  and (t.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR t.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));

-- 2、机票-出票-客票级事实表
-- 是否首次出票
-- 该TID作为预订人，历史至今，第一次出现（机票出票-客票级）则为是。否则为否
-- 机票-出票-航段级：通过“票号+出票日期”查询机票-出票-客票级 对应字段，写入该值。
-- 注意：历史数据迁移问题"
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(PK_ID, AK_FIRST_ISSUE, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT PK_ID,
       CASE
           WHEN ROW_NUMBER() OVER (
               PARTITION BY FK_BOOKING_USER_TID
               ORDER BY FK_TICKETING_DATE, FK_TICKETING_TIME
               ) = 1 THEN 1
           ELSE 0
           END AS AK_FIRST_ISSUE,
       NOW()   AS SYSTEM_CREATETIME,
       NOW()   AS SYSTEM_LAST_UPDATETIME
FROM DWD_PROD.T_DWD_TICKING_TIC_FACT
WHERE FK_BOOKING_USER_TID IS NOT NULL
  and DATA_ACTIVE = 1
  AND FK_TICKETING_DATE IS NOT NULL
  AND FK_TICKETING_TIME IS NOT NULL;




