-- 常旅客FTP--FFP_DBRQ_YYYYMMDD（YYYYMMDD为日期）-sheet2（达标人群(无需报名)数据表）
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY))) AS TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_CLK_QUALIFIED_NO_REGISTRATION t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY))) STRONGID,
    'FFP' STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_CLK_QUALIFIED_NO_REGISTRATION t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE>=@ETL_DATE;

-- 第三步：写入活动报名事实表
INSERT INTO DWD_PROD.T_DWD_ACT_SIGNUP_FACT
(
    PK_ID,
    PRODUCT_ID,
    PRODUCT_CN_NAME,
    MEMBER_CARD,
    IS_QUALIFIED,
    MEMBER_TID,
    SIGNUP_TYPE,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    CONCAT(t1.ACTIVITY_CODE, TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY)))) AS PK_ID,
    t1.ACTIVITY_CODE AS PRODUCT_ID,
    t1.ACTIVITY_CHINESE_NAME AS PRODUCT_CN_NAME,
    TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY))) AS MEMBER_CARD,
    '1' AS IS_QUALIFIED,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY)))) AS MEMBER_TID,
    'FM' AS SIGNUP_TYPE,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME
FROM
    ODS_PROD.T_ODS_CLK_QUALIFIED_NO_REGISTRATION t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(t1.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE>=@ETL_DATE;


-- FFP_DBRQ_YYYYMMDD（YYYYMMDD为日期）-sheet1（达标人群(报名)数据表）
-- T_DWD_ACT_SIGNUP_FACT-IS_QUALIFIED
-- SET @ETL_DATE = '2025-10-21';

INSERT INTO DWD_PROD.T_DWD_ACT_SIGNUP_FACT
(PK_ID, IS_QUALIFIED)
SELECT T1.PK_ID,
       1 AS IS_QUALIFIED
FROM DWD_PROD.T_DWD_ACT_SIGNUP_FACT T1
         JOIN ODS_PROD.T_ODS_CLK_QUALIFIED_REGISTRATION T2
              ON T1.PRODUCT_CN_NAME = T2.ACTIVITY_CHINESE_NAME
                  AND T1.MEMBER_CARD =
                      TO_BASE64(SM4_ENCRYPT(TRIM(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(T2.MEMBER_CARD_NUMBER), FROM_BASE64(@SM4_KEY)), '[^0-9]', '')), FROM_BASE64(@SM4_KEY)))

WHERE T2.ETL_DATE >= @ETL_DATE
  AND T1.PRODUCT_CN_NAME IS NOT NULL
  AND T1.MEMBER_CARD IS NOT NULL
  AND T2.MEMBER_CARD_NUMBER IS NOT NULL
  AND T2.ACTIVITY_CHINESE_NAME IS NOT NULL;
