-- 常客-注册-业务事实表 - 常旅客注册表渠道标签补写（含扫码覆写）
-- 数据来源：T_DWD_MEMBER_REGISTER_FACT（仅处理 FROM_MILE_REGISTER = 1 的记录）
-- 只更新4个渠道标签字段，其他字段保持不变（Doris使用INSERT方式，DUPLICATE KEY模型会自动处理）
-- 写入顺序：第3步（在老数据号段匹配、会员天地完成后执行）

INSERT INTO DWD_PROD.T_DWD_MEMBER_REGISTER_FACT
(PK_ID, DEV_CHANNEL_ONE, DEV_CHANNEL_TWO, DEV_CHANNEL_THREE, DEV_CHANNEL_FOUR, SYSTEM_LAST_UPDATETIME)
WITH scan_distinct AS (
    SELECT DISTINCT FFP_REGISTER_INFO_ID
    FROM ODS_PROD.T_ODS_CLK_FFP_REGISTER_SCAN
    WHERE ETL_DATE = @ETL_DATE
),
scan_match AS (
    SELECT sd.FFP_REGISTER_INFO_ID, info.FCARD
    FROM scan_distinct sd
    JOIN ODS_PROD.T_ODS_CLK_FFP_REGISTER_INFO info
      ON info.ID = sd.FFP_REGISTER_INFO_ID
     AND info.SEND_FLAG = 'Y'
     AND info.SEND_STATUS = '1'
)
SELECT
    fact.PK_ID AS PK_ID,
    CASE
        WHEN scan.FFP_REGISTER_INFO_ID IS NOT NULL THEN 'XXFZ'
        WHEN reg.reg_date >= '2023-12-01' AND reg.reg_date <= '2025-09-02'
             AND fact.FROM_CRM_MEMBER = 1 THEN 'XXFZ'              -- 机上发展成功（在会员天地中）
        WHEN reg.reg_date >= '2023-12-01' AND reg.reg_date <= '2025-09-02'
             AND fact.FROM_CRM_MEMBER IS NULL AND fact.FROM_INTEGRATION IS NULL THEN 'XXFZ' -- 常旅客系统发展成功
        WHEN dict.LEVEL1_CODE IS NOT NULL AND COALESCE(fact.DEV_CHANNEL_ONE, '') = '' THEN dict.LEVEL1_CODE
        ELSE fact.DEV_CHANNEL_ONE
    END AS DEV_CHANNEL_ONE,
    CASE
        WHEN scan.FFP_REGISTER_INFO_ID IS NOT NULL THEN 'FFP_CLK'
        WHEN reg.reg_date >= '2023-12-01' AND reg.reg_date <= '2025-09-02'
             AND fact.FROM_CRM_MEMBER = 1 THEN 'FFP_JS'            -- 机上发展成功（在会员天地中）
        WHEN reg.reg_date >= '2023-12-01' AND reg.reg_date <= '2025-09-02'
             AND fact.FROM_CRM_MEMBER IS NULL AND fact.FROM_INTEGRATION IS NULL THEN 'FFP_CLK' -- 常旅客系统发展成功
        WHEN dict.LEVEL2_CODE IS NOT NULL AND COALESCE(fact.DEV_CHANNEL_TWO, '') = '' THEN dict.LEVEL2_CODE
        ELSE fact.DEV_CHANNEL_TWO
    END AS DEV_CHANNEL_TWO,
    CASE
        WHEN scan.FFP_REGISTER_INFO_ID IS NOT NULL THEN 'FFP_JSSM'
        WHEN dict.LEVEL3_CODE IS NOT NULL AND COALESCE(fact.DEV_CHANNEL_THREE, '') = '' THEN dict.LEVEL3_CODE
        ELSE fact.DEV_CHANNEL_THREE
    END AS DEV_CHANNEL_THREE,
    CASE
        WHEN dict.LEVEL4_CODE IS NOT NULL AND COALESCE(fact.DEV_CHANNEL_FOUR, '') = '' THEN dict.LEVEL4_CODE
        ELSE fact.DEV_CHANNEL_FOUR
    END AS DEV_CHANNEL_FOUR,
    NOW() AS SYSTEM_LAST_UPDATETIME
FROM DWD_PROD.T_DWD_MEMBER_REGISTER_FACT fact
LEFT JOIN scan_match scan
    ON fact.PK_ID = scan.FCARD
-- 基于 OPERATE_DEPT 匹配渠道字典（优先级：4级code/name -> 3级code/name -> 2级code/name -> 1级code/name）
LEFT JOIN (
    SELECT 
        OPERATE_DEPT,
        LEVEL1_CODE,
        LEVEL2_CODE,
        LEVEL3_CODE,
        LEVEL4_CODE,
        ROW_NUMBER() OVER (PARTITION BY OPERATE_DEPT ORDER BY 
            CASE 
                WHEN LEVEL4_CODE IS NOT NULL THEN 4
                WHEN LEVEL3_CODE IS NOT NULL THEN 3
                WHEN LEVEL2_CODE IS NOT NULL THEN 2
                WHEN LEVEL1_CODE IS NOT NULL THEN 1
                ELSE 0 END DESC
        ) AS rn
    FROM (
        SELECT LEVEL4_CODE AS OPERATE_DEPT, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
        UNION ALL SELECT LEVEL4_NAME, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
        UNION ALL SELECT LEVEL3_CODE, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
        UNION ALL SELECT LEVEL3_NAME, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
        UNION ALL SELECT LEVEL2_CODE, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
        UNION ALL SELECT LEVEL2_NAME, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
        UNION ALL SELECT LEVEL1_CODE, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
        UNION ALL SELECT LEVEL1_NAME, LEVEL1_CODE, LEVEL2_CODE, LEVEL3_CODE, LEVEL4_CODE FROM DIM_PROD.T_DIM_FFP_CHANNEL_DICT WHERE FFP_DEPT_FLAG = '1'
    ) dict_all
) dict ON fact.DEV_DEPARTMENT = dict.OPERATE_DEPT AND dict.rn = 1
LEFT JOIN (
    SELECT PK_ID,
           COALESCE(FK_REGISTER_DATE, SUBSTRING(SYSTEM_CREATETIME,1,10)) AS reg_date
    FROM DWD_PROD.T_DWD_MEMBER_REGISTER_FACT
) reg ON reg.PK_ID = fact.PK_ID
WHERE fact.PK_ID IS NOT NULL
  AND fact.FROM_MILE_REGISTER = 1
  AND (
        reg.reg_date = @ETL_DATE
     OR fact.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
     OR fact.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
      );

INSERT INTO DIM_PROD.T_DIM_FFP_DIM
(SYSTEM_KEY, DEV_CHANNEL_ONE, DEV_CHANNEL_TWO, DEV_CHANNEL_THREE, DEV_CHANNEL_FOUR, UPDATE_TIME)
SELECT
    fact.PK_ID AS SYSTEM_KEY,
    fact.DEV_CHANNEL_ONE,
    fact.DEV_CHANNEL_TWO,
    fact.DEV_CHANNEL_THREE,
    fact.DEV_CHANNEL_FOUR,
    NOW() AS UPDATE_TIME
FROM DWD_PROD.T_DWD_MEMBER_REGISTER_FACT fact
WHERE fact.PK_ID IS NOT NULL
  AND fact.FROM_MILE_REGISTER = 1
  AND (fact.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR fact.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'))
  AND (fact.DEV_CHANNEL_ONE IS NOT NULL
    OR fact.DEV_CHANNEL_TWO IS NOT NULL
    OR fact.DEV_CHANNEL_THREE IS NOT NULL
    OR fact.DEV_CHANNEL_FOUR IS NOT NULL);