-- 常客-注册-业务事实表  -  是否为高价值发展会员
INSERT INTO DWD_PROD.T_DWD_MEMBER_REGISTER_FACT
(PK_ID, IS_HIGH_VALUE_DEVELOPER)
SELECT PK_ID,
       CASE WHEN h.ID_NUM IS NOT NULL THEN TRUE ELSE FALSE END AS IS_HIGH_VALUE_DEVELOPER
FROM DWD_PROD.T_DWD_MEMBER_REGISTER_FACT r
         LEFT JOIN ODS_PROD.T_ODS_LYGJ_HP_PSG_INFO h
                   ON h.ID_NUM = r.CERT_NUMBER
                       AND DATE_FORMAT(h.FLT_DATE, '%Y-%m-%d') = DATE_FORMAT(r.MEMBER_REGIST_FLT_DATE, '%Y-%m-%d')
WHERE r.DEV_CHANNEL_ONE = 'XXFZ'
  AND (r.SYSTEM_CREATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000')
    OR r.SYSTEM_LAST_UPDATETIME >= CONCAT(@ETL_DATE, ' 00:00:00.000'));
