-- 常客-注册-业务事实表 - 会员天地渠道标签全量补写
-- 数据来源：T_DWD_MEMBER_REGISTER_FACT（仅处理 FROM_CRM_MEMBER = 1 的记录）
-- 只更新4个渠道标签字段，其他字段保持不变（Doris使用INSERT方式，DUPLICATE KEY模型会自动处理）
-- 全量版本：不依赖 @ETL_DATE

INSERT INTO DWD_PROD.T_DWD_MEMBER_REGISTER_FACT
(PK_ID, DEV_CHANNEL_ONE, DEV_CHANNEL_TWO, DEV_CHANNEL_THREE, DEV_CHANNEL_FOUR, SYSTEM_LAST_UPDATETIME)
SELECT
    fact.PK_ID AS PK_ID,
    -- 渠道映射：B类渠道（线下发展）优先，然后是A类渠道（线上发展）
    CASE
        -- B类渠道：线下发展
        WHEN fact.CRM_MEMBER_CHANNEL = 'SCLYGJ' THEN 'XXFZ'  -- 机上会员发展
        WHEN fact.CRM_MEMBER_CHANNEL = 'clkFFP' THEN 'XXFZ'  -- 常旅客系统
        -- A类渠道：线上发展
        WHEN fact.CRM_MEMBER_CHANNEL IN ('SC_LYX_LYZ', 'wechatmini', 'APP', 'SCAPP', 'SCGW', 'hytd@pc', 'hytd@h5', 'XCXHYTD', 'SCZSF', 'GWHYTD') THEN 'XSFZ'
        ELSE NULL
    END AS DEV_CHANNEL_ONE,
    CASE
        -- B类渠道：线下发展
        WHEN fact.CRM_MEMBER_CHANNEL = 'SCLYGJ' THEN 'FFP_JS'  -- 机上会员发展
        WHEN fact.CRM_MEMBER_CHANNEL = 'clkFFP' THEN 'FFP_CLK'  -- 常旅客系统
        -- A类渠道：线上发展
        WHEN fact.CRM_MEMBER_CHANNEL = 'SC_LYX_LYZ' THEN 'FFP_LYX'
        WHEN fact.CRM_MEMBER_CHANNEL = 'wechatmini' THEN 'FFP_WECHAT'
        WHEN fact.CRM_MEMBER_CHANNEL IN ('APP', 'SCAPP') THEN 'FFP_ZSF'
        WHEN fact.CRM_MEMBER_CHANNEL = 'SCGW' THEN 'FFP_GW'
        WHEN fact.CRM_MEMBER_CHANNEL IN ('hytd@pc', 'hytd@h5', 'XCXHYTD', 'SCZSF', 'GWHYTD') THEN 'FFP_HYTD'
        ELSE NULL
    END AS DEV_CHANNEL_TWO,
    CASE
        -- B类渠道的三级、四级渠道通过后续逻辑补全，此处先设为NULL
        -- A类渠道：线上发展
        WHEN fact.CRM_MEMBER_CHANNEL = 'SC_LYX_LYZ' THEN 'SC_LYX_LYZ'
        WHEN fact.CRM_MEMBER_CHANNEL = 'wechatmini' THEN 'wechatmini'
        WHEN fact.CRM_MEMBER_CHANNEL = 'APP' THEN 'APP'
        WHEN fact.CRM_MEMBER_CHANNEL = 'SCAPP' THEN 'SCAPP'
        WHEN fact.CRM_MEMBER_CHANNEL = 'SCGW' THEN 'SCGW'
        WHEN fact.CRM_MEMBER_CHANNEL = 'hytd@pc' THEN 'hytd@pc'
        WHEN fact.CRM_MEMBER_CHANNEL = 'hytd@h5' THEN 'hytd@h5'
        WHEN fact.CRM_MEMBER_CHANNEL = 'XCXHYTD' THEN 'XCXHYTD'
        WHEN fact.CRM_MEMBER_CHANNEL = 'SCZSF' THEN 'SCZSF'
        WHEN fact.CRM_MEMBER_CHANNEL = 'GWHYTD' THEN 'GWHYTD'
        ELSE NULL
    END AS DEV_CHANNEL_THREE,
    NULL AS DEV_CHANNEL_FOUR,
    NOW() AS SYSTEM_LAST_UPDATETIME
FROM DWD_PROD.T_DWD_MEMBER_REGISTER_FACT fact
WHERE fact.PK_ID IS NOT NULL
  AND fact.FROM_CRM_MEMBER = 1;

-- 同步到用户维表-常客信息维表（全量）
INSERT INTO DIM_PROD.T_DIM_FFP_DIM
(SYSTEM_KEY, DEV_CHANNEL_ONE, DEV_CHANNEL_TWO, DEV_CHANNEL_THREE, DEV_CHANNEL_FOUR, UPDATE_TIME, CREATE_TIME)
SELECT
    fact.PK_ID AS SYSTEM_KEY,
    fact.DEV_CHANNEL_ONE,
    fact.DEV_CHANNEL_TWO,
    fact.DEV_CHANNEL_THREE,
    fact.DEV_CHANNEL_FOUR,
    NOW() AS UPDATE_TIME,
    NOW() AS CREATE_TIME
FROM DWD_PROD.T_DWD_MEMBER_REGISTER_FACT fact
WHERE fact.PK_ID IS NOT NULL
  AND fact.FROM_CRM_MEMBER = 1
  AND (fact.DEV_CHANNEL_ONE IS NOT NULL
   OR fact.DEV_CHANNEL_TWO IS NOT NULL
   OR fact.DEV_CHANNEL_THREE IS NOT NULL
   OR fact.DEV_CHANNEL_FOUR IS NOT NULL);

