-- 用户维表 - 从常客注册事实表同步渠道标签
-- 数据来源：T_DWD_MEMBER_REGISTER_FACT
-- 通过常客卡号关联，将事实表的渠道标签同步到用户维表
-- 只更新4个渠道标签字段，其他字段保持不变（Doris使用INSERT方式，DUPLICATE KEY模型会自动处理）

INSERT INTO DIM_PROD.T_DIM_USER_DIM
(PK_ID, DEV_CHANNEL_ONE, DEV_CHANNEL_TWO, DEV_CHANNEL_THREE, DEV_CHANNEL_FOUR, UPDATE_TIME)
SELECT
    u.PK_ID,
    fact.DEV_CHANNEL_ONE,
    fact.DEV_CHANNEL_TWO,
    fact.DEV_CHANNEL_THREE,
    fact.DEV_CHANNEL_FOUR,
    NOW() AS UPDATE_TIME
FROM DWD_PROD.T_DWD_MEMBER_REGISTER_FACT fact
INNER JOIN DIM_PROD.T_DIM_USER_DIM u
    ON u.FREQUENT_TRAVELER_CARDNO = fact.PK_ID
WHERE (fact.DEV_CHANNEL_ONE IS NOT NULL
   OR fact.DEV_CHANNEL_TWO IS NOT NULL
   OR fact.DEV_CHANNEL_THREE IS NOT NULL
   OR fact.DEV_CHANNEL_FOUR IS NOT NULL)
  AND (DATE(fact.SYSTEM_CREATETIME) = @ETL_DATE
   OR DATE(fact.SYSTEM_LAST_UPDATETIME) = @ETL_DATE);

