-- 任务名DJKSC_PAYMENT_INFO2DWD
-- 升舱整合平台-登机口升舱 登机口升舱数据T+1入库后，取PAYMENT_INFO订单支付信息表UPDATE_TIME是T时间的，PAY_STATE不等于0的，连表：PAYMENT_INFO订单支付信息表的ORDER_NO=ORDER_INFO主订单表的ORDER_NO。
--现金情况和券支付：主键均为：数据源代号SCSDJ+PAYMENT_INFO.ORDER_NO+BILL_NO
--T_ODS_DJKSC_PAYMENT_INFO T_ODS_DJKSC_ORDER_INFO
--1、写入T_DIM_TID_SET
--2、模拟IDMapping写入T_DIM_STRONGID表
--3、写入支付流水号表：现金/券
--SET batch_size = 4096;
--SET @ETL_DATE='2025-10-18'
BEGIN;
--1、不存在的TID写入T_DIM_TID_SET表
INSERT
    INTO
    DIM_TEST.T_DIM_TID_SET
    (TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,         --预订人TID
    @ETL_DATE ETL_DATE,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    1 TID_STATUS
FROM ODS_TEST.T_ODS_DJKSC_PAYMENT_INFO t1
    INNER JOIN ODS_TEST.T_ODS_DJKSC_ORDER_INFO t2 
      ON 
         t1.ORDER_NO=t2.ORDER_NO
    LEFT JOIN DIM_TEST.T_DIM_STRONGID tds 
    ON
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))= tds.STRONGID
	    AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE=@ETL_DATE
AND t1.PAY_STATE is not NULL
AND t1.PAY_STATE=2
AND t1.PAY_TYPE<>8
    AND tds.TID is null;
--模拟IDMapping写入T_DIM_STRONGID表
--2、写入证件类型+证件号强ID
INSERT
    INTO
    DIM_TEST.T_DIM_STRONGID
    (STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE)
SELECT
    DISTINCT TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'OT' STRONGID_TYPE,
    IFNULL(tds.TID,TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    CURRENT_TIMESTAMP(3) CREATE_TIME,
    CURRENT_TIMESTAMP(3) UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM ODS_TEST.T_ODS_DJKSC_PAYMENT_INFO t1
    INNER JOIN ODS_TEST.T_ODS_DJKSC_ORDER_INFO t2 
      ON 
         t1.ORDER_NO=t2.ORDER_NO
    LEFT JOIN DIM_TEST.T_DIM_STRONGID tds 
    ON
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))= tds.STRONGID
	    AND tds.STRONGID_STATUS = 1
WHERE t1.ETL_DATE=@ETL_DATE
AND t1.PAY_STATE is not NULL
AND t1.PAY_STATE=2
AND t1.PAY_TYPE<>8
;
COMMIT;

--写入支付流水号表
INSERT
    INTO
    DWD_TEST.T_DWD_PAYDETAILS_ORD_FACT(
    PK_ID
    ,BUSINESS_ORDER_ID
    ,PAY_NO
    ,FK_BOOKING_USER_TID
    ,FK_BOOKING_USER_ORIGIN_ID
    ,FK_BOOKING_DATE
    ,FK_BOOKING_TIME
    ,FK_PAY_DATE
    ,FK_PAY_TIME
    ,AK_PAY_CHANNEL
    ,AK_PAY_METHOD
    ,COUPON_CATEGORY
    ,AK_CASH_PAY_PLATFORM
    ,AK_PAY_STATUS
    ,AK_CASH_TYPE
    ,CASH_AMOUNT
    ,AK_COUPON
    ,COUPON_COUNT
    ,COUPON_NO
    ,COUPON_NAME
    ,SOURCE_LAST_UPDATETIME
    ,SYSTEM_CREATETIME
    ,SYSTEM_LAST_UPDATETIME
    ,ORD_COUNT
)
SELECT
    CONCAT('SCSDJ',t1.ORDER_NO,t1.BILL_NO) PK_ID
    ,t1.ORDER_NO BUSINESS_ORDER_ID
    ,t1.BILL_NO PAY_NO
    ,IFNULL(tds.TID,TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) FK_BOOKING_USER_TID
    ,TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) FK_BOOKING_USER_ORIGIN_ID
    ,t2.CREATE_TIME FK_BOOKING_DATE
    ,t2.CREATE_TIME FK_BOOKING_TIME
    ,t1.PAY_TIME FK_PAY_DATE
    ,t1.PAY_TIME FK_PAY_TIME
    ,'SCSDJ' AK_PAY_CHANNEL
    ,CASE WHEN t1.PAY_TYPE IN('0','8','9','4','5','6','7') THEN 'CSH' WHEN t1.PAY_TYPE IN('1','2','3') THEN 'VCH' END AS AK_PAY_METHOD
    ,CASE WHEN t1.PAY_TYPE IN('1','2','3') THEN 'UPG' ELSE null END AS COUPON_CATEGORY
    ,sid1.CFG_VALUE AK_CASH_PAY_PLATFORM
    ,IFNULL(sid2.CFG_VALUE, t1.PAY_STATE) AK_PAY_STATUS
    ,CASE WHEN t1.PAY_TYPE IN('0','4','5','6','7','9') THEN 'CNY' ELSE null END AS AK_CASH_TYPE
    ,CASE WHEN t1.PAY_TYPE IN('0','4','5','6','7','9') THEN t1.PAY_AMOUNT ELSE null END AS CASH_AMOUNT
    ,CASE WHEN t1.PAY_TYPE IN('1','2','3') THEN true ELSE null END AS AK_COUPON
    ,CASE WHEN t1.PAY_TYPE IN('1','2','3') THEN 1 ELSE null END AS COUPON_COUNT
    ,CASE WHEN t1.PAY_TYPE IN('1','2','3') THEN t1.PAY_WAY ELSE null END AS COUPON_NO 
    ,CASE WHEN t1.PAY_TYPE IN('1','2','3') THEN '升舱券' ELSE null END AS COUPON_NAME
    ,t1.UPDATE_TIME SOURCE_LAST_UPDATETIME                                                                                                                                                    --
    ,CURRENT_TIMESTAMP(3) SYSTEM_CREATETIME                                                                                                                                                   ----本系统创建日期时间
    ,CURRENT_TIMESTAMP(3) SYSTEM_LAST_UPDATETIME                                                                                                                                              ----本系统最后更新日期时间
    ,1 AS ORD_COUNT                                                                                                                                                                            ----支付单计数
FROM ODS_TEST.T_ODS_DJKSC_PAYMENT_INFO t1
    INNER JOIN ODS_TEST.T_ODS_DJKSC_ORDER_INFO t2 
      ON 
         t1.ORDER_NO=t2.ORDER_NO
    LEFT JOIN DIM_TEST.T_DIM_STRONGID tds 
    ON
        TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t2.CARD_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))= tds.STRONGID
	    AND tds.STRONGID_STATUS = 1
    LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid1 
      ON
        CASE WHEN t1.PAY_TYPE IN('0','4','5','6','7','9') THEN t1.PAY_TYPE ELSE NULL END = sid1.CFG_CODE
        AND sid1.CFG_TYPE = 'CASH_PAYMENT_PLATFORM'
        AND sid1.CFG_TYPE_CHANNEL = 'GATE_UPGRADE'
    LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid2 
    ON
        t1.PAY_STATE = sid2.CFG_CODE
        AND sid2.CFG_TYPE = 'PAYMENT_STATUS'
        AND sid2.CFG_TYPE_CHANNEL = 'GATE_UPGRADE' 
WHERE t1.ETL_DATE=@ETL_DATE
AND t1.PAY_STATE is not NULL
AND t1.PAY_STATE=2
AND t1.PAY_TYPE<>8
;

COMMIT;