-- 是否首次出票
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT
(PK_ID, AK_FIRST_ISSUE, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT PK_ID,
       CASE
           WHEN ROW_NUMBER() OVER (
               PARTITION BY FK_BOOKING_USER_TID
               ORDER BY FK_TICKETING_DATE, FK_TICKETING_TIME
               ) = 1 THEN 1
           ELSE 0
           END AS AK_FIRST_ISSUE,
       NOW()   AS SYSTEM_CREATETIME,
       NOW()   AS SYSTEM_LAST_UPDATETIME
FROM DWD_PROD.T_DWD_TICKING_TIC_FACT
WHERE FK_BOOKING_USER_TID IS NOT NULL
  AND FK_TICKETING_DATE IS NOT NULL
  AND FK_TICKETING_TIME IS NOT NULL
  AND DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
-- 机票出票航段级
INSERT INTO DWD_PROD.T_DWD_TICKING_SEG_FACT (PK_ID,AK_FIRST_ISSUE)
SELECT ts.PK_ID as PK_ID,tt.AK_FIRST_ISSUE as AK_FIRST_ISSUE
FROM DWD_PROD.T_DWD_TICKING_SEG_FACT ts INNER JOIN DWD_PROD.T_DWD_TICKING_TIC_FACT tt
    ON ts.AK_TICKET_NUMBER = tt.TICKET_NUMBER AND ts.FK_ISSUE_DATE = tt.FK_TICKETING_DATE
WHERE ts.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
--事务提交
commit;
