-- 是否与儿童同行
-- 机票预订航段级事实表
INSERT INTO DWD_PROD.T_DWD_BOOKING_SEG_FACT (PK_ID,AK_PEER_CHD)
SELECT
    PK_ID,
    CASE
        WHEN MAX(CASE WHEN PASSENGER_TYPE = 'CHD' THEN 1 ELSE 0 END) OVER (
            PARTITION BY FK_BOOKING_DATE, PNR_NUMBER
        ) = 1 THEN 1
        ELSE 0
        END AS AK_PEER_CHD
FROM
    DWD_PROD.T_DWD_BOOKING_SEG_FACT
WHERE DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
-- 机票预订PNR级事实表
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT (PK_ID,PEER_CHD)
SELECT
    bpf.PK_ID AS PK_ID,
    bsf.AK_PEER_CHD AS PEER_CHD
FROM
    DWD_PROD.T_DWD_BOOKING_PNR_FACT bpf INNER JOIN DWD_PROD.T_DWD_BOOKING_SEG_FACT bsf
     ON bpf.PNR_NUMBER = bsf.PNR_NUMBER AND bpf.FK_PNRCREATE_DATE =  bsf.FK_BOOKING_DATE
WHERE bpf.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
--机票出票航段级事实表
INSERT INTO DWD_PROD.T_DWD_TICKING_SEG_FACT (PK_ID,AK_PEER_CHD)
SELECT
    t.PK_ID,b.AK_PEER_CHD AS PEER_CHD
FROM DWD_PROD.T_DWD_TICKING_SEG_FACT AS t INNER JOIN DWD_PROD.T_DWD_BOOKING_SEG_FACT AS b
 ON t.AK_PNR_NUMBER = b.PNR_NUMBER AND t.FK_DEPAIRPORT = b.FK_DEPAIRPORT
  AND t.FK_SEG_DATE = b.FK_SEG_DATE AND t.FK_SEG_TIME = b.FK_SEG_TIME
AND t.CERT_NUMBER = b.CERT_NUMBER AND t.CN_NAME = b.CN_NAME AND t.CERT_NUMBER = b.CERT_NUMBER
WHERE t.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
-- 成行-航段级
INSERT INTO DWD_PROD.T_DWD_DEPART_SEG_FACT (PK_ID,PEER_CHD)
SELECT
    depart_seg.PK_ID as PK_ID,
    ticking_seg.AK_PEER_CHD as PEER_CHD
FROM
    DWD_PROD.T_DWD_DEPART_SEG_FACT depart_seg
        INNER JOIN
    DWD_PROD.T_DWD_TICKING_SEG_FACT ticking_seg
    ON
        depart_seg.PK_ID = ticking_seg.PK_ID
WHERE depart_seg.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
-- 退票-航段级
INSERT INTO DWD_PROD.T_DWD_REFUND_SEG_FACT (PK_ID,AK_PEER_CHD)
SELECT
    refund_seg.PK_ID as PK_ID,
    ticking_seg.AK_PEER_CHD as AK_PEER_CHD
FROM
    DWD_PROD.T_DWD_REFUND_SEG_FACT refund_seg
        INNER JOIN
    DWD_PROD.T_DWD_TICKING_SEG_FACT ticking_seg
    ON
        refund_seg.PK_ID = ticking_seg.PK_ID
WHERE refund_seg.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999');
--机票出票客票级事实表
INSERT INTO DWD_PROD.T_DWD_TICKING_TIC_FACT (PK_ID,AK_PEER_CHD)
SELECT
    tic.PK_ID,
    CASE
        WHEN MAX(CASE WHEN seg.AK_PEER_CHD = 1 THEN 1 ELSE 0 END) = 1 THEN 1
        ELSE 0
        END AS AK_PEER_CHD
FROM
    DWD_PROD.T_DWD_TICKING_TIC_FACT tic
        LEFT JOIN
    DWD_PROD.T_DWD_TICKING_SEG_FACT seg
    ON
        tic.TICKET_NUMBER = seg.AK_TICKET_NUMBER
            AND tic.FK_TICKETING_DATE = seg.FK_ISSUE_DATE
WHERE tic.DATA_ACTIVE_TIME  BETWEEN CONCAT(@ETL_DATE,' 00:00:00.000') AND CONCAT(@ETL_DATE,' 23:59:59.999')
GROUP BY
    tic.PK_ID,
    tic.TICKET_NUMBER,
    tic.FK_TICKETING_DATE;
--事务提交
commit;
