-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--用户维表-证件信息维表-写DWD
INSERT INTO DIM_TEST.T_DIM_CERT_DIM
(T_ID,SYSTEM_KEY,CERT_TYPE,CERT_NUMBER,IS_DIRECT_SALES_REAL_NAME_VERIFIED_CARD,IS_LY_REGIST_CARD,IS_FREQUENT_FLYER_REGISTRATION_CARD,IS_PURCHASERS_BENEFICIARY_CARD,IS_DOUYIN_PURCHASERS_BENEFICIARY_CARD,CURRENT_CERT_HIGHEST_PRIORITY,UPDATE_TIME,CREATE_TIME)
SELECT CERT_NO AS T_ID,concat(CERT_NO,sid.CFG_VALUE,CERT_NO) AS SYSTEM_KEY,sid.CFG_VALUE AS CERT_TYPE,CERT_NO AS CERT_NUMBER,
FALSE AS IS_DIRECT_SALES_REAL_NAME_VERIFIED_CARD,FALSE AS IS_LY_REGIST_CARD,FALSE AS IS_FREQUENT_FLYER_REGISTRATION_CARD,
FALSE AS IS_PURCHASERS_BENEFICIARY_CARD,FALSE AS IS_DOUYIN_PURCHASERS_BENEFICIARY_CARD,
CASE
	WHEN SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)) REGEXP '^[1-9]\\d{5}(18|19|20)\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])\\d{3}[0-9X]$' THEN TRUE
	WHEN SM4_DECRYPT(FROM_BASE64(CERT_NO), FROM_BASE64(@SM4_KEY)) REGEXP '^9(1[1-5]|2[1-3]|3[1-7]|4[1-6]|5[0-4]|6[1-5]|71|8[1-2])(\\d{3})(19|20)(\\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])(\\d{3})(\\d)$' THEN TRUE
	ELSE FALSE
END AS CURRENT_CERT_HIGHEST_PRIORITY,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE concat(CERT_NO,sid.CFG_VALUE,CERT_NO) IS not NULL
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;