-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--用户维表-手机号维表-写DWD
INSERT INTO DIM_TEST.T_DIM_MOBILE_DIM
(T_ID,SYSTEM_KEY,MOBILE_NUMBER,IS_DIRECT_SALE_MOBILE,IS_LYX_REALNAME_MOBILE,IS_DOUYIN_CARD_PURCHASERS_MOBILE,IS_FREQUENT_FLYER_MOBILE,IS_HIGH_MOBILE_NUMBER,CURRENT_PHONE_HIGHEST_PRIORITY,IS_VIRTUAL_MOBILE,UPDATE_TIME,CREATE_TIME)
SELECT CERT_NO AS T_ID,concat(CERT_NO,MOBILE_PHONE) AS SYSTEM_KEY,MOBILE_PHONE AS MOBILE_NUMBER,
FALSE AS IS_DIRECT_SALE_MOBILE,FALSE AS IS_LYX_REALNAME_MOBILE,FALSE AS IS_DOUYIN_CARD_PURCHASERS_MOBILE,
FALSE AS IS_FREQUENT_FLYER_MOBILE,FALSE AS IS_HIGH_MOBILE_NUMBER,2 AS CURRENT_PHONE_HIGHEST_PRIORITY,
SM4_DECRYPT(FROM_BASE64(MOBILE_PHONE), FROM_BASE64(@SM4_KEY)) REGEXP '^(170|171|162|165|167)[0-9]+' AS IS_VIRTUAL_MOBILE,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
WHERE concat(CERT_NO,MOBILE_PHONE) IS not NULL
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;