-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--航程维表-写DWD
INSERT INTO DIM_TEST.T_DIM_SEG_DIM
(SEGMENT_KEY,DEPARTURE_DATE,DEPARTURE_TIME,ARRIVAL_DATE, ARRIVAL_TIME,AIRLINE,MARKET_AIRLINE,MARKET_FLIGHT_NUM,OPERAT_AIRLINE,OPERAT_FLIGHT_NUM,UPDATE_TIME,CREATE_TIME)
SELECT concat(ifnull(date_format(FLT_DATE,'%Y%m%d'),null),FLT_NUM,MC_FLT,ORIG,DEST) AS SEGMENT_KEY,
date_format(FLT_DATE,'%Y-%m-%d') AS DEPARTURE_DATE,concat(DCS_DPTM,':00') AS DEPARTURE_TIME,
date_format(DCS_ATDATE,'%Y-%m-%d') AS ARRIVAL_DATE,concat(DCS_ATTM,':00') AS ARRIVAL_TIME,
concat(ORIG,'_',DEST) AS AIRLINE,SUBSTRING(MC_FLT,1,2) AS MARKET_AIRLINE,SUBSTRING(MC_FLT,3) AS MARKET_FLIGHT_NUM,
SUBSTRING(FLT_NUM,1,2) AS OPERAT_AIRLINE,SUBSTRING(FLT_NUM,3) AS OPERAT_FLIGHT_NUM,
now() AS UPDATE_TIME,
now() AS CREATE_TIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
WHERE concat(ifnull(date_format(FLT_DATE,'%Y%m%d'),null),FLT_NUM,MC_FLT,ORIG,DEST) IS not NULL
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;