-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--机票-预订-航段级事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_BOOKING_SEG_FACT
(PK_ID, PNR_NUMBER, FK_BOOKING_DATE, FK_BOOKING_TIME, FK_DEPAIRPORT, FK_ARRIAIRPORT, FK_BOOKING_SEG, FK_SEG_DATE, FK_SEG_TIME,
PASSENGER_TYPE, EN_LAST_NAME, EN_FIRST_NAME, CN_NAME, CERT_TYPE, CERT_NUMBER, PASSENGER_AGE, FK_PASSENGER_USER_TID, VVIP,
AK_BOOKING_OFFICE_NUMBER, AK_TEAMMARK, AK_SEG_STATUS, AK_SEGCABIN, AK_CABIN, FFRF, FF_LEVEL, FF_AIRLINE, AK_ADVBOOK_DAY,
AK_KEY_ACCOUNT_CODE, AK_PEER_NUMBER, AK_PEER_CHD, PEER_SENIOR, SINGLE_TRAVEL, DATA_ACTIVE, DATA_ACTIVE_TIME, SYSTEM_CREATETIME, SYSTEM_LAST_UPDATETIME)
SELECT concat(PNR_ICS,ORIG,ifnull(date_format(FLT_DATE,'%Y%m%d'),''),ifnull(concat(REPLACE(DCS_DPTM,':',''),'00'),''),CERT_NO,
ifnull(PSG_NAME_CN,REPLACE(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''))) AS PK_ID,
PNR_ICS AS PNR_NUMBER,
SUBSTRING(RECORD_CREATE_TIME,1,10) AS FK_BOOKING_DATE,
SUBSTRING(RECORD_CREATE_TIME,12,8) AS FK_BOOKING_TIME,
ORIG AS FK_DEPAIRPORT,DEST AS FK_ARRIAIRPORT,
concat(ifnull(date_format(FLT_DATE,'%Y%m%d'),null),FLT_NUM,MC_FLT,ORIG,DEST) AS FK_BOOKING_SEG,
date_format(FLT_DATE,'%Y-%m-%d') AS FK_SEG_DATE,concat(DCS_DPTM,':00') AS FK_SEG_TIME,
CASE WHEN IS_CHILD = 'Y' THEN 'CHD' WHEN IS_INFANT = '1' THEN 'INF' ELSE 'ADT' END AS PASSENGER_TYPE,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[1] AS EN_LAST_NAME,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[2] AS EN_FIRST_NAME,
PSG_NAME_CN AS CN_NAME,sid.CFG_VALUE AS CERT_TYPE,CERT_NO AS CERT_NUMBER,
(YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END
AS PASSENGER_AGE,CERT_NO AS FK_PASSENGER_USER_TID,IS_VVIP AS VVIP,BOOK_OFFI AS AK_BOOKING_OFFICE_NUMBER,
CASE WHEN IS_GROUP = 'Y' THEN true ELSE FALSE END AS AK_TEAMMARK,LKT_STATUS AS AK_SEG_STATUS,
SUBSTRING(SELL_CLASS,1,1) AS AK_SEGCABIN,
CASE
  WHEN to_date(FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
    CASE
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'CDPI') > 0 THEN 'BC'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'WR') > 0 THEN 'PE'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
  ELSE  -- 2023.10.29及以后
    CASE
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'JCDRZI') > 0 THEN 'BC'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'GE') > 0 THEN 'PE'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
END AS AK_CABIN,TO_BASE64(SM4_ENCRYPT(REGEXP_REPLACE(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),'\\D',''), FROM_BASE64(@SM4_KEY))) AS FFRF,
IS_FFP_JK AS FF_LEVEL,SUBSTRING(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),1, 2) AS FF_AIRLINE,datediff(FLT_DATE, RECORD_CREATE_TIME) AS AK_ADVBOOK_DAY,
BIG_CUTNUM AS AK_KEY_ACCOUNT_CODE,PASSENGER_NUMBER AS AK_PEER_NUMBER,CASE WHEN IS_CHILD = 'Y' THEN true ELSE false END AS AK_PEER_CHD,
CASE WHEN (YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END > 65
    THEN TRUE
    ELSE FALSE
END AS PEER_SENIOR,CASE WHEN PASSENGER_NUMBER = 1 THEN true ELSE false END AS SINGLE_TRAVEL,
true AS DATA_ACTIVE, now() AS DATA_ACTIVE_TIME,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE concat(PNR_ICS,ORIG,ifnull(date_format(FLT_DATE,'%Y%m%d'),''),ifnull(concat(REPLACE(DCS_DPTM,':',''),':00'),''),CERT_NO,
ifnull(PSG_NAME_CN,REPLACE(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/',''))) IS not NULL
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));


--事务提交
--commit;