-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--机票-成行-航段级事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_DEPART_SEG_FACT
(PK_ID,TIK_NUM,FK_DEPARTURES_DATE,FK_DEPARTURES_TIME,FK_ARRIVE_DATE,FK_ARRIVE_TIME,FK_PNRD_SEG,FK_DEPAIRPORT,FK_ARRIAIRPORT,FK_PASSENGER_USER_TID,AK_TEAMMARK,EN_LAST_NAME,EN_FIRST_NAME,CN_NAME,CERT_TYPE,CERT_NUMBER,IS_KEY_ACCOUNT,PASSENGER_AGE,AK_SEGCABIN,AK_CABIN,AK_DIMARK,PASSENGER_TYPE,PEER_CHD,PEER_SENIOR,FK_ISSUE_DATE,FK_ISSUE_TIME,FF_AIRLINE ,FFRF ,FF_LEVEL ,IS_USED_EFR,DATA_ACTIVE,DATA_ACTIVE_TIME,SYSTEM_CREATETIME,SYSTEM_LAST_UPDATETIME)
SELECT concat(ET_NUM,orig,ifnull(date_format(FLT_DATE,'%Y%m%d'),'')) AS PK_ID,
ET_NUM AS TIK_NUM,date_format(FLT_DATE,'%Y-%m-%d') AS FK_DEPARTURES_DATE,concat(DCS_DPTM,':00') AS FK_DEPARTURES_TIME,
date_format(DCS_ATDATE,'%Y-%m-%d') AS FK_ARRIVE_DATE,concat(DCS_ATTM,':00') AS FK_ARRIVE_TIME,
concat(ifnull(date_format(FLT_DATE,'%Y%m%d'),null),FLT_NUM,MC_FLT,ORIG,DEST) AS FK_PNRD_SEG,
ORIG AS FK_DEPAIRPORT,DEST AS FK_ARRIAIRPORT,CERT_NO AS FK_PASSENGER_USER_TID,
CASE WHEN IS_GROUP = 'Y' THEN true ELSE FALSE END AS AK_TEAMMARK,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[1] AS EN_LAST_NAME,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[2] AS EN_FIRST_NAME,
PSG_NAME_CN AS CN_NAME,sid.CFG_VALUE AS CERT_TYPE,CERT_NO AS CERT_NUMBER,
CASE
    WHEN BIG_CUTNUM REGEXP '^[0-9][A-Za-z0-9]{7}$' THEN true  -- 匹配 CA_PATTERN
    WHEN BIG_CUTNUM REGEXP '^[A-Za-z0-9]{5}$' THEN true  -- 匹配 CA_GLOBAL_PATTERN
    WHEN BIG_CUTNUM REGEXP '^[0-9]{8}$' THEN true  -- 匹配 DIGITAL_PATTERN
    ELSE false
END AS IS_KEY_ACCOUNT,
(YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END
AS PASSENGER_AGE,
SUBSTRING(DCS_SELL_CLASS,1,1) AS AK_SEGCABIN,
CASE
  WHEN to_date(FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
    CASE
      WHEN locate(upper(substring(DCS_SELL_CLASS, 1, 1)), 'CDPI') > 0 THEN 'BC'
      WHEN locate(upper(substring(DCS_SELL_CLASS, 1, 1)), 'WR') > 0 THEN 'PE'
      WHEN locate(upper(substring(DCS_SELL_CLASS, 1, 1)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
  ELSE  -- 2023.10.29及以后
    CASE
      WHEN locate(upper(substring(DCS_SELL_CLASS, 1, 1)), 'JCDRZI') > 0 THEN 'BC'
      WHEN locate(upper(substring(DCS_SELL_CLASS, 1, 1)), 'GE') > 0 THEN 'PE'
      WHEN locate(upper(substring(DCS_SELL_CLASS, 1, 1)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
END AS AK_CABIN,TICKET_TYPE AS AK_DIMARK,CASE WHEN IS_CHILD = 'Y' THEN 'CHD' WHEN IS_INFANT = '1' THEN 'INF' ELSE 'ADT' END AS PASSENGER_TYPE,
CASE WHEN IS_CHILD = 'Y' THEN true ELSE false END AS PEER_CHD,
CASE WHEN (YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END > 65
    THEN TRUE
    ELSE FALSE
END AS PEER_SENIOR,
date_format(PRINT_TICKET_TIME,'%Y-%m-%d') AS FK_ISSUE_DATE, date_format(PRINT_TICKET_TIME,'%T') AS FK_ISSUE_TIME,
SUBSTRING(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),1,2) AS FFR_AIRLINE,
TO_BASE64(SM4_ENCRYPT(SUBSTRING(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),3), FROM_BASE64(@SM4_KEY)))  AS FFR,
IS_FFP_JK ,
CASE 
        WHEN FFP IS NOT NULL THEN TRUE 
        ELSE FALSE 
    END AS is_ffp,
true AS DATA_ACTIVE, now() AS DATA_ACTIVE_TIME,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE concat(ET_NUM,orig,ifnull(date_format(FLT_DATE,'%Y%m%d'),'')) IS not NULL AND STATUS = 'AC'
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;