-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--机票-值机-航段级事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_CHECKIN_SEG_FACT
(PK_ID,TIK_NUM,FK_SEG_DATE,FK_SEG_TIME,FK_CHECKIN_DATE,FK_CHECKIN_TIME,FK_PASSENGER_USER_TID,EN_LAST_NAME,EN_FIRST_NAME,CN_NAME,CERT_TYPE,CERT_NUMBER,PASSENGER_AGE,FF_AIRLINE,FFRF,FF_LEVEL,FK_CHECKIN_SEG,FK_SEG_TIME,FK_DEPAIRPORT,FK_ARRIAIRPORT,AK_DIMARK,AK_CHECKIN_PID,CHECKIN_AGENT,AK_SEAT_ASSIGN,AK_SEGCABIN,AK_CABIN,AK_CHECKIN_STATUS,AK_CHECKIN_TYPE,CHECKIN_CHANNEL,SEG_BAGGAGECOUNT,AK_BAGGAGE_FLAG,SEG_BAGGAGEWEIGHT,EARLY_CHECKINTIME,DATA_ACTIVE,DATA_ACTIVE_TIME,SYSTEM_CREATETIME,SYSTEM_LAST_UPDATETIME)
SELECT concat(date_format(FLT_DATE,'%Y%m%d'),ET_NUM,ORIG,DEST) AS PK_ID,
ET_NUM AS TIK_NUM,date_format(FLT_DATE,'%Y-%m-%d') AS FK_SEG_DATE,concat(DCS_DPTM,':00') AS FK_SEG_TIME,
date_format(CHECK_IN_TIME,'%Y-%m-%d') AS FK_CHECKIN_DATE,date_format(CHECK_IN_TIME,'%T') AS FK_CHECKIN_TIME,
CERT_NO AS FK_PASSENGER_USER_TID,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[1] AS EN_LAST_NAME,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[2] AS EN_FIRST_NAME,
PSG_NAME_CN AS CN_NAME,sid.CFG_VALUE AS CERT_TYPE,CERT_NO AS CERT_NUMBER,
(YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END
AS PASSENGER_AGE,
SUBSTRING(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),1,2) AS FF_AIRLINE,
TO_BASE64(SM4_ENCRYPT(SUBSTRING(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),3),FROM_BASE64(@SM4_KEY))) AS FFRF,
IS_FFP_JK AS FF_LEVEL,concat(date_format(FLT_DATE,'%Y%m%d'),FLT_NUM,MC_FLT,ORIG,DEST) AS FK_CHECKIN_SEG,
concat(DCS_DPTM,':00') AS FK_SEG_TIME,ORIG AS FK_DEPAIRPORT,DEST AS FK_ARRIAIRPORT,TICKET_TYPE AS AK_DIMARK,
CKI_PID AS AK_CHECKIN_PID,CKI_AGENT AS CHECKIN_AGENT,SEAT_NO AS AK_SEAT_ASSIGN,
SUBSTRING(SELL_CLASS,1,1) AS AK_SEGCABIN,
CASE
  WHEN to_date(FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
    CASE
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'CDPI') > 0 THEN 'BC'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'WR') > 0 THEN 'PE'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
  ELSE  -- 2023.10.29及以后
    CASE
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'JCDRZI') > 0 THEN 'BC'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'GE') > 0 THEN 'PE'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
END AS AK_CABIN,CKI_STATUS AS AK_CHECKIN_STATUS,ifnull(sid2.CFG_VALUE,'NONC') AS AK_CHECKIN_TYPE,
CASE
  WHEN CKI_AGENT='70810' THEN 'SCIBE'
  WHEN CKI_AGENT='70812' THEN 'SCXCX'
  WHEN CKI_AGENT='70807' THEN 'SCZSF'
  WHEN CKI_AGENT='70811' THEN 'SCWEX'
  ELSE CKI_AGENT
END AS CHECKIN_CHANNEL,
ifnull(BAGS,0) AS SEG_BAGGAGECOUNT, CASE WHEN BAGS>0 THEN TRUE ELSE FALSE END AS AK_BAGGAGE_FLAG,
BAGWHT AS SEG_BAGGAGEWEIGHT,
(unix_timestamp(str_to_date(concat(date_format(FLT_DATE,'%Y-%m-%d'),DCS_DPTM),'%Y-%m-%d%H')) - unix_timestamp(str_to_date(date_format(CHECK_IN_TIME,'%Y-%m-%d%H'),'%Y-%m-%d%H'))) / 3600 AS EARLY_CHECKINTIME,
true AS DATA_ACTIVE, now() AS DATA_ACTIVE_TIME,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid2 ON CKI_TYPE=sid2.CFG_CODE
AND sid2.CFG_TYPE = 'CHECK_IN_METHOD' AND sid2.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE concat(date_format(FLT_DATE,'%Y%m%d'),ET_NUM,ORIG,DEST) IS not null AND STATUS = 'AC'
AND CHECK_IN_TIME is not null
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;