-- 1. 设置会话变量 (在执行 INSERT 语句前执行)
--SET batch_size = 4096;
--SET @ETL_DATE = '2025-01-01';
--SET @SM4_KEY = 'VFlLSFNUc200MjAyNX5+fg==';
--婴儿姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('INF(01JAN)dfdfdCHD', '(?i)^INF\\((\\d{2})?(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\)\\s*', '')));
--英文姓名标准化
--SELECT UPPER(TRIM(REGEXP_REPLACE('MS Lisa', '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', '')))

--机票-改升换开出票-航段级事实表-写DWD
INSERT INTO DWD_TEST.T_DWD_DATECHANGE_SEG_FACT
(PK_ID,AK_PNR_NUMBER,NEW_TIK_NUM,ORI_TIK_NUM,AK_BOOKING_OFFICE_NUMBER,FK_EXCHANGE_DATE,FK_EXCHANGE_TIME,FK_DEPARTURES_DATE,FK_DEPARTURES_TIME,FK_DEPAIRPORT,FK_ARRIAIRPORT,FK_DC_SEG,EN_LAST_NAME,EN_FIRST_NAME,CN_NAME,CERT_TYPE,CERT_NUMBER,FK_PASSENGER_USER_TID,PASSENGER_AGE,AK_KEY_ACCOUNT_CODE,IS_KEY_ACCOUNT,AK_SEGCABIN,AK_CABIN,AK_DIMARK,SEGMENT_STATUS,FFRF,FF_LEVEL,DATA_ACTIVE,DATA_ACTIVE_TIME,SYSTEM_CREATETIME,SYSTEM_LAST_UPDATETIME)
SELECT concat(ET_NUM,orig,ifnull(date_format(FLT_DATE,'%Y%m%d'),'')) AS PK_ID,
PNR_ICS AS AK_PNR_NUMBER,ET_NUM AS NEW_TIK_NUM, ORIGINALTKNE AS ORI_TIK_NUM,ISSUE_OFFI AS AK_BOOKING_OFFICE_NUMBER,
date_format(PRINT_TICKET_TIME,'%Y-%m-%d') AS FK_EXCHANGE_DATE, date_format(PRINT_TICKET_TIME,'%T') AS FK_EXCHANGE_TIME,
date_format(FLT_DATE,'%Y-%m-%d') AS FK_DEPARTURES_DATE,concat(DCS_DPTM,':00') AS FK_DEPARTURES_TIME,
ORIG AS FK_DEPAIRPORT,DEST AS FK_ARRIAIRPORT,concat(ifnull(date_format(FLT_DATE,'%Y%m%d'),null),FLT_NUM,MC_FLT,ORIG,DEST) AS FK_DC_SEG,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[1] AS EN_LAST_NAME,
SPLIT_BY_STRING(UPPER(TRIM(REGEXP_REPLACE(PSG_NAME_EN, '(?i)^\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*|\s*(CHD|INF|MR|MS|GM|JC|VIP|VVIP|CIP)\s*$', ''))),'/')[2] AS EN_FIRST_NAME,
PSG_NAME_CN AS CN_NAME,sid.CFG_VALUE AS CERT_TYPE,CERT_NO AS CERT_NUMBER,CERT_NO AS FK_PASSENGER_USER_TID,
(YEAR(CURDATE()) - YEAR(BIRTHDAY)) -
    CASE
       WHEN MONTH(CURDATE()) * 100 + DAY(CURDATE()) < MONTH(BIRTHDAY) * 100 + DAY(BIRTHDAY)
    THEN 1 ELSE 0 END
AS PASSENGER_AGE,BIG_CUTNUM AS AK_KEY_ACCOUNT_CODE,
CASE
    WHEN BIG_CUTNUM REGEXP '^[0-9][A-Za-z0-9]{7}$' THEN true  -- 匹配 CA_PATTERN
    WHEN BIG_CUTNUM REGEXP '^[A-Za-z0-9]{5}$' THEN true  -- 匹配 CA_GLOBAL_PATTERN
    WHEN BIG_CUTNUM REGEXP '^[0-9]{8}$' THEN true  -- 匹配 DIGITAL_PATTERN
    ELSE false
END AS IS_KEY_ACCOUNT,
SUBSTRING(SELL_CLASS,1,1) AS AK_SEGCABIN,
CASE
  WHEN to_date(FLT_DATE) < '2023-10-29' THEN  -- 2022.1.1-2023.10.28
    CASE
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'CDPI') > 0 THEN 'BC'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'WR') > 0 THEN 'PE'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'YBHLQGVUZMKTSJEAOXN') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
  ELSE  -- 2023.10.29及以后
    CASE
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'JCDRZI') > 0 THEN 'BC'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'GE') > 0 THEN 'PE'
      WHEN locate(upper(substring(SELL_CLASS, 1, 1)), 'YBMUHQVWSLPNKTAOX') > 0 THEN 'EC'
      ELSE NULL  -- 可选：处理未匹配的舱位代码
    END
END AS AK_CABIN,TICKET_TYPE AS AK_DIMARK,COUPON_STATUS AS SEGMENT_STATUS,
TO_BASE64(SM4_ENCRYPT(SUBSTRING(SM4_DECRYPT(FROM_BASE64(FFP), FROM_BASE64(@SM4_KEY)),3),FROM_BASE64(@SM4_KEY))) AS FFRF,IS_FFP_JK AS FF_LEVEL,
true AS DATA_ACTIVE, now() AS DATA_ACTIVE_TIME,
now() AS SYSTEM_CREATETIME,
now() AS SYSTEM_LAST_UPDATETIME
FROM ODS_TEST.T_ODS_LYGJ_DEPART_PASSENGER_INFO toldpi
LEFT JOIN DWD_TEST.STANDARDIZE_FIELD sid ON ID_TYPE=sid.CFG_CODE
AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL ='LUYAN_STEWARD'
WHERE concat(ET_NUM,orig,ifnull(date_format(FLT_DATE,'%Y%m%d'),'')) IS not NULL
AND (ETL_CREATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000') OR ETL_UPDATE_TIME >= CONCAT(@ETL_DATE,' 00:00:00.000'));

--事务提交
--commit;
