package com.travelsky.trp.usercenter.data.analysis.model.dwd.fact;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDateTime;

/**
 * 附加服务无陪儿童出EMD票航段事实表实体类-T_DWD_UMCHILD_TIK_FACT
 * @author generated by tool
 * @date 2025/7/30
 */
public class UmchildTikFactModel {
    /**
     * pk_id
     */
    @JsonProperty("PK_ID")
    private String pkId;

    /**
     * EMD出票日期
     */
    @JsonProperty("FK_UMCHILDTIK_DATE")
    private String fkUmchildtikDate;

    /**
     * EMD出票时间
     */
    @JsonProperty("FK_UMCHILDTIK_TIME")
    private String fkUmchildtikTime;

    /**
     * 起飞机场
     */
    @JsonProperty("DEPAIRPORT")
    private String depairport;

    /**
     * 到达机场
     */
    @JsonProperty("ARRIAIRPORT")
    private String arriairport;

    /**
     * 航班日期
     */
    @JsonProperty("FK_UMCHILDSTART_DATE")
    private String fkUmchildstartDate;

    /**
     * 航班时间
     */
    @JsonProperty("FK_UMCHILDSTART_TIME")
    private String fkUmchildstartTime;

    /**
     * 乘机人英文姓
     */
    @JsonProperty("EN_LAST_NAME")
    private String enLastName;

    /**
     * 乘机人英文名
     */
    @JsonProperty("EN_FIRST_NAME")
    private String enFirstName;

    /**
     * 乘机人中文姓名
     */
    @JsonProperty("CN_NAME")
    private String cnName;

    /**
     * 乘机人类型
     */
    @JsonProperty("PASSENGER_TYPE")
    private String passengerType;

    /**
     * 乘机人证件类型
     */
    @JsonProperty("CERT_TYPE")
    private String certType;

    /**
     * 乘机人证件号
     */
    @JsonProperty("CERT_NUMBER")
    private String certNumber;

    /**
     * 乘机人年龄
     */
    @JsonProperty("PASSENGER_AGE")
    private Integer passengerAge;

    /**
     * 乘机人TID
     */
    @JsonProperty("FK_PASSENGER_USER_TID")
    private String fkPassengerUserTid;

    /**
     * 航程
     */
    @JsonProperty("FK_UMCHILD_SEG")
    private String fkUmchildSeg;

    /**
     * 国内国际标识
     */
    @JsonProperty("AK_DIMARK")
    private String akDimark;

    /**
     * 关联票号
     */
    @JsonProperty("AK_TIKNUM")
    private String akTiknum;

    /**
     * EMD票号
     */
    @JsonProperty("AK_EMDNUM")
    private String akEmdnum;

    /**
     * EMD票状态
     */
    @JsonProperty("AK_EMD_STATUS")
    private String akEmdStatus;

    /**
     * 币种
     */
    @JsonProperty("AK_CURRENCY")
    private String akCurrency;

    /**
     * 金额
     */
    @JsonProperty("AK_PAY_AMOUNT")
    private Double akPayAmount;

    /**
     * EMD出票office
     */
    @JsonProperty("AK_EMDTIKCHANNEL")
    private String akEmdtikchannel;

    /**
     * EMD出票Office对应的IataCode
     */
    @JsonProperty("AK_EMDIATACODE")
    private String akEmdiataCode;

    /**
     * EMD类型
     */
    @JsonProperty("AK_EMDTYPE")
    private String akEmdtype;

    /**
     * 无陪儿童EMD出票计数，固定写入1
     */
    @JsonProperty("UMCHILD_EMD_COUNT")
    private int umchildEmdCount;

    /**
     * 数据是否启用
     */
    @JsonProperty("DATA_ACTIVE")
    private Boolean dataActive;

    /**
     * 数据启用时间
     */
    @JsonProperty("DATA_ACTIVE_TIME")
    private String dataActiveTime;

    /**
     * 本系统创建日期时间
     */
    @JsonProperty("SYSTEM_CREATETIME")
    private String systemCreatetime;

    /**
     * 本系统最后更新日期时间
     */
    @JsonProperty("SYSTEM_LAST_UPDATETIME")
    private String systemLastUpdatetime;

    // Getter and Setter methods
    public String getPkId() {
        return pkId;
    }

    public void setPkId(String pkId) {
        this.pkId = pkId;
    }

    public String getFkUmchildtikDate() {
        return fkUmchildtikDate;
    }

    public void setFkUmchildtikDate(String fkUmchildtikDate) {
        this.fkUmchildtikDate = fkUmchildtikDate;
    }

    public String getFkUmchildtikTime() {
        return fkUmchildtikTime;
    }

    public void setFkUmchildtikTime(String fkUmchildtikTime) {
        this.fkUmchildtikTime = fkUmchildtikTime;
    }

    public String getDepairport() {
        return depairport;
    }

    public void setDepairport(String depairport) {
        this.depairport = depairport;
    }

    public String getArriairport() {
        return arriairport;
    }

    public void setArriairport(String arriairport) {
        this.arriairport = arriairport;
    }

    public String getFkUmchildstartDate() {
        return fkUmchildstartDate;
    }

    public void setFkUmchildstartDate(String fkUmchildstartDate) {
        this.fkUmchildstartDate = fkUmchildstartDate;
    }

    public String getFkUmchildstartTime() {
        return fkUmchildstartTime;
    }

    public void setFkUmchildstartTime(String fkUmchildstartTime) {
        this.fkUmchildstartTime = fkUmchildstartTime;
    }

    public String getEnLastName() {
        return enLastName;
    }

    public void setEnLastName(String enLastName) {
        this.enLastName = enLastName;
    }

    public String getEnFirstName() {
        return enFirstName;
    }

    public void setEnFirstName(String enFirstName) {
        this.enFirstName = enFirstName;
    }

    public String getCnName() {
        return cnName;
    }

    public void setCnName(String cnName) {
        this.cnName = cnName;
    }

    public String getPassengerType() {
        return passengerType;
    }

    public void setPassengerType(String passengerType) {
        this.passengerType = passengerType;
    }

    public String getCertType() {
        return certType;
    }

    public void setCertType(String certType) {
        this.certType = certType;
    }

    public String getCertNumber() {
        return certNumber;
    }

    public void setCertNumber(String certNumber) {
        this.certNumber = certNumber;
    }

    public Integer getPassengerAge() {
        return passengerAge;
    }

    public void setPassengerAge(Integer passengerAge) {
        this.passengerAge = passengerAge;
    }

    public String getFkPassengerUserTid() {
        return fkPassengerUserTid;
    }

    public void setFkPassengerUserTid(String fkPassengerUserTid) {
        this.fkPassengerUserTid = fkPassengerUserTid;
    }

    public String getFkUmchildSeg() {
        return fkUmchildSeg;
    }

    public void setFkUmchildSeg(String fkUmchildSeg) {
        this.fkUmchildSeg = fkUmchildSeg;
    }

    public String getAkDimark() {
        return akDimark;
    }

    public void setAkDimark(String akDimark) {
        this.akDimark = akDimark;
    }

    public String getAkTiknum() {
        return akTiknum;
    }

    public void setAkTiknum(String akTiknum) {
        this.akTiknum = akTiknum;
    }

    public String getAkEmdnum() {
        return akEmdnum;
    }

    public void setAkEmdnum(String akEmdnum) {
        this.akEmdnum = akEmdnum;
    }

    public String getAkEmdStatus() {
        return akEmdStatus;
    }

    public void setAkEmdStatus(String akEmdStatus) {
        this.akEmdStatus = akEmdStatus;
    }

    public String getAkCurrency() {
        return akCurrency;
    }

    public void setAkCurrency(String akCurrency) {
        this.akCurrency = akCurrency;
    }

    public Double getAkPayAmount() {
        return akPayAmount;
    }

    public void setAkPayAmount(Double akPayAmount) {
        this.akPayAmount = akPayAmount;
    }

    public String getAkEmdtikchannel() {
        return akEmdtikchannel;
    }

    public void setAkEmdtikchannel(String akEmdtikchannel) {
        this.akEmdtikchannel = akEmdtikchannel;
    }

    public String getAkEmdiataCode() {
        return akEmdiataCode;
    }

    public void setAkEmdiataCode(String akEmdiataCode) {
        this.akEmdiataCode = akEmdiataCode;
    }

    public String getAkEmdtype() {
        return akEmdtype;
    }

    public void setAkEmdtype(String akEmdtype) {
        this.akEmdtype = akEmdtype;
    }

    public int getUmchildEmdCount() {
        return umchildEmdCount;
    }

    public void setUmchildEmdCount(int umchildEmdCount) {
        this.umchildEmdCount = umchildEmdCount;
    }

    public Boolean getDataActive() {
        return dataActive;
    }

    public void setDataActive(Boolean dataActive) {
        this.dataActive = dataActive;
    }

    public String getDataActiveTime() {
        return dataActiveTime;
    }

    public void setDataActiveTime(String dataActiveTime) {
        this.dataActiveTime = dataActiveTime;
    }

    public String getSystemCreatetime() {
        return systemCreatetime;
    }

    public void setSystemCreatetime(String systemCreatetime) {
        this.systemCreatetime = systemCreatetime;
    }

    public String getSystemLastUpdatetime() {
        return systemLastUpdatetime;
    }

    public void setSystemLastUpdatetime(String systemLastUpdatetime) {
        this.systemLastUpdatetime = systemLastUpdatetime;
    }

    @Override
    public String toString() {
        return "UmchildTikFactModel{" +
                "pkId='" + pkId + '\'' +
                ", fkUmchildtikDate='" + fkUmchildtikDate + '\'' +
                ", fkUmchildtikTime='" + fkUmchildtikTime + '\'' +
                ", depairport='" + depairport + '\'' +
                ", arriairport='" + arriairport + '\'' +
                ", fkUmchildstartDate='" + fkUmchildstartDate + '\'' +
                ", fkUmchildstartTime='" + fkUmchildstartTime + '\'' +
                ", enLastName='" + enLastName + '\'' +
                ", enFirstName='" + enFirstName + '\'' +
                ", cnName='" + cnName + '\'' +
                ", passengerType='" + passengerType + '\'' +
                ", certType='" + certType + '\'' +
                ", certNumber='" + certNumber + '\'' +
                ", passengerAge=" + passengerAge +
                ", fkPassengerUserTid='" + fkPassengerUserTid + '\'' +
                ", fkUmchildSeg='" + fkUmchildSeg + '\'' +
                ", akDimark='" + akDimark + '\'' +
                ", akTiknum='" + akTiknum + '\'' +
                ", akEmdnum='" + akEmdnum + '\'' +
                ", akEmdStatus='" + akEmdStatus + '\'' +
                ", akCurrency='" + akCurrency + '\'' +
                ", akPayAmount=" + akPayAmount +
                ", akEmdtikchannel='" + akEmdtikchannel + '\'' +
                ", akEmdiataCode='" + akEmdiataCode + '\'' +
                ", akEmdtype='" + akEmdtype + '\'' +
                ", umchildEmdCount=" + umchildEmdCount +
                ", dataActive=" + dataActive +
                ", dataActiveTime='" + dataActiveTime + '\'' +
                ", systemCreatetime='" + systemCreatetime + '\'' +
                ", systemLastUpdatetime='" + systemLastUpdatetime + '\'' +
                '}';
    }
}

