-- TRP（FTP）写入预订PNR事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.BOOKING_USERNAME IS NOT NULL;

-- 第三步：写入预订PNR事实表
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_NAME,
    CONTACT_MOBILE_NUMBER,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 预订日期(YYYYMMDD格式)
    CONCAT(
            COALESCE(t1.PNR, ''),
            DATE_FORMAT(t1.BOOKING_DATE, '%Y%m%d')
        ) AS PK_ID,

    t1.ORDER_NUMBER AS CHANNEL_ORDER_ID,

    -- 预订渠道标准化
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.CONTACT_PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    t1.PAYMENT_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
    -- 预订渠道标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.PNR IS NOT NULL AND t1.PNR != ''
  AND t1.BOOKING_DATE IS NOT NULL;

-- 第四步：23:00:00-00:00:00的预订PNR需要T+1日期
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_NAME,
    CONTACT_MOBILE_NUMBER,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 预订日期+1天(YYYYMMDD格式) - T+1日期
    CONCAT(
            COALESCE(t1.PNR, ''),
            DATE_FORMAT(DATE_ADD(STR_TO_DATE(SUBSTRING(t1.BOOKING_DATE, 1, 10), '%Y/%m/%d'), INTERVAL 1 DAY), '%Y%m%d')
        ) AS PK_ID,

    t1.ORDER_NUMBER AS CHANNEL_ORDER_ID,

    -- 预订渠道标准化
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,

    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.CONTACT_PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    t1.PAYMENT_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
    -- 预订渠道标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 23:00:00-00:00:00时间段
  AND HOUR(STR_TO_DATE(t1.BOOKING_DATE, '%Y/%m/%d %H:%i')) = 23
  AND t1.PNR IS NOT NULL AND t1.PNR != ''
  AND t1.BOOKING_DATE IS NOT NULL;

-- 第五步：00:00:00-00:01:00的预订PNR需要T-1日期
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_NAME,
    CONTACT_MOBILE_NUMBER,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 预订日期+1天(YYYYMMDD格式) - T+1日期
    CONCAT(
            COALESCE(t1.PNR, ''),
            DATE_FORMAT(DATE_SUB(STR_TO_DATE(SUBSTRING(t1.BOOKING_DATE, 1, 10), '%Y/%m/%d'), INTERVAL 1 DAY), '%Y%m%d')
        ) AS PK_ID,

    t1.ORDER_NUMBER AS CHANNEL_ORDER_ID,

    -- 预订渠道标准化
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,

    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.CONTACT_PHONE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    t1.PAYMENT_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_TRP_SC_SALE_DETAIL t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.BOOKING_USERNAME), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
    -- 预订渠道标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 00:00:00-00:01:00时间段
  AND HOUR(t1.BOOKING_DATE) = 0
  AND MINUTE(t1.BOOKING_DATE) < 1
  AND t1.PNR IS NOT NULL AND t1.PNR != ''
  AND t1.BOOKING_DATE IS NOT NULL;

-- trp-数仓写入预订pnr事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND t1.ORDER_USER IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'CCID' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  AND t1.ORDER_USER IS NOT NULL;

-- 第三步：写入预订PNR事实表（正常时间）
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_NAME,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 订单日期(YYYYMMDD格式)
    CONCAT(
            COALESCE(t1.PNR, ''),
            DATE_FORMAT(t1.ORDER_DATE, '%Y%m%d')
        ) AS PK_ID,

    t1.ORDER_NO AS CHANNEL_ORDER_ID,

    -- 预订渠道标准化
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    t1.PAY_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
    -- 预订渠道标准化
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND t1.PNR IS NOT NULL AND t1.PNR != ''
  AND t1.ORDER_DATE IS NOT NULL;

-- 第四步：23:00:00-00:00:00的订单需要T，T+1
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_NAME,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 订单日期(YYYYMMDD格式) - T日期
    CONCAT(
            COALESCE(t1.PNR, ''),
            DATE_FORMAT(DATE_ADD(t1.ORDER_DATE, INTERVAL 1 DAY), '%Y%m%d')
        ) AS PK_ID,

    t1.ORDER_NO AS CHANNEL_ORDER_ID,
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,
    t1.PAY_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 23:00:00-00:00:00时间段
  AND HOUR(t1.ORDER_DATE) = 23
  AND t1.PNR IS NOT NULL AND t1.PNR != ''
  AND t1.ORDER_DATE IS NOT NULL;

-- 第六步：00:00:00-00:01:00的订单需要T-1
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_NAME,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 订单日期-1天(YYYYMMDD格式) - T-1日期
    CONCAT(
            COALESCE(t1.PNR, ''),
            DATE_FORMAT(DATE_SUB(t1.ORDER_DATE, INTERVAL 1 DAY), '%Y%m%d')
        ) AS PK_ID,

    t1.ORDER_NO AS CHANNEL_ORDER_ID,
    IFNULL(sid1.CFG_VALUE, t1.ORDER_CHANNEL) AS AK_CHANNEL,
    REPLACE(COALESCE(t1.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,
    t1.PAY_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_SC_UPLOAD_B2C_ORDERINFO t1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(t1.ORDER_USER), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
         LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid1 ON t1.ORDER_CHANNEL = sid1.CFG_CODE
    AND sid1.CFG_TYPE = 'ORDER_CHANNEL_AIRTICKET' AND sid1.CFG_TYPE_CHANNEL = 'ALL'
WHERE t1.ORDER_CHANNEL NOT IN ('TSDF','TSIF','SD','全渠道')
  AND t1.ETL_DATE >= @ETL_DATE
  -- 00:00:00-00:01:00时间段
  AND HOUR(t1.ORDER_DATE) = 0
  AND MINUTE(t1.ORDER_DATE) < 1
  AND t1.PNR IS NOT NULL AND t1.PNR != ''
  AND t1.ORDER_DATE IS NOT NULL;


-- 客服白屏写入预订pnr事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE BO.ORDER_TYPE = 2
  AND BO.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND BO.CUR_TEL IS NOT NULL;

-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    'PHONE' AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE BO.ORDER_TYPE = 2
  AND BO.ETL_DATE >= @ETL_DATE
  AND BO.CUR_TEL IS NOT NULL;

-- 第三步：写入预订PNR事实表（正常时间）
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    CONTACT_LANDLINE_MOBILE_NUMBER,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 创建日期(YYYYMMDD格式)
    CONCAT(
            COALESCE(BO.PNR, ''),
            DATE_FORMAT(BO.CREATE_DATE, '%Y%m%d')
        ) AS PK_ID,

    BO.ORDER_SN AS CHANNEL_ORDER_ID,
    'SCWHP' AS AK_CHANNEL,

    -- 联系人手机号标准化（去除空白字符）
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CONTACT_MOBILE), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS CONTACT_MOBILE_NUMBER,

    -- 联系人姓名标准化（去除空白字符）
    REPLACE(COALESCE(BO.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,

    -- 联系人固定电话
    COALESCE(BO.CONTACT_PHONE, '') AS CONTACT_LANDLINE_MOBILE_NUMBER,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    BO.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE BO.ORDER_TYPE = 2
  AND BO.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND BO.PNR IS NOT NULL AND BO.PNR != ''
  AND BO.CREATE_DATE IS NOT NULL;

-- 第四步：23:00:00-00:00:00的订单需要T，T+1
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    CONTACT_LANDLINE_MOBILE_NUMBER,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 创建日期(YYYYMMDD格式) - T日期
    CONCAT(
            COALESCE(BO.PNR, ''),
            DATE_FORMAT(DATE_ADD(BO.CREATE_DATE, INTERVAL 1 DAY), '%Y%m%d')
        ) AS PK_ID,

    BO.ORDER_SN AS CHANNEL_ORDER_ID,
    'SCWHP' AS AK_CHANNEL,

    REPLACE(COALESCE(BO.CONTACT_MOBILE, ''), ' ', '') AS CONTACT_MOBILE_NUMBER,
    REPLACE(COALESCE(BO.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    COALESCE(BO.CONTACT_PHONE, '') AS CONTACT_LANDLINE_MOBILE_NUMBER,

    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    BO.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE BO.ORDER_TYPE = 2
  AND BO.ETL_DATE >= @ETL_DATE
  -- 23:00:00-00:00:00时间段
  AND HOUR(BO.CREATE_DATE) = 23
  AND BO.PNR IS NOT NULL AND BO.PNR != ''
  AND BO.CREATE_DATE IS NOT NULL;

-- 第五步：00:00:00-00:01:00的订单需要T-1
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    CONTACT_MOBILE_NUMBER,
    CONTACT_NAME,
    CONTACT_LANDLINE_MOBILE_NUMBER,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 创建日期-1天(YYYYMMDD格式) - T-1日期
    CONCAT(
            COALESCE(BO.PNR, ''),
            DATE_FORMAT(DATE_SUB(BO.CREATE_DATE, INTERVAL 1 DAY), '%Y%m%d')
        ) AS PK_ID,

    BO.ORDER_SN AS CHANNEL_ORDER_ID,
    'SCWHP' AS AK_CHANNEL,

    REPLACE(COALESCE(BO.CONTACT_MOBILE, ''), ' ', '') AS CONTACT_MOBILE_NUMBER,
    REPLACE(COALESCE(BO.CONTACT_NAME, ''), ' ', '') AS CONTACT_NAME,
    COALESCE(BO.CONTACT_PHONE, '') AS CONTACT_LANDLINE_MOBILE_NUMBER,

    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) AS FK_BOOKING_USER_ORIGIN_ID,

    BO.UPDATE_DATE AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_KFBP_BUS_ORDER BO
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(BO.CUR_TEL), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE BO.ORDER_TYPE = 2
  AND BO.ETL_DATE >= @ETL_DATE
  -- 00:00:00-00:01:00时间段
  AND HOUR(BO.CREATE_DATE) = 0
  AND MINUTE(BO.CREATE_DATE) < 1
  AND BO.PNR IS NOT NULL AND BO.PNR != ''
  AND BO.CREATE_DATE IS NOT NULL;




-- 大客户差旅 写入预订PNR事实表
-- 第一步：不存在的TID写入T_DIM_TID_SET表
INSERT INTO DIM_PROD.T_DIM_TID_SET
(
    TID,
    ETL_DATE,
    CREATE_TIME,
    TID_STATUS
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) TID,
    @ETL_DATE ETL_DATE,
    NOW() CREATE_TIME,
    1 TID_STATUS
FROM
    ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.ETL_DATE >= @ETL_DATE
  AND tds.TID IS NULL
  AND rc.CERT_NO IS NOT NULL;
-- 第二步：模拟IDMapping写入T_DIM_STRONGID表
INSERT INTO DIM_PROD.T_DIM_STRONGID
(
    STRONGID,
    STRONGID_TYPE,
    TID,
    STRONGID_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    ETL_DATE
)
SELECT
    DISTINCT
    TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) STRONGID,
    IFNULL(sid.CFG_VALUE, rc.CERT_TYPE) AS STRONGID_TYPE,
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) TID,
    1 STRONGID_STATUS,
    NOW() CREATE_TIME,
    NOW() UPDATE_TIME,
    @ETL_DATE ETL_DATE
FROM
    ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
        LEFT JOIN (
        SELECT
            EMPLOYEE_ID,
            CERT_NO,
            CERT_TYPE,
            ROW_NUMBER() OVER (
                PARTITION BY EMPLOYEE_ID
                ORDER BY
                    CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                    RAND()
                ) AS rn
        FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
        WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
    ) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
        LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
                TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
            AND tds.STRONGID_STATUS = 1
        LEFT JOIN DWD_PROD.STANDARDIZE_FIELD sid ON rc.CERT_TYPE = sid.CFG_CODE
        AND sid.CFG_TYPE = 'DOCUMENT_TYPE' AND sid.CFG_TYPE_CHANNEL = 'KEY_ACCOUNT_TRAVEL'
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.ETL_DATE = @ETL_DATE
  AND rc.CERT_NO IS NOT NULL;
-- 第三步：写入预订PNR事实表（正常时间）
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 创建日期(YYYYMMDD格式)
    CONCAT(
            COALESCE(o.PNR, ''),
            DATE_FORMAT(o.CREATE_TIME, '%Y%m%d')
        ) AS PK_ID,

    o.ORDER_NO AS CHANNEL_ORDER_ID,

    -- 预订渠道标准化
    'SCSME' AS AK_CHANNEL,

    -- 预订人TID
    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,

    -- 预订人源ID
    o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

    -- 源系统最后更新时间
    o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,

    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
  -- 确保关键字段不为空
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.CREATE_TIME IS NOT NULL;
-- 第四步：23:00:00-00:00:00的订单需要T，T+1
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
    -- 主键ID：PNR + 创建日期+1天(YYYYMMDD格式) - T+1日期
    CONCAT(
            COALESCE(o.PNR, ''),
            DATE_FORMAT(DATE_ADD(o.CREATE_TIME, INTERVAL 1 DAY), '%Y%m%d')
        ) AS PK_ID,

    o.ORDER_NO AS CHANNEL_ORDER_ID,

    'SCSME' AS AK_CHANNEL,

    IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
    o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

    o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,
    NOW() AS SYSTEM_CREATETIME,
    NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1

WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
  -- 23:00:00-00:00:00时间段
  AND HOUR(o.CREATE_TIME) = 23
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.CREATE_TIME IS NOT NULL;
-- 第五步：00:00:00-00:01:00的订单需要T-1
INSERT INTO DWD_PROD.T_DWD_BOOKING_PNR_FACT
(
    PK_ID,
    CHANNEL_ORDER_ID,
    AK_CHANNEL,
    FK_BOOKING_USER_TID,
    FK_BOOKING_USER_ORIGIN_ID,
    SOURCE_LAST_UPDATETIME,
    SYSTEM_CREATETIME,
    SYSTEM_LAST_UPDATETIME
)
SELECT
-- 主键ID：PNR + 创建日期-1天(YYYYMMDD格式) - T-1日期
CONCAT(
        COALESCE(o.PNR, ''),
        DATE_FORMAT(DATE_SUB(o.CREATE_TIME, INTERVAL 1 DAY), '%Y%m%d')
    ) AS PK_ID,

o.ORDER_NO AS CHANNEL_ORDER_ID,

'SCSME' AS AK_CHANNEL,

IFNULL(tds.TID, TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY)))) AS FK_BOOKING_USER_TID,
o.CREATOR_ID AS FK_BOOKING_USER_ORIGIN_ID,

o.CREATE_TIME AS SOURCE_LAST_UPDATETIME,
NOW() AS SYSTEM_CREATETIME,
NOW() AS SYSTEM_LAST_UPDATETIME

FROM ODS_PROD.T_ODS_DKHCL_AIR_ORDER_CHILD_ORDER o
         LEFT JOIN (
    SELECT
        EMPLOYEE_ID,
        CERT_NO,
        CERT_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID
            ORDER BY
                CASE WHEN CERT_TYPE = 'NI' THEN 0 ELSE 1 END,
                RAND()
            ) AS rn
    FROM ODS_PROD.T_ODS_DKHCL_CRM_EMPLOYEE_CERT
    WHERE CERT_NO IS NOT NULL AND TRIM(CERT_NO) <> ''
) rc ON o.CREATOR_ID = rc.EMPLOYEE_ID AND rc.rn = 1
         LEFT JOIN DIM_PROD.T_DIM_STRONGID tds ON
            TO_BASE64(SM4_ENCRYPT(UPPER(TRIM(SM4_DECRYPT(FROM_BASE64(rc.CERT_NO), FROM_BASE64(@SM4_KEY)))), FROM_BASE64(@SM4_KEY))) = tds.STRONGID
        AND tds.STRONGID_STATUS = 1
WHERE o.CUS_BIG_CODE = '99998181'
  AND o.ETL_DATE >= @ETL_DATE
-- 00:00:00-00:01:00时间段
  AND HOUR(o.CREATE_TIME) = 0
  AND MINUTE(o.CREATE_TIME) <= 1
  AND o.PNR IS NOT NULL AND o.PNR != ''
  AND o.CREATE_TIME IS NOT NULL;
