
package com.travelsky.trp.usercenter.data.analysis.cascrmclient.querycard;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryCardService", targetNamespace = "http://service.QueryCard.crm_interface.sda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryCardService {


    /**
     * 
     * @param queryCardInputEntity
     * @return
     *     returns com.travelsky.trp.usercenter.data.analysis.cascrmclient.querycard.QueryCardOutputEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQueryCardInfo", targetNamespace = "http://service.QueryCard.crm_interface.sda.com/", className = "com.travelsky.trp.usercenter.data.analysis.cascrmclient.querycard.GetQueryCardInfo")
    @ResponseWrapper(localName = "getQueryCardInfoResponse", targetNamespace = "http://service.QueryCard.crm_interface.sda.com/", className = "com.travelsky.trp.usercenter.data.analysis.cascrmclient.querycard.GetQueryCardInfoResponse")
    public QueryCardOutputEntity getQueryCardInfo(
        @WebParam(name = "queryCardInputEntity", targetNamespace = "")
        QueryCardInputEntity queryCardInputEntity);

}
