
package com.travelsky.trp.usercenter.data.analysis.cascrmclient.querycard;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "QueryCardServiceImplService", targetNamespace = "http://service.QueryCard.crm_interface.sda.com/", wsdlLocation = "http://10.31.0.10:58091/crm/services/querycard?wsdl")
public class QueryCardServiceImplService
    extends Service
{

    private final static URL QUERYCARDSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYCARDSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName QUERYCARDSERVICEIMPLSERVICE_QNAME = new QName("http://service.QueryCard.crm_interface.sda.com/", "QueryCardServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.31.0.10:58091/crm/services/querycard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYCARDSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        QUERYCARDSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public QueryCardServiceImplService() {
        super(__getWsdlLocation(), QUERYCARDSERVICEIMPLSERVICE_QNAME);
    }

    public QueryCardServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYCARDSERVICEIMPLSERVICE_QNAME, features);
    }

    public QueryCardServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, QUERYCARDSERVICEIMPLSERVICE_QNAME);
    }

    public QueryCardServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYCARDSERVICEIMPLSERVICE_QNAME, features);
    }

    public QueryCardServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryCardServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns QueryCardService
     */
    @WebEndpoint(name = "QueryCardServicePort")
    public QueryCardService getQueryCardServicePort() {
        return super.getPort(new QName("http://service.QueryCard.crm_interface.sda.com/", "QueryCardServicePort"), QueryCardService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryCardService
     */
    @WebEndpoint(name = "QueryCardServicePort")
    public QueryCardService getQueryCardServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.QueryCard.crm_interface.sda.com/", "QueryCardServicePort"), QueryCardService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYCARDSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw QUERYCARDSERVICEIMPLSERVICE_EXCEPTION;
        }
        return QUERYCARDSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
